project_id = "pjrcwvvkjmsscnnfvhug"

[functions.ask-ai]
verify_jwt = true

[functions.transcribe-audio]
verify_jwt = true

[functions.revenuecat-webhook]
verify_jwt = false

[functions.delete-account]
verify_jwt = true
