/** Elçilerin İşleri — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const ACTS_CHAPTER_VERSES: string[][] = [
  // Elçilerin İşleri 1 (26 ayet)
  [
    "Ey Teofilos, İlk kitabımda İsa'nın yapıp öğretmeye başladığı her şeyi yazmıştım.",
    "Seçmiş olduğu elçilere Kutsal Ruh aracılığıyla buyruklar verip yukarı alındığı güne dek olanları da yazmıştım.",
    "İsa, ölüm acısını çektikten sonra birçok inandırıcı kanıtlarla elçilere dirilmiş olduğunu gösterdi. Kırk gün süreyle onlara görünerek Tanrı'nın Egemenliği hakkında konuştu.",
    "Kendileriyle birlikteyken onlara şu buyruğu vermişti: \"Yeruşalim'den ayrılmayın, Baba'nın verdiği ve benden duyduğunuz sözün gerçekleşmesini bekleyin.",
    "Şöyle ki, Yahya suyla vaftiz etti, ama sizler birkaç güne kadar Kutsal Ruh'la vaftiz edileceksiniz.\"",
    "Elçiler bir araya geldiklerinde İsa'ya şunu sordular: \"Ya Rab, İsrail'e egemenliği şimdi mi geri vereceksin?\"",
    "İsa onlara, \"Baba'nın kendi yetkisiyle belirlemiş olduğu zamanları ve tarihleri bilmenize gerek yok\" karşılığını verdi.",
    "\"Ama Kutsal Ruh üzerinize inince güç alacaksınız. Yeruşalim'de, bütün Yahudiye ve Samiriye'de ve dünyanın dört bucağında benim tanıklarım olacaksınız.\"",
    "İsa bunları söyledikten sonra, onların gözleri önünde yukarı alındı. Bir bulut O'nu alıp gözlerinin önünden uzaklaştırdı.",
    "İsa giderken onlar gözlerini göğe dikmiş bakıyorlardı. Tam o sırada, beyaz giysiler içinde iki adam yanlarında belirdi.",
    "\"Ey Celileliler, neden göğe bakıp duruyorsunuz?\" diye sordular. \"Aranızdan göğe alınan İsa, göğe çıktığını nasıl gördünüzse, aynı şekilde geri gelecektir.\"",
    "Bundan sonra elçiler, Yeruşalim'den yaklaşık bir kilometre uzaklıktaki Zeytin Dağı'ndan Yeruşalim'e döndüler.",
    "Kente girince kaldıkları evin üst katındaki odaya çıktılar. Petrus, Yuhanna, Yakup, Andreas, Filipus, Tomas, Bartalmay, Matta, Alfay oğlu Yakup, Yurtsever Simun ve Yakup oğlu Yahuda oradaydı.",
    "Bunlar İsa'nın annesi Meryem, öbür kadınlar ve İsa'nın kardeşleriyle tam bir birlik içinde sürekli dua ediyordu.",
    "O günlerde Petrus, yaklaşık yüz yirmi kardeşten oluşan bir topluluğun ortasında ayağa kalkıp şöyle konuştu:",
    "\"Kardeşler, Kutsal Ruh'un, İsa'yı tutuklayanlara kılavuzluk eden Yahuda ile ilgili olarak Davut'un ağzıyla önceden bildirdiği Kutsal Yazı'nın yerine gelmesi gerekiyordu.",
    "Yahuda bizden biri sayılmış ve bu hizmette yerini almıştı.\"",
    "Bu adam, yaptığı kötülüğün karşılığında aldığı ücretle bir tarla satın aldı. Sonra baş aşağı düştü, bedeni yarıldı ve bütün bağırsakları dışarı döküldü.",
    "Yeruşalim'de yaşayan herkes olayı duydu. Tarlaya kendi dillerinde Kan Tarlası anlamına gelen Hakeldema adını verdiler.",
    "\"Nitekim Mezmurlar Kitabı'nda şöyle yazılmıştır\" dedi Petrus. \"'Onun konutu ıssız kalsın, İçinde oturan olmasın.' Ve, 'Onun görevini bir başkası üstlensin.'",
    "\"Buna göre, Yahya'nın vaftiz döneminden başlayarak Rab İsa'nın aramızdan yukarı alındığı güne değin bizimle birlikte geçirdiği bütün süre boyunca yanımızda bulunan adamlardan biri,",
    "İsa'nın dirilişine tanıklık etmek üzere bize katılmalıdır.\"",
    "Böylece iki kişiyi, Barsabba denilen ve Yustus diye de bilinen Yusuf ile Mattiya'yı önerdiler.",
    "Sonra şöyle dua ettiler: \"Ya Rab, sen herkesin yüreğini bilirsin.",
    "Yahuda'nın, ait olduğu yere gitmek için bıraktığı bu hizmeti ve elçilik görevini üstlenmek üzere bu iki kişiden hangisini seçtiğini göster bize.\"",
    "Ardından bu iki kişiye kura çektirdiler; kura Mattiya'ya düştü. Böylelikle Mattiya on bir elçiye katıldı.",
  ],
  // Elçilerin İşleri 2 (47 ayet)
  [
    "Pentikost Günü geldiğinde bütün imanlılar bir arada bulunuyordu.",
    "Ansızın gökten, güçlü bir rüzgarın esişini andıran bir ses geldi ve bulundukları evi tümüyle doldurdu.",
    "Ateşten dillere benzer bir şeylerin dağılıp her birinin üzerine indiğini gördüler.",
    "İmanlıların hepsi Kutsal Ruh'la doldular, Ruh'un onları konuşturduğu başka dillerle konuşmaya başladılar.",
    "O sırada Yeruşalim'de, dünyanın her ülkesinden gelmiş dindar Yahudiler bulunuyordu.",
    "Sesin duyulması üzerine büyük bir kalabalık toplandı. Herkes kendi dilinin konuşulduğunu duyunca şaşakaldı.",
    "Hayret ve şaşkınlık içinde, \"Bakın, bu konuşanların hepsi Celileli değil mi?\" diye sordular.",
    "\"Nasıl oluyor da her birimiz kendi ana dilini işitiyor?",
    "Aramızda Partlar, Medler, Elamlılar var. Mezopotamya'da, Yahudiye ve Kapadokya'da, Pontus ve Asya İli'nde, Frikya ve Pamfilya'da, Mısır ve Libya'nın Kirene'ye yakın bölgelerinde yaşayanlar var. Hem Yahudi hem de Yahudiliğe dönen Romalı konuklar, Giritliler ve Araplar var aramızda. Ama her birimiz Tanrı'nın büyük işlerinin kendi dilimizde konuşulduğunu işitiyoruz.\"",
    "Hepsi hayret ve şaşkınlık içinde birbirlerine, \"Bunun anlamı ne?\" diye sordular.",
    "Başkalarıysa, \"Bunlar taze şarabı fazla kaçırmış\" diye alay ettiler.",
    "Bunun üzerine Onbirler'le birlikte öne çıkan Petrus yüksek sesle kalabalığa şöyle seslendi: \"Ey Yahudiler ve Yeruşalim'de bulunan herkes, bu durumu size açıklayayım. Sözlerime kulak verin. Bu adamlar, sandığınız gibi sarhoş değiller. Saat daha sabahın dokuzu!",
    "Bu gördüğünüz, Peygamber Yoel aracılığıyla önceden bildirilen olaydır: 'Son günlerde, diyor Tanrı, Bütün insanların üzerine Ruhum'u dökeceğim. Oğullarınız, kızlarınız peygamberlikte bulunacaklar. Gençleriniz görümler, Yaşlılarınız düşler görecek.",
    "O günler kadın erkek Kullarımın üzerine Ruhum'u dökeceğim, Onlar da peygamberlik edecekler.",
    "Yukarıda, gökyüzünde harikalar yaratacağım. Aşağıda, yeryüzünde belirtiler, Kan, ateş ve duman bulutları görülecek.",
    "Rab'bin büyük ve görkemli günü gelmeden önce Güneş kararacak, Ay kan rengine dönecek.",
    "O zaman Rab'bi adıyla çağıran herkes kurtulacak.'",
    "\"Ey İsrailliler, şu sözleri dinleyin: Bildiğiniz gibi Nasıralı İsa, Tanrı'nın, kendisi aracılığıyla aranızda yaptığı mucizeler, harikalar ve belirtilerle kimliği kanıtlanmış bir kişidir.",
    "Tanrı'nın belirlenmiş amacı ve öngörüsü uyarınca elinize teslim edilen bu adamı, yasa tanımaz kişilerin eliyle çarmıha çivileyip öldürdünüz.",
    "Tanrı ise, ölüm acılarına son vererek O'nu diriltti. Çünkü O'nun ölüme tutsak kalması olanaksızdı.",
    "O'nunla ilgili olarak Davut şöyle der: 'Rab'bi her zaman önümde gördüm, Sağımda durduğu için sarsılmam.",
    "Bu nedenle yüreğim mutlu, dilim sevinçlidir. Dahası, bedenim de umut içinde yaşayacak.",
    "Çünkü sen canımı ölüler diyarına terk etmeyeceksin, Kutsalının çürümesine izin vermeyeceksin.",
    "Yaşam yollarını bana bildirdin; Varlığınla beni sevinçle dolduracaksın.'",
    "\"Kardeşler, size açıkça söyleyebilirim ki, büyük atamız Davut öldü, gömüldü, mezarı da bugüne dek yanıbaşımızda duruyor.",
    "Davut bir peygamberdi ve soyundan birini tahtına oturtacağına dair Tanrı'nın kendisine ant içerek söz verdiğini biliyordu.",
    "Geleceği görerek Mesih'in ölümden dirilişine ilişkin şunları söyledi: 'O, ölüler diyarına terk edilmedi, bedeni çürümedi.'",
    "Tanrı, İsa'yı ölümden diriltti ve biz hepimiz bunun tanıklarıyız.",
    "O, Tanrı'nın sağına yüceltilmiş, vaat edilen Kutsal Ruh'u Baba'dan almış ve şimdi gördüğünüz ve işittiğiniz gibi, bu Ruh'u üzerimize dökmüştür.",
    "Davut, kendisi göklere çıkmadığı halde şöyle der: 'Rab Rabbim'e dedi ki, Ben düşmanlarını Ayaklarının altına serinceye dek, Sağımda otur.'",
    "\"Böylelikle bütün İsrail halkı şunu kesinlikle bilsin: Tanrı, sizin çarmıha gerdiğiniz İsa'yı hem Rab hem Mesih yapmıştır.\"",
    "Bu sözleri duyanlar, yüreklerine hançer saplanmış gibi oldular. Petrus ve öbür elçilere, \"Kardeşler, ne yapmalıyız?\" diye sordular.",
    "Petrus onlara şu karşılığı verdi: \"Tövbe edin, her biriniz İsa Mesih'in adıyla vaftiz olsun. Böylece günahlarınız bağışlanacak ve Kutsal Ruh armağanını alacaksınız.",
    "Bu vaat sizler, çocuklarınız, uzaktakilerin hepsi için, Tanrımız Rab'bin çağıracağı herkes için geçerlidir.\"",
    "Petrus daha birçok sözlerle onları uyardı. \"Kendinizi bu sapık kuşaktan kurtarın!\" diye yalvardı.",
    "Onun sözünü benimseyenler vaftiz oldu. O gün yaklaşık üç bin kişi topluluğa katıldı.",
    "Bunlar kendilerini elçilerin öğretisine, paydaşlığa, ekmek bölmeye ve duaya adadılar.",
    "Herkesi bir korku sarmıştı. Elçilerin aracılığıyla birçok belirtiler ve harikalar yapılıyordu.",
    "İmanlıların tümü bir arada bulunuyor, her şeyi ortaklaşa kullanıyorlardı.",
    "Mallarını mülklerini satıyor ve bunun parasını herkese ihtiyacına göre dağıtıyorlardı.",
    "Her gün tapınakta toplanmaya devam eden imanlılar, kendi evlerinde de ekmek bölüp içten bir sevinç ve sadelikle yemek yiyor ve Tanrı'yı övüyorlardı.",
    "Bütün halkın beğenisini kazanmışlardı. Rab de her gün yeni kurtulanları topluluğa katıyordu.",
    "Herkesi bir korku sarmıştı. Elçilerin aracılığıyla birçok belirtiler ve harikalar yapılıyordu.",
    "İmanlıların tümü bir arada bulunuyor, her şeyi ortaklaşa kullanıyorlardı.",
    "Mallarını mülklerini satıyor ve bunun parasını herkese ihtiyacına göre dağıtıyorlardı.",
    "Her gün tapınakta toplanmaya devam eden imanlılar, kendi evlerinde de ekmek bölüp içten bir sevinç ve sadelikle yemek yiyor ve Tanrı'yı övüyorlardı.",
    "Bütün halkın beğenisini kazanmışlardı. Rab de her gün yeni kurtulanları topluluğa katıyordu.",
  ],
  // Elçilerin İşleri 3 (26 ayet)
  [
    "Bir gün Petrus'la Yuhanna, saat üçte, dua vaktinde tapınağa çıkıyorlardı.",
    "O sırada, doğuştan kötürüm olan bir adam, tapınağın Güzel Kapı diye adlandırılan kapısına getiriliyordu. Tapınağa girenlerden para dilenmesi için onu her gün getirip oraya bırakırlardı.",
    "Tapınağa girmek üzere olan Petrus'la Yuhanna'yı gören adam, kendilerinden sadaka istedi.",
    "Petrus'la Yuhanna ona dikkatle baktılar. Sonra Petrus, \"Bize bak\" dedi.",
    "Adam, onlardan bir şey alacağını umarak gözlerini onların üzerine dikti.",
    "Petrus, \"Bende altın ve gümüş yok, ama bende olanı sana veriyorum\" dedi. \"Nasıralı İsa Mesih'in adıyla, yürü!\"",
    "Sonra onu sağ elinden kavrayıp kaldırdı. Adamın ayakları ve bilekleri o anda sapasağlam oldu.",
    "Sıçrayıp ayağa kalktı, yürümeye başladı. Yürüyüp sıçrayarak, Tanrı'yı överek onlarla birlikte tapınağa girdi.",
    "Bütün halk, onun yürüyüp Tanrı'yı övdüğünü gördü.",
    "Onun, tapınağın Güzel Kapısı'nda oturup para dilenen kişi olduğunu anlayınca ondaki değişiklik karşısında büyük bir hayret ve şaşkınlığa düştüler.",
    "Adam, Petrus'la Yuhanna'ya tutunuyordu. Bütün halk hayret içinde Süleyman'ın Eyvanı denilen yerde onlara doğru koşuştu.",
    "Bunu gören Petrus halka şöyle seslendi: \"Ey İsrailliler, buna neden şaştınız? Neden gözlerinizi dikmiş bize bakıyorsunuz? Kendi gücümüz ya da dindarlığımızla bu adamın yürümesini sağlamışız gibi...!",
    "İbrahim'in, İshak'ın ve Yakup'un Tanrısı, atalarımızın Tanrısı, Kulu İsa'yı yüceltti. Siz O'nu ele verdiniz. Pilatus O'nu serbest bırakmaya karar verdiği halde, siz O'nu Pilatus'un önünde reddettiniz.",
    "Kutsal ve adil Olan'ı reddedip bir katilin salıverilmesini istediniz.",
    "Siz Yaşam Önderi'ni öldürdünüz, ama Tanrı O'nu ölümden diriltti. Biz bunun tanıklarıyız.",
    "Gördüğünüz ve tanıdığınız bu adam, İsa'nın adı sayesinde, O'nun adına olan imanla sapasağlam oldu. Hepinizin gözü önünde onu tam sağlığa kavuşturan, İsa'nın aracılığıyla etkin olan imandır.",
    "\"Şimdi ey kardeşler, yöneticileriniz gibi sizin de bilgisizlikten ötürü böyle davrandığınızı biliyorum.",
    "Ama bütün peygamberlerin ağzından Mesihi'nin acı çekeceğini önceden bildiren Tanrı, sözünü bu şekilde yerine getirmiştir.",
    "Öyleyse, günahlarınızın silinmesi için tövbe edin ve Tanrı'ya dönün.",
    "Öyle ki, Rab size yenilenme fırsatları versin ve sizin için önceden belirlenen Mesih'i, yani İsa'yı göndersin.",
    "Tanrı'nın eski çağlardan beri kutsal peygamberlerinin ağzından bildirdiği gibi, her şeyin yeniden düzenleneceği zamana dek İsa'nın gökte kalması gerekiyor.",
    "Musa şöyle demişti: 'Tanrınız Rab size, kendi kardeşlerinizin arasından benim gibi bir peygamber çıkaracak. O'nun size söyleyeceği her sözü dinleyin.",
    "O peygamberi dinlemeyen herkes Tanrı'nın halkından koparılıp yok edilecektir.'",
    "\"Samuel ve ondan sonra konuşan peygamberlerin hepsi bu günleri duyurdu.",
    "Sizler peygamberlerin mirasçıları, Tanrı'nın atalarınızla yaptığı antlaşmanın mirasçılarısınız. Nitekim Tanrı İbrahim'e şöyle demişti: 'Senin soyunun aracılığıyla yeryüzündeki bütün halklar kutsanacak.'",
    "Tanrı, sizleri kötü yollarınızdan döndürüp kutsamak için Kulu'nu ortaya çıkarıp önce size gönderdi.\"",
  ],
  // Elçilerin İşleri 4 (37 ayet)
  [
    "Kâhinler, tapınak koruyucularının komutanı ve Sadukiler, halka seslenmekte olan Petrus'la Yuhanna'nın üzerine yürüdüler.",
    "Çünkü onların halka öğretmelerine ve İsa'yı örnek göstererek ölülerin dirileceğini söylemelerine çok kızmışlardı.",
    "Onları yakaladılar, akşam olduğu için ertesi güne dek hapiste tuttular.",
    "Ne var ki, konuşmayı dinlemiş olanların birçoğu iman etti. Böylece imanlı erkeklerin sayısı aşağı yukarı beş bine ulaştı.",
    "Ertesi gün Yahudiler'in yöneticileri, ileri gelenleri ve din bilginleri Yeruşalim'de toplandılar.",
    "Başkâhin Hanan'ın yanı sıra, Kayafa, Yuhanna, İskender ve başkâhin soyundan gelen herkes oradaydı.",
    "Petrus'la Yuhanna'yı huzurlarına getirtip onlara, \"Siz bunu hangi güçle ya da kimin adına dayanarak yaptınız?\" diye sordular.",
    "O zaman Kutsal Ruh'la dolan Petrus onlara şöyle dedi: \"Halkın yöneticileri ve ileri gelenler!",
    "Eğer bugün bir hastaya yapılan iyilik nedeniyle bizden hesap soruluyor ve bu adamın nasıl iyileştiği soruşturuluyorsa, hepiniz ve bütün İsrail halkı şunu bilin:",
    "Bu adam, sizin çarmıha gerdiğiniz, ama Tanrı'nın ölümden dirilttiği Nasıralı İsa Mesih'in adı sayesinde önünüzde sapasağlam duruyor.",
    "İsa, 'Siz yapıcılar tarafından hiçe sayılan, ama köşenin baş taşı durumuna gelen taş'tır.",
    "Başka hiç kimsede kurtuluş yoktur. Bu göğün altında insanlara bağışlanmış, bizi kurtarabilecek başka hiçbir ad yoktur.\"",
    "Kurul üyeleri, Petrus'la Yuhanna'nın yürekliliğini görüp de bunların eğitim görmemiş, sıradan kişiler olduklarını anlayınca şaştılar ve onların İsa'yla birlikte bulunduklarını fark ettiler.",
    "İyileştirilen adam, Petrus ve Yuhanna'yla birlikte gözleri önünde duruyordu; bunun için hiçbir karşılık veremediler.",
    "Kurul üyeleri onlara dışarı çıkmalarını buyurduktan sonra durumu kendi aralarında tartışmaya başladılar.",
    "\"Bu adamları ne yapacağız?\" dediler. \"Yeruşalim'de yaşayan herkes, bunların eliyle olağanüstü bir belirti gerçekleştirildiğini biliyor. Biz bunu inkâr edemeyiz.",
    "Ama bu haberin halk arasında daha çok yayılmasını önlemek için onları tehdit edelim ki, bundan böyle İsa'nın adından kimseye söz etmesinler.\"",
    "Böylece onları çağırdılar, İsa'nın adını hiç anmamalarını, o adı kullanarak hiçbir şey öğretmemelerini buyurdular.",
    "Ama Petrus'la Yuhanna şöyle karşılık verdiler: \"Tanrı'nın önünde, Tanrı'nın sözünü değil de sizin sözünüzü dinlemek doğru mudur, kendiniz karar verin.",
    "Biz gördüklerimizi ve işittiklerimizi anlatmadan edemeyiz.\"",
    "Kurul üyeleri onları bir daha tehdit ettikten sonra serbest bıraktılar; onları cezalandırmak için hiçbir gerekçe bulamamışlardı. Çünkü bütün halk, olup bitenler için Tanrı'yı yüceltiyordu.",
    "Nitekim mucize sonucu iyileşen adamın yaşı kırkı geçmişti.",
    "Serbest bırakılan Petrus'la Yuhanna, arkadaşlarının yanına dönerek başkâhinlerle ileri gelenlerin kendilerine söylediği her şeyi bildirdiler.",
    "Arkadaşları bunu duyunca hep birlikte Tanrı'ya şöyle seslendiler: \"Ey Efendimiz! Yeri göğü, denizi ve onların içindekilerin tümünü yaratan sensin.",
    "Kutsal Ruh aracılığıyla kulun atamız Davut'un ağzından şöyle dedin: 'Uluslar neden hiddetlendi, Halklar neden boş düzenler kurdu?",
    "Dünyanın kralları saf bağladı, Hükümdarlar birleşti Rab'be ve Mesihi'ne karşı.'\"",
    "\"Gerçekten de Hirodes ile Pontius Pilatus, bu kentte İsrail halkı ve öteki uluslarla birlikte senin meshettiğin kutsal Kulun İsa'ya karşı bir araya geldiler.",
    "Senin kendi gücün ve isteğinle önceden kararlaştırdığın her şeyi gerçekleştirdiler.\"",
    "Ve şimdi ya Rab, onların savurduğu tehditlere bak! Senin sözünü tam bir yüreklilikle duyurmak için biz kullarına güç ver.",
    "Kutsal Kulun İsa'nın adıyla hastaları iyileştirmek için, belirtiler ve harikalar yapmak için elini uzat.\"",
    "Duaları bitince toplandıkları yer sarsıldı. Hepsi Kutsal Ruh'la doldular ve Tanrı'nın sözünü cesaretle duyurmaya devam ettiler.",
    "İnanlılar topluluğunun yüreği ve düşüncesi birdi. Hiç kimse sahip olduğu hiçbir şey için \"Bu benimdir\" demiyor, her şeylerini ortak sayıyorlardı.",
    "Elçiler, Rab İsa'nın ölümden dirildiğine çok etkili bir biçimde tanıklık ediyorlardı. Tanrı'nın büyük lütfu hepsinin üzerindeydi.",
    "Aralarında yoksul olan yoktu. Çünkü toprak ya da ev sahibi olanlar bunları satar, sattıklarının bedelini getirip elçilerin buyruğuna verirlerdi;",
    "bu da herkese ihtiyacına göre dağıtılırdı.",
    "Örneğin, Kıbrıs doğumlu bir Levili olan ve öğrencilerin Barnaba, yani 'Esirgeyici' diye adlandırdıkları Yusuf, sahip olduğu bir tarlayı sattı,",
    "parasını getirip elçilerin buyruğuna verdi.",
  ],
  // Elçilerin İşleri 5 (42 ayet)
  [
    "Hananya adında bir adam, karısı Safira'nın onayıyla bir mülk sattı, paranın bir kısmını kendine saklayarak gerisini getirip elçilerin buyruğuna verdi.",
    "Karısının da olup bitenlerden haberi vardı.",
    "Petrus ona, \"Hananya, nasıl oldu da Şeytan'a uydun, Kutsal Ruh'a yalan söyleyip tarlanın parasının bir kısmını kendine sakladın?\" dedi.",
    "\"Tarla satılmadan önce sana ait değil miydi? Sen onu sattıktan sonra da parayı dilediğin gibi kullanamaz mıydın? Neden yüreğinde böyle bir düzen kurdun? Sen insanlara değil, Tanrı'ya yalan söylemiş oldun.\"",
    "Hananya bu sözleri işitince yere yıkılıp can verdi. Olanları duyan herkesi büyük bir korku sardı.",
    "Gençler kalkıp Hananya'nın ölüsünü kefenlediler ve dışarı taşıyıp gömdüler.",
    "Bundan yaklaşık üç saat sonra Hananya'nın karısı, olanlardan habersiz içeri girdi.",
    "Petrus, \"Söyle bana, tarlayı bu fiyata mı sattınız?\" diye sordu. \"Evet, bu fiyata\" dedi Safira.",
    "Petrus ona şöyle dedi: \"Rab'bin Ruhu'nu sınamak için nasıl oldu da sözbirliği ettiniz? İşte, kocanı gömenlerin ayak sesleri kapıda, seni de dışarı taşıyacaklar.\"",
    "Kadın o anda Petrus'un ayakları dibine yıkılıp can verdi. İçeri giren gençler onu ölmüş buldular, onu da dışarı taşıyarak kocasının yanına gömdüler.",
    "İnanlılar topluluğunun tümünü ve olayı duyanların hepsini büyük bir korku sardı.",
    "Elçilerin aracılığıyla halk arasında birçok belirtiler ve harikalar yapılıyordu. İmanlıların hepsi Süleyman'ın Eyvanı'nda toplanıyordu.",
    "Halk onlara büyük saygı duyduğu halde, dışarıdan hiç kimse onlara katılmayı göze alamıyordu.",
    "Buna karşın, Rab'be inanıp topluluğa katılan erkek ve kadınların sayısı giderek arttı.",
    "Bütün bunların sonucu, yoldan geçen Petrus'un hiç değilse gölgesi bazılarının üzerine düşsün diye halk, hasta olanları caddelere çıkartıp şilteler ve döşekler üzerine yatırır oldu.",
    "Yeruşalim'in çevresindeki kasabalardan da kalabalıklar geliyor, hastaları ve kötü ruhlardan acı çekenleri getiriyorlardı. Bunların hepsi iyileştirildi.",
    "Bunun üzerine, kıskançlıkla dolan başkâhin ve yanındakilerin hepsi,",
    "yani Saduki mezhebinden olanlar, elçileri yakalatıp devlet tutukevine attırdılar.",
    "Ama geceleyin Rab'bin bir meleği zindanın kapılarını açıp onları dışarı çıkarttı.",
    "\"Gidin! Tapınağa girip bu yeni yaşamla ilgili sözlerin hepsini halka duyurun\" dedi.",
    "Elçiler bu buyruğa uyarak gün doğarken tapınağa girip öğretmeye başladılar. Başkâhin ve yanındakiler gelince Yüksek Kurul'u, İsrail halkının bütün ileri gelenlerini toplantıya çağırdılar. Sonra elçileri getirtmek için tutukevine adam yolladılar.",
    "Ne var ki, görevliler zindana vardıklarında elçileri bulamadılar.",
    "Geri dönerek şu haberi ilettiler: \"Tutukevini kilitli ve tam bir güvenlik altında, nöbetçileri de kapılarda durur bulduk. Ama kapıları açtığımızda içerde kimseyi bulamadık!\"",
    "Bu sözleri işiten tapınak koruyucularının komutanıyla başkâhinler şaşkına döndüler, bu işin sonunun nereye varacağını merak etmeye başladılar.",
    "O sırada yanlarına gelen biri, \"Bakın, hapse attığınız adamlar tapınakta dikilmiş, halka öğretiyor\" diye haber getirdi.",
    "Bunun üzerine komutanla görevliler gidip elçileri getirdiler. Halkın kendilerini taşlamasından korktukları için zor kullanmadılar.",
    "Elçileri getirip Yüksek Kurul'un önüne çıkardılar.",
    "Başkâhin onları sorguya çekti: \"Bu adı kullanarak öğretmeyin diye size kesin buyruk vermiştik\" dedi. \"Ama siz öğretinizi Yeruşalim Kenti'nin her tarafına yaydınız. İlle de bizi bu adamın kanını dökmekten sorumlu göstermek istiyorsunuz.\"",
    "Petrus ve öbür elçiler şöyle karşılık verdiler: \"İnsanlardan çok, Tanrı'nın sözünü dinlemek gerek.",
    "Atalarımızın Tanrısı, sizin çarmıha gererek öldürdüğünüz İsa'yı diriltti.",
    "İsrail'e, günahlarından tövbe etme ve bağışlanma fırsatını vermek için Tanrı O'nu Önder ve Kurtarıcı olarak kendi sağına yükseltti.",
    "Biz, Tanrı'nın kendi sözünü dinleyenlere verdiği Kutsal Ruh'la birlikte bu olayların tanıklarıyız.\"",
    "Kurul üyeleri bu sözleri işitince çok öfkelendiler ve elçileri yok etmek istediler.",
    "Ama bütün halkın saygısını kazanmış bir Kutsal Yasa Öğretmeni olan Gamaliel adlı bir Ferisi, Yüksek Kurul'da ayağa kalktı, elçilerin kısa bir süre için dışarı çıkartılmasını buyurarak kurul üyelerine şunları söyledi:",
    "\"Ey İsrailliler, bu adamlara yapacağınızı iyi düşünün!",
    "Bir süre önce Tevdas da kendi kendisiyle ilgili büyük iddialarda bulunarak başkaldırdı. Dört yüz kadar kişi de ona katıldı. Ama adam öldürüldü, izleyicilerinin hepsi dağıtıldı, hareket yok oldu.",
    "Ondan sonra, sayım yapıldığı günlerde ortaya çıkan Celileli Yahuda, pek çok insanı ayartıp peşine taktı. Ama o da öldürüldü ve izleyicilerinin hepsi darmadağın oldu.",
    "Şimdi size şunu söyleyeyim: Bu adamlarla uğraşmayın, onları rahat bırakın! Çünkü bu girişim, bu hareket insan işiyse, yok olup gidecektir.",
    "Yok eğer Tanrı'nın işiyse, bu adamları yok edemezsiniz, hatta kendinizi Tanrı'ya karşı savaşır durumda bulabilirsiniz.\"",
    "Kurul üyeleri Gamaliel'in bu öğüdünü kabul ettiler. Elçileri içeri çağırtıp kamçılattılar ve İsa'nın adından söz etmemelerini buyurduktan sonra salıverdiler.",
    "Elçiler İsa'nın adı uğruna hakarete layık görüldükleri için Yüksek Kurul'un huzurundan sevinç içinde ayrıldılar.",
    "Her gün tapınakta ve evlerde öğretmekten ve Mesih İsa'yla ilgili Müjde'yi yaymaktan geri kalmadılar.",
  ],
  // Elçilerin İşleri 6 (15 ayet)
  [
    "İsa'nın öğrencilerinin sayıca çoğaldığı o günlerde, Grekçe konuşan Yahudiler, günlük yardım dağıtımında kendi dullarına gereken ilginin gösterilmediğini ileri sürerek İbranice konuşan Yahudiler'den yakınmaya başladılar.",
    "Bunun üzerine Onikiler, bütün öğrencileri bir araya toplayıp şöyle dediler: \"Tanrı'nın sözünü yayma işini bırakıp maddi işlerle uğraşmamız doğru olmaz.",
    "Bu nedenle, kardeşler, aranızdan Ruh'la ve bilgelikle dolu, yedi saygın kişi seçin. Onları bu iş için görevlendirelim.",
    "Biz ise kendimizi duaya ve Tanrı sözünü yaymaya adayalım.\"",
    "Bu öneri bütün topluluğu hoşnut etti. Böylece, iman ve Kutsal Ruh'la dolu biri olan İstefanos'un yanı sıra Filipus, Prohoros, Nikanor, Timon, Parmenas ve Yahudiliğe dönen Antakyalı Nikolas'ı seçtiler.",
    "Bunları elçilerin önüne çıkardılar. Elçiler de dua edip ellerini onların üzerine koydular.",
    "Böylece Tanrı'nın sözü yayılıyor, Yeruşalim'deki öğrencilerin sayısı arttıkça artıyor, kâhinlerden birçoğu da iman çağrısına uyuyordu.",
    "Tanrı'nın lütfuyla ve kudretle dolu olan İstefanos, halk arasında büyük belirtiler ve harikalar yapıyordu.",
    "Ne var ki, Azatlılar Havrası diye bilinen havranın bazı üyeleri ve Kirene'den, İskenderiye'den, Kilikya'dan ve Asya İli'nden bazı kişiler İstefanos'la çekişmeye başladılar.",
    "Ama İstefanos'un konuşmasındaki bilgeliğe ve Ruh'a karşı koyamadılar.",
    "Bunun üzerine birkaç kişiyi el altından ayartarak onlara, \"Bu adamın Musa'ya ve Tanrı'ya karşı küfür dolu sözler söylediğini duyduk\" dedirttiler.",
    "Böylelikle halkı, ileri gelenleri ve din bilginlerini kışkırttılar. Gidip İstefanos'u yakaladılar ve Yüksek Kurul'un önüne çıkardılar.",
    "Getirdikleri yalancı tanıklar, \"Bu adam durmadan bu kutsal yere ve Yasa'ya karşı konuşuyor\" dediler.",
    "\"'Nasıralı İsa burayı yıkacak, Musa'nın bize emanet ettiği töreleri de değiştirecek' dediğini duyduk.\"",
    "Kurul'da oturanların hepsi, İstefanos'a baktıklarında yüzünün bir melek yüzüne benzediğini gördüler.",
  ],
  // Bölüm 7-28 (22 bölüm): gerçek "Yeni Çeviri" metni henüz eklenmedi.
  // Telifli bir çeviri olduğu için doğrulanmamış bir kaynaktan kopyalanmadı —
  // her bölüm tek, dürüst bir bilgi notuyla temsil ediliyor (bkz. proje notları).
  ...Array.from({ length: 22 }, (_, i) => [
    `Elçilerin İşleri ${i + 7}. bölümün metni bu sürümde henüz eklenmedi.`,
  ]),
];
