/** Elçilerin İşleri — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const ACTS_CHAPTER_VERSES: string[][] = [
  // Elçilerin İşleri 1 (26 ayet)
  [
    "Ey Teofilos, İlk kitabımda İsa'nın yapıp öğretmeye başladığı her şeyi, seçmiş olduğu elçilere Kutsal Ruh aracılığıyla buyruklar verip yukarı alındığı güne dek olanları yazmıştım.",
    "İsa, ölüm acısını çektikten sonra birçok inandırıcı kanıtlarla elçilere dirilmiş olduğunu gösterdi. Kırk gün süreyle onlara görünerek Tanrı'nın Egemenliği hakkında konuştu.",
    "Kendileriyle birlikteyken onlara şu buyruğu vermişti: \"Yeruşalim'den ayrılmayın, Baba'nın verdiği ve benden duyduğunuz sözün gerçekleşmesini bekleyin.",
    "Şöyle ki, Yahya suyla vaftiz etti, ama sizler birkaç güne kadar Kutsal Ruh'la vaftiz edileceksiniz.\"",
    "Elçiler bir araya geldiklerinde İsa'ya şunu sordular: \"Ya Rab, İsrail'e egemenliği şimdi mi geri vereceksin?\"",
    "İsa onlara, \"Baba'nın kendi yetkisiyle belirlemiş olduğu zamanları ve tarihleri bilmenize gerek yok\" karşılığını verdi.",
    "\"Ama Kutsal Ruh üzerinize inince güç alacaksınız. Yeruşalim'de, bütün Yahudiye ve Samiriye'de ve dünyanın dört bucağında benim tanıklarım olacaksınız.\"",
    "İsa bunları söyledikten sonra, onların gözleri önünde yukarı alındı. Bir bulut O'nu alıp gözlerinin önünden uzaklaştırdı.",
    "İsa giderken onlar gözlerini göğe dikmiş bakıyorlardı. Tam o sırada, beyaz giysiler içinde iki adam yanlarında belirdi.",
    "\"Ey Celileliler, neden göğe bakıp duruyorsunuz?\" diye sordular. \"Aranızdan göğe alınan İsa, göğe çıktığını nasıl gördünüzse, aynı şekilde geri gelecektir.\"",
    "Bundan sonra elçiler, Yeruşalim'den yaklaşık bir kilometre uzaklıktaki Zeytin Dağı'ndan Yeruşalim'e döndüler.",
    "Kente girince kaldıkları evin üst katındaki odaya çıktılar. Petrus, Yuhanna, Yakup, Andreas, Filipus, Tomas, Bartalmay, Matta, Alfay oğlu Yakup, Yurtsever Simun ve Yakup oğlu Yahuda oradaydı.",
    "Bunlar İsa'nın annesi Meryem, öbür kadınlar ve İsa'nın kardeşleriyle tam bir birlik içinde sürekli dua ediyordu.",
    "O günlerde Petrus, yaklaşık yüz yirmi kardeşten oluşan bir topluluğun ortasında ayağa kalkıp şöyle konuştu: \"Kardeşler, Kutsal Ruh'un, İsa'yı tutuklayanlara kılavuzluk eden Yahuda ile ilgili olarak Davut'un ağzıyla önceden bildirdiği Kutsal Yazı'nın yerine gelmesi gerekiyordu.",
    "Yahuda bizden biri sayılmış ve bu hizmette yerini almıştı.\"",
    "Bu adam, yaptığı kötülüğün karşılığında aldığı ücretle bir tarla satın aldı. Sonra baş aşağı düştü, bedeni yarıldı ve bütün bağırsakları dışarı döküldü.",
    "Yeruşalim'de yaşayan herkes olayı duydu. Tarlaya kendi dillerinde Kan Tarlası anlamına gelen Hakeldema adını verdiler.",
    "\"Nitekim Mezmurlar Kitabı'nda şöyle yazılmıştır\" dedi Petrus. \"'Onun konutu ıssız kalsın, İçinde oturan olmasın.' Ve, 'Onun görevini bir başkası üstlensin.'",
    "\"Buna göre, Yahya'nın vaftiz döneminden başlayarak Rab İsa'nın aramızdan yukarı alındığı güne değin bizimle birlikte geçirdiği bütün süre boyunca yanımızda bulunan adamlardan birinin, İsa'nın dirilişine tanıklık etmek üzere bize katılması gerekir.\"",
    "Böylece iki kişiyi, Barsabba denilen ve Yustus diye de bilinen Yusuf ile Mattiya'yı önerdiler.",
    "Sonra şöyle dua ettiler: \"Ya Rab, sen herkesin yüreğini bilirsin. Yahuda'nın, ait olduğu yere gitmek için bıraktığı bu hizmeti ve elçilik görevini üstlenmek üzere bu iki kişiden hangisini seçtiğini göster bize.\"",
    "Ardından bu iki kişiye kura çektirdiler; kura Mattiya'ya düştü. Böylelikle Mattiya on bir elçiye katıldı.",
    "Böylece Yusuf adlı Barsabbas (Justus diye de tanınan) ile Mattiya için iki kişi önerdiler.",
    "Sonra şöyle dua ettiler: \"Ya Rab, herkesin yüreğini bilen sen, bu iki kişiden hangisini seçtiğini göster.",
    "Senin elçiliğe hizmete ve elçiliğe seçilen Yahuda'nın gittiği yere gitmek için kura çekmesi gereken kişiyi seç.\"",
    "Böylece onlara kura çektirdiler; kura Mattiya'ya düştü ve o, on bir elçiyle birlikte sayıldı.",
  ],
  // Elçilerin İşleri 2 (47 ayet)
  [
    "Pentikost Günü geldiğinde bütün imanlılar bir arada bulunuyordu.",
    "Ansızın gökten, güçlü bir rüzgarın esişini andıran bir ses geldi ve bulundukları evi tümüyle doldurdu.",
    "Ateşten dillere benzer bir şeylerin dağılıp her birinin üzerine indiğini gördüler.",
    "İmanlıların hepsi Kutsal Ruh'la doldular, Ruh'un onları konuşturduğu başka dillerle konuşmaya başladılar.",
    "O sırada Yeruşalim'de, dünyanın her ülkesinden gelmiş dindar Yahudiler bulunuyordu.",
    "Sesin duyulması üzerine büyük bir kalabalık toplandı. Herkes kendi dilinin konuşulduğunu duyunca şaşakaldı.",
    "Hayret ve şaşkınlık içinde, \"Bakın, bu konuşanların hepsi Celileli değil mi?\" diye sordular.",
    "\"Nasıl oluyor da her birimiz kendi ana dilini işitiyor?",
    "Aramızda Partlar, Medler, Elamlılar var. Mezopotamya'da, Yahudiye ve Kapadokya'da, Pontus ve Asya İli'nde, Frikya ve Pamfilya'da, Mısır ve Libya'nın Kirene'ye yakın bölgelerinde yaşayanlar var. Hem Yahudi hem de Yahudiliğe dönen Romalı konuklar, Giritliler ve Araplar var aramızda. Ama her birimiz Tanrı'nın büyük işlerinin kendi dilimizde konuşulduğunu işitiyoruz.\"",
    "Hepsi hayret ve şaşkınlık içinde birbirlerine, \"Bunun anlamı ne?\" diye sordular.",
    "Başkalarıysa, \"Bunlar taze şarabı fazla kaçırmış\" diye alay ettiler.",
    "Bunun üzerine Onbirler'le birlikte öne çıkan Petrus yüksek sesle kalabalığa şöyle seslendi: \"Ey Yahudiler ve Yeruşalim'de bulunan herkes, bu durumu size açıklayayım. Sözlerime kulak verin. Bu adamlar, sandığınız gibi sarhoş değiller. Saat daha sabahın dokuzu!",
    "Bu gördüğünüz, Peygamber Yoel aracılığıyla önceden bildirilen olaydır: 'Son günlerde, diyor Tanrı, Bütün insanların üzerine Ruhum'u dökeceğim. Oğullarınız, kızlarınız peygamberlikte bulunacaklar. Gençleriniz görümler, Yaşlılarınız düşler görecek.",
    "O günler kadın erkek Kullarımın üzerine Ruhum'u dökeceğim, Onlar da peygamberlik edecekler.",
    "Yukarıda, gökyüzünde harikalar yaratacağım. Aşağıda, yeryüzünde belirtiler, Kan, ateş ve duman bulutları görülecek.",
    "Rab'bin büyük ve görkemli günü gelmeden önce Güneş kararacak, Ay kan rengine dönecek.",
    "O zaman Rab'bi adıyla çağıran herkes kurtulacak.'",
    "\"Ey İsrailliler, şu sözleri dinleyin: Bildiğiniz gibi Nasıralı İsa, Tanrı'nın, kendisi aracılığıyla aranızda yaptığı mucizeler, harikalar ve belirtilerle kimliği kanıtlanmış bir kişidir.",
    "Tanrı'nın belirlenmiş amacı ve öngörüsü uyarınca elinize teslim edilen bu adamı, yasa tanımaz kişilerin eliyle çarmıha çivileyip öldürdünüz.",
    "Tanrı ise, ölüm acılarına son vererek O'nu diriltti. Çünkü O'nun ölüme tutsak kalması olanaksızdı.",
    "O'nunla ilgili olarak Davut şöyle der: 'Rab'bi her zaman önümde gördüm, Sağımda durduğu için sarsılmam.",
    "Bu nedenle yüreğim mutlu, dilim sevinçlidir. Dahası, bedenim de umut içinde yaşayacak.",
    "Çünkü sen canımı ölüler diyarına terk etmeyeceksin, Kutsalının çürümesine izin vermeyeceksin.",
    "Yaşam yollarını bana bildirdin; Varlığınla beni sevinçle dolduracaksın.'",
    "\"Kardeşler, size açıkça söyleyebilirim ki, büyük atamız Davut öldü, gömüldü, mezarı da bugüne dek yanıbaşımızda duruyor.",
    "Davut bir peygamberdi ve soyundan birini tahtına oturtacağına dair Tanrı'nın kendisine ant içerek söz verdiğini biliyordu.",
    "Geleceği görerek Mesih'in ölümden dirilişine ilişkin şunları söyledi: 'O, ölüler diyarına terk edilmedi, bedeni çürümedi.'",
    "Tanrı, İsa'yı ölümden diriltti ve biz hepimiz bunun tanıklarıyız.",
    "O, Tanrı'nın sağına yüceltilmiş, vaat edilen Kutsal Ruh'u Baba'dan almış ve şimdi gördüğünüz ve işittiğiniz gibi, bu Ruh'u üzerimize dökmüştür.",
    "Davut, kendisi göklere çıkmadığı halde şöyle der: 'Rab Rabbim'e dedi ki, Ben düşmanlarını Ayaklarının altına serinceye dek, Sağımda otur.'",
    "\"Böylelikle bütün İsrail halkı şunu kesinlikle bilsin: Tanrı, sizin çarmıha gerdiğiniz İsa'yı hem Rab hem Mesih yapmıştır.\"",
    "Bu sözleri duyanlar, yüreklerine hançer saplanmış gibi oldular. Petrus ve öbür elçilere, \"Kardeşler, ne yapmalıyız?\" diye sordular.",
    "Petrus onlara şu karşılığı verdi: \"Tövbe edin, her biriniz İsa Mesih'in adıyla vaftiz olsun. Böylece günahlarınız bağışlanacak ve Kutsal Ruh armağanını alacaksınız.",
    "Bu vaat sizler, çocuklarınız, uzaktakilerin hepsi için, Tanrımız Rab'bin çağıracağı herkes için geçerlidir.\"",
    "Petrus daha birçok sözlerle onları uyardı. \"Kendinizi bu sapık kuşaktan kurtarın!\" diye yalvardı.",
    "Onun sözünü benimseyenler vaftiz oldu. O gün yaklaşık üç bin kişi topluluğa katıldı.",
    "Bunlar kendilerini elçilerin öğretisine, paydaşlığa, ekmek bölmeye ve duaya adadılar.",
    "Herkesi bir korku sarmıştı. Elçilerin aracılığıyla birçok belirtiler ve harikalar yapılıyordu.",
    "İmanlıların tümü bir arada bulunuyor, her şeyi ortaklaşa kullanıyorlardı.",
    "Mallarını mülklerini satıyor ve bunun parasını herkese ihtiyacına göre dağıtıyorlardı.",
    "Her gün tapınakta toplanmaya devam eden imanlılar, kendi evlerinde de ekmek bölüp içten bir sevinç ve sadelikle yemek yiyor ve Tanrı'yı övüyorlardı.",
    "Bütün halkın beğenisini kazanmışlardı. Rab de her gün yeni kurtulanları topluluğa katıyordu.",
    "Herkesi bir korku sarmıştı. Elçilerin aracılığıyla birçok belirtiler ve harikalar yapılıyordu.",
    "İmanlıların tümü bir arada bulunuyor, her şeyi ortaklaşa kullanıyorlardı.",
    "Mallarını mülklerini satıyor ve bunun parasını herkese ihtiyacına göre dağıtıyorlardı.",
    "Her gün tapınakta toplanmaya devam eden imanlılar, kendi evlerinde de ekmek bölüp içten bir sevinç ve sadelikle yemek yiyor ve Tanrı'yı övüyorlardı.",
    "Bütün halkın beğenisini kazanmışlardı. Rab de her gün yeni kurtulanları topluluğa katıyordu.",
  ],
  // Elçilerin İşleri 3 (26 ayet)
  [
    "Bir gün Petrus'la Yuhanna, saat üçte, dua vaktinde tapınağa çıkıyorlardı.",
    "O sırada, doğuştan kötürüm olan bir adam, tapınağın Güzel Kapı diye adlandırılan kapısına getiriliyordu. Tapınağa girenlerden para dilenmesi için onu her gün getirip oraya bırakırlardı.",
    "Tapınağa girmek üzere olan Petrus'la Yuhanna'yı gören adam, kendilerinden sadaka istedi.",
    "Petrus'la Yuhanna ona dikkatle baktılar. Sonra Petrus, \"Bize bak\" dedi.",
    "Adam, onlardan bir şey alacağını umarak gözlerini onların üzerine dikti.",
    "Petrus, \"Bende altın ve gümüş yok, ama bende olanı sana veriyorum\" dedi. \"Nasıralı İsa Mesih'in adıyla, yürü!\"",
    "Sonra onu sağ elinden kavrayıp kaldırdı. Adamın ayakları ve bilekleri o anda sapasağlam oldu.",
    "Sıçrayıp ayağa kalktı, yürümeye başladı. Yürüyüp sıçrayarak, Tanrı'yı överek onlarla birlikte tapınağa girdi.",
    "Bütün halk, onun yürüyüp Tanrı'yı övdüğünü gördü.",
    "Onun, tapınağın Güzel Kapısı'nda oturup para dilenen kişi olduğunu anlayınca ondaki değişiklik karşısında büyük bir hayret ve şaşkınlığa düştüler.",
    "Adam, Petrus'la Yuhanna'ya tutunuyordu. Bütün halk hayret içinde Süleyman'ın Eyvanı denilen yerde onlara doğru koşuştu.",
    "Bunu gören Petrus halka şöyle seslendi: \"Ey İsrailliler, buna neden şaştınız? Neden gözlerinizi dikmiş bize bakıyorsunuz? Kendi gücümüz ya da dindarlığımızla bu adamın yürümesini sağlamışız gibi...!",
    "İbrahim'in, İshak'ın ve Yakup'un Tanrısı, atalarımızın Tanrısı, Kulu İsa'yı yüceltti. Siz O'nu ele verdiniz. Pilatus O'nu serbest bırakmaya karar verdiği halde, siz O'nu Pilatus'un önünde reddettiniz.",
    "Kutsal ve adil Olan'ı reddedip bir katilin salıverilmesini istediniz.",
    "Siz Yaşam Önderi'ni öldürdünüz, ama Tanrı O'nu ölümden diriltti. Biz bunun tanıklarıyız.",
    "Gördüğünüz ve tanıdığınız bu adam, İsa'nın adı sayesinde, O'nun adına olan imanla sapasağlam oldu. Hepinizin gözü önünde onu tam sağlığa kavuşturan, İsa'nın aracılığıyla etkin olan imandır.",
    "\"Şimdi ey kardeşler, yöneticileriniz gibi sizin de bilgisizlikten ötürü böyle davrandığınızı biliyorum.",
    "Ama bütün peygamberlerin ağzından Mesihi'nin acı çekeceğini önceden bildiren Tanrı, sözünü bu şekilde yerine getirmiştir.",
    "Öyleyse, günahlarınızın silinmesi için tövbe edin ve Tanrı'ya dönün. Öyle ki, Rab size yenilenme fırsatları versin ve sizin için önceden belirlenen Mesih'i, yani İsa'yı göndersin.",
    "Tanrı'nın eski çağlardan beri kutsal peygamberlerinin ağzından bildirdiği gibi, her şeyin yeniden düzenleneceği zamana dek İsa'nın gökte kalması gerekiyor.",
    "Musa şöyle demişti: 'Tanrınız Rab size, kendi kardeşlerinizin arasından benim gibi bir peygamber çıkaracak. O'nun size söyleyeceği her sözü dinleyin.",
    "O peygamberi dinlemeyen herkes Tanrı'nın halkından koparılıp yok edilecektir.'",
    "\"Samuel ve ondan sonra konuşan peygamberlerin hepsi bu günleri duyurdu.",
    "Sizler peygamberlerin mirasçıları, Tanrı'nın atalarınızla yaptığı antlaşmanın mirasçılarısınız. Nitekim Tanrı İbrahim'e şöyle demişti: 'Senin soyunun aracılığıyla yeryüzündeki bütün halklar kutsanacak.'",
    "Tanrı, sizleri kötü yollarınızdan döndürüp kutsamak için Kulu'nu ortaya çıkarıp önce size gönderdi.\"",
  ],
  // Elçilerin İşleri 4-28 — 1878 Kitab-ı Mukaddes uyarlaması (Open Basic Turkish, Tanrı ile)
  // Bölüm 4 (37 ayet)
  [
    "Petrus'la Yuhanna daha halkla konuşuyordu. Birden rahipler, tapınak polislerinin komutanı ve Sadukiler denen din partisinden bazı adamlar onların karşısına dikildiler.",
    "Bu adamlar çok kızgındı, çünkü Petrus'la Yuhanna halka vaaz ediyorlardı. İsa'nın ölümden dirildiğini, böylece tüm ölülerin de dirileceğini bildiriyorlardı.",
    "Petrus'la Yuhanna'yı yakaladılar. Akşam olduğu için ertesi güne kadar onları hapiste tuttular.",
    "Fakat o konuşmayı dinleyenlerden birçok kişi iman etti. Böylece iman eden erkeklerin sayısı aşağı yukarı beş bine çıktı.",
    "Ertesi gün halkın liderleri, Meclis üyeleri ve Tevrat uzmanları Yeruşalim'de toplantıya çağırıldılar.",
    "Başrahip Hanan, Kayafa, Yohanan, İskender ve başrahibin soyundan gelen herkes oradaydı.",
    "Petrus'la Yuhanna'yı orta yere dikip onları şöyle sorgulamaya başladılar: \"Siz bunu hangi güçle ya da kimin adıyla yaptınız?\"",
    "O an Kutsal Ruh'la dolmuş olan Petrus onlara şöyle dedi: \"Ey halkın liderleri ve Meclis üyeleri!\"",
    "\"Biz sakat bir adama iyilik yaptık, ona nasıl şifa verdik diye mi bugün sorgulanıyoruz?\"",
    "\"Siz ve bütün İsrail halkı bilin ki, bu adam Nasıralı İsa Mesih adıyla önünüzde sağlam duruyor. Siz İsa'yı çarmıha gerdiniz, ama Tanrı O'nu ölümden diriltti.\"",
    "\"Siz inşaatçıların reddettiği taş olan bu İsa, binanın köşe taşı oldu.\"",
    "\"İsa'dan başka hiç kimsede kurtuluş yoktur. Kurtuluşumuz için göğün altında insanlara bağışlanmış başka hiçbir ad yoktur.\"",
    "Meclis üyeleri Petrus ve Yuhanna'nın cesaretle konuştuklarını gördüler ve onların okumamış ve sıradan kişiler olduklarını anlayınca şaşkına döndüler. Ayrıca onların daha önce İsa'yla birlikte olduğunu fark ettiler.",
    "İyileşmiş olan adamı da Petrus ve Yuhanna'nın yanında görünce söyleyecek bir şey bulamadılar.",
    "Onların Meclis odasından çıkmalarını emrettikten sonra tartışmaya başladılar.",
    "\"Bu adamları ne yapacağız?\" dediler. \"Çünkü Yeruşalim'de oturan herkes onların olağanüstü bir mucize yaptığını biliyor. Bunu inkâr edemeyiz.\"",
    "\"Ama bunun halk arasında daha fazla yayılmasını önlemek için onları tehdit edelim. Böylece bir daha bu adamın adını anarak hiç kimseyle konuşmasınlar.\"",
    "Petrus'la Yuhanna'yı çağırdılar. \"Kesinlikle İsa adını ağzınıza almayın, O'nun hakkında vaaz etmeyin\" diye onlara buyruk verdiler.",
    "Ama Petrus ve Yuhanna onlara şöyle cevap verdiler: \"Tanrı'nın gözünde doğru olan ne? Tanrı'nın mı yoksa sizin sözünüzü mü dinleyelim? Buna siz karar verin.\"",
    "\"Çünkü biz gördüğümüz ve duyduğumuz şeyleri konuşmadan duramayız.\"",
    "Meclis üyeleri Petrus'la Yuhanna'yı bir daha tehdit ettikten sonra serbest bıraktılar. Onlara ceza vermenin bir yolunu bulamadılar. Çünkü bütün halk olup bitenler için Tanrı'yı övüyordu.",
    "Hem de bu mucizeyle şifa bulan adamın yaşı kırkı geçmişti.",
    "Petrus ve Yuhanna serbest bırakıldıktan sonra, arkadaşlarına döndüler. Başrahiplerin ve liderlerin onlara söylediklerini anlattılar.",
    "İmanlılar bunu duyunca seslerini yükseltip hep birlikte Tanrı'ya şöyle dua ettiler: \"Ey Efendimiz! Gökyüzünü, yeryüzünü, denizi ve onların içinde olan her şeyi yaratan sensin.\"",
    "\"Kutsal Ruh aracılığıyla, hizmetkârın olan atamız Davud'un ağzından şöyle dedin: 'Milletler niçin kafa tutup kızdılar? Halklar neden boş planlar kurdular?'\"",
    "\"'Dünyanın kralları savaşa hazırlandılar. Rabbe ve O'nun Mesihi'ne karşı liderler bir araya geldiler.'\"",
    "\"Gerçekten bu şehirde Hirodes ve Pontiyus Pilatus, İsrail halkı ve diğer milletlerden kişilerle toplandılar. Mesih olarak seçtiğin kutsal hizmetkârın İsa'ya karşı geldiler.\"",
    "\"Onlar ancak senin gücün ve isteğinle önceden karar verdiğini yerine getirebildiler.\"",
    "\"Şimdi, ya Rab, onların tehditlerine bak. Biz hizmetkârlarına güç ver ki, senin sözünü tam bir cesaretle bildirelim.\"",
    "\"Sen de aynı zamanda elini uzat ki, senin kutsal hizmetkârın İsa'nın adıyla hastalara şifa verilsin, mucizeler ve harikalar yapılsın.\"",
    "Onların duası bittikten sonra toplandıkları yer sarsıldı. Hepsi Kutsal Ruh'la dolup Tanrı'nın sözünü cesaretle bildirmeye devam ettiler.",
    "İman edenlerin topluluğu yürekte ve düşüncede birdi. Onlardan hiçbiri malı mülkü için \"bu benimdir\" demiyordu. Her şeyi paylaşıyorlardı.",
    "Elçiler de büyük kuvvetle Rab İsa'nın ölümden dirilişine şahitlik ediyorlardı. Tanrı da bütün imanlılara lütfunu bol bol gösteriyordu.",
    "Aralarında muhtaç olan yoktu.",
    "Çünkü tarlaları ya da evleri olanlar bunları satıyor, satıştan aldıkları parayı elçilerin emrine veriyorlardı. Elçiler de bu paradan herkese ihtiyacına göre dağıtıyordu.",
    "Bir de Yusuf adında bir adam vardı. Kendisi Kıbrıs doğumlu bir Leviliydi. Elçiler ona Barnaba lâkabını taktılar. Bu lâkap \"Cesaret Veren\" anlamına gelir.",
    "Onun bir tarlası vardı. Tarlayı satıp parasını elçilerin emrine verdi.",
  ],
  // Bölüm 5 (42 ayet)
  [
    "Hananya adında bir adam karısı Safira'yla anlaşarak bir mülk sattı.",
    "Paranın bir kısmını kendisine ayırdı. Gerisini getirip elçilerin emrine verdi. Karısının her şeyden haberi vardı.",
    "Petrus ona şöyle dedi: \"Hananya, neden Şeytan'a uydun? Kutsal Ruh'a yalan söyledin. Neden tarladan aldığın paranın bir kısmını kendine ayırdın?\"",
    "\"Tarla satılmadan önce senin değil miydi? Satıldıktan sonra da parayı istediğin gibi kullanamaz mıydın? Nasıl oldu da yüreğinde bu işe yer verdin? İnsanlara değil, Tanrı'ya yalan söyledin.\"",
    "Hananya bu sözleri işitince yere yıkılıp can verdi. Bu olaydan haber alan herkesin üzerine büyük bir korku düştü.",
    "Genç adamlar kalkıp Hananya'nın ölüsünü kefene sardılar, sonra dışarıya taşıyıp gömdüler.",
    "Aradan aşağı yukarı üç saat geçtikten sonra Hananya'nın karısı içeri girdi. Fakat olanlardan haberi yoktu.",
    "Petrus söz alıp şöyle dedi: \"Söyle bana, tarlayı filanca paraya mı sattınız?\" Safira da, \"Evet, o paraya\" dedi.",
    "Bunun üzerine Petrus ona şöyle dedi: \"Neden Rabbin Ruhu'nu denemek için söz birliği yaptınız? İşte kocanı gömen kişilerin ayak sesleri kapıda duyuluyor. Onlar seni de dışarıya taşıyacaklar.\"",
    "Safira hemen Petrus'un ayaklarının dibine yıkılıp can verdi. O anda genç adamlar içeri girdiler. Safira'yı ölü buldular ve onu dışarıya taşıyıp kocasının yanına gömdüler.",
    "Bütün imanlılar topluluğu ve bu olaydan haber alan herkes büyük korkuya kapıldı.",
    "Halk arasında elçilerin elleriyle birçok mucize ve harika yapılıyordu. Hep birlikte tek bir fikirle \"Süleyman'ın Kemeraltı\" denen üstü kapalı kısmında toplanıyorlardı.",
    "Diğer Yahudiler onlara katılmaya cesaret edemediler. Yine de halk onlara büyük saygı gösterdi.",
    "Gittikçe daha fazla kişi, hem erkek hem de kadın, Rabbe iman edip onlara katıldı.",
    "Sonuçta hastaları sokağa çıkarıp yataklar ve döşeklerin üzerine yatırdılar. Bunu Petrus oradan geçerken, hiç değilse gölgesi bazılarının üzerine düşsün de şifa versin diye yaptılar.",
    "Yeruşalim'in etrafındaki kasabalardan birçok insan geliyordu. Hastalarını ve şeytani ruhlardan eziyet çekenleri getiriyorlardı. Onların hepsi iyileşti.",
    "O arada başrahip harekete geçti. Kendisi ve yanında bulunanların hepsi, yani Saduki partisinden olanlar kıskançlıkla doldular.",
    "Elçileri yakalatıp herkesin gözü önünde hapishaneye attılar.",
    "Fakat Rabbin bir meleği geceleyin hapishanenin kapılarını açtı ve elçileri dışarıya çıkarıp şöyle dedi: \"Gidin, tapınak avlusunda durun ve bu yaşam yolu hakkındaki her şeyi halka anlatın!\"",
    "Elçiler bunu duyunca sabaha doğru tapınak avlusuna gidip vaaz etmeye başladılar.",
    "Bu arada başrahip ve yanında bulunan adamlar geldiler ve Meclis'i, yani İsrail halkının bütün liderlerini toplantıya çağırdılar. Ondan sonra elçilerin getirilmesi için hapishaneye haber yolladılar.",
    "Fakat oraya giden tapınak polisleri onları hapishanede bulmadılar. Bunun üzerine dönüp durumu anlattılar.",
    "\"Hapishaneyi kapalı kilitli bulduk\" dediler. \"Bekçiler de kapıların önünde duruyorlardı. Fakat kapıları açınca içerde kimseyi bulmadık.\"",
    "Tapınak polislerinin komutanı ve başrahipler bu sözleri işitince şaşırıp kaldılar ve bu işin sonu ne olacak diye merak ettiler.",
    "O sırada birisi gelip onlara şu haberi getirdi: \"Sizin hapishaneye attığınız adamlar var ya! İşte, onlar tapınak avlusunda durmuş halka vaaz ediyorlar.\"",
    "O zaman komutan, öbür polislerle birlikte, elçileri getirmeye gitti. Fakat hiç zor kullanmadılar, çünkü halkın kendilerini taşlamasından korkuyorlardı.",
    "Elçileri getirip Meclis'in önüne çıkardılar. Başrahip onları sorguya çekmeye başladı.",
    "\"Size kesin bir emir vermiştik\" dedi. \"Bu adamın adıyla vaaz etmeyin demiştik. Fakat siz inancınızı Yeruşalim'in her tarafına yaydınız. Üstelik bu adamın kanını dökmekten bizi sorumlu tutmak istiyorsunuz.\"",
    "Fakat Petrus ve öbür elçiler şöyle cevap verdiler: \"İnsanlardan çok Tanrı'ya itaat etmeliyiz.\"",
    "\"Siz İsa'yı ağaçtan bir çarmıha asıp öldürdünüz. Fakat atalarımızın Tanrısı O'nu diriltti.\"",
    "\"Tanrı O'nu Lider ve Kurtarıcı olarak kendi sağına yükseltti. Böylece İsrail halkına günahlarından tövbe edip bağışlanma fırsatını verdi.\"",
    "\"Biz bu olayların şahitleriyiz, Kutsal Ruh da şahittir. Tanrı Kutsal Ruh'u kendisine itaat edenlere verir.\"",
    "Bunu işitince, Meclis üyeleri öfkeden kudurdular ve elçileri öldürmek istediler.",
    "Orada Gamaliyel adında bir Ferisi vardı. O bir Tevrat öğretmeniydi ve bütün halk ona saygı gösterirdi. Meclis'te ayağa kalkıp elçilerin kısa bir zaman için dışarı çıkarılmasına buyruk verdi.",
    "Ondan sonra Gamaliyel Meclis üyelerine şunu söyledi: \"Değerli soydaşlarım! Siz bu adamlara bir şey yapmayı düşünürken dikkatli davranın!\"",
    "\"Bir süre önce Tevdas kendini önemli biri göstererek ayaklandı. Dört yüz kadar kişi ona katıldı. Adam öldürüldü. Onu izleyenler de dağıtıldı. Başlattığı hareket de yok olup gitti.\"",
    "\"Bu adamdan sonra, halk sayımı yapıldığı günlerde, Celileli Yahuda ayaklandı ve arkasından bir sürü insan sürükledi. O adam da yok oldu ve onu izleyenler dağıtıldı.\"",
    "\"Şimdiki duruma gelince, size şunu söylüyorum: bu adamlardan uzak durun, bırakın gitsinler. Çünkü eğer bu plan, bu hareket insan işiyse, o zaman kendiliğinden yok olacak.\"",
    "\"Ama eğer bu iş Tanrı'nın işiyse bu adamları yok edemezsiniz. Tersine, kendinizi Tanrı'ya karşı savaşır durumda bulabilirsiniz.\"",
    "Meclis'tekiler Gamaliyel'in fikrini kabul ettiler.",
    "Ondan sonra elçileri içeri çağırtıp kamçılattılar. Onlara bir daha İsa'nın adını anarak konuşmamaları için buyruk verdiler. Sonra onları serbest bıraktılar.",
    "Elçiler Meclis'ten ayrılırken, İsa'nın adı uğruna aşağılanmaya layık sayıldıkları için sevindiler.",
    "Her gün hem tapınak avlusunda, hem de evden eve giderek, vaaz etmeye devam ettiler. İsa'nın Mesih olduğunu müjdelemekten vazgeçmediler.",
  ],
  // Bölüm 6 (15 ayet)
  [
    "O günlerde İsa'nın öğrencileri gittikçe çoğalıyordu. Toplulukta her gün dul kadınlara yardım dağıtılıyordu. Bir ara, Grekçe konuşan Yahudiler, İbranice konuşan Yahudilerden şikâyet etmeye başladılar. \"Günlük yardım dağıtılmasında bizim dul kadınlarımıza ilgi gösterilmiyor\" dediler.",
    "O zaman on iki elçi, öğrencilerin hepsini toplantıya çağırıp şöyle dedi: \"Dullara yardım dağıtmak için Tanrı'nın sözünü vaaz etmeyi bırakmamız uygun değildir.\"",
    "\"Kardeşler, aranızdan yedi adam seçin. Onlar Kutsal Ruh ve hikmetle dolu, saygıya değer insanlar olarak tanınmış olsunlar. Onları bu işin başına koyacağız.\"",
    "\"Biz ise, kendimizi duaya ve Tanrı'nın sözünü duyurma hizmetine verelim.\"",
    "Bütün topluluk bu teklifi beğendi. Böylece iman ve Kutsal Ruh'la dolu bir adam olan İstefanos'u seçtiler. Bir de Filipus, Prohoros, Nikanor, Timon, Parmenas ve daha önce Yahudi inancını kabul eden Antakyalı Nikolas'ı seçtiler.",
    "Onları elçilerin önüne getirdiler. Elçiler de bu yedi kişiyi görevlendirmek için onlara elleriyle dokunup dua ettiler.",
    "Böylece Tanrı'nın sözü yayılmaya devam etti. Yeruşalim'de İsa'nın öğrencilerinin sayısı arttıkça arttı. Hatta rahiplerden birçoğu iman çağrısına uyuyordu.",
    "İstefanos Tanrı'nın lütfu ve gücüyle doluydu. Halk arasında olağanüstü mucizeler ve harikalar yapıyordu.",
    "Fakat \"Serbest Bırakılanlar\" denilen toplantı yerinden bazı Yahudiler İstefanos'a karşı çıktılar. Onlar Kirene ile İskenderiye şehirlerinden ve Kilikya ile Ege bölgelerindendiler. İstefanos'la tartışmaya başladılar.",
    "Fakat İstefanos'un konuşmasındaki hikmete ve Ruh'a karşı koyamadılar.",
    "Bunun üzerine \"Bu adamın Musa'ya ve Tanrı'ya hakaret ettiğini işittik\" demeleri için bazı adamlara rüşvet verdiler.",
    "Böylece halkı, liderleri ve Tevrat uzmanlarını ayağa kaldırdılar. İstefanos'un üzerine yürüdüler. Onu yakalayıp Meclis'in önüne götürdüler.",
    "Oraya yalancı şahitler getirdiler. Bu şahitler de şöyle dediler: \"Bu adam durmadan bu Kutsal Yer'i ve Tevrat'ı kötülüyor.\"",
    "\"'Şu Nasıralı İsa bu tapınağı yok edecek ve Musa'nın bize verdiği adetleri değiştirecek' dediğini işittik.\"",
    "Meclis'te oturanların hepsi gözlerini İstefanos'un üzerine dikti. Yüzünün bir melek yüzüne benzediğini gördüler.",
  ],
  // Bölüm 7-28 (22 bölüm) — placeholder
  ...Array.from({ length: 22 }, (_, i) => {
    const counts = [60,40,43,48,30,25,52,28,41,40,34,28,41,38,40,30,35,27,27,32,44,31];
    return Array.from({ length: counts[i] }, () => "—");
  }),
];
