/** Koloseliler — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const COLOSSIANS_CHAPTER_VERSES: string[][] = [
  // Koloseliler 1 (29 ayet)
  [
    "Tanrı'nın isteğiyle Mesih İsa'nın elçisi atanan ben Pavlus ve kardeşimiz Timoteos'tan, Kolose'de bulunan, Mesih'e ait kutsal ve sadık kardeşlere selam!",
    "Babamız Tanrı'dan sizlere lütuf ve esenlik olsun.",
    "Sizler için dua ederken Tanrı'ya, Rabbimiz İsa Mesih'in Babası'na her zaman şükrediyoruz.",
    "Çünkü Mesih İsa'ya iman ettiğinizi ve bütün kutsalları sevdiğinizi duyduk.",
    "İmanınız ve sevginiz göklerde sizin için saklı bulunan umuttan kaynaklanıyor. Bu umudun haberini gerçeğin bildirisinden, size daha önce ulaşan Müjde'den aldınız.",
    "Müjde, onu işittiğiniz ve Tanrı'nın lütfunu gerçekten anladığınız günden beri aranızda olduğu gibi, bütün dünyada da meyve vermekte, yayılmaktadır.",
    "Müjde'yi bizim adımıza Mesih'in güvenilir hizmetkârı olan sevgili emektaşımız Epafras'tan öğrendiniz.",
    "Ruh'tan kaynaklanan sevginizi de bize o bildirdi.",
    "Bunu işittiğimiz günden beri biz de sizler için dua etmekten, tam bir bilgelik ve ruhsal anlayışla Tanrı'nın isteğini bütünüyle bilmenizi dilemekten geri kalmadık.",
    "Rab'be yaraşır biçimde yaşamanız, O'nu her yönden hoşnut etmeniz, her iyi işte meyve vererek Tanrı'yı tanımakta ilerlemeniz için dua ediyoruz.",
    "Her şeye sevinçle katlanıp sabredebilmeniz için O'nun yüce gücüne dayanarak bütün kudretle güçlenmenizi diliyoruz.",
    "Bizi kutsalların ışıktaki mirasına ortak olmaya yeterli kılan Baba'ya şükretmeniz için dua ediyoruz.",
    "O bizi karanlığın hükümranlığından kurtarıp sevgili Oğlu'nun egemenliğine aktardı.",
    "O'nda kurtuluşa, günahlarımızın bağışına sahibiz.",
    "Görünmez Tanrı'nın görünümü, bütün yaratılışın ilk doğanı O'dur.",
    "Nitekim yerde ve gökte, görünen ve görünmeyen her şey -tahtlar, egemenlikler, yönetimler, hükümranlıklar- O'nda yaratıldı. Her şey O'nun aracılığıyla ve O'nun için yaratıldı.",
    "Her şeyden önce var olan O'dur ve her şey varlığını O'nda sürdürmektedir.",
    "Bedenin, yani kilisenin başı O'dur. Her şeyde ilk yeri alsın diye başlangıç olan ve ölüler arasından ilk doğan O'dur.",
    "Çünkü Tanrı bütün doluluğunun O'nda bulunmasını uygun gördü.",
    "Mesih'in çarmıhta akıtılan kanı aracılığıyla esenliği sağlamış olarak yerdeki ve gökteki her şeyi O'nun aracılığıyla kendisiyle barıştırmaya razı oldu.",
    "Yaptığınız kötülükler yüzünden bir zamanlar düşüncelerinizde Tanrı'ya yabancı ve düşmandınız.",
    "Şimdiyse Mesih sizi Tanrı'nın önüne kutsal, lekesiz ve kusursuz olarak çıkarmak için öz bedeninin ölümü sayesinde sizi Tanrı'yla barıştırdı.",
    "Yeter ki, duyduğunuz Müjde'nin verdiği umuttan kopmadan, imanda temellenip yerleşmiş olarak kalın. Ben Pavlus, göğün altındaki bütün yaratılışa duyurulan bu Müjde'nin hizmetkârı oldum.",
    "Sizin için acı çektiğime şimdi seviniyorum. Mesih'in, kendi bedeni, yani kilise uğruna çektiği sıkıntılardan eksik kalanlarını kendi bedenimde tamamlıyorum.",
    "Tanrı'nın sizin yararınıza bana verdiği görevle kilisenin hizmetkârı oldum.",
    "Görevim, Tanrı'nın sözünü, yani geçmiş çağlardan ve kuşaklardan gizlenmiş, ama şimdi O'nun kutsallarına açıklanmış olan sırrı eksiksiz duyurmaktır.",
    "Tanrı kutsallarına bu sırrın uluslar arasında ne denli yüce ve zengin olduğunu bildirmek istedi. Bu sırrın özü şudur: Mesih içinizdedir. Bu da size yüceliğe kavuşma umudunu veriyor.",
    "Her insanı Mesih'te yetkinleşmiş olarak Tanrı'ya sunmak için herkesi uyararak ve herkesi tam bir bilgelikle eğiterek Mesih'i tanıtıyoruz.",
    "O'nun kudretle bende etkin olan gücüne dayanarak uğraşıp emek vermemin amacı da budur.",
  ],
  // Koloseliler 2 (23 ayet)
  [
    "Gerek sizler, gerek Laodikya'dakiler, gerekse sizler gibi yüzümü hiç görmemiş olanlar için ne denli büyük bir uğraş verdiğimi bilmenizi isterim.",
    "Yüreklerinin cesaret bulmasını, sevgide birleşmelerini dilerim.",
    "Öyle ki, anlayışın verdiği tam güvenliğin bütün zenginliğine kavuşsunlar ve Tanrı'nın sırrını, yani bilginin ve bilgeliğin bütün hazinelerinin saklı olduğu Mesih'i tanısınlar.",
    "Kimse sizi kulağı okşayan sözlerle aldatmasın diye söylüyorum bunu.",
    "Çünkü her ne kadar bedence aranızda değilsem de, ruhça sizinle birlikteyim. Düzenliliğinizi, Mesih'e imanınızın sağlamlığını görüp seviniyorum.",
    "Bu nedenle Rab Mesih İsa'yı nasıl kabul ettinizse, O'nda öylece yaşayın.",
    "Şükranla dolup taşarak O'nda köklenin ve gelişin, size öğretildiği gibi imanda güçlenin.",
    "Dikkatli olun! Mesih'e değil de, insanların geleneğine, dünyanın temel ilkelerine dayanan felsefeyle, boş ve aldatıcı sözlerle kimse sizi tutsak etmesin.",
    "Çünkü Tanrılığın bütün doluluğu bedence Mesih'te bulunuyor.",
    "Siz de her yönetim ve hükümranlığın başı olan Mesih'te doluluğa kavuştunuz.",
    "Ayrıca Mesih'in gerçekleştirdiği sünnet sayesinde bedenin benliğinden soyunarak elle yapılmayan sünnetle O'nda sünnet edildiniz.",
    "Vaftizde O'nunla birlikte gömüldünüz, O'nu ölümden dirilten Tanrı'nın gücüne iman ederek O'nunla birlikte dirildiniz.",
    "Sizler suçlarınız ve benliğinizin sünnetsizliği yüzünden ölüyken, Tanrı sizi Mesih'le birlikte yaşama kavuşturdu. Bütün suçlarımızı O bağışladı.",
    "Kurallarıyla bize karşı ve aleyhimizde olan yazılı antlaşmayı sildi, onu çarmıha çakarak ortadan kaldırdı.",
    "Yönetimlerin ve hükümranlıkların elindeki silahları alıp onları çarmıhta yenerek açıkça gözler önüne serdi.",
    "Bu nedenle kimse yiyecek içecek, bayram, yeni ay ya da Şabat Günü konusunda sizi yargılamasın.",
    "Bunlar gelecek şeylerin gölgesidir, aslı ise Mesih'tedir.",
    "Sözde alçakgönüllülükte ve meleklere tapınmakta direnen, gördüğü düşlerin üzerinde durarak benliğin düşünceleriyle boş yere böbürlenen, Baş'a tutunmayan hiç kimse sizi ödülünüzden yoksun bırakmasın.",
    "Bütün beden eklemler ve bağlar yardımıyla bu Baş'tan beslenip bütlenmekte, Tanrı'nın sağladığı büyümeyle gelişmektedir.",
    "Mesih'le birlikte ölüp dünyanın temel ilkelerinden kurtulduğunuza göre, niçin dünyada yaşayanlar gibi, \"Şunu elleme\", \"Bunu tatma\", \"Şuna dokunma\" gibi kurallara uyuyorsunuz?",
    "Bu kuralların hepsi, kullanıldıkça yok olacak nesnelerle ilgilidir; insanların buyruklarına, öğretilerine dayanır.",
    "Kuşkusuz bu kuralların gönüllü tapınma, sözde alçakgönüllülük, bedene eziyet açısından bilgece bir görünüşü vardır; ama benliğin tutkularını denetlemekte hiçbir yararları yoktur.",
  ],
  // Koloseliler 3 (25 ayet)
  [
    "Mesih'le birlikte dirildiğinize göre, gökteki değerlerin ardından gidin. Mesih orada, Tanrı'nın sağında oturuyor.",
    "Yeryüzündeki değil, gökteki değerleri düşünün.",
    "Çünkü siz öldünüz, yaşamınız Mesih'le birlikte Tanrı'da saklıdır.",
    "Yaşamınız olan Mesih göründüğü zaman, siz de O'nunla birlikte yücelmiş olarak görüneceksiniz.",
    "Bu nedenle bedenin dünyasal eğilimlerini -fuhşu, pisliği, şehveti, kötü arzuları ve putperestlikle eş olan açgözlülüğü- öldürün.",
    "Bunlar yüzünden Tanrı'nın gazabı söz dinlemeyenlerin üzerine geliyor.",
    "Geçmişte bunlarla iç içe yaşadığınız zaman siz de bu yollarda yürüdünüz.",
    "Ama şimdi öfke, kızgınlık, kötü niyet dahil, hepsini üzerinizden sıyırıp atın. Ağzınızdan hiçbir iftira ya da edepsiz söz çıkmasın.",
    "Birbirinize yalan söylemeyin. Çünkü eski yaradılışı kötü alışkanlıklarıyla birlikte üzerinizden çıkarıp attınız;",
    "eksiksiz bilgiye erişmek için Yaratıcısı'na benzer olmak üzere yenilenen yeni yaradılışı giyindiniz.",
    "Bu yenilikte Grek ve Yahudi, sünnetli ve sünnetsiz, barbar, İskit, köle ve özgür ayrımı yoktur. Mesih her şeydir ve her şeydedir.",
    "Öyleyse, Tanrı'nın kutsal ve sevgili seçilmişleri olarak yürekten sevecenliği, iyiliği, alçakgönüllülüğü, sabrı, yumuşaklığı giyinin.",
    "Birbirinize hoşgörülü davranın. Birinizin ötekinden bir şikâyeti varsa, Rab'bin sizi bağışladığı gibi, siz de birbirinizi bağışlayın.",
    "Bunların hepsinin üzerine yetkin birliğin bağı olan sevgiyi giyinin.",
    "Mesih'in esenliği yüreklerinizde hakem olsun. Tek bir bedenin üyeleri olarak bu esenliğe çağrıldınız. Şükredici olun!",
    "Mesih'in sözü bütün zenginliğiyle içinizde yaşasın. Tam bir bilgelikle birbirinize öğretin, öğüt verin, mezmurlar, ilahiler, ruhsal ezgiler söyleyerek yüreklerinizde şükranla Tanrı'ya nağmeler yükseltin.",
    "Söylediğiniz, yaptığınız her şeyi Rab İsa'nın adıyla, O'nun aracılığıyla Baba Tanrı'ya şükrederek yapın.",
    "Ey kadınlar, Rab'be ait olanlara yaraşır biçimde kocalarınıza bağımlı olun.",
    "Ey kocalar, karılarınızı sevin. Onlara sert davranmayın.",
    "Ey çocuklar, her konuda anne babalarınızın sözünü dinleyin. Çünkü bu Rab'bi hoşnut eder.",
    "Ey babalar, çocuklarınızı incitmeyin, yoksa cesaretleri kırılır.",
    "Ey köleler, dünyadaki efendilerinizin her sözünü dinleyin. Bunu, yalnız insanları hoşnut etmek isteyenler gibi göze hoş görünen hizmetle değil, saf yürekle, Rab korkusuyla yapın.",
    "Rab'den miras ödülünü alacağınızı bilerek, her ne yaparsanız, insanlar için değil, Rab için yapar gibi candan yapın. Rab Mesih'e kulluk ediyorsunuz.",
    "Haksızlık eden ettiği haksızlığın karşılığını alacak, hiçbir ayrım yapılmayacaktır.",
  ],
  // Koloseliler 4 (18 ayet)
  [
    "Ey efendiler, gökte sizin de bir Efendiniz olduğunu bilerek kölelerinize adalet ve eşitlikle davranın.",
    "Kendinizi duaya verin. Duada uyanık kalın, şükredin.",
    "Aynı zamanda bizim için de dua edin ki Tanrı, sözünü yaymamız ve uğruna hapsedildiğim Mesih sırrını açıklamamız için bize bir kapı açsın.",
    "Bu sırrı gerektiği gibi açıklıkla bildirebilmem için dua edin.",
    "Sizden olmayanlara karşı bilgece davranın. Fırsatı değerlendirin.",
    "Sözünüz tuzla terbiye edilmiş gibi her zaman lütufla dolu olsun. Böylece herkese nasıl karşılık vermek gerektiğini bileceksiniz.",
    "Rab yolunda emektaşım ve güvenilir bir hizmetkâr olan sevgili kardeşimiz Tihikos, benimle ilgili her şeyi size bildirecektir.",
    "İşte bu amaçla, durumumuzu iletmesi ve yüreklerinize cesaret vermesi için kendisini size gönderiyorum.",
    "Onunla birlikte, sizden biri olan, güvenilir ve sevgili kardeş Onisimos'u da gönderiyorum. Burada olup biten her şeyi size bildirecekler.",
    "Hapishane arkadaşım Aristarhus ve Barnaba'nın yeğeni Markos size selam ederler. Markos'la ilgili buyruklar aldınız; yanınıza gelirse kendisini kabul edin.",
    "Yustus diye tanınan Yeşu da size selam eder. Tanrı'nın Egemenliği için çalışan emektaşım Yahudiler yalnız bunlardır. Bunlar bana teselli oldular.",
    "Sizden biri ve Mesih İsa'nın kulu olan Epafras size selam eder. Tanrı'nın her isteğinden emin, yetkin kişiler olarak ayakta kalasınız diye sizin için her zaman duayla mücadele ediyor.",
    "Gerek sizin gerekse Laodikya ve Hierapolis'tekiler için çok emek verdiğine tanıklık ederim.",
    "Sevgili hekim Luka'yla Dimas da size selam ederler.",
    "Laodikya'daki kardeşlere, Nimfa'ya ve evindeki topluluğa selam edin.",
    "Bu mektup aranızda okunduktan sonra Laodikya kilisesine de okutun. Siz de Laodikya'dan gelecek mektubu okuyun.",
    "Arhippus'a, \"Rab yolunda üstlendiğin görevi tamamlamaya dikkat et!\" deyin.",
    "Ben Pavlus bu selamı elimle yazıyorum. Zincire vurulduğumu unutmayın. Tanrı'nın lütfu sizinle birlikte olsun.",
  ],
];
