import type { ContextNote } from './context-note-types';

/** Yuhanna (tam), Matta (seçili bölümler), Elçilerin İşleri (giriş) */
export const contextNotesLegacy: ContextNote[] = [
  {
    bookId: 'joh',
    chapter: 1,
    title: "Söz'ün Bedene Bürünmesi",
    summary: "Yuhanna İncili'nin girişi. İsa'nın ilahi doğasını ve dünyaya gelişini anlatır.",
    historicalContext: "MS 85-90 yıllarında Efes'te yazıldığı tahmin edilir. Yuhanna diğer İncillerden farklı olarak felsefi bir giriş yapar.",
    keyVerse: 'Yuhanna 1:14',
  },
  {
    bookId: 'joh',
    chapter: 2,
    title: "Kana'daki Düğün",
    summary: "İsa'nın ilk mucizesi: suyu şaraba çevirmesi. Tapınak'ın temizlenmesi.",
    historicalContext: "Kana bugünkü Türkiye'de, Celile bölgesindedir. Düğün törenleri o dönemde haftalarca sürerdi.",
    keyVerse: 'Yuhanna 2:11',
  },
  {
    bookId: 'joh',
    chapter: 3,
    title: 'Nikodim ile Gece Görüşmesi',
    summary: "Ferisilerden Nikodim gece İsa'ya gelir. \"Yeniden doğmak\" ve Yuhanna 3:16.",
    historicalContext: "Ferisiler dini liderlerdi. Nikodim'in gece gelmesi, İsa'ya açıkça destek vermekten korktuğunu gösterir.",
    keyVerse: 'Yuhanna 3:16',
  },
  {
    bookId: 'joh',
    chapter: 4,
    title: 'Samiriyeli Kadın',
    summary: "İsa bir Samiriyeli kadınla konuşur, \"diri su\"dan bahseder. Samireliler inanır.",
    historicalContext: "Yahudiler ve Samiriyeliler birbirinden nefret ederdi. İsa'nın bu konuşması dönemin normlarını kırıyordu.",
    keyVerse: 'Yuhanna 4:14',
  },
  {
    bookId: 'joh',
    chapter: 5,
    title: 'Bethesda Havuzu',
    summary: "İsa 38 yıldır hasta olan adamı Şabat günü iyileştirir. Yahudi yetkililerle çatışma.",
    historicalContext: "Şabat kuralları katıydı. İsa'nın Şabat'ta iyileştirme yapması yetkilileri kızdırıyordu.",
    keyVerse: 'Yuhanna 5:24',
  },
  {
    bookId: 'joh',
    chapter: 6,
    title: 'Beş Ekmek İki Balık',
    summary: "5000 kişiyi doyurma mucizesi. \"Yaşam ekmeği\" vaazi. Birçok öğrenci İsa'yı terk eder.",
    historicalContext: "Celile gölü kıyısında geçer. Halk İsa'yı zorla kral yapmak ister; O da dağa çekilir.",
    keyVerse: 'Yuhanna 6:35',
  },
  {
    bookId: 'joh',
    chapter: 7,
    title: 'Çardak Bayramı',
    summary: "İsa Yeruşalim'de gizlice öğretir. \"Diri su\" ve Ruh hakkında konuşur.",
    historicalContext: "Çardak Bayramı (Sukkot) sonbaharda kutlanan bir hasat bayramıydı. İsa tehlikede olduğu halde öğretir.",
    keyVerse: 'Yuhanna 7:37',
  },
  {
    bookId: 'joh',
    chapter: 8,
    title: 'Zina Yapan Kadın',
    summary: "İsa \"İlk taşı atan\" diyerek kadını kurtarır. \"Dünyanın ışığı\" ve \"Önce İbrahim vardı\".",
    historicalContext: "Ferisiler İsa'yı tuzağa düşürmek ister. Musa'nın yasası zina için taşlamayı emrediyordu.",
    keyVerse: 'Yuhanna 8:12',
  },
  {
    bookId: 'joh',
    chapter: 9,
    title: 'Doğuştan Kör Adam',
    summary: "İsa çamurla körün gözünü açar. Ferisiler sorgulayınca adam \"Bir şey bilmiyorum, körken şimdi görüyorum\" der.",
    historicalContext: "Şabat'ta iyileştirme yine tartışma yaratır. Adam sonunda İsa'ya tapar.",
    keyVerse: 'Yuhanna 9:25',
  },
  {
    bookId: 'joh',
    chapter: 10,
    title: 'İyi Çoban',
    summary: "İsa kendini \"kapı\" ve \"iyi çoban\" olarak tanıtır. Koyunlar O'nun sesini tanır.",
    historicalContext: "Yahudiler İsa'yı taşlamak ister. \"Baba ile birim\" sözü kızgınlığı artırır.",
    keyVerse: 'Yuhanna 10:11',
  },
  {
    bookId: 'joh',
    chapter: 11,
    title: "Lazarus'un Dirilişi",
    summary: "İsa dört gündür ölü olan Lazarus'u diriltir. \"Diriliş ve yaşam Ben'im\".",
    historicalContext: "Beytanya'da geçer. Bu mucize yetkililerin İsa'yı öldürme kararını pekiştirir.",
    keyVerse: 'Yuhanna 11:25',
  },
  {
    bookId: 'joh',
    chapter: 12,
    title: 'Mesih Olarak Giriş',
    summary: "İsa Yeruşalim'e eşek üzerinde girer. \"Bir buğday tanesi\" benzetmesi. Yunanlar İsa'yı görmek ister.",
    historicalContext: "Fısıh öncesi. Halk dallarla karşılar. İsa çarmıhı ve yüceliği önceden bildirir.",
    keyVerse: 'Yuhanna 12:24',
  },
  {
    bookId: 'joh',
    chapter: 13,
    title: 'Ayak Yıkama',
    summary: "İsa öğrencilerin ayaklarını yıkar. \"Birbirinize sevgiyle hizmet edin\". Yahuda'nın ihaneti.",
    historicalContext: "Fısıh yemeği öncesi. Öğretmenin ayak yıkaması alışılmadık bir alçakgönüllülüktü.",
    keyVerse: 'Yuhanna 13:34',
  },
  {
    bookId: 'joh',
    chapter: 14,
    title: 'Yol, Gerçek ve Yaşam',
    summary: "İsa \"Baba'ya giden yol Ben'im\" der. Yardımcı Ruh vaadi. Barış bırakır.",
    historicalContext: "Son akşam yemeği konuşmaları. İsa ayrılık ve Ruh'un gelişini anlatır.",
    keyVerse: 'Yuhanna 14:6',
  },
  {
    bookId: 'joh',
    chapter: 15,
    title: 'Asma ve Çubuklar',
    summary: "İsa \"Ben asmayım, siz çubuklarsınız\" der. Sevgide kalma, dünyanın nefreti.",
    historicalContext: "Bağcılık o dönemde yaygındı. İsa öğrencileri meyve vermeye çağırır.",
    keyVerse: 'Yuhanna 15:5',
  },
  {
    bookId: 'joh',
    chapter: 16,
    title: "Ruh'un İşi",
    summary: "İsa Ruh'un gelişini ve dünyayı suçlayacağını anlatır. \"Kederiniz sevince dönüşecek\".",
    historicalContext: "Öğrenciler İsa'nın ayrılışına üzülür. Ruh gerçeğe yönlendirecek.",
    keyVerse: 'Yuhanna 16:13',
  },
  {
    bookId: 'joh',
    chapter: 17,
    title: "İsa'nın Duası",
    summary: "İsa Baba'ya uzun bir dua eder: kendisi, öğrenciler ve gelecekteki imanlılar için.",
    historicalContext: "Gethsemane'ye gitmeden önce. \"Birlik içinde olsunlar\" dileği.",
    keyVerse: 'Yuhanna 17:21',
  },
  {
    bookId: 'joh',
    chapter: 18,
    title: 'Tutuklanma ve Petrus\'un İnkârı',
    summary: "İsa tutuklanır. Petrus üç kez İsa'yı tanımadığını söyler. Pilatus ile görüşme.",
    historicalContext: "Zeytinlikte Yahuda ile gelen birlik. Yahudi ve Roma yetkilileri devreye girer.",
    keyVerse: 'Yuhanna 18:36',
  },
  {
    bookId: 'joh',
    chapter: 19,
    title: 'Çarmıha Geriliş',
    summary: "İsa çarmıha gerilir. \"Tamamlandı\" der. Yusuf ve Nikodim cesedi alıp gömer.",
    historicalContext: "Pilatus yıkayarak sorumluluğu reddeder. Peygamberlikler yerine gelir.",
    keyVerse: 'Yuhanna 19:30',
  },
  {
    bookId: 'joh',
    chapter: 20,
    title: 'Diriliş',
    summary: "Mecdelli Meryem boş mezarı görür. İsa ona ve öğrencilere görünür. Tomas \"Rabbim ve Tanrım\" der.",
    historicalContext: "Pazar sabahı. İsa dirilmiş olarak önce Meryem'e, sonra öğrencilere görünür.",
    keyVerse: 'Yuhanna 20:28',
  },
  {
    bookId: 'joh',
    chapter: 21,
    title: "Celile'de Görünme",
    summary: "İsa öğrencilere balık tutarken görünür. Petrus'a \"Koyunlarımı güt\" der. Son bölüm.",
    historicalContext: "İncil'in eklenmiş bir bölümü olabilir. Petrus'un görevi ve Yuhanna'nın tanıklığı vurgulanır.",
    keyVerse: 'Yuhanna 21:17',
  },
  {
    bookId: 'mat',
    chapter: 1,
    title: "İsa'nın Soykütüğü",
    summary: "İbrahim'den Davut'a, Davut'tan İsa'ya uzanan soy zinciri. İsa'nın doğumu.",
    historicalContext: "Matta İncili Yahudi okuyucular için yazılmıştır. Soykütüğü İsa'nın Mesih olduğunu kanıtlamak için verilir.",
    keyVerse: 'Matta 1:21',
  },
  {
    bookId: 'mat',
    chapter: 5,
    title: 'Dağdaki Vaaz — Kutlu Olanlar',
    summary: "İsa'nın en ünlü vaazının başlangıcı. Sekiz \"Kutlu olsun\" ile açılır.",
    historicalContext: "Celile gölü yakınlarındaki bir dağda verildiği düşünülür. Bugün bu yerde bir kilise bulunmaktadır.",
    keyVerse: 'Matta 5:3',
  },
  {
    bookId: 'mat',
    chapter: 6,
    title: 'Dua ve Oruç',
    summary: "Sadaka, dua ve oruç gizli yapılmalı. \"Göklerdeki Baba'nız\" ve \"Bize günlük ekmeğimizi ver\".",
    historicalContext: "Dağdaki Vaaz'ın devamı. İsa Yahudi dini uygulamalarını yeniden yorumlar.",
    keyVerse: 'Matta 6:9',
  },
  {
    bookId: 'mat',
    chapter: 7,
    title: 'Altın Kural ve Ev İnşa Edenler',
    summary: "\"Başkalarına yapılmasını istediğinizi siz de onlara yapın.\" Dar kapı, sahte peygamberler.",
    historicalContext: "Dağdaki Vaaz'ın sonu. Kalabalık İsa'nın öğretişine hayran kalır.",
    keyVerse: 'Matta 7:12',
  },
  {
    bookId: 'act',
    chapter: 1,
    title: 'Göğe Alınma',
    summary: "İsa son talimatları verir, göğe alınır. Öğrenciler Yeruşalim'de kalıp dua eder. Mattiyas seçilir.",
    historicalContext: "Zeytin Dağı'ndan alınır. \"Yahudiye ve Samiriye'de... yeryüzünün dört bucağına\" tanık olacaklardır.",
    keyVerse: 'Elçilerin İşleri 1:8',
  },
  {
    bookId: 'act',
    chapter: 2,
    title: "Pentekost — Ruh'un Gelişi",
    summary: "Kutsal Ruh havarilerin üzerine gelir. Petrus vaaz eder, 3000 kişi iman eder.",
    historicalContext: "Pentekost Yahudi bir bayramdı. Havariler Yeruşalim'de bir aradaydı. Bu olay kilisenin doğuşu kabul edilir.",
    keyVerse: 'Elçilerin İşleri 2:38',
  },
];
