/** 2. Korintliler — Türkçe Kutsal Kitap (Yeni Çeviri) 2001 ayet metinleri */
export const CORINTHIANS2_CHAPTER_VERSES: string[][] = [
  // 2. Korintliler 1 (24 ayet)
  [
    "Tanrı'nın isteğiyle Mesih İsa'nın elçisi atanan ben Pavlus ve kardeşimiz Timoteos'tan Ahaya'nın her yanındaki bütün kutsallara ve Tanrı'nın Korint'teki kilisesine selam!",
    "Babamız Tanrı'dan ve Rab İsa Mesih'ten sizlere lütuf ve esenlik olsun.",
    "Her türlü tesellinin kaynağı olan Tanrı'ya, merhametli Baba'ya, Rabbimiz İsa Mesih'in Tanrısı ve Babası'na övgüler olsun!",
    "Kendisinden aldığımız teselliyle her türlü sıkıntıda olanları teselli edebilmemiz için bizi bütün sıkıntılarımızda teselli ediyor.",
    "Çünkü Mesih'in acılarını nasıl büyük ölçüde çekiyorsak, Mesih sayesinde büyük teselli de buluyoruz.",
    "Sıkıntı çekiyorsak, bu sizin teselliniz ve kurtuluşunuz içindir. Teselli buluyorsak bu, bizim çektiğimiz acıların aynısına dayanmanızda etkin olan bir teselli bulmanız içindir.",
    "Size ilişkin umudumuz sarsılmaz. Çünkü acılarımıza olduğu gibi, tesellimize de ortak olduğunuzu biliyoruz.",
    "Kardeşlerim, Asya İli'nde çektiğimiz sıkıntılardan habersiz kalmanızı istemiyoruz. Dayanabileceğimizden çok ağır bir yük altındaydık. Öyle ki, yaşamaktan bile umudumuzu kesmiştik.",
    "Ölüme mahkûm olduğumuzu içimizde hissettik. Ama bu, kendimize değil, ölüleri dirilten Tanrı'ya güvenmemiz için oldu.",
    "Tanrı bizi böylesine büyük bir ölüm tehlikesinden kurtardı; daha da kurtaracaktır. Umudumuzu O'na bağladık.",
    "Siz de dualarınızla bize yardım ettikçe, bizi yine kurtaracaktır. Öyle ki, birçok kişinin dualarıyla bize sağlanan lütuftan ötürü birçoklarının ağzından bizim için şükranlar sunulsun.",
    "Dünyaya ve özellikle size, insan bilgeliğiyle değil, Tanrı'nın lütfuyla, Tanrı'dan gelen kutsallık ve içtenlikle davrandığımıza vicdanımız tanıktır. Ve biz bununla övünüyoruz.",
    "Okuyup anlayabileceğinizden başka bir şey yazmıyoruz.",
    "Bizi bir ölçüde anladığınız gibi, tümüyle anlayacağınızı umarım. Rabbimiz İsa'nın gününde bizim övüncümüz siz olacağınız gibi, sizin övüncünüz de biz olalım.",
    "Bu güvenle, sizleri iki kez sevindirmek için önce size uğramak, sonra Makedonya'ya geçmek niyetindeydim.",
    "Makedonya'dan yine size geri gelerek tarafınızdan Yahudiye'ye uğurlanmak niyetindeydim.",
    "Bunu isterken acaba kararsız mıydım? Ya da isteklerim benlikten mi doğuyor ki, önce «Evet, evet», sonra «Hayır, hayır» diyeyim?",
    "Tanrı'nın güvenilirliği hakkı için diyorum ki, size ilettiğimiz söz hem «evet» hem «hayır» değildir.",
    "Silvanus ve Timoteos'la birlikte size tanıttığımız Tanrı'nın Oğlu İsa Mesih hem «evet» hem «hayır» değildi. O'nda yalnız «evet» vardır.",
    "Çünkü Tanrı'nın bütün vaatleri Mesih'te «evet»tir. Bu nedenle Tanrı'nın yüceliği için Mesih aracılığıyla Tanrı'ya «Amin» deriz.",
    "Bizi sizinle birlikte Mesih'te pekiştiren ve meshetmiş olan Tanrı'dır.",
    "O bizi mühürledi, güvence olarak da yüreklerimize Kutsal Ruh'u yerleştirdi.",
    "Tanrı'yı tanık tutarım ki, Korint'e dönmeyişimin nedeni sizi esirgemekti.",
    "İmanınıza egemen olmak istemiyoruz, sevinmeniz için sizinle birlikte çalışıyoruz. Çünkü imanda dimdik duruyorsunuz.",
  ],
  // 2. Korintliler 2 (17 ayet)
  [
    "Size tekrar keder dolu bir ziyaret yapmamaya karar verdim.",
    "Çünkü sizi kederlendirirsem, keder verdiğim sizlerden başka beni kim sevindirecek?",
    "Bunu yazdım ki, geldiğimde beni sevindirmesi gerekenler beni kederlendirmesin. Sevincimin hepinizin sevinci olduğuna ilişkin hepinize güvenim var.",
    "Kederlenesiniz diye değil, size beslediğim derin sevgiyi anlayasınız diye büyük bir sıkıntı ve yürek acısıyla gözyaşları içinde size yazdım.",
    "Eğer biri bir başkasını kederlendirdiyse, beni değil –abartmadan söyleyeyim– bir dereceye kadar hepinizi kederlendirmiş olur.",
    "Böyle birine çoğunluğun verdiği bu ceza yeterlidir.",
    "Aşırı kedere boğulmasın diye o kişiyi daha fazla cezalandırmayıp bağışlamalı ve teselli etmelisiniz.",
    "Bunun için ona duyduğunuz sevgiyi yenilemenizi rica ederim.",
    "Sizi sınamak ve her durumda söz dinleyenler olup olmadığınızı anlamak için yazdım size.",
    "Kimi bağışlarsanız, ben de onu bağışlarım. Eğer bir şeyi bağışladımsa, bunu sizin için Mesih'in önünde bağışladım.",
    "Öyle ki, Şeytan'ın oyununa gelmeyelim. Çünkü onun düzenlerini bilmez değiliz.",
    "Mesih'in Müjdesi'ni yaymak amacıyla Troas'a geldiğimde Rab'bin işi için bana bir kapı açıldığı halde, kardeşim Titus'u orada bulamadığım için iç huzurum yoktu.",
    "Bu nedenle oradakilere veda ederek Makedonya'ya gittim.",
    "Bizi her zaman Mesih'in zafer alayında yürüten, O'nu tanımanın güzel kokusunu aracılığımızla her yerde yayan Tanrı'ya şükürler olsun!",
    "Çünkü biz hem kurtulanlar hem de mahvolanlar arasında Tanrı için Mesih'in güzel kokusuyuz.",
    "Mahvolanlar için ölüme götüren ölüm kokusu, kurtulanlar içinse yaşama götüren yaşam kokusuyuz. Böylesi bir işe kim yeterlidir?",
    "Birçokları gibi, Tanrı'nın sözünü ticaret aracı yapanlar değiliz. Tanrı tarafından gönderilen ve Mesih'e ait olan kişiler olarak Tanrı'nın önünde içtenlikle konuşuyoruz.",
  ],
  // 2. Korintliler 3 (18 ayet)
  [
    "Kendimizi yine tavsiye etmeye mi başlıyoruz? Yoksa bazıları gibi size ya da sizden tavsiye mektuplarına ihtiyacımız mı var?",
    "Bütün insanlarca bilinen ve okunan, yüreklerimize yazılmış mektubumuz sizsiniz.",
    "Hizmetimizin sonucu olup mürekkeple değil, yaşayan Tanrı'nın Ruhu'yla, taş levhalara değil, insan yüreğinin levhalarına yazılmış Mesih'in mektubu olduğunuz açıktır.",
    "Mesih sayesinde Tanrı'ya böyle bir güvenimiz vardır.",
    "Herhangi bir şeyi kendi başarımız olarak saymaya yeterliyiz demek istemiyorum; bizi yeterli kılan Tanrı'dır.",
    "O bizi yazılı yasaya değil, Ruh'a dayalı yeni bir antlaşmanın hizmetkârları olmaya yeterli kıldı. Yazılı yasa öldürür, Ruh ise yaşatır.",
    "Ölümle sonuçlanan hizmet, yani taş üzerine harf harf kazılan yasa yücelik içinde geldiyse –öyle ki, İsrailoğulları geçici olan parlaklığından ötürü Musa'nın yüzüne bakamadılar–",
    "Ruh'a dayalı hizmetin yücelik içinde olacağı daha kesin değil mi?",
    "İnsanı suçlu çıkaran hizmetin yüceliği varsa, aklanmayı sağlayan hizmetin yüceliği çok daha aşkındır.",
    "Çünkü eskiden yüceltilmiş olanın, şimdi yücelikte aşkın olana göre yüceliği yoktur.",
    "Geçici olan, yücelik içinde geldiyse, kalıcı olanın yüceliği çok daha büyüktür.",
    "Böyle bir umuda sahip olduğumuz için büyük cesaretle konuşabiliriz.",
    "Yüzündeki parlaklığın giderek söndüğünü İsrailoğulları görmesin diye yüzünü peçeyle örten Musa gibi değiliz.",
    "İsrailoğulları'nın zihinleri körelmişti. Bugün bile Eski Antlaşma okunurken zihinleri aynı peçeyle örtülü kalıyor. Çünkü bu peçe ancak Mesih aracılığıyla kalkar.",
    "Ne var ki, bugün bile Musa'nın yazıları okunduğunda yüreklerini bir peçe örtüyor.",
    "Oysa ne zaman biri Rab'be dönerse, o peçe kaldırılır.",
    "Rab Ruh'tur, Rab'bin Ruhu neredeyse orada özgürlük vardır.",
    "Ve biz hepimiz peçesiz yüzle Rab'bin yüceliğini görerek yücelik üstüne yücelikle O'na benzer olmak üzere değiştiriliyoruz. Bu da Ruh olan Rab sayesinde oluyor.",
  ],
  // 2. Korintliler 4 (18 ayet)
  [
    "Bu hizmeti Tanrı'nın merhametiyle üstlendiğimiz için cesaretimizi yitirmeyiz.",
    "Utanç verici gizli yolları reddettik. Hileye başvurmayız, Tanrı'nın sözünü de çarpıtmayız. Gerçeği ortaya koyarak kendimizi Tanrı'nın önünde her insanın vicdanına tavsiye ederiz.",
    "Yaydığımız Müjde örtülüyse de, mahvolanlar için örtülüdür.",
    "Tanrı'nın görünümü olan Mesih'in yüceliğiyle ilgili Müjde'nin ışığı imansızların üzerine doğmasın diye, bu çağın ilahı onların zihinlerini kör etmiştir.",
    "Biz kendimizi ilan etmiyoruz; ama Mesih İsa'yı Rab, kendimizi de İsa uğruna kullarınız ilan ediyoruz.",
    "Çünkü, «Işık karanlıktan parlayacak» diyen Tanrı, İsa Mesih'in yüzünde parlayan kendi yüceliğini tanımamızdan doğan ışığı bize vermek için yüreklerimizi aydınlattı.",
    "Üstün gücün bizden değil, Tanrı'dan kaynaklandığı bilinsin diye bu hazineye toprak kaplar içinde sahibiz.",
    "Her yönden sıkıştırılmışız, ama ezilmiş değiliz. Şaşırmışız, ama çaresiz değiliz.",
    "Kovalanıyoruz, ama terk edilmiş değiliz. Yere yıkılmışız, ama yok olmuş değiliz.",
    "İsa'nın yaşamı bedenimizde açıkça görülsün diye İsa'nın ölümünü her an bedenimizde taşıyoruz.",
    "Çünkü İsa'nın yaşamı ölümlü bedenimizde açıkça görülsün diye, biz yaşayanlar İsa uğruna sürekli olarak ölüme teslim ediliyoruz.",
    "Böylece ölüm bizde, yaşamsa sizde etkin olmaktadır.",
    "«İman ettim, bu nedenle konuştum» diye yazılmıştır. Aynı iman ruhuna sahip olarak biz de iman ediyor ve bu nedenle konuşuyoruz.",
    "Çünkü Rab İsa'yı dirilten Tanrı'nın, bizi de İsa'yla diriltip sizinle birlikte kendi önüne çıkaracağını biliyoruz.",
    "Bütün bunlar sizin yararınızadır. Böylelikle Tanrı'nın lütfu çoğalıp daha çok insana ulaştıkça, Tanrı'nın yüceliği için şükran da artsın.",
    "Bu nedenle cesaretimizi yitirmeyiz. Her ne kadar dış varlığımız harap oluyorsa da, iç varlığımız günden güne yenileniyor.",
    "Çünkü geçici, hafif sıkıntılarımız bize, ağırlıkta hiçbir şeyle karşılaştırılamayacak kadar büyük, sonsuz bir yücelik kazandırmaktadır.",
    "Gözlerimizi görünen şeylere değil, görünmeyenlere çeviriyoruz. Çünkü görünenler geçicidir, görünmeyenlerse sonsuza dek kalıcıdır.",
  ],
  // 2. Korintliler 5 (21 ayet)
  [
    "Biliyoruz ki, barındığımız bu dünyasal çadır yıkılırsa, göklerde Tanrı'nın bize sağladığı bir konut –elle yapılmamış, sonsuza dek kalacak bir evimiz– vardır.",
    "Şimdiyse göksel evimizi giyinmeyi özleyerek inliyoruz.",
    "Onu giyinirsek çıplak kalmayız.",
    "Dünyasal çadırda yaşayan bizler ağır bir yük altında inliyoruz. Asıl istediğimiz soyunmak değil, giyinmektir. Öyle ki, ölümlü olan, yaşam tarafından yutulsun.",
    "Bizleri tam bu amaç için hazırlamış ve güvence olarak bize Ruh'u vermiş olan Tanrı'dır.",
    "Bu nedenle her zaman cesaretimiz vardır. Şunu biliyoruz ki, bu bedende yaşadıkça Rab'den uzaktayız.",
    "Gözle görülene değil, imana dayanarak yaşarız.",
    "Cesaretimiz vardır diyorum ve bedenden uzakta, Rab'bin yanında olmayı yeğleriz.",
    "Bunun için, ister bedende yaşayalım ister bedenden uzak olalım, amacımız Rab'bi hoşnut etmektir.",
    "Çünkü bedende yaşarken gerek iyi gerek kötü, yaptıklarımızın karşılığını almak için hepimiz Mesih'in yargı kürsüsü önüne çıkmak zorundayız.",
    "Rab'den korkmanın ne demek olduğunu bildiğimizden insanları ikna etmeye çalışıyoruz. Ne olduğumuzu Tanrı biliyor; umarım siz de vicdanınızda biliyorsunuz.",
    "Kendimizi yine size tavsiye etmeye çalışmıyoruz. Ama yürekle değil, dış görünüşle övünenleri yanıtlayabilmeniz için bizimle övünmenize fırsat veriyoruz.",
    "Eğer kendimizde değilsek, bu Tanrı içindir. Aklımız başımızdaysa, bu sizin içindir.",
    "Bizi zorlayan, Mesih'in sevgisidir. Yargımız şu: Biri herkes için öldü; öyleyse hepsi öldü.",
    "Evet, Mesih herkes için öldü. Öyle ki, yaşayanlar artık kendileri için değil, kendileri uğruna ölüp dirilen Mesih için yaşasınlar.",
    "Bu nedenle, biz artık kimseyi insan ölçülerine göre tanımayız. Mesih'i bu ölçülere göre tanıdıksa da, artık öyle tanımıyoruz.",
    "Bir kimse Mesih'teyse, yeni yaratıktır; eski şeyler geçmiş, her şey yeni olmuştur.",
    "Bunların hepsi Tanrı'dandır. Tanrı, Mesih aracılığıyla bizi kendisiyle barıştırdı ve bize barıştırma görevini verdi.",
    "Şöyle ki Tanrı, insanların suçlarını saymayarak dünyayı Mesih'te kendisiyle barıştırdı ve barıştırma sözünü bize emanet etti.",
    "Böylece, Tanrı aracılığımızla çağrıda bulunuyormuş gibi Mesih'in adına elçilik ediyor, O'nun adına yalvarıyoruz: Tanrı'yla barışın.",
    "Tanrı, günahı bilmeyen Mesih'i bizim için günah sunusu yaptı. Öyle ki, Mesih sayesinde Tanrı'nın doğruluğu olalım.",
  ],
  // 2. Korintliler 6 (18 ayet)
  [
    "Tanrı'yla birlikte çalışan bizler, O'nun lütfunu boş yere kabul etmemenizi ayrıca rica ediyoruz.",
    "Çünkü Tanrı diyor ki, «Uygun zamanda seni duydum, Kurtuluş günü sana yardım ettim.» Uygun zaman işte şimdidir, kurtuluş günü işte şimdidir.",
    "Hizmetimizin kötülenmemesi için hiçbir konuda hiç kimsenin sürçmesine neden olmadık.",
    "Tersine Tanrı'nın hizmetkârları olarak olağanüstü dayanmada, sıkıntı, güçlük ve elemlerde, dayak, hapis, karışıklık, emek, uykusuzluk ve açlıkta kendimizi örnek gösteriyoruz.",
    "Pak yaşayışta, bilgi, sabır, iyilik, Kutsal Ruh ve içten sevgide; gerçeğin ilanında ve Tanrı'nın gücünde kendimizi örnek gösteriyoruz.",
    "Sağ ve sol ellerimizde doğruluğun silahlarıyla, yücelikte ve onursuzlukta, iyi ünde ve kötü ünde kendimizi her durumda örnek gösteriyoruz.",
    "Aldatanlar sayılıyorsak da dürüst kişileriz.",
    "Tanınmıyor gibiyiz, ama iyi tanınıyoruz. Ölümün ağzındayız, ama işte yaşıyoruz. Dövülüyorsak bile öldürülmüş değiliz.",
    "Kederliyiz ama her zaman seviniyoruz. Yoksuluz ama birçoklarını zengin ediyoruz. Hiçbir şeyimiz yok ama her şeye sahibiz.",
    "Ey Korintliler, sizinle açıkça konuştuk, size yüreğimizi açtık.",
    "Sizden sevgimizi esirgemedik, ama siz bizden sevginizi esirgediniz.",
    "Bize aynı karşılığı verebilmek için –çocuklarıma söyler gibi söylüyorum– siz de yüreğinizi açın.",
    "İmansızlarla aynı boyunduruğa girmeyin. Çünkü doğrulukla fesadın ne ortaklığı, ışıkla karanlığın ne paydaşlığı olabilir?",
    "Mesih'le Beliyal uyum içinde olabilir mi? İman edenle iman etmeyenin ortak yanı olabilir mi?",
    "Tanrı'nın tapınağıyla putlar uyuşabilir mi? Çünkü biz yaşayan Tanrı'nın tapınağıyız. Nitekim Tanrı şöyle diyor: «Aralarında yaşayacak, aralarında yürüyeceğim. Onların Tanrısı olacağım, onlar da benim halkım olacak.»",
    "Bu nedenle, «İmansızların arasından çıkıp ayrılın» diyor Rab. «Murdara dokunmayın, ben de sizi kabul edeceğim.»",
    "Her Şeye Gücü Yeten Rab diyor ki, «Size Baba olacağım, siz de oğullarım, kızlarım olacaksınız.»",
  ],
  // 2. Korintliler 7 (16 ayet)
  [
    "Sevgili kardeşler, bu vaatlere sahip olduğumuza göre, bedeni ve ruhu lekeleyen her şeyden kendimizi arındıralım; Tanrı korkusuyla kutsallıkta yetkinleşelim.",
    "Yüreklerinizde bize yer verin. Kimseye haksızlık etmedik, kimseyi yoldan saptırmadık, kimseyi sömürmedik.",
    "Bunu sizi yargılamak için söylemiyorum. Daha önce de söylediğim gibi, yüreğimizde öyle bir yeriniz var ki, sizinle ölürüz de yaşarız da.",
    "Size çok güveniyor, sizinle çok övünüyorum. Teselliyle doluyum. Bütün sıkıntılar arasında sevincim sonsuzdur.",
    "Makedonya'ya geldiğimizde de hiç rahat yüzü görmedik. Her bakımdan sıkıntı çekiyorduk. Dışarıda kavgalar, yüreğimizde korkular vardı.",
    "Ama yüreği ezik olanları teselli eden Tanrı, Titus'un yanımıza gelişiyle bizi teselli etti.",
    "Yalnız gelişiyle değil, sizden aldığı teselliyle de. Titus beni özlediğinizi, benim için üzülüp gayret ettiğinizi bize anlatınca sevincim bir kat daha arttı.",
    "Mektubumla size acı verdiysem bile pişman değilim. Aslında pişman olmuştum –kısa bir süre için de olsa, o mektubun size acı verdiğini görüyorum–",
    "ama şimdi seviniyorum; acı duymanıza değil, bu acınızın sizi tövbeye yöneltmesine seviniyorum. Tanrı'nın isteğine uygun olarak acı çektiniz. Böylece hiçbir şekilde bizden zarar görmediniz.",
    "Tanrı'nın isteğiyle çekilen acı, kişiyi kurtuluşla sonuçlanan ve pişmanlık doğurmayan tövbeye götürür. Dünyanın acılarıysa ölüm getirir.",
    "Bakın bu acılar, Tanrı'nın isteğiyle çektiğiniz bu acılar sizde ne büyük ciddiyet, paklanmak için ne büyük istek yarattı! Sizde ne büyük öfke, korku, özlem, gayret ve suçluyu cezalandırma arzusu uyandırdı! Bu konuda her bakımdan masum olduğunuzu kanıtladınız.",
    "Size o mektubu yazdımsa da, haksızlık edeni ya da haksızlık göreni düşünerek yazmadım; bize ne denli adanmış olduğunuzu Tanrı önünde açıkça görmenizi istiyordum.",
    "Bütün bunlarla teselli buluyoruz. Tesellimize ek olarak Titus'un sevinci bizi daha da çok sevindirdi. Çünkü hepiniz onun yüreğini ferahlattınız.",
    "Sizleri ona övdüm, beni utandırmadınız. Size söylediğimiz her şey nasıl doğru idiyse, sizi Titus'a övmemiz de öylece doğru çıktı.",
    "Hepinizin nasıl söz dinlediğini, kendisini nasıl saygı ve korkuyla kabul ettiğinizi anımsadıkça size olan sevgisi daha da artıyor.",
    "Size her bakımdan güvenebildiğim için seviniyorum.",
  ],
  // 2. Korintliler 8 (24 ayet)
  [
    "Kardeşler, sizlere Tanrı'nın Makedonya'daki kiliselerine sağladığı lütuftan söz etmek istiyoruz:",
    "Büyük sıkıntılarla denendiklerinde, coşkun sevinçleri ve aşırı yoksullukları tam bir cömertliğe dönüştü.",
    "Ellerinden geldiği kadarını, hatta daha fazlasını kendi istekleriyle verdiklerine tanıklık ederim.",
    "Kutsallara yapılan yardıma katkıda bulunma ayrıcalığının kendilerine verilmesi için bize yalvarıp yakardılar.",
    "Umduğumuzdan da öte, kendilerini önce Rab'be, sonra Tanrı'nın isteğiyle bize adadılar.",
    "Bu nedenle, aranızda daha önce başladığı bu hayırlı işi tamamlaması için Titus'u isteklendirdik.",
    "İmanda, söz söylemekte, bilgide, her tür gayrette, bize beslediğiniz sevgide, her şeyde üstün olduğunuz gibi, bu hayırlı işte de üstün olmaya bakın.",
    "Bunu buyruk olarak söylemiyorum, yalnızca sevginizin içtenliğini ötekilerin gayretiyle karşılaştırarak sınamak istiyorum.",
    "Rabbimiz İsa Mesih'in lütfunu bilirsiniz. O'nun yoksulluğuyla siz zengin olasınız diye, zengin olduğu halde sizin uğrunuza yoksul oldu.",
    "Bu konuda size yararlı olanı salık veriyorum. Geçen yıl bağış toplamaya ilk girişen, hatta buna ilk heveslenen siz oldunuz.",
    "Şimdi bu işi tamamlayın; bunu candan arzuladığınız gibi, elinizden geldiğince tamamlamaya bakın.",
    "Çünkü istek varsa, insanın elinde olmayana göre değil, elindekine göre yardımda bulunması uygundur.",
    "Amacımız sizi sıkıntıya sokup başkalarını rahatlatmak değildir.",
    "Ama eşitlik olsun diye, şimdi elinizdeki fazlalık onların eksiğini tamamladığı gibi, başka zaman onların elindeki fazlalık sizin eksiğinizi tamamlasın.",
    "Öyle ki, «Çok toplayanın fazlası, az toplayanın da eksiği yoktu» diye yazılmış olduğu gibi, eşitlik olsun.",
    "Titus'un yüreğinde sizin için aynı ilgiyi uyandıran Tanrı'ya şükürler olsun!",
    "Çünkü Titus yalnız ricamızı kabul etmekle kalmadı, size derin ilgi duyduğu için kendi isteğiyle yanınıza geliyor.",
    "Müjde'yi yayma çabalarından ötürü bütün kiliselerce övülen bir kardeşi de onunla birlikte gönderiyoruz.",
    "Üstelik bu kardeş, Rab'bi yüceltmek ve yardıma hazır olduğumuzu göstermek için yürüttüğümüz bu hayırlı hizmette yol arkadaşımız olmak üzere kiliseler tarafından seçildi.",
    "Bu büyük bağışla ilgili hizmetimizde kimsenin eleştirisine hedef olmamaya özen gösteriyoruz.",
    "Çünkü yalnız Rab'bin gözünde değil, insanların gözünde de doğru olanı yapmaya dikkat ediyoruz.",
    "Birçok konuda defalarca deneyip gayretli bulduğumuz, şimdi size duyduğu büyük güvenle çok daha gayretli olan kardeşimizi de bu iki kişiyle birlikte gönderiyoruz.",
    "Titus'a gelince, o benim paydaşım ve aranızdaki emektaşımdır. Öbür kardeşlerimizse kiliselerin elçileri, Mesih'in kıvancıdırlar.",
    "Bunun için onlara sevginizi kanıtlayın, kiliselerin önünde sizinle övünmemizin nedenini gösterin.",
  ],
  // 2. Korintliler 9 (15 ayet)
  [
    "Kutsallara yapılacak bu yardımla ilgili olarak size yazmama gerek yok.",
    "Çünkü yardıma hazır olduğunuzu biliyorum. Ahaya'daki sizlerin geçen yıldan beri hazırlıklı olduğunu söyleyerek Makedonyalılar karşısında sizinle övünmekteyim. Gayretiniz onların çoğunu harekete geçirdi.",
    "Bu konuda sizinle övünmemiz boşa çıkmasın; dediğim gibi, hazırlıklı olasınız diye kardeşleri yanınıza gönderiyorum.",
    "Öyle ki, bazı Makedonyalılar benimle birlikte gelir ve sizi hazırlıksız bulurlarsa, sizler bir yana, bizler duyduğumuz güvenden ötürü utanmayalım.",
    "Bu nedenle önce yanınıza gelmeleri ve cömertçe vermeyi vaat ettiğiniz armağanları hazırlamaları için kardeşlere ricada bulunmayı gerekli gördüm. Öyle ki, armağanınız cimrilik değil, cömertlik örneği olarak hazır olsun.",
    "Şunu unutmayın: Az eken az biçer, çok eken çok biçer.",
    "Herkes yüreğinde niyet ettiği gibi versin; isteksizce ya da zorlanmış gibi değil. Çünkü Tanrı sevinçle vereni sever.",
    "Her zaman, her yönden, her şeye yeterli ölçüde sahip olarak her iyi işe cömertçe katkıda bulunabilmeniz için, Tanrı her nimeti size bol bol sağlayacak güçtedir.",
    "Nitekim şöyle yazılmıştır: «Armağanlar dağıttı, yoksullara verdi; doğruluğu sonsuza dek kalıcıdır.»",
    "Ekinciye tohum ve yiyecek ekmek sağlayan Tanrı, sizin de ekeceğinizi sağlayıp çoğaltacak, doğruluğunuzun ürünlerini artıracaktır.",
    "Her durumda cömert olmanız için her bakımdan zenginleştiriliyorsunuz. Cömertliğiniz bizim aracılığımızla Tanrı'ya şükran nedeni oluyor.",
    "Yaptığınız bu hizmet yalnız kutsalların eksiklerini gidermekle kalmıyor, birçoklarının Tanrı'ya şükretmesiyle de zenginleşiyor.",
    "Onlar, içtenliğinizi kanıtlayan bu hizmetten ötürü, açıkça benimsediğiniz Mesih Müjdesi'ne uyarak kendileriyle ve herkesle malınızı cömertçe paylaştığınız için Tanrı'yı yüceltiyorlar.",
    "Tanrı'nın size bağışladığı olağanüstü lütuftan dolayı sizler için dua ediyor, sizi özlüyorlar.",
    "Sözle anlatılamayan armağanı için Tanrı'ya şükürler olsun!",
  ],
  // 2. Korintliler 10 (18 ayet)
  [
    "Sizinle birlikteyken ürkek, ama aranızda değilken yiğit kesilen ben Pavlus, Mesih'teki alçakgönüllülük ve yumuşaklıkla size rica ediyor, yalvarıyorum: Yanınıza geldiğim zaman, bizi olağan insanlar gibi yaşayanlardan sayan bazılarına karşı güvenle takınmak niyetinde olduğum tavrı aynı cesaretle size karşı takınmaya zorlamayın beni.",
    "Olağan insanlar gibi yaşıyorsak da, insansal güce dayanarak savaşmıyoruz.",
    "Çünkü savaşımızın silahları insansal silahlar değil, kaleleri yıkan tanrısal güce sahip silahlardır.",
    "Safsataları, Tanrı bilgisine karşı diklenen her engeli yıkıyor, her düşünceyi tutsak edip Mesih'e bağımlı kılıyoruz.",
    "Mesih'e tümüyle bağımlı olduğunuz zaman, O'na bağımlı olmayan her eylemi cezalandırmaya hazır olacağız.",
    "Gözünüzün önündekine bakın. Bir kimse Mesih'e ait olduğuna güveniyorsa, yine düşünsün: Kendisi kadar biz de Mesih'e aitiz.",
    "Sizi yıkmak için değil, geliştirmek için Rab'bin bize verdiği yetkiyle biraz fazla övünsem de utanmam.",
    "Mektuplarımla sizi korkutmaya çalışıyormuş gibi görünmek istemiyorum.",
    "Çünkü bazıları, «Mektupları ağır ve etkilidir, ama kişisel varlığı etkisiz, konuşma yeteneği de sıfır» diyormuş.",
    "Böyle diyenler şunu bilsin ki, uzaktayken mektuplarımızda ne diyorsak, aranızdayken de öyle davranıyoruz.",
    "Kendilerini tavsiye eden bazılarıyla kendimizi bir tutmaya ya da karşılaştırmaya elbette cesaret edemeyiz! Onlar kendilerini kendileriyle ölçüp karşılaştırmakla akılsızlık ediyorlar.",
    "Ama biz haddimizi aşıp fazla övünmeyiz; övünmemiz, Tanrı'nın bizim için belirlediği, sizlere kadar da uzanan alanın sınırları içinde kalır.",
    "Etkinlik alanımız size kadar uzanmasaydı, sizinle ilgilenmekle sınırlarımızın dışına çıkmış sayılabilirdik. Oysa Mesih'in Müjdesi'ni size kadar ilk ulaştıran biz olduk.",
    "Başkalarının emeğiyle övünüp haddimizi aşmayız. Umudumuz odur ki, sizin imanınız büyüdükçe sayenizde etkinlik alanımız alabildiğine genişleyecek.",
    "Böylelikle Müjde'yi sizlerden daha ötelere yayabileceğiz. Çünkü başkasının etkinlik alanında başarılmış işlerle övünmek istemiyoruz.",
    "«Övünen, Rab'le övünsün.»",
    "Kabule değer kişi kendi kendini tavsiye eden değil, Rab'bin tavsiye ettiği kişidir.",
  ],
  // 2. Korintliler 11 (33 ayet)
  [
    "Umarım yapacağım küçük bir akılsızlığı hoş görürsünüz. Ne olur, beni hoş görün!",
    "Sizler için tanrısal bir kıskançlık duyuyorum. Çünkü sizleri el değmemiş kız gibi tek ere, Mesih'e sunmak üzere nişanladım.",
    "Ne var ki, yılanın Havva'yı kurnazlığıyla aldatması gibi, düşüncelerinizin Mesih'e olan içten ve pak adanmışlıktan saptırılmasından korkuyorum.",
    "Çünkü size gelen ve bizim tanıttığımızdan değişik bir İsa'yı tanıtanları pekâlâ hoş görüyorsunuz. Ayrıca, aldığınız ruhtan farklı bir ruhu ve kabul ettiğinizden farklı bir müjdeyi kabul ederek bunları hoş görüyorsunuz.",
    "Sözüm ona üstün elçilerden hiç de aşağı olduğumu sanmıyorum!",
    "Acemi bir konuşmacı olabilirim, ama bilgiden yana acemi değilim. Bunu size her durumda, her bakımdan açıkça gösterdik.",
    "Yücelmeniz için kendimi alçaltarak Tanrı'nın Müjdesi'ni size karşılıksız bildirmekle günah mı işledim?",
    "Size hizmet etmek için yardım aldığım başka kiliseleri adeta soydum.",
    "Aranızdayken ihtiyacım olduğu halde hiçbirinize yük olmadım. Çünkü Makedonya'dan gelen kardeşler eksiklerimi tamamladılar. Size yük olmamaya hep özen gösterdim, bundan böyle de özen göstereceğim.",
    "Mesih'in gerçeğine sahip olarak kesinlikle diyebilirim ki, Ahaya İli'nde hiç kimse beni böyle övünmekten alıkoyamaz.",
    "Neden mi? Sizi sevmediğimden mi? Tanrı biliyor ki, sizi seviyorum.",
    "Övündükleri konuda bize eşit sayılmak isteyen fırsatçılara fırsat vermemek için, yaptığımı yapmaya devam edeceğim.",
    "Bu tür adamlar sahte elçiler, düzenbaz işçiler, kendilerine Mesih'in elçisi süsü verenlerdir.",
    "Buna şaşmamalı. Şeytan da kendisine ışık meleği süsü verir.",
    "Ona hizmet edenlerin de kendilerine doğruluğun hizmetkârları süsü vermesi şaşırtıcı değildir. Onların sonu yaptıklarına göre olacaktır.",
    "Yine söylüyorum, kimse beni akılsız sanmasın. Öyle sanıyorsanız, akılsız birini kabul eder gibi de olsa beni kabul edin ki, ben de biraz övüneyim!",
    "Söylediklerimi Rab'bin söyleyeceği gibi değil, akılsız biri gibi, bu övüngen tavırla söylüyorum.",
    "Mademki birçokları ne olduklarıyla övünüyorlar, ben de övüneceğim.",
    "Sizler akıllı olduğunuz için akılsızlara seve seve katlanıyorsunuz!",
    "Aslında sizi köle edenlere, sömürenlere, sizden yararlananlara, büyüklük taslayanlara ya da sizi tokatlayanlara katlanıyorsunuz.",
    "Utanarak kabul ediyorum ki, biz bunu yapacak güçte değildik! Ama birinin övünmeye cesaret ettiği konuda –akılsız biri gibi konuşuyorum– ben de övünmeye cesaret ediyorum.",
    "Onlar İbrani mi? Ben de İbrani'yim. İsrailli mi? Ben de İsrailli'yim. İbrahim'in soyundan mıdırlar? Ben de onun soyundanım.",
    "Mesih'in hizmetkârları mıdırlar? Aklımı kaçırmış gibi konuşuyorum. Ben O'nun daha üstün bir hizmetkârıyım. Ben daha çok emek verdim, hapse daha çok girdim, sayısız dayak yedim, çok kez ölümle burun buruna geldim.",
    "Beş kez Yahudiler'den otuz dokuzar kırbaç yedim.",
    "Üç kez değnekle dövüldüm, bir kez taşlandım, üç kez deniz kazasına uğradım. Bir gün bir gece açık denizde kaldım.",
    "Sık sık yolculuk ettim. Irmaklarda, haydutlar arasında, gerek soydaşlarımın gerekse öteki ulusların arasında tehlikelere uğradım. Kentte, kırda, denizde, sahte kardeşler arasında tehlikelere düştüm.",
    "Emek verdim, sıkıntı çektim, çok kez uykusuz kaldım. Açlığı, susuzluğu tattım. Çok kez yiyecek sıkıntısı çektim, soğukta çıplak kaldım.",
    "Öbür sorunların yanısıra, bütün kiliseler için her gün çektiğim kaygının baskısı var üzerimde.",
    "Kim güçsüz olur da ben güçsüz olmam? Kim günaha düşürülür de ben onun için yanmam?",
    "Övünmem gerekiyorsa, güçsüzlüğümü gösteren şeylerle övüneceğim.",
    "Rab İsa'nın sonsuza dek övülecek olan Tanrısı ve Babası biliyor ki, yalan söylemiyorum.",
    "Şam'da Kral Aretas'ın valisi beni yakalatmak için kenti denetim altına almıştı.",
    "Ama beni küfe içinde surdaki bir pencereden sarkıttılar; böylece onun elinden sıyrılıp kaçtım.",
  ],
  // 2. Korintliler 12 (21 ayet)
  [
    "Yararlı olmasa da övünmek gereklidir. Şimdi görümlere ve Rab'bin vahiylerine geleyim.",
    "On dört yıl önce alınıp üçüncü göğe götürülmüş bir Mesih izleyicisi tanıyorum. Bu, bedensel olarak mı, yoksa beden dışında mı oldu, bilmiyorum, Tanrı bilir.",
    "Evet, bu adamın cennete götürüldüğünü biliyorum; bu, bedensel olarak mı, yoksa bedenden ayrı mı oldu, bilmiyorum, Tanrı bilir.",
    "Orada, dille anlatılamaz, insanın söylemesi yasak olan sözler işitti.",
    "Böyle biriyle övüneceğim. Ama kendimle ilgili olarak, güçsüzlüklerimden başka bir şeyle övünmeyeceğim.",
    "Övünmek istesem bile akılsız olmayacağım. Çünkü gerçeği söylemiş olacağım. Ama kimse beni gördüğünden ya da işittiğinden daha üstün görmesin diye övünmekten kaçınıyorum.",
    "Aldığım vahiylerin üstünlüğüyle gururlanmayayım diye bana bedende bir diken, beni yumruklamak için Şeytan'ın bir meleği verildi, gururlanmayayım diye.",
    "Bundan kurtulmak için Rab'be üç kez yalvardım.",
    "Ama O bana, «Lütfum sana yeter. Çünkü gücüm, güçsüzlükte tamamlanır» dedi. İşte, Mesih'in gücü içimde bulunsun diye güçsüzlüklerimle sevinerek daha çok övüneceğim.",
    "Bu nedenle Mesih uğruna güçsüzlükleri, hakaretleri, zorlukları, zulümleri ve darlıkları sevinçle karşılıyorum. Çünkü ne zaman güçsüzsem, o zaman güçlüyüm.",
    "Akılsız biri gibi davrandım, ama beni buna siz zorladınız. Aslında beni siz tavsiye etmeliydiniz. Çünkü bir hiç isem de, sözüm ona üstün elçilerden hiç de aşağı değilim.",
    "Elçiliğimin kanıtları aranızda büyük bir sabırla, belirtiler, harikalar ve mucizelerle gösterildi.",
    "Size yük olmayışımdan başka öbür kiliselerden ne eksiğiniz var ki? Bu haksızlığımı bağışlayın!",
    "İşte, üçüncü kez yanınıza gelmeye hazırım ve size yük olmayacağım. Çünkü sizde olanı değil, sizi istiyorum. Çocukların anne babaları için değil, anne babaların çocukları için para biriktirmesi gerekir.",
    "Ben de canlarınız uğruna malımı da kendimi de seve seve harcayacağım. Sizi daha çok seversem, daha az mı sevileceğim?",
    "Öyle olsun, ben size yük olmadım. Ama kurnaz biri olduğumdan sizi hileyle elde etmişim!",
    "Size gönderdiğim adamlardan biri aracılığıyla sizi sömürdüm mü?",
    "Titus'u size gelmeye isteklendirdim ve öbür kardeşi de onunla birlikte gönderdim. Titus sizi sömürmedi, değil mi? Aynı ruhla davranmadık mı, aynı yolu izlemedik mi?",
    "Bunca zamandır önünüzde kendimizi savunduğumuzu mu düşünüyorsunuz? Tanrı'nın önünde, Mesih'e ait kişiler olarak konuşuyoruz. Sevgili kardeşler, yaptığımız her şey sizin gelişmeniz içindir.",
    "Çünkü geldiğimde sizi istediğim durumda bulamayacağımdan korkuyorum. Sizler de beni istediğiniz durumda bulamayabilirsiniz. Aranızda çekişme, kıskançlık, öfke, bencil tutkular, iftira, dedikodu, böbürlenme, kargaşa olmasından korkuyorum.",
    "Korkarım size tekrar geldiğimde Tanrım beni önünüzde utandıracak; daha önce günah işleyip de kapıldıkları pisliklerden, fuhuş ve sefahatten tövbe etmeyen birçokları için yas tutacağım.",
  ],
  // 2. Korintliler 13 (14 ayet)
  [
    "Bu, yanınıza üçüncü gelişim olacak. Her suçlama iki ya da üç tanığın tanıklığıyla doğrulanmalıdır.",
    "Daha önce, aranızda ikinci kez bulunduğumda, geçmişte günah işlemiş olanlarla onların dışında kalanların hepsine söylemiştim, şimdi sizden uzaktayken de yineliyorum: Tekrar yanınıza gelirsem, hiç kimseyi esirgemeyeceğim!",
    "Mesih'in benim aracılığımla konuştuğuna ilişkin kanıt istiyorsunuz. Mesih size karşı güçsüz değildir; O'nun gücü sizde etkindir.",
    "Güçsüzlük içinde çarmıha gerildiği halde, şimdi Tanrı'nın gücüyle yaşıyor. Biz de O'nda güçsüz olduğumuz halde, Tanrı'nın gücü sayesinde O'nunla birlikte sizin yararınıza yaşayacağız.",
    "İman yolunda olup olmadığınızı anlamak için kendinizi sınayıp yoklayın. İsa Mesih'in içinizde olduğunu bilmiyor musunuz? Yoksa sınavdan başarısız çıkarsınız.",
    "Umarım bizim başarısızlığa uğramadığımızı anlayacaksınız.",
    "Kötü bir şey yapmamanız için Tanrı'ya dua ediyoruz. Dileğimiz, bizim sınavı geçmiş görünmemiz değil, biz sınavda başarısız görünsek bile sizin iyi olanı yapmanızdır.",
    "Çünkü gerçeğe karşı değil, ancak gerçek uğruna bir şey yapabiliriz.",
    "Biz güçsüz, sizse güçlüyken seviniyoruz. Yetkin olmanız için de dua ediyoruz.",
    "Rab'bin yıkmak değil, geliştirmek için bana verdiği yetkiyi yanınıza geldiğimde sert biçimde kullanmak zorunda kalmayayım diye, bunları aranızda değilken yazıyorum.",
    "Son olarak hoşça kalın, kardeşlerim. Yaşantınızı düzeltin, çağrıma kulak verin, düşüncelerinizde birlik olun, esenlik içinde yaşayın. Sevgi ve esenlik kaynağı olan Tanrı sizinle birlikte olacaktır.",
    "Birbirinizi kutsal öpüşle selamlayın.",
    "Bütün kutsallar size selam eder.",
    "Rab İsa Mesih'in lütfu, Tanrı'nın sevgisi ve Kutsal Ruh'un paydaşlığı hepinizle birlikte olsun.",
  ],
];
