/** 1. Korintliler — Türkçe Kutsal Kitap (Yeni Çeviri) 2001 ayet metinleri */
export const CORINTHIANS1_CHAPTER_VERSES: string[][] = [
  // 1. Korintliler 1 (31 ayet)
  [
    "Tanrı'nın isteğiyle Mesih İsa'nın elçisi olmaya çağrılan ben Pavlus ve kardeşimiz Sostenis'ten Tanrı'nın Korint'teki kilisesine selam!",
    "Mesih İsa'da kutsal kılınmış, kutsal olmaya çağrılmış olan sizlere ve hepimizin Rabbi İsa Mesih'in adını her yerde anan herkese Babamız Tanrı'dan ve Rab İsa Mesih'ten lütuf ve esenlik olsun.",
    "Tanrı'nın Mesih İsa'da size bağışladığı lütuftan ötürü sizin için her zaman Tanrım'a şükrediyorum.",
    "Mesih'le ilgili tanıklığımız sizde pekiştiği gibi Mesih'te her bakımdan –her tür söz ve bilgi bakımından– zenginleştiniz.",
    "Şöyle ki, tanıklığımız sizde pekişti.",
    "Rabbimiz İsa Mesih'in görünmesini beklerken hiçbir ruhsal armağandan yoksun değilsiniz.",
    "Rabbimiz İsa Mesih kendi gününde kusursuz olmanız için sizi sonuna dek pekiştirecektir.",
    "Sizleri Oğlu Rabbimiz İsa Mesih'le paydaşlığa çağıran Tanrı güvenilirdir.",
    "Kardeşler, Rabbimiz İsa Mesih'in adıyla yalvarıyorum: Hepiniz uyum içinde olun, aranızda bölünmeler olmadan aynı düşünce ve görüşte birleşin.",
    "Kardeşlerim, Kloi'nin ev halkından aranızda çekişmeler olduğunu öğrendim.",
    "Şunu demek istiyorum: Her biriniz, «Ben Pavlus yanlısıyım», «Ben Apollos yanlısıyım», «Ben Kefas yanlısıyım» ya da «Ben Mesih yanlısıyım» diyormuş.",
    "Mesih bölündü mü? Sizin için çarmıha gerilen Pavlus muydu? Pavlus'un adıyla mı vaftiz edildiniz?",
    "Hiç kimse benim adımla vaftiz edildiğinizi söylemesin diye Krispus'la Gayus'tan başka hiçbirinizi vaftiz etmediğim için Tanrı'ya şükrediyorum.",
    "Evet, bir de İstefanas'ın ev halkını vaftiz ettim; bunun dışında kimseyi vaftiz ettiğimi anımsamıyorum.",
    "Çünkü Mesih beni vaftiz etmeye değil, Mesih'in çarmıhtaki ölümü boşa gitmesin diye, bilgece sözlere dayanmaksızın Müjde'yi yaymaya gönderdi.",
    "Çarmıhla ilgili bildiri mahva gidenler için saçmalık, biz kurtulmakta olanlar içinse Tanrı gücüdür.",
    "Nitekim şöyle yazılmıştır: «Bilgelerin bilgeliğini yok edeceğim, Akıllıların aklını boşa çıkaracağım.»",
    "Hani nerede bilge kişi? Din bilgini nerede? Nerede bu çağın hünerli tartışmacısı? Tanrı dünya bilgeliğinin saçma olduğunu göstermedi mi?",
    "Mademki dünya Tanrı'nın bilgeliği uyarınca Tanrı'yı kendi bilgeliğiyle tanımadı, Tanrı iman edenleri saçma sayılan bildiriyle kurtarmaya razı oldu.",
    "Yahudiler doğaüstü belirtiler ister, Grekler'se bilgelik arar.",
    "Ama biz çarmıha gerilmiş Mesih'i duyuruyoruz. Yahudiler bunu yüzkarası, öteki uluslar da saçmalık sayarlar.",
    "Oysa Mesih, çağrılmış olanlar için –ister Yahudi ister Grek olsun– Tanrı'nın gücü ve Tanrı'nın bilgeliğidir.",
    "Çünkü Tanrı'nın «saçmalığı» insan bilgeliğinden daha üstün, Tanrı'nın «zayıflığı» insan gücünden daha güçlüdür.",
    "Kardeşlerim, aldığınız çağrıyı düşünün. Birçoğunuz insan ölçülerine göre bilge, güçlü ya da soylu kişiler değildiniz.",
    "Ne var ki, Tanrı bilgeleri utandırmak için dünyanın saçma saydıklarını, güçlüleri utandırmak için de dünyanın zayıf saydıklarını seçti.",
    "Dünyanın önemli gördüklerini hiçe indirmek için dünyanın önemsiz, soysuz, değersiz gördüklerini seçti.",
    "Öyle ki, Tanrı'nın önünde hiç kimse övünemesin.",
    "Ama siz Tanrı sayesinde Mesih İsa'dasınız. O bizim için tanrısal bilgelik, doğruluk, kutsallık ve kurtuluş oldu.",
    "Bunun için yazılmış olduğu gibi, «Övünen, Rab'le övünsün.»",
  ],
  // 1. Korintliler 2 (16 ayet)
  [
    "Kardeşler, size geldiğimde Tanrı'nın sırrını bilgece sözlerle ya da üstün konuşmayla açıklamadım.",
    "Çünkü aranızdayken Mesih'ten başka bir şey bilmemeye kararlıydım. Sizin aranızda çarmıha gerilmiş Mesih'i sergiledim.",
    "Size zayıf ve korkak geldim, büyük korku ve titreme içindeydim.",
    "Sözüm ve bildirimim bilgece ikna edici sözlerle değil, Ruh ve güç kanıtıyla sunuldu.",
    "Öyle ki, imanınız insan bilgeliğine değil, Tanrı gücüne dayansın.",
    "Olgun kişiler arasında bilgelikten söz ediyoruz. Ama bu dünyanın bilgeliği değil, bu çağın gelip geçen önderlerinin bilgeliği de değil.",
    "Gizli kalmış, Tanrı'nın önceden belirlediği ve yüceliğimiz için önceden hazırladığı bilgelikten söz ediyoruz.",
    "Bu dünyanın önderlerinden hiçbiri bu bilgeliği anlamadı. Anlasalardı, yücelik veren Rabbi çarmıha germezlerdi.",
    "Yazılmış olduğu gibi: «Tanrı'nın kendisine bağlı olanlar için hazırladıklarını hiçbir göz görmedi, hiçbir kulak işitmedi, hiçbir insanın yüreği kavramadı.»",
    "Tanrı bunları bize Ruh aracılığıyla açıkladı. Çünkü Ruh her şeyi, Tanrı'nın derinliklerini bile araştırır.",
    "Hangimiz bir insanın düşüncelerini bilir? İnsanın kendi ruhundan başka. Aynı şekilde Tanrı'nın düşüncelerini de Tanrı'nın Ruhu'ndan başka kimse bilmez.",
    "Biz dünyanın ruhunu değil, Tanrı'dan gelen Ruh'u aldık. Öyle ki, Tanrı'nın bize lütfettiği şeyleri bilelim.",
    "Bunları bilgelikle öğretilen insan sözleriyle değil, Ruh'un öğrettiği sözlerle, ruhsal gerçekleri ruhsal sözlerle açıklıyoruz.",
    "Doğal insan Tanrı'nın Ruhu'na ait gerçekleri kabul etmez. Çünkü bunlar ona saçma gelir. Ruhça değerlendirildiği için bunları anlayamaz.",
    "Ruhça değerlendiren kişiyse her şeyi değerlendirir. Oysa kendisi kimse tarafından değerlendirilmez.",
    "«Rab'bin aklını kim bilebilir? O'na kim öğretmenlik edebilir?» Ama biz Mesih'in aklına sahibiz.",
  ],
  // 1. Korintliler 3 (23 ayet)
  [
    "Kardeşler, ben sizinle Tanrı'ya ait olmayan kişilere değil, Ruh'ta bebeklere seslenecek sözler söyledim.",
    "Size süt içirdim, katı yiyecek vermedim. Çünkü ona henüz hazır değildiniz. Aslında şimdi de hazır değilsiniz.",
    "Hâlâ benliğe ait olduğunuz için. Aranızda kıskançlık, çekişme var. Benliğe ait değil misiniz? İnsan gibi davranmıyor musunuz?",
    "Biri «Ben Pavlus yanlısıyım», öbürü «Ben Apollos yanlısıyım» dediğine göre siz ne oluyorsunuz?",
    "Apollos kimdir? Pavlus kimdir? Bunlar sizin iman etmeniz için size hizmet eden görevlilerdir. Her biri Rab'bin verdiği görevi yapmıştır.",
    "Ben ektim, Apollos suladı, ama büyüten Tanrı'dır.",
    "Ne eken bir şeydir, ne sulayan. Önemli olan büyüten Tanrı'dır.",
    "Eken de sulayan da birdir. Her biri kendi emeğinin karşılığını alacaktır.",
    "Çünkü biz Tanrı'nın iş arkadaşlarıyız. Sizler Tanrı'nın tarlası, Tanrı'nın binasısınız.",
    "Tanrı'nın bana bağışladığı lütfa göre ben usta bir mimar gibi temel attım. Başkası da onun üzerine inşa ediyor. Ama herkes nasıl inşa ettiğine dikkat etsin!",
    "Çünkü kimse atılmış olan temelden başka bir temel atamaz. O temel İsa Mesih'tir.",
    "Biri bu temel üzerine altın, gümüş, değerli taşlar, bir başkası tahta, ot, saman koyabilir.",
    "Herkesin yaptığı iş açığa çıkacak. Çünkü O Gün onu ateş gösterecek. Ateş herkesin yaptığının ne olduğunu ortaya çıkaracak.",
    "Temel üzerine kurduğu yapı ayakta kalırsa, yapan kişi ödül alır.",
    "Yapısı yanarsa, zarar görür. Kendisi kurtulacaktır, ama ateşten geçerek.",
    "Tanrı'nın tapınağı olduğunuzu ve Tanrı'nın Ruhu'nun sizde yaşadığını bilmiyor musunuz?",
    "Tanrı'nın tapınağını bozanı Tanrı yok edecektir. Çünkü Tanrı'nın tapınağı kutsaldır ve siz o tapınaksınız.",
    "Kimse kendini aldatmasın. Aranızda bir kimse bu çağda bilge görünüyorsa, bilgeliği bırakıp «akılsız» olsun ki gerçekten bilge olsun.",
    "Çünkü bu dünyanın bilgeliği Tanrı katında saçmalıktır. Nitekim yazılmıştır: «Bilgeleri kurnazlıklarıyla yakalar.»",
    "Yine şöyle yazılmıştır: «Rab bilgelerin düşüncelerinin boş olduğunu bilir.»",
    "Öyleyse kimse insanlarla övünmesin. Her şey sizindir.",
    "İster Pavlus, ister Apollos, ister Kefas, ister dünya, ister yaşam, ister ölüm, ister şimdiki, ister gelecek şeyler – hepsi sizindir.",
    "Siz de Mesih'indir, Mesih de Tanrı'nındır.",
  ],
  // 1. Korintliler 4 (21 ayet)
  [
    "Böylece insanlar bizi Mesih'in hizmetkârları ve Tanrı'nın sırlarının kâhyaları saysın.",
    "Şimdi kâhyalarda aranan, güvenilir olmalarıdır.",
    "Sizin tarafınızdan ya da insan mahkemesi tarafından yargılanmam benim için çok önemsiz bir şeydir. Kendimi de yargılamam.",
    "Çünkü kendi vicdanımda hiçbir suçlama duymuyorum. Ama bu beni aklanmış saymaz. Beni yargılayan Rab'dir.",
    "Bu nedenle Rab gelene dek bir şey yargılamayın. O karanlıktaki gizli şeyleri açığa çıkaracak ve yüreklerdeki amaçları ortaya koyacaktır. O zaman herkes Tanrı'dan payına düşen övgüyü alacaktır.",
    "Kardeşler, ben ve Apollos sizin uğrunuza bu sözleri örnek olsun diye söyledim. «Yazılmış olanların ötesine geçmeyin» diye öğrendiniz ki, kimse biri için övünmesin.",
    "Kim seni başkasından üstün kılıyor? Sende olup da almadığın ne var? Eğer aldıysan, neden almadığın gibi övünüyorsun?",
    "Doyduk, zenginleştik, sizin olmadan da krallar gibi egemenlik sürüyoruz! Keşke gerçekten egemenlik sürseydiniz ki, biz de sizinle birlikte egemenlik sürelim!",
    "Sanırım Tanrı bizi elçileri –son sıraya konan, ölüme mahkûm kişiler gibi– dünyaya, hem meleklere hem insanlara sergiledi.",
    "Biz Mesih uğruna akılsızız, siz Mesih'te akıllısınız. Biz zayıfız, siz güçlüsünüz. Siz saygı görüyorsunuz, biz aşağılanıyoruz.",
    "Şu ana dek açız, susuzuz, çıplaklık çekiyoruz, dayak yiyoruz, yersiz yurtsuz dolaşıyoruz.",
    "Elimizin emeğiyle yorulup çalışıyoruz. Sövülünce kutsuyoruz, zulme uğrayınca sabrediyoruz.",
    "İftiraya uğrayınca yatıştırıcı sözler söylüyoruz. Şu ana dek dünyanın süprüntüsü, herkesin ayak pası sayıldık.",
    "Bunları sizi utandırmak için yazmıyorum. Sevgili çocuklarım gibi uyarıyorum.",
    "Mesih İsa'da on binlerce eğitmeniniz olsa bile çok sayıda babanız yoktur. Müjde'yle sizi Mesih İsa'da yaşama kavuşturan benim.",
    "Bu nedenle size yalvarıyorum: Bana örnek olun.",
    "Bunun için size kardeşimiz Timoteos'u gönderdim. Rab'de Mesih İsa'ya ait olan sevgiyi size anımsatacaktır.",
    "Kimse sizi aldatmasın. Beklediğim gibi yanınıza tez gelirsem, Müjde'yi küstahça yayan bazı kişileri de tanımak isteyeceğim.",
    "Çünkü Tanrı'nın egemenliği sözde değil, güçtedir.",
    "Ne istersiniz? Size sopayla mı geleyim, yoksa sevgi ve yumuşaklık ruhuyla mı?",
  ],
  // 1. Korintliler 5 (13 ayet)
  [
    "Aranızda fuhuş var ve öyle bir fuhuş ki, öteki uluslarda bile yok: Biri babasının karısını almış.",
    "Siz de şişinmişsiniz! Yerine yas tutmanız gerekmez miydi? Bu yaptığı işi yapan kişi aranızdan atılsın diye.",
    "Beden olarak uzakta olsam da ruhça sizinle birlikteyim. Bu işi yapan kişi orada bulunmuşum gibi yargılamış bulunuyorum.",
    "Rabbimiz İsa'nın adıyla toplandığınızda, ben de ruhça sizinle birlikte olarak, Rabbimiz İsa'nın gücüyle",
    "böyle bir kişiyi Şeytan'a teslim ediyorum. Öz benliği mahvolsun ki, Ruh kurtulsun.",
    "Övünmeniz iyi değil. Biraz maya bütün hamuru kabartır bilmiyor musunuz?",
    "Eski mayayı temizleyin ki, taptaze hamur olasınız. Zaten mayasızsınız. Çünkü Mesih kurbanımız kesildi.",
    "Bunun için eski mayayla değil, mayasız, içtenlik ve dürüstlük ekmeğiyle kutlayalım.",
    "Size yazdığımda fuhuş yapanlarla arkadaşlık etmeyin dememi anımsıyorsunuz.",
    "Bu dünyanın fuhuş yapanlarıyla, açgözlüleriyle, soyguncularıyla ya da putperestleriyle arkadaşlık etmeyin demek değildi. Öyle olsaydı bu dünyadan çıkmanız gerekirdi.",
    "Aslında size yazdığım şu: Fuhuş yapan, açgözlü, putperest ya da sövücü, ayyaş ya da soyguncu olan –böyle biriyle birlikte yemek bile yemeyin– kardeş diye anılan biriyle arkadaşlık etmeyin.",
    "Benden uzaktakileri yargılamak bana düşmez. Benden yakındakileri siz yargılarsınız.",
    "Aranızdaki kötü kişiyi kendiniz atın.",
  ],
  // 1. Korintliler 6 (20 ayet)
  [
    "Birinizin ötekinden davacı olduğu durumda nasıl olur da kutsal olmayanların önünde dava açarsınız? Kutsalların önünde değil mi?",
    "Bilmiyor musunuz, kutsallar dünyayı yargılayacak? Dünya sizin tarafınızdan yargılanacaksa, önemsiz davalara bakmaya layık değil misiniz?",
    "Bilmiyor musunuz, melekleri yargılayacağız? Öyleyse bu dünyaya ait konuları da yargılamaya layığız.",
    "Bu dünyaya ait davalarınız olunca, kiliseye hiç saygısı olmayanları mı yargıç atıyorsunuz?",
    "Utanç verici bir şey söylüyorum. Gerçekten aranızda tek bir bilge yok mu? Hiç kimse kardeşiyle kardeşi arasında yargıçlık edemez mi?",
    "Kardeş kardeşle davalı, hem de imansızlara karşı!",
    "Zaten aranızda tamamen yenilgi var. Neden birbirinize haksızlık etmeyi yeğlersiniz? Neden birbirinizi soymayı yeğlersiniz?",
    "Oysa siz birbirinize haksızlık ediyor, birbirinizi soyuyorsunuz – hem de kardeşlere!",
    "Bilenler bilmez misin, haksızlar Tanrı'nın egemenliğine mirasçı olmayacak? Aldanmayın! Fuhuş yapanlar, putperestler, zina edenler, oğlancılar, erkeklerle yatanlar,",
    "hırsızlar, açgözlüler, ayyaşlar, sövenler, soyguncular – Tanrı'nın egemenliğine mirasçı olmayacak.",
    "Bazılarınız böyleydiniz. Ama Rab İsa'nın adıyla ve Tanrımız'ın Ruhu'yla yıkandınız, kutsal kılındınız, aklanmış sayıldınız.",
    "«Her şey bana serbest» diyorum, ama her şey yararlı değil. «Her şey bana serbest» diyorum, ama hiçbir şeyin tutsağı olmayacağım.",
    "«Yemekler mide için, mide yemekler için» diyor. Ama Tanrı hem onu hem bunu ortadan kaldıracak. Beden fuhuş için değil, Rab için. Rab da beden için.",
    "Tanrı Rab'bi dirilttiği gibi kendi gücüyle bizi de diriltecek.",
    "Bedenlerinizin Mesih'in üyeleri olduğunu bilmiyor musunuz? Mesih'in üyelerini alıp fahişenin üyeleri mi yapayım? Asla!",
    "Fahişeyle birleşenle tek beden olduğunu bilmiyor musunuz? «İkisi tek beden olacak» diyor.",
    "Rab'be bağlananla tek ruh olduğunuz.",
    "Fuhuştan kaçının. İnsanın işlediği her günah bedenin dışındadır. Ama fuhuş yapan kendi bedenine karşı günah işler.",
    "Yoksa bedeninizin, içinizdeki Kutsal Ruh'un tapınağı olduğunu bilmiyor musunuz? Ruh'u Tanrı'dan aldınız. Artık kendinize ait değilsiniz.",
    "Bir beden karşılığında satın alındınız. Onun için Tanrı'yı bedeninizde yüceltin.",
  ],
  // 1. Korintliler 7 (40 ayet)
  [
    "Yazdığınız konulara gelince: Erkeğin kadına dokunmaması iyidir.",
    "Ama fuhuştan kaçınmak için her erkeğin kendi karısı, her kadının da kendi kocası olsun.",
    "Koca karısına borcunu ödesin, karı da kocasına.",
    "Kadın kendi bedeni üzerinde yetkiye sahip değildir, kocasındadır. Erkek de kendi bedeni üzerinde yetkiye sahip değildir, karısındadır.",
    "Birbirinizi mahrum etmeyin. Ancak karşılıklı rıza ile, duanıza engel olmamak için bir süre ayrı kalabilirsiniz. Sonra yine bir araya gelin. Yoksa Şeytan sizi denememek için kendinize egemen olamayacaksınız.",
    "Bunu bir buyruk olarak değil, bir tavsiye olarak söylüyorum.",
    "Herkes benim gibi olmak ister. Ama herkesin kendine göre Tanrı'dan bir armağanı vardır. Biri böyle, öbürü şöyle.",
    "Evlenmemişlere ve dullara söylüyorum: Benim gibi kalmaları kendileri için iyidir.",
    "Ama kendilerini tutamıyorlarsa evlensinler. Çünkü tutuşmak evlenmekten iyidir.",
    "Evlilere –ben değil, Rab– buyuruyorum: Karı kocadan ayrılmasın.",
    "Ayrıldıysa evlenmesin ya da kocasıyla barışsın. Koca da karısını boşamasın.",
    "Öbürlerine ben –Rab değil– söylüyorum: Bir kardeşin karısı imanlı değilse ve karısıyla birlikte yaşamak istiyorsa, onu boşamasın.",
    "İmanlı olmayan karı, kocasıyla birlikte yaşamak istiyorsa kocası onu boşamasın.",
    "Çünkü imanlı olmayan koca karısı sayesinde kutsal kılınır. İmanlı olmayan karı da kocası sayesinde kutsal kılınır. Yoksa çocuklarınız murdar olurdu. Oysa şimdi kutsaldır.",
    "Ama imanlı olmayan taraf ayrılmak isterse ayrılsın. Böyle durumlarda kardeş ya da kızkardeş tutsak değildir. Tanrı sizi esenlikte çağırdı.",
    "Ey imanlı kadın, kocan imanlı değilse onunla birlikte yaşamaya devam edebilir misin bilmiyorum. Ama ey imanlı erkek, karın imanlı değilse onunla birlikte yaşamaya devam edebilir misin bilmiyorum. Belki karı ya da koca kurtulur.",
    "Yoksa ey kadın, kocanı kurtaracak mısın? Ey erkek, karını kurtaracak mısın?",
    "Rab her birine nasıl pay verdiğini, her birini nasıl çağırdığını dikkate alın. Böyle yaşayın.",
    "Sünnetli olarak çağrıldı mı kimse? Sünneti gizlemesin. Sünnetsiz olarak mı çağrıldı? Sünnet olmasın.",
    "Sünnet bir şey değildir, sünnetsizlik de bir şey değildir. Önemli olan Tanrı'nın buyruklarını yerine getirmektir.",
    "Herkes hangi durumda çağrıldıysa o durumda kalsın.",
    "Köle olarak mı çağrıldın? Üzülme. Özgür olabilirsen yararlan.",
    "Çünkü Rab'de köle olarak çağrılan kişi Rab'bin azat ettiğidir. Özgür olarak çağrılan kişi de Mesih'in kölesidir.",
    "Bir beden karşılığında satın alındınız. İnsanların kölesi olmayın.",
    "Kardeşler, herkes hangi durumda çağrıldıysa Tanrı'nın önünde o durumda kalsın.",
    "Bekârlar ve dullar konusunda Rab'bin buyruğu yoktur. Ama benim tavsiyem şu: Benim gibi kalmak iyidir.",
    "Zorluklar içinde olduğumuz için böyle söylüyorum. İnsan için mevcut durumda kalmak iyidir.",
    "Bir kadına bağlı mısın? Ayrılmayı arama. Bağlı değil misin? Eş arama.",
    "Evlensen de günah işlemiş olmazsın. Bekâr kız evlense de günah işlemiş olmaz. Ama böyle kişiler bedensel sıkıntı çekecek. Ben sizi bundan esirgemek isterim.",
    "Şunu demek istiyorum, kardeşler: Zaman kısa. Bundan böyle karısı olanlar karısı yokmuş gibi,",
    "ağlayanlar ağlamıyormuş gibi, sevinenler sevinmiyormuş gibi, alanlar hiçbir şeye sahip değilmiş gibi,",
    "dünyadan yararlananlar buna hiç dokunmuyormuş gibi olsun. Çünkü bu dünyanın biçimi geçiyor.",
    "Sizin kaygısız olmanızı isterim. Evlenmemiş kişi Rab'bin işleriyle uğraşır, Rab'bi nasıl hoşnut edeceğini düşünür.",
    "Evli kişiyse dünya işleriyle uğraşır, karısını nasıl hoşnut edeceğini düşünür. İçi ikiye bölünmüştür.",
    "Evlenmemiş kadın ile bekâr da Rab'bin işleriyle uğraşır, böylece hem bedence hem ruhen kutsal olsun diye. Evlenmiş kadınsa dünya işleriyle uğraşır, kocasını nasıl hoşnut edeceğini düşünür.",
    "Bunu sizin yararınıza söylüyorum. Sizi kıstırmak için değil, uygun olanı yapmanız, Rab'be kayıtsız şartsız bağlı kalmanız için.",
    "Bir baba kızının bekâr kalmasının uygun olduğuna inanıyorsa ve böyle davranıyorsa, doğru yapıyor.",
    "Evlendirirse günah işlemiş olmaz. Bekâr kalmaya karar verirse daha iyi yapıyor.",
    "Kadın kocası yaşadığı sürece kocasına bağlıdır. Kocası ölürse dilediği biriyle evlenmekte özgürdür. Yeter ki Rab'be ait olsun.",
    "Ama benim görüşüme göre daha mutludur. Sanırım bende de Tanrı'nın Ruhu var.",
  ],
  // 1. Korintliler 8 (13 ayet)
  [
    "Şimdi putlara sunulan kurbanların etine gelelim. «Hepimizin bilgisi var» diyorsunuz, bunu biliyoruz. Bilgi insanı böbürlendirir, sevgiyse geliştirir.",
    "Bir şey bildiğini sanan, henüz bilmesi gerektiği gibi bilmiyordur.",
    "Ama Tanrı'yı seveni Tanrı bilir.",
    "Putlara sunulan kurban etinin yenmesine gelince, biliyoruz ki, «Dünyada put bir hiçtir» ve «Birden fazla Tanrı yoktur».",
    "Yerde ya da gökte ilah diye adlandırılanlar varsa da –nitekim pekçok «ilah», pekçok «rab» vardır–",
    "bizim için tek bir Tanrı Baba vardır. O her şeyin kaynağıdır, bizler O'nun için yaşıyoruz. Tek bir Rab var, O da İsa Mesih'tir. Her şey O'nun aracılığıyla yaratıldı, biz de O'nun aracılığıyla yaşıyoruz.",
    "Ne var ki, herkes bu bilgiye sahip değildir. Hâlâ putperest alışkanlıklarının etkisinde kalan bazıları, yedikleri etin puta sunulduğunu düşünüyorlar. Vicdanları zayıf olduğu için lekeleniyor.",
    "Yiyecek bizi Tanrı'ya yaklaştırmaz. Yemezsek bir kaybımız olmaz, yersek de bir kazancımız olmaz.",
    "Yalnız dikkat edin, bu özgürlüğünüz vicdanı zayıf olanların sürçmesine neden olmasın.",
    "Eğer zayıf vicdanlı biri, bilgili olan seni bir put tapınağında sofraya oturmuş görürse, puta sunulan kurbanın etini yemek için cesaret almaz mı?",
    "Sonuçta bu zayıf vicdanlı kişi, Mesih'in uğruna öldüğü bu kardeş, senin bilgin yüzünden mahvolur!",
    "Bu şekilde kardeşlere karşı günah işleyip onların zayıf vicdanlarını yaralayarak Mesih'e karşı günah işlemiş olursunuz.",
    "Bu nedenle, yediğim şey kardeşimin sendeleyip düşmesine yol açacaksa, kardeşimin düşmemesi için bir daha et yemeyeceğim.",
  ],
  // 1. Korintliler 9 (27 ayet)
  [
    "Özgür değil miyim? Elçi değil miyim? Rabbimiz İsa'yı görmedim mi? Sizler Rab yolunda verdiğim emeğin ürünü değil misiniz?",
    "Başkaları için elçi değilsem bile, sizler için elçiyim ya! Rab yolunda elçiliğimin kanıtı sizsiniz.",
    "Beni sorguya çekenlere karşı kendimi böyle savunurum.",
    "Yiyip içmeye hakkımız yok mu bizim?",
    "Öbür elçiler gibi, Rab'bin kardeşleri ve Kefas gibi, yanımızda imanlı bir eş gezdirmeye hakkımız yok mu?",
    "Geçimi için çalışması gereken yalnız Barnaba'yla ben miyim?",
    "Kim kendi parasıyla askerlik yapar? Kim bağ diker de ürününü yemez? Kim sürüyü güder de sütünden içmez?",
    "İnsansal açıdan mı söylüyorum bunları? Kutsal Yasa da aynı şeyleri söylemiyor mu?",
    "Musa'nın Yasası'nda, «Harman döven öküzün ağzını bağlamayacaksın» diye yazılmıştır.",
    "Tanrı'nın kaygısı öküzler mi, yoksa bunu özellikle bizim için mi söylüyor? Kuşkusuz, bizim için yazılmıştır bu. Çünkü çift sürenin umutla sürmesi, harman dövenin de harmana ortak olma umuduyla dövmesi gerekir.",
    "Aranıza ruhsal tohumlar ektiysek, sizden maddesel bir harman biçmemiz çok mu?",
    "Başkalarının sizden yardım almaya hakları varsa, bizim daha çok hakkımız yok mu? Ama biz bu hakkımızı kullanmadık. Mesih Müjdesi'nin yayılmasına engel olmayalım diye her şeye katlanıyoruz.",
    "Tapınakta çalışanların tapınaktan beslendiklerini, sunakta görevli olanların da sunakta adanan adaklardan pay aldıklarını bilmiyor musunuz?",
    "Bunun gibi, Rab Müjde'yi yayanların da geçimlerini Müjde'den sağlamasını buyurdu.",
    "Ama ben bu haklardan hiçbirini kullanmış değilim. Bunlar bana sağlansın diye de yazmıyorum. Bunu yapmaktansa ölmeyi yeğlerim. Kimse beni bu övünçten yoksun bırakmayacaktır!",
    "Müjde'yi yayıyorum diye övünmeye hakkım yok. Çünkü bunu yapmakla yükümlüyüm. Müjde'yi yaymazsam vay halime!",
    "Eğer Müjde'yi gönülden yayarsam, ödülüm olur; gönülsüzce yayarsam, yalnızca bana emanet edilen görevi yapmış olurum.",
    "Peki, ödülüm nedir? Müjde'yi karşılıksız yaymak ve böylece Müjde'yi yaymaktan doğan hakkımı kullanmamaktır.",
    "Ben özgürüm, kimsenin kölesi değilim. Ama daha çok kişi kazanayım diye herkesin kölesi oldum.",
    "Yahudiler'i kazanmak için Yahudiler'e Yahudi gibi davrandım. Kendim Kutsal Yasa'nın denetimi altında olmadığım halde, Yasa altında olanları kazanmak için onlara Yasa altındaymışım gibi davrandım.",
    "Tanrı'nın Yasası'na sahip olmayan biri değilim, Mesih'in Yasası altındayım. Buna karşın, Yasa'ya sahip olmayanları kazanmak için Yasa'ya sahip değilmişim gibi davrandım.",
    "Güçsüzleri kazanmak için onlarla güçsüz oldum. Ne yapıp yapıp bazılarını kurtarmak için herkesle her şey oldum.",
    "Bunların hepsini Müjde'de payım olsun diye, Müjde uğruna yapıyorum.",
    "Koşu alanında yarışanların hepsi koştuğu halde ödülü bir kişinin kazandığını bilmiyor musunuz? Öyle koşun ki ödülü kazanasınız.",
    "Yarışa katılan herkes kendini her yönden denetler. Böyleleri bunu çürüyüp gidecek bir defne tacı kazanmak için yaparlar. Bizse hiç çürümeyecek bir taç için yapıyoruz.",
    "Bunun içindir ki, amaçsızca koşan biri gibi koşmuyorum. Yumruğumu havayı döver gibi boşa atmıyorum.",
    "Müjde'yi başkalarına duyurduktan sonra kendim reddedilmemek için bedenime eziyet çektirip onu köle ediyorum.",
  ],
  // 1. Korintliler 10 (33 ayet)
  [
    "Kardeşler, atalarımızın hepsinin bulut altında korunduğunu ve hepsinin denizden geçtiğini bilmenizi istiyorum.",
    "Musa'ya bağlanmak üzere hepsi bulutta ve denizde vaftiz edildi.",
    "Hepsi aynı ruhsal yiyeceği yedi;",
    "hepsi aynı ruhsal içeceği içti. Artlarından gelen ruhsal kayadan içtiler; o kaya Mesih'ti.",
    "Ne var ki, Tanrı onların çoğundan hoşnut değildi; nitekim cesetleri çöle serildi.",
    "Bu olaylar, onlar gibi kötü şeylere özlem duymamamız için bize ders olsun diye oldu.",
    "Onlardan bazıları gibi puta tapanlar olmayın. Nitekim şöyle yazılmıştır: «Halk yiyip içmeye oturdu, sonra kalkıp çılgınca eğlendi.»",
    "Onlardan bazıları gibi fuhuş yapmayalım. Fuhuş yapanların yirmi üç bini bir günde yok oldu.",
    "Yine bazıları gibi Rab'bi denemeyelim. Böyle yapanları yılanlar öldürdü.",
    "Kimileri gibi de söylenip durmayın. Söylenenleri ölüm meleği öldürdü.",
    "Bu olaylar başkalarına ders olsun diye onların başına geldi; çağların sonuna ulaşmış olan bizleri uyarmak için yazıya geçirildi.",
    "Onun için, ayakta sağlam durduğunu sanan dikkat etsin, düşmesin!",
    "Herkesin karşılaştığı denemelerden başka denemelerle karşılaşmadınız. Tanrı güvenilirdir, gücünüzü aşan biçimde denenmenize izin vermez. Dayanabilmeniz için denemeyle birlikte çıkış yolunu da sağlayacaktır.",
    "Bu nedenle, sevgili kardeşlerim, putperestlikten kaçının.",
    "Aklı başında insanlarla konuşur gibi konuşuyorum. Söylediklerimi kendiniz tartın.",
    "Tanrı'ya şükrettiğimiz şükran kâsesiyle Mesih'in kanına paydaş olmuyor muyuz? Bölüp yediğimiz ekmekle Mesih'in bedenine paydaş olmuyor muyuz?",
    "Ekmek bir olduğu gibi, biz de çok olduğumuz halde bir bedeniz. Çünkü hepimiz bir ekmeği paylaşıyoruz.",
    "İsrail halkına bakın; kurban etini yiyenler sunağa paydaş değil midir?",
    "Öyleyse ne demek istiyorum? Puta sunulan kurban etinin bir özelliği mi var? Ya da putun bir önemi mi var?",
    "Hayır, yok! Dediğim şu: Putperestler kurbanlarını Tanrı'ya değil, cinlere sunuyorlar. Cinlerle paydaş olmanızı istemem.",
    "Hem Rab'bin, hem cinlerin kâsesinden içemezsiniz; hem Rab'bin, hem cinlerin sofrasına ortak olamazsınız.",
    "Yoksa Rab'bi kıskandırmaya mı çalışıyoruz? Biz O'ndan daha mı güçlüyüz?",
    "«Her şey serbest» diyorsunuz, ama her şey yararlı değildir. «Her şey serbest» diyorsunuz, ama her şey yapıcı değildir.",
    "Herkes kendi yararını değil, başkalarının yararını gözetsin.",
    "Kasaplar çarşısında satılan her eti vicdan sorunu yapmadan, sorgusuz sualsiz yiyin.",
    "Çünkü «Yeryüzü ve içindeki her şey Rab'bindir.»",
    "İman etmemiş biri sizi yemeğe çağırır, siz de gitmek isterseniz, önünüze konulan her şeyi vicdan sorunu yapmadan, sorgusuz sualsiz yiyin.",
    "Ama biri size, «Bu kurban etidir» derse, hem bunu söyleyen için, hem de vicdan huzuru için yemeyin.",
    "Senin değil, öbür adamın vicdan huzuru için demek istiyorum. Benim özgürlüğümü neden başkasının vicdanı yargılasın?",
    "Şükrederek yemeğe katılırsam, şükrettiğim yiyecekten ötürü neden kınanayım?",
    "Sonuç olarak, ne yer ne içerseniz, ne yaparsanız, her şeyi Tanrı'nın yüceliği için yapın.",
    "Yahudiler'in, Grekler'in ya da Tanrı topluluğunun tökezleyip düşmesine neden olmayın.",
    "Ben de kendi yararımı değil, kurtulsunlar diye birçoklarının yararını gözeterek herkesi her yönden hoşnut etmeye çalışıyorum.",
  ],
  // 1. Korintliler 11 (34 ayet)
  [
    "Mesih'i örnek aldığım gibi, siz de beni örnek alın.",
    "Her durumda beni anımsadığınız ve size ilettiğim öğretileri olduğu gibi koruduğunuz için sizi övüyorum.",
    "Ama şunu da bilmenizi isterim: Her erkeğin başı Mesih, kadının başı erkek, Mesih'in başı da Tanrı'dır.",
    "Başına bir şey takıp dua ya da peygamberlik eden her erkek, başını küçük düşürür.",
    "Ama başı açık dua ya da peygamberlik eden her kadın, başını küçük düşürür. Böylesinin, başı tıraş edilmiş bir kadından farkı yoktur.",
    "Kadın başını açarsa, saçını kestirsin. Ama kadının saçını kestirmesi ya da tıraş etmesi ayıpsa, başını örtsün.",
    "Erkek başını örtmemeli; o, Tanrı'nın benzeri ve yüceliğidir. Kadın da erkeğin yüceliğidir.",
    "Çünkü erkek kadından değil, kadın erkekten yaratıldı.",
    "Erkek kadın için değil, kadın erkek için yaratıldı.",
    "Bu nedenle ve melekler uğruna kadının başı üzerinde yetkisi olmalıdır.",
    "Ne var ki, Rab'de ne kadın erkekten ne de erkek kadından bağımsızdır.",
    "Çünkü kadın erkekten yaratıldığı gibi, erkek de kadından doğar. Ama her şey Tanrı'dandır.",
    "Siz kendiniz karar verin: Kadının açık başla Tanrı'ya dua etmesi uygun mu?",
    "Doğanın kendisi bile size erkeğin uzun saçlı olmasının kendisini küçük düşürdüğünü, kadının uzun saçlı olmasının ise kendisini yücelttiğini öğretmiyor mu?",
    "Çünkü saç kadına örtü olarak verilmiştir.",
    "Bu konuda çekişmek isteyen varsa, şunu bilsin ki, bizim ya da Tanrı'nın kiliselerinin böyle bir alışkanlığı yoktur.",
    "Toplantılarınız yarardan çok zarar getirdiği için aşağıdaki uyarıları yaparken sizi övemem.",
    "Birincisi, toplulukça bir araya geldiğinizde aranızda ayrılıklar olduğunu duyuyorum. Buna biraz da inanıyorum.",
    "Çünkü Tanrı'nın beğenisini kazananların belli olması için aranızda bölünmeler olması gerekiyor!",
    "Toplandığınızda Rab'bin Sofrası'na katılmak için toplanmıyorsunuz.",
    "Her biriniz ötekini beklemeden kendi yemeğini yiyor. Kimi aç kalıyor, kimi sarhoş oluyor.",
    "Yiyip içmek için evleriniz yok mu? Tanrı'nın topluluğunu hor mu görüyorsunuz, yiyeceği olmayanları utandırmak mı istiyorsunuz? Size ne diyeyim? Sizi öveyim mi? Bu konuda övemem!",
    "Size ilettiğimi ben Rab'den öğrendim. Ele verildiği gece Rab İsa eline ekmek aldı, şükredip ekmeği böldü ve şöyle dedi: «Bu sizin uğrunuza feda edilen bedenimdir. Beni anmak için böyle yapın.»",
    "Aynı biçimde yemekten sonra kâseyi alıp şöyle dedi: «Bu kâse kanımla gerçekleşen yeni antlaşmadır. Her içtiğinizde beni anmak için böyle yapın.»",
    "Bu ekmeği her yediğinizde ve bu kâseden her içtiğinizde, Rab'bin gelişine dek Rab'bin ölümünü ilan etmiş olursunuz.",
    "Bu nedenle kim uygun olmayan biçimde ekmeği yer ya da Rab'bin kâsesinden içerse, Rab'bin bedenine ve kanına karşı suç işlemiş olur.",
    "Kişi önce kendini sınasın, sonra ekmekten yiyip kâseden içsin.",
    "Çünkü bedeni farketmeden yiyip içen, böyle yiyip içmekle kendi kendini mahkûm eder.",
    "İşte bu yüzden birçoğunuz zayıf ve hastadır, bazılarınız da ölmüştür.",
    "Kendimizi doğrulukla yargılasaydık, yargılanmazdık.",
    "Dünyayla birlikte mahkûm olmayalım diye Rab bizi yargılayıp terbiye ediyor.",
    "Öyleyse kardeşlerim, yemek için bir araya geldiğinizde birbirinizi bekleyin.",
    "Aç olan karnını evde doyursun. Öyle ki, toplanmanız yargılanmanıza yol açmasın. Öbür sorunları ise geldiğimde çözerim.",
  ],
  // 1. Korintliler 12 (31 ayet)
  [
    "Ruhsal armağanlara gelince, kardeşlerim, bu konuda bilgisiz kalmanızı istemem.",
    "Biliyorsunuz, putperestken şöyle ya da böyle saptırılıp dilsiz putlara tapmaya yöneltilmiştiniz.",
    "Bunun için bilmenizi isterim ki: Tanrı'nın Ruhu aracılığıyla konuşan hiç kimse, «İsa'ya lanet olsun!» demez. Kutsal Ruh'un aracılığı olmaksızın da kimse, «İsa Rab'dir» diyemez.",
    "Çeşitli ruhsal armağanlar vardır, ama Ruh birdir.",
    "Çeşitli görevler vardır, ama Rab birdir.",
    "Çeşitli etkinlikler vardır, ama herkeste hepsini etkin kılan aynı Tanrı'dır.",
    "Herkesin ortak yararı için herkese Ruh'u belli eden bir yetenek veriliyor.",
    "Ruh aracılığıyla birine bilgece konuşma yeteneği, ötekine aynı Ruh'tan bilgi iletme yeteneği veriliyor.",
    "Birine aynı Ruh aracılığıyla iman, ötekine aynı Ruh aracılığıyla hastaları iyileştirme armağanları veriliyor.",
    "Birine mucize yapma olanakları, birine peygamberlikte bulunma, birine ruhları ayırt etme, birine çeşitli dillerle konuşma, bir başkasına da bu dilleri çevirme armağanı veriliyor.",
    "Bunların tümünü etkin kılan tek ve aynı Ruh'tur. Ruh bunları herkese dilediği gibi, ayrı ayrı dağıtır.",
    "Beden bir olmakla birlikte birçok üyeden oluşur ve çok sayıdaki bu üyelerin hepsi tek bir beden oluşturur. Mesih de böyledir.",
    "İster Yahudi ister Grek, ister köle ister özgür olalım, hepimiz bir beden olmak üzere aynı Ruh'ta vaftiz edildik ve hepimizin aynı Ruh'tan içmesi sağlandı.",
    "İşte beden tek üyeden değil, birçok üyeden oluşur.",
    "Ayak, «El olmadığım için bedene ait değilim» derse, bu onu bedenden ayırmaz.",
    "Kulak, «Göz olmadığım için bedene ait değilim» derse, bu onu bedenden ayırmaz.",
    "Bütün beden göz olsaydı, nasıl duyardık? Bütün beden kulak olsaydı, nasıl koklardık?",
    "Gerçek şu ki, Tanrı bedenin her üyesini dilediği biçimde bedene yerleştirmiştir.",
    "Eğer hepsi bir tek üye olsaydı, beden olur muydu?",
    "Gerçek şu ki, çok sayıda üye, ama tek beden vardır.",
    "Göz ele, «Sana ihtiyacım yok!» ya da baş ayaklara, «Size ihtiyacım yok!» diyemez.",
    "Tam tersine, bedenin daha zayıf görünen üyeleri vazgeçilmezdir.",
    "Bedenin daha az değerli saydığımız üyelerine daha çok değer veririz. Böylece gösterişsiz üyelerimiz daha gösterişli olur.",
    "Gösterişli üyelerimizin özene ihtiyacı yoktur. Ama Tanrı, değeri az olana daha çok değer vererek bedende birliği sağladı.",
    "Öyle ki, bedende ayrılık olmasın, üyeler birbirini eşit biçimde gözetsin.",
    "Bir üye acı çekerse, bütün üyeler birlikte acı çeker; bir üye yüceltilirse, bütün üyeler birlikte sevinir.",
    "Sizler Mesih'in bedenisiniz, bu bedenin ayrı ayrı üyelerisiniz.",
    "Tanrı kilisede ilkin elçileri, ikinci olarak peygamberleri, üçüncü olarak öğretmenleri, sonra mucize yapanları, hastaları iyileştirme armağanlarına sahip olanları, başkalarına yardım edenleri, yönetme yeteneği olanları ve çeşitli dillerle konuşanları atadı.",
    "Hepsi elçi mi? Hepsi peygamber mi? Hepsi öğretmen mi? Hepsi mucize yapar mı?",
    "Hepsinin hastaları iyileştirme armağanları var mı? Hepsi bilmediği dilleri konuşabilir mi? Hepsi bu dilleri çevirebilir mi?",
    "Ama siz daha üstün armağanları gayretle isteyin. Şimdi size en iyi yolu göstereyim.",
  ],
  // 1. Korintliler 13 (13 ayet) — Sevgi bölümü
  [
    "İnsanların ve meleklerin diliyle konuşsam, ama sevgim olmasa, ses çıkaran bakırdan ya da çınlayan zilden farkım kalmaz.",
    "Peygamberlikte bulunabilsem, bütün sırları bilsem, her bilgiye sahip olsam, dağları yerinden oynatacak kadar büyük imanım olsa, ama sevgim olmasa, bir hiçim.",
    "Varımı yoğumu sadaka olarak dağıtsam, bedenimi yakılmak üzere teslim etsem, ama sevgim olmasa, bunun bana hiçbir yararı olmaz.",
    "Sevgi sabırlıdır, sevgi şefkatlidir. Sevgi kıskanmaz, övünmez, böbürlenmez.",
    "Sevgi kaba davranmaz, kendi çıkarını aramaz, kolay kolay öfkelenmez, kötülüğün hesabını tutmaz.",
    "Sevgi haksızlığa sevinmez, gerçek olanla sevinir.",
    "Sevgi her şeye katlanır, her şeye inanır, her şeyi umut eder, her şeye dayanır.",
    "Sevgi asla son bulmaz. Ama peygamberlikler ortadan kalkacak, diller sona erecek, bilgi ortadan kalkacaktır.",
    "Çünkü bilgimiz de peygamberliğimiz de sınırlıdır.",
    "Ne var ki, yetkin olan geldiğinde sınırlı olan ortadan kalkacaktır.",
    "Çocukken çocuk gibi konuşur, çocuk gibi anlar, çocuk gibi düşünürdüm. Yetişkin biri olunca çocukça davranışları bıraktım.",
    "Şimdi her şeyi aynadaki silik görüntü gibi görüyoruz, ama o zaman yüz yüze görüşeceğiz. Şimdi bilgim sınırlıdır, ama o zaman bilindiğim gibi tam bileceğim.",
    "İşte kalıcı olan üç şey vardır: İman, umut, sevgi. Bunların en üstünü de sevgidir.",
  ],
  // 1. Korintliler 14 (40 ayet)
  [
    "Sevginin ardınca koşun ve ruhsal armağanları, özellikle peygamberlik yeteneğini gayretle isteyin.",
    "Bilmediği dilde konuşan, insanlarla değil, Tanrı'yla konuşur. Kimse onu anlamaz. O, ruhuyla sırlar söyler.",
    "Peygamberlikte bulunansa insanların ruhça gelişmesi, cesaret ve teselli bulması için insanlara seslenir.",
    "Bilmediği dilde konuşan kendi kendini geliştirir; ama peygamberlikte bulunan, inanlılar topluluğunu geliştirir.",
    "Hepinizin dillerle konuşmasını isterim, ama peygamberlikte bulunmanızı yeğlerim. Diller inanlılar topluluğunun gelişmesi için çevrilmedikçe peygamberlikte bulunan, dillerle konuşandan üstündür.",
    "Şimdi kardeşlerim, yanınıza gelip dillerle konuşsam, ama size bir vahiy, bir bilgi, bir peygamberlik sözü ya da bir öğreti getirmesem, size ne yararım olur?",
    "Kaval ya da lir gibi ses veren cansız nesneler bile değişik sesler çıkarmasa, kaval mı, lir mi çalındığını kim anlar?",
    "Borazan belirgin bir ses çıkarmasa, kim savaşa hazırlanır?",
    "Bunun gibi, siz de anlaşılır bir dil konuşmazsanız, söyledikleriniz nasıl anlaşılır? Havaya konuşmuş olursunuz!",
    "Kuşkusuz dünyada çeşit çeşit diller vardır, hiçbiri de anlamsız değildir.",
    "Ne var ki, konuşulan dili anlamazsam, ben konuşana yabancı olurum, konuşan da bana yabancı olur.",
    "Bu nedenle, siz de ruhsal armağanlara heveslendiğinize göre, inanlılar topluluğunu geliştiren ruhsal armağanlar bakımından zenginleşmeye bakın.",
    "Bunun için, bilmediği dili konuşan, kendi söylediklerini çevirebilmek için dua etsin.",
    "Bilmediğim dille dua edersem ruhum dua eder, ama zihnimin buna katkısı olmaz.",
    "Öyleyse ne yapmalıyım? Ruhumla da zihnimle de dua edeceğim. Ruhumla da zihnimle de ilahi söyleyeceğim.",
    "Tanrı'yı yalnız ruhunla översen, yeni katılanlar senin ne söylediğini bilmediğinden, ettiğin şükran duasına nasıl «Amin!» desin?",
    "Uygun biçimde şükrediyor olabilirsin, ama bu başkasını geliştirmez.",
    "Dillerle hepinizden çok konuştuğum için Tanrı'ya şükrediyorum.",
    "Ama inanlılar topluluğunda dillerle on bin söz söylemektense, başkalarını eğitmek için zihnimden beş söz söylemeyi yeğlerim.",
    "Kardeşler, çocuk gibi düşünmeyin. Kötülük konusunda çocuklar gibi, ama düşünmekte yetişkinler gibi olun.",
    "Kutsal Yasa'da şöyle yazılmıştır: «Rab, ‹Yabancı diller konuşanların aracılığıyla, yabancıların dudaklarıyla bu halka sesleneceğim; yine de beni dinlemeyecekler!› diyor.»",
    "Görülüyor ki, bilinmeyen diller imanlılar için değil, imansızlar için bir belirtidir. Peygamberlikse imansızlar için değil, imanlılar için bir belirtidir.",
    "Şimdi bütün inanlılar topluluğu bir araya gelip hep birlikte bilmedikleri dillerle konuşurlarken yeni katılanlar ya da iman etmeyenler içeri girerse, «Siz çıldırmışsınız!» demezler mi?",
    "Ama herkes peygamberlikte bulunurken iman etmeyen ya da yeni katılan biri içeri girerse, söylenen her sözle günahlı olduğuna ikna edilecek, her sözle yargılanacak.",
    "Yüreğindeki gizli düşünceler açığa çıkacak ve, «Tanrı gerçekten aranızdadır!» diyerek yüzüstü yere kapanıp Tanrı'ya tapınacaktır.",
    "Öyleyse ne diyelim, kardeşler? Toplandığınızda her birinizin bir ilahisi, öğretecek bir konusu, bir vahyi, bilmediği dilde söyleyecek bir sözü ya da bir çevirisi vardır. Her şey topluluğun gelişmesi için olsun.",
    "Eğer bilinmeyen dillerle konuşulacaksa, iki ya da en çok üç kişi sırayla konuşsun, biri de söylenenleri çevirsin.",
    "Çeviri yapacak biri yoksa, bilmediği dilde konuşan, toplulukta sessiz kalsın, içinden Tanrı'yla konuşsun.",
    "İki ya da üç peygamber konuşsun, öbürleri söylenenleri iyice düşünüp tartsın.",
    "Toplantıda oturanlardan birine vahiy gelirse, konuşmakta olan sussun.",
    "Herkesin öğrenmesi ve cesaret bulması için hepiniz teker teker peygamberlikte bulunabilirsiniz.",
    "Peygamberlerin ruhları peygamberlerin denetimi altındadır.",
    "Çünkü Tanrı karışıklık değil, esenlik Tanrısı'dır. Kutsalların bütün topluluklarında böyledir.",
    "Kadınlar toplantılarınızda sessiz kalsın. Konuşmalarına izin yoktur. Kutsal Yasa'nın da belirttiği gibi, uysal olsunlar.",
    "Öğrenmek istedikleri bir şey varsa, evde kocalarına sorsunlar. Çünkü kadının toplantı sırasında konuşması ayıptır.",
    "Tanrı'nın sözü sizden mi kaynaklandı, ya da yalnız size mi ulaştı?",
    "Kendini peygamber ya da ruhça olgun sayan varsa, bilsin ki, size yazdıklarım Rab'bin buyruğudur.",
    "Bunları önemsemeyenin kendisi de önemsenmesin.",
    "Özet olarak, kardeşlerim, peygamberlikte bulunmayı gayretle isteyin, bilinmeyen dillerle konuşulmasına engel olmayın.",
    "Ancak her şey uygun ve düzenli biçimde yapılsın.",
  ],
  // 1. Korintliler 15 (58 ayet) — Diriliş bölümü
  [
    "Şimdi, kardeşler, size bildirdiğim, sizin de kabul edip bağlı kaldığınız Müjde'yi anımsatmak istiyorum.",
    "Size müjdelediğim söze sımsıkı sarılırsanız, onun aracılığıyla kurtulursunuz. Yoksa boşuna iman etmiş olursunuz.",
    "Aldığım bilgiyi size öncelikle ilettim: Kutsal Yazılar uyarınca Mesih günahlarımıza karşılık öldü, gömüldü",
    "ve Kutsal Yazılar uyarınca üçüncü gün ölümden dirildi.",
    "Kefas'a, sonra Onikiler'e göründü.",
    "Daha sonra da beş yüzden çok kardeşe aynı anda göründü. Bunların çoğu hâlâ yaşıyor, bazılarıysa öldüler.",
    "Bundan sonra Yakup'a, sonra bütün elçilere göründü.",
    "Son olarak zamansız doğmuş bir çocuğa benzeyen bana da göründü.",
    "Ben elçilerin en önemsiziyim. Tanrı'nın kilisesine zulmettiğim için elçi olarak anılmaya bile layık değilim.",
    "Ama şimdi neysem, Tanrı'nın lütfuyla öyleyim. O'nun bana olan lütfu boşa gitmedi. Elçilerin hepsinden çok emek verdim. Aslında ben değil, Tanrı'nın bende olan lütfu emek verdi.",
    "İşte, gerek benim yaydığım, gerek öbür elçilerin yaydığı ve sizin de iman ettiğiniz bildiri budur.",
    "Eğer Mesih'in ölümden dirildiği duyuruluyorsa, nasıl oluyor da aranızda bazıları ölüler dirilmez diyor?",
    "Ölüler dirilmezse, Mesih de dirilmemiştir.",
    "Mesih dirilmemişse, bildirimiz de imanınız da boştur.",
    "Bu durumda Tanrı'yla ilgili tanıklığımız da yalan demektir. Çünkü Tanrı'nın, Mesih'i dirilttiğine tanıklık ettik. Ama ölüler gerçekten dirilmezse, Tanrı Mesih'i de diriltmemiştir.",
    "Ölüler dirilmezse, Mesih de dirilmemiştir.",
    "Mesih dirilmemişse imanınız yararsızdır, siz de hâlâ günahlarınızın içindesiniz.",
    "Buna göre Mesih'e ait olarak ölmüş olanlar da mahvolmuşlardır.",
    "Eğer yalnız bu yaşam için Mesih'e umut bağlamışsak, herkesten çok acınacak durumdayız.",
    "Oysa Mesih, ölmüş olanların ilk örneği olarak ölümden dirilmiştir.",
    "Ölüm bir insan aracılığıyla geldiğine göre, ölümden diriliş de bir insan aracılığıyla gelir.",
    "Herkes nasıl Adem'de ölüyorsa, herkes Mesih'te yaşama kavuşacak.",
    "Her biri sırası gelince dirilecek: İlk örnek olarak Mesih, sonra Mesih'in gelişinde Mesih'e ait olanlar.",
    "Bundan sonra Mesih her yönetimi, her hükümranlığı, her gücü ortadan kaldırıp egemenliği Baba Tanrı'ya teslim ettiği zaman son gelmiş olacak.",
    "Çünkü Tanrı bütün düşmanlarını ayakları altına serinceye dek O'nun egemenlik sürmesi gerekir.",
    "Ortadan kaldırılacak son düşman ölümdür.",
    "Çünkü, «Tanrı her şeyi Mesih'in ayakları altına sererek O'na bağımlı kıldı.» «Her şey O'na bağımlı kılındı» sözünün, her şeyi Mesih'e bağımlı kılan Tanrı'yı içermediği açıktır.",
    "Her şey Oğul'a bağımlı kılınınca, Oğul da her şeyi kendisine bağımlı kılan Tanrı'ya bağımlı olacaktır. Öyle ki, Tanrı her şeyde her şey olsun.",
    "Diriliş yoksa, ölüler için vaftiz edilenler ne olacak? Ölüler gerçekten dirilmeyecekse, insanlar neden ölüler için vaftiz ediliyorlar?",
    "Biz de neden her saat kendimizi tehlikeye atıyoruz?",
    "Kardeşler, sizinle ilgili olarak Rabbimiz Mesih İsa'da sahip olduğum övüncün hakkı için her gün ölüyorum.",
    "Eğer insansal nedenlerle Efes'te canavarlarla dövüştümse, bunun bana yararı ne? Eğer ölüler dirilmeyecekse, «Yiyelim içelim, nasıl olsa yarın öleceğiz.»",
    "Aldanmayın, «Kötü arkadaşlıklar iyi huyu bozar.»",
    "Uslanıp kendinize gelin, artık günah işlemeyin. Bazılarınız Tanrı'yı hiç tanımıyor. Utanasınız diye söylüyorum bunları.",
    "Ama biri çıkıp, «Ölüler nasıl dirilecek? Nasıl bir bedenle gelecekler?» diye sorabilir.",
    "Ne akılsızca bir soru! Ektiğin tohum ölmedikçe yaşama kavuşmaz ki!",
    "Ekerken, oluşacak bitkinin kendisini değil, yalnızca tohumunu –buğday ya da başka bir bitkinin tohumunu– ekersin.",
    "Tanrı tohuma dilediği bedeni –her birine kendine özgü bedeni– verir.",
    "Her canlının eti aynı değildir. İnsan eti başka, hayvan eti başka, kuş eti, balık eti başka başkadır.",
    "Göksel bedenler vardır, dünyasal bedenler vardır. Göksel olanların görkemi başka, dünyasal olanlarınki başkadır.",
    "Güneşin görkemi başka, ayın görkemi başka, yıldızların görkemi başkadır. Görkem bakımından yıldız yıldızdan farklıdır.",
    "Ölülerin dirilişi de böyledir. Beden çürümeye mahkûm olarak gömülür, çürümez olarak diriltilir.",
    "Düşkün olarak gömülür, görkemli olarak diriltilir. Zayıf olarak gömülür, güçlü olarak diriltilir.",
    "Doğal beden olarak gömülür, ruhsal beden olarak diriltilir. Doğal beden olduğu gibi, ruhsal beden de vardır.",
    "Nitekim şöyle yazılmıştır: «İlk insan Adem yaşayan can oldu.» Son Adem'se yaşam veren ruh oldu.",
    "Önce ruhsal olan değil, doğal olan geldi. Ruhsal olan sonra geldi.",
    "İlk insan yerden, yani topraktandır. İkinci insan göktendir.",
    "Topraktan olan insan nasılsa, topraktan olanlar da öyledir. Göksel insan nasılsa, göksel olanlar da öyledir.",
    "Bizler topraktan olana nasıl benzediysek, göksel olana da benzeyeceğiz.",
    "Kardeşler, şunu demek istiyorum, et ve kan Tanrı'nın Egemenliği'ni miras alamaz. Çürüyen de çürümezliği miras alamaz.",
    "İşte size bir sır açıklıyorum. Hepimiz ölmeyeceğiz; son borazan çalınınca hepimiz bir anda, göz açıp kapayana dek değiştirileceğiz.",
    "Evet, borazan çalınacak, ölüler çürümez olarak dirilecek, ve biz de değiştirileceğiz.",
    "Çünkü bu çürüyen beden çürümezliği, bu ölümlü beden ölümsüzlüğü giyinmelidir.",
    "Çürüyen ve ölümlü beden çürümezliği ve ölümsüzlüğü giyinince, «Ölüm yok edildi, zafer kazanıldı!» diye yazılmış olan söz yerine gelecektir.",
    "«Ey ölüm, zaferin nerede? Ey ölüm, dikenin nerede?»",
    "Ölümün dikeni günahtır. Günah ise gücünü Kutsal Yasa'dan alır.",
    "Rabbimiz İsa Mesih aracılığıyla bizi zafere ulaştıran Tanrı'ya şükürler olsun!",
    "Bu nedenle, sevgili kardeşlerim, Rab yolunda verdiğiniz emeğin boşa gitmeyeceğini bilerek dayanın, sarsılmayın, Rab'bin işinde her zaman gayretli olun.",
  ],
  // 1. Korintliler 16 (24 ayet)
  [
    "Kutsallara yapılacak para yardımına gelince: Galatya kiliselerine ne buyurduysam, siz de öyle yapın.",
    "Haftanın ilk günü herkes kazancına göre bir miktar para ayırıp biriktirsin. Öyle ki, yanınıza geldiğimde para toplamaya gerek kalmasın.",
    "Oraya vardığımda, bağışlarınızı götürmek üzere uygun gördüğünüz kişileri tanıtıcı mektuplarla Yeruşalim'e göndereceğim.",
    "Benim de gitmeme değerse, onları yanıma alıp gideceğim.",
    "Makedonya'dan geçtikten sonra yanınıza geleceğim. Çünkü Makedonya'dan geçmek niyetindeyim.",
    "Belki bir süre yanınızda kalırım, hatta kışı da sizinle geçirebilirim. Öyle ki, sonra nereye gidecek olsam, bana yardım edebilesiniz.",
    "Sizi öyle kısaca görüp geçmek istemiyorum. Rab'bin izniyle uzunca bir süre yanınızda kalmayı umut ediyorum.",
    "Ama Pentikost Günü'ne dek Efes'te kalacağım.",
    "Çünkü büyük ve etkili işler yapmam için burada bana bir kapı açıldı. Ne var ki, bana karşı çıkanlar çoktur.",
    "Timoteos yanınıza gelirse, bir şeyden korkmamasına dikkat edin. Çünkü o da benim gibi Rab'bin işini yapıyor.",
    "Kimse onu hor görmesin. Yanıma gelmesi için onu esenlikle uğurlayın. Kardeşlerle birlikte onun da gelmesini bekliyorum.",
    "Kardeşimiz Apollos'a gelince, kardeşlerle birlikte size gelmesi için ona çok ricada bulundum, ama şimdilik gelmeye hiç de istekli değil. Fırsat bulunca gelecek.",
    "Uyanık kalın, imanda dimdik durun, mert ve güçlü olun.",
    "Her şeyi sevgiyle yapın.",
    "Ahaya'da ilk iman eden ve kendilerini kutsalların hizmetine adayan İstefanas'ın ev halkını bilirsiniz.",
    "Kardeşler, size yalvarırım, bu gibilere ve onlarla birlikte çalışıp emek verenlerin hepsine bağımlı olun.",
    "İstefanas, Fortunatus ve Ahaykos'un gelişine sevindim. Yokluğunuzu bana unutturdular.",
    "Sizin ruhunuzu da benim ruhumu da ferahlattılar. Böylelerinin değerini bilin.",
    "Asya İli'ndeki kiliseler size selam eder. Akvila ve Priska, evlerinde buluşan toplulukla birlikte Rab'de size çok selam ederler.",
    "Buradaki bütün kardeşlerin size selamı var. Birbirinizi kutsal öpüşle selamlayın.",
    "Ben Pavlus, bu selamı kendi elimle yazıyorum.",
    "Rab'bi sevmeyene lanet olsun. Maranata!",
    "Rab İsa'nın lütfu sizinle birlikte olsun.",
    "Hepinize Mesih İsa'da sevgiler! Amin.",
  ],
];
