/** Efesliler — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const EPHESIANS_CHAPTER_VERSES: string[][] = [
  // Efesliler 1 (23 ayet)
  [
    "Tanrı'nın isteğiyle Mesih İsa'nın elçisi atanan ben Pavlus'tan Efes'te bulunan kutsallara, Mesih İsa'ya ait olan sadıklara selam!",
    "Babamız Tanrı'dan ve Rab İsa Mesih'ten sizlere lütuf ve esenlik olsun.",
    "Bizi Mesih'te her ruhsal kutsamayla göksel yerlerde kutsamış olan Rabbimiz İsa Mesih'in Babası Tanrı'ya övgüler olsun.",
    "O kendi önünde sevgide kutsal ve kusursuz olmamız için dünyanın kuruluşundan önce bizi Mesih'te seçti.",
    "Kendi isteği ve iyi amacı uyarınca İsa Mesih aracılığıyla kendisine oğullar olalım diye bizi önceden belirledi.",
    "Öyle ki, sevgili Oğlu'nda bize bağışladığı yüce lütfu övülsün.",
    "Tam bir bilgelik ve anlayışla üzerimize yağdırdığı lütfunun zenginliği sayesinde Mesih'in kanı aracılığıyla Mesih'te kurtuluşa, suçlarımızın bağışlanmasına kavuştuk.",
    "Tanrı sır olan isteğini, Mesih'te edindiği iyi amaç uyarınca bize açıkladı.",
    "Zaman dolunca gerçekleştireceği bu tasarıya göre, yerdeki ve gökteki her şeyi Mesih'te birleştirecek.",
    "Her şeyi kendi isteği doğrultusunda düzenleyen Tanrı'nın amacı uyarınca önceden belirlenip Mesih'te seçildik.",
    "Öyle ki, Mesih'e ilk umut bağlayan bizler, O'nun yüceliğinin övülmesi için yaşayalım.",
    "Gerçeğin bildirisini, kurtuluşunuzun Müjdesi'ni duyup O'na iman ettiğinizde, siz de vaat edilen Kutsal Ruh'la O'nda mühürlendiniz.",
    "Ruh, Tanrı'nın yüceliğinin övülmesi için Tanrı'ya ait olanların kurtuluşuna dek mirasımızın güvencesidir.",
    "Bunun için, Rab İsa'ya iman ettiğinizi ve bütün kutsalları sevdiğinizi duyduğumdan beri ben de sizin için sürekli şükrediyor, sizi dualarımda hep anıyorum.",
    "Rabbimiz İsa Mesih'in Tanrısı, yüce Baba, kendisini tanımanız için size bilgelik ve vahiy ruhunu versin diye dua ediyorum.",
    "O'nun çağrısından doğan umudu ve kutsallara verdiği mirasın yüce zenginliğini anlamanız için, yüreklerinizin gözleri aydınlansın diye dua ediyorum.",
    "İman eden bizler için etkin olan kudretinin aşkın büyüklüğünü anlamanız için dua ediyorum.",
    "Bu kudret, Tanrı'nın Mesih'i ölümden diriltirken ve göksel yerlerde kendi sağında oturturken O'nda sergilediği üstün güçle aynı etkinliktedir.",
    "Tanrı O'nu bütün yönetimlerin, hükümranlıkların, güç ve egemenliklerin, yalnız bu çağda değil, gelecek çağda da anılacak bütün adların çok üstüne çıkardı.",
    "Her şeyi ayakları altına sererek O'na bağımlı kıldı.",
    "O'nu her şeyin üzerinde baş olmak üzere kiliseye verdi.",
    "Kilise O'nun bedenidir, her yönden her şeyi dolduranın doluluğudur.",
  ],
  // Efesliler 2 (22 ayet)
  [
    "Sizler bir zamanlar içinde yaşadığınız suçlardan ve günahlardan ötürü ölüydünüz. Bu dünyanın gidişine ve havadaki hükümranlığın egemenine, yani söz dinlemeyen insanlarda şimdi etkin olan ruha uymaktaydınız.",
    "Bir zamanlar hepimiz böyle insanların arasında, benliğin ve aklın isteklerini yerine getirerek benliğimizin tutkularına göre yaşıyorduk. Doğal olarak ötekiler gibi biz de gazap çocuklarıydık.",
    "Ama merhameti bol olan Tanrı bizi çok sevdiği için, suçlarımızdan ötürü ölü olduğumuz halde, bizi Mesih'le birlikte yaşama kavuşturdu.",
    "O'nun lütfuyla kurtuldunuz.",
    "Tanrı bizi Mesih İsa'da, Mesih'le birlikte diriltip göksel yerlerde oturttu.",
    "Bunu, Mesih İsa'da bize gösterdiği iyilikle, lütfunun sonsuz zenginliğini gelecek çağlarda sergilemek için yaptı.",
    "İman yoluyla, lütufla kurtuldunuz. Bu sizin başarınız değil, Tanrı'nın armağanıdır.",
    "Kimsenin övünmemesi için iyi işlerin ödülü değildir.",
    "Çünkü biz Tanrı'nın yapıtıyız, O'nun önceden hazırladığı iyi işleri yapmak üzere Mesih İsa'da yaratıldık.",
    "Bunun için, öteki uluslardan doğan sizler bir zamanlar ne olduğunuzu anımsayın: Bedende elle yapılmış sünnete sahip olup \"sünnetli\" diye anılanların \"sünnetsiz\" dedikleri sizler,",
    "o zaman Mesihsiz, İsrail'de vatandaşlıktan yoksun, vaade dayanan antlaşmalara yabancı, dünyada umutsuz ve tanrısızdınız.",
    "Ama bir zamanlar uzak olan sizler, şimdi Mesih İsa'da Mesih'in kanı sayesinde yakın kılındınız.",
    "Çünkü Mesih'in kendisi barışımızdır. Kutsal Yasa'yı, buyrukları ve kurallarıyla birlikte etkisiz kılarak iki topluluğu birleştirdi, aradaki engel duvarını, yani düşmanlığı kendi bedeninde yıktı.",
    "Amacı bu iki topluluktan kendisinde yeni bir insan yaratarak esenliği sağlamak, düşmanlığı çarmıhta öldürmek ve çarmıh aracılığıyla bir bedende iki topluluğu Tanrı'yla barıştırmaktı.",
    "O gelip hem uzakta olan sizlere hem de yakındakilere esenliği müjdeledi.",
    "O'nun aracılığıyla hepimiz tek Ruh'ta Baba'nın huzuruna çıkabiliriz.",
    "Böylece artık yabancı ve garip değil, kutsallarla birlikte yurttaş ve Tanrı'nın ev halkısınız.",
    "Elçilerle peygamberlerden oluşan temel üzerine inşa edildiniz. Köşe taşı Mesih İsa'nın kendisidir.",
    "Bütün yapı Rab'be ait kutsal bir tapınak olmak üzere O'nda kenetlenip yükseliyor.",
    "Siz de Ruh aracılığıyla Tanrı'nın konutu olmak üzere hep birlikte Mesih'te inşa ediliyorsunuz.",
  ],
  // Efesliler 3 (21 ayet)
  [
    "Bu nedenledir ki, ben Pavlus siz uluslar uğruna Mesih İsa'nın tutuklusu oldum.",
    "Tanrı'nın bana bağışladığı lütfu size ulaştırmakla görevlendirildiğimi duymuşsunuzdur.",
    "Yukarıda kısaca değindiğim gibi Tanrı, sır olan tasarısını bana vahiy yoluyla bildirdi.",
    "Bu mektubu okuduğunuzda Mesih sırrını nasıl kavradığımı anlayabilirsiniz.",
    "Bu sır önceki kuşaklara açıkça bildirilmemişti. Şimdiyse Mesih'in kutsal elçilerine ve peygamberlerine Ruh aracılığıyla açıklanmış bulunuyor.",
    "Şöyle ki, öteki uluslar da mirasa ortaktır, aynı bedenin üyeleridir ve Müjde aracılığıyla Mesih İsa'da vaade ortaktır.",
    "Tanrı'nın etkin gücüyle bana verilen lütuf armağanı uyarınca bu Müjde'yi yaymakla görevlendirildim.",
    "Bütün kutsalların en değersiziydim. Yine de Mesih'in akıl ermez zenginliğini uluslara müjdeleme ayrıcalığı bana verildi.",
    "Her şeyi yaratan Tanrı'da öncesizlikten beri gizli tutulan sırrın nasıl düzenlendiğini bütün insanlara açıklama ayrıcalığı bana verildi.",
    "Öyle ki, Tanrı'nın çok yönlü bilgeliği, kilise aracılığıyla göksel yerlerdeki yönetimlere ve hükümranlıklara şimdiki dönemde bildirilsin.",
    "Bu, Tanrı'nın başlangıçtan beri tasarladığı ve Rabbimiz Mesih İsa'da yerine getirdiği amaca uygundu.",
    "Mesih'te ve Mesih'e olan imanımızla Tanrı'ya cesaret ve güvenle yaklaşabiliriz.",
    "Bu nedenle, uğrunuza çektiğim sıkıntılar karşısında yılmamanızı rica ediyorum. Bunlar size yücelik kazandırır.",
    "Bunun için, yerde ve gökte her ailenin adını kendisinden aldığı Baba'nın önünde diz çökerim.",
    "Baba'nın kendi yüceliğinin zenginliği uyarınca Ruhu'yla sizi iç varlığınızda kudretle güçlendirmesini ve Mesih'in iman yoluyla yüreklerinizde yaşamasını dilerim.",
    "Öyle ki, sevgide köklenmiş ve temellenmiş olarak bütün kutsallarla birlikte Mesih'in sevgisinin ne denli geniş ve uzun, yüksek ve derin olduğunu anlamaya, bilgiyi çok aşan bu sevgiyi kavramaya gücünüz yetsin.",
    "Tanrı'nın bütün doluluğuyla dolmanızı dilerim.",
    "Tanrı, bizde etkin olan kudretiyle, dilediğimiz ya da düşündüğümüz her şeyden çok daha fazlasını yapabilecek güçtedir.",
    "Kilisede ve Mesih İsa'da bütün kuşaklar boyunca sonsuzlara dek O'na yücelik olsun! Amin.",
  ],
  // Efesliler 4 (32 ayet)
  [
    "Bu nedenle, Rab'bin uğruna tutuklu olan ben, aldığınız çağrıya yaraşır biçimde yaşamanızı rica ederim.",
    "Her bakımdan alçakgönüllü, yumuşak huylu, sabırlı olun. Birbirinize sevgiyle, hoşgörüyle davranın.",
    "Ruh'un birliğini esenlik bağıyla korumaya gayret edin.",
    "Tek beden, tek Ruh var - nasıl ki çağrıldığınızda tek bir umuda çağrıldınız.",
    "Tek Rab, tek iman, tek vaftiz.",
    "Hepimizin Rabbi, her şeyin üstünde, her şeyle ve her şeyde olan tek Tanrı ve Baba.",
    "Ama lütuf her birimize Mesih'in armağanı ölçüsünde bağışlandı.",
    "Bunun için Kutsal Yazı şöyle der: «Yükseğe çıktı ve tutsakları peşine taktı, insanlara armağanlar verdi.»",
    "Şimdi bu «çıktı» sözcüğü, Mesih önce aşağılara, yeryüzüne indi demek değil de nedir?",
    "İnen de O'dur, her şeyi doldurmak üzere bütün göklerin çok üstüne çıkan da O'dur.",
    "Kendisi kimini elçi, kimini peygamber, kimini müjdeci, kimini önder ve öğretmen atadı.",
    "Öyle ki, kutsallar hizmet görevini yapmak ve Mesih'in bedenini geliştirmek üzere donatılsın.",
    "Sonunda hepimiz imanda ve Tanrı Oğlu'nu tanımada birliğe, yetkinliğe, Mesih doluluğundaki olgunluk düzeyine erişeceğiz.",
    "Böylece artık insanların kurnazlığıyla, aldatıcı düzenler kurmaktaki becerileriyle, her öğretinin rüzgarıyla çalkalanıp öteye beriye sürüklenen çocuklar olmayacağız.",
    "Tersine, sevgiyle gerçeğe uyarak bedenin başı olan Mesih'e doğru her yönden büyüyeceğiz.",
    "O'nun önderliğinde bütün beden, her eklemin yardımıyla kenetlenip kaynaşmış olarak her üyesinin düzenli işleyişiyle büyüyüp sevgide gelişiyor.",
    "Bunun için şunu söylüyor ve Rab adına sizi uyarıyorum: Artık öteki uluslar gibi boş düşüncelerle yaşamayın.",
    "Onların zihinleri karardı. Bilgisizlikleri ve yüreklerinin duygusuzluğu yüzünden Tanrı'nın yaşamına yabancılaştılar.",
    "Bütün duyarlılıklarını yitirip açgözlülükle her türlü pisliği yapmak üzere kendilerini sefahate verdiler.",
    "Ama siz Mesih'i böyle öğrenmediniz.",
    "Kuşkusuz İsa'nın sesini duydunuz, O'ndaki gerçeğe uygun olarak O'nun yolunda eğitildiniz.",
    "Önceki yaşayışınıza ait olup aldatıcı tutkularla yozlaşan eski yaradılışı üzerinizden sıyırıp atmayı öğrendiniz.",
    "Düşüncede ve ruhta yenilenmeyi öğrendiniz.",
    "Gerçek doğruluk ve kutsallıkta Tanrı'ya benzer yaratılan yeni yaradılışı giyinmeyi öğrendiniz.",
    "Bunun için yalanı üzerinizden sıyırıp atarak her biriniz komşusuna gerçeği söylesin. Çünkü hepimiz aynı bedenin üyeleriyiz.",
    "Öfkelenin, ama günah işlemeyin. Öfkenizin üzerine güneş batmasın.",
    "İblis'e de fırsat vermeyin.",
    "Hırsızlık eden artık hırsızlık etmesin. Tersine, kendi elleriyle iyi olanı yaparak emek versin; böylece ihtiyacı olanla paylaşacak bir şeyi olsun.",
    "Ağzınızdan hiç kötü söz çıkmasın. İşitenler yararlansın diye, ihtiyaca göre, başkalarının gelişmesine yarayacak olanı söyleyin.",
    "Tanrı'nın Kutsal Ruhu'nu kederlendirmeyin. Kurtuluş günü için o Ruh'la mühürlendiniz.",
    "Her kötü niyetle birlikte her türlü kin, öfke, kızgınlık, bağrışma ve iftira sizden uzak olsun.",
    "Birbirinize karşı iyi yürekli, şefkatli olun. Tanrı sizi Mesih'te bağışladığı gibi, siz de birbirinizi bağışlayın.",
  ],
  // Efesliler 5 (33 ayet)
  [
    "Bunun için, sevgili çocukları olarak Tanrı'yı örnek alın.",
    "Mesih bizi nasıl sevdiyse ve bizim için kendisini güzel kokulu bir sunu ve kurban olarak nasıl Tanrı'ya sunduysa, siz de öylece sevgi yolunda yürüyün.",
    "Aranızda fuhuş, ahlaksızlık ya da açgözlülük anılmasın bile. Kutsallara yaraşmaz bu.",
    "Aranızda açık saçıklık, budalaca konuşmalar, bayağı şakalar da olmasın. Bunlar size yakışmaz. Bunun yerine şükredin.",
    "Şunu kesinlikle bilin ki, fuhuş yapanın, pisliğe düşkün olanın ya da putperest demek olan açgözlü kişinin, Mesih'in ve Tanrı'nın Egemenliği'nde mirası yoktur.",
    "Hiç kimse sizi boş sözlerle aldatmasın. Bu şeylerden ötürü Tanrı'nın gazabı söz dinlemeyenlerin üzerine gelir.",
    "Onun için böyleleriyle oturup kalkmayın.",
    "Bir zamanlar karanlıktınız, şimdiyse Rab'de ışıksınız. Işık çocukları gibi yaşayın.",
    "Işığın meyvesi her iyilikte, doğrulukta ve gerçekte görülür.",
    "Rab'bin hoşnut olduğu şeyin ne olduğunu sınayıp anlayın.",
    "Karanlığın verimsiz işlerine katılmayın. Tersine, onları açığa çıkarın.",
    "Çünkü onların gizlilikte yapılanlarından söz etmek bile ayıptır.",
    "Ama ışık tarafından açığa çıkarılan her şey görünür olur. Görünür olan her şey de ışıktır.",
    "Bunun için, «Uyan, ey uyuyan, ölümden kalk, Mesih sana ışık saçacak» deniyor.",
    "Öyleyse dikkatli olun. Akılsızca değil, bilgece yaşayın.",
    "Fırsatı değerlendirin. Çünkü günler kötüdür.",
    "Bu nedenle anlamsız olmayın, Rab'bin isteğinin ne olduğunu anlayın.",
    "Şarapla sarhoş olmayın. Bu sizi yozlaştırır. Tersine, Ruh'la dolu olun.",
    "Mezmurlar, ilahiler, ruhsal ezgiler söyleyerek birbirinize nağmeler yükseltin. Yürekten Rab'be mezmurlar, ilahiler söyleyin.",
    "Her zaman her şey için Rabbimiz İsa Mesih'in adıyla Baba Tanrı'ya şükredin.",
    "Mesih'e saygı göstererek birbirinize bağımlı olun.",
    "Ey kadınlar, Rab'be bağımlı olduğunuz gibi, kocalarınıza bağımlı olun.",
    "Çünkü Mesih bedenin kurtarıcısı olarak kilisenin başı olduğu gibi, erkek de kadının başıdır.",
    "Kilise Mesih'e bağımlı olduğu gibi, kadınlar da her durumda kocalarına bağımlı olsunlar.",
    "Ey kocalar, Mesih kiliseyi nasıl sevip onun uğruna kendini feda ettiyse, siz de karılarınızı öyle sevin.",
    "Mesih kiliseyi suyla yıkayıp tanrısal sözle temizleyerek kutsal kılmak için kendini feda etti.",
    "Öyle ki, kiliseyi üzerinde leke, buruşukluk ya da buna benzer bir şey olmadan, görkemli biçimde kendine sunabilsin. Amacı kilisenin kutsal ve kusursuz olmasıdır.",
    "Aynı biçimde kocalar da karılarını kendi bedenleri gibi sevmelidir. Karısını seven kendini sever.",
    "Hiç kimse hiçbir zaman kendi bedeninden nefret etmemiştir. Tersine, onu besler ve kayırır; tıpkı Mesih'in kiliseyi besleyip kayırdığı gibi.",
    "Çünkü bizler O'nun bedeninin üyeleriyiz.",
    "«Bunun için adam annesini babasını bırakıp karısına bağlanacak, ikisi tek beden olacak.»",
    "Bu sır büyüktür; ben bunu Mesih ve kiliseyle ilgili olarak söylüyorum.",
    "Size gelince, her biriniz karısını kendisi gibi sevsin. Kadın da kocasına saygı göstersin.",
  ],
  // Efesliler 6 (24 ayet)
  [
    "Ey çocuklar, Rab'be ait olanlara yaraşır biçimde anne babanızın sözünü dinleyin.",
    "Çünkü bu doğrudur. «Anneni babanı say ki, sana iyi olsun ve yeryüzünde uzun ömürlü olasın.»",
    "Ey babalar, çocuklarınızı öfkelendirmeyin. Onları Rab'bin terbiye ve öğüdüyle büyütün.",
    "Ey köleler, dünyadaki efendilerinizin sözünü Mesih'e kulluk eder gibi saygı ve korkuyla, saf yürekle dinleyin.",
    "İnsanları hoşnut etmek isteyenler gibi göze hoş görünmek için değil, Mesih'in kulları olarak Tanrı'nın isteğini yürekten yapın.",
    "İyi niyetle hizmet edin. Rab'be hizmet ediyormuş gibi, insanlara değil.",
    "Çünkü herkesin yaptığı iyiliği, köle ya da özgür olsun, Rab'den karşılığını alacağını bilirsiniz.",
    "Ey efendiler, kölelerinize de aynı biçimde davranın. Tehdidi bırakın. Gökte sizin de bir Efendiniz olduğunu bilin; O'nun önünde ayrım yoktur.",
    "Son olarak, kardeşlerim, Rab'de ve O'nun üstün gücünde güçlenin.",
    "Tanrı'nın tüm silahlarını kuşanın ki, İblis'in hilelerine karşı durabilesiniz.",
    "Çünkü savaşımız insanlara karşı değil, yönetimlere, hükümranlıklara, bu karanlık dünyanın güçlerine, göksel yerlerdeki kötü ruhlara karşıdır.",
    "Bu nedenle Tanrı'nın tüm silahlarını kuşanın ki, kötü günde dayanabilesiniz. Her şeyi tamamladıktan sonra ayakta kalabilesiniz.",
    "Öyleyse ayakta durun. Gerçeği belinize kuşanın, doğruluğu göğüslüğünüz gibi takın.",
    "Esenlik Müjdesi'ni yayan hazırlığı ayaklarınıza giyin.",
    "Bunların hepsinin üzerine, her türlü ateşli oku söndürebileceğiniz iman kalkanını alın.",
    "Kurtuluş miğferini ve Ruh'un kılıcını, yani Tanrı'nın sözünü alın.",
    "Her türlü dua ve yalvaryla her zaman Ruh'ta dua edin. Bunun için uyanık kalın. Bütün kutsallar için sebatla dua edin.",
    "Ben de sizin için, Müjde'yi cesaretle duyurabilmem için ağzım açılsın diye dua ediyorum. Bunun için elçi sıfatımla zincire vurulmuşum.",
    "Öyle ki, Müjde'nin sırrını gerektiği gibi cesaretle açıklayabileyim.",
    "Sevgili kardeşimiz, Rab'de güvenilir bir hizmetkâr olan Tihikos sizi bilgilendirecektir.",
    "Ben size her şeyi bildirmek için onu gönderiyorum.",
    "Durumumu ve yaptıklarımı anlamanız için onu bilinçle gönderiyorum.",
    "Babamız Tanrı'dan ve Rab İsa Mesih'ten kardeşlere sevgi ve imanla birlikte esenlik olsun.",
    "Rab İsa Mesih'i ölümsüz sevgiyle seven bütün kutsallara lütuf olsun.",
  ],
];
