/** İbraniler — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const HEBREWS_CHAPTER_VERSES: string[][] = [
  // İbraniler 1 (14 ayet)
  [
    "Eskiden peygamberler aracılığıyla birçok kez, birçok biçimde atalarımıza konuşan Tanrı, bu son günlerde bize Oğul aracılığıyla konuştu.",
    "O'nu her şeye mirasçı atadı. O'nun aracılığıyla evreni yarattı.",
    "O, Tanrı'nın yüceliğinin parıltısı, varlığının öz görüntüsüdür. Güçlü sözüyle her şeyi sürdürüyor. Günahlardan arınmayı sağladıktan sonra yücelerde Ulu Olan'ın sağında oturdu.",
    "Meleklerden ne kadar üstün bir ad miras aldı!",
    "Çünkü Tanrı meleklerden hangisine «Sen benim Oğlum'sun, bugün ben sana baba oldum» demiş ve yine «Ben O'na baba olacağım, O da bana oğul olacak» demiştir?",
    "O ilk doğanı yine dünyaya getirdiğinde «Tanrı'nın bütün melekleri O'na tapınsın» diyor.",
    "Melekler için «Ruhlarını rüzgâr, hizmetkârlarını alev alev ateş yapıyor» diyor.",
    "Ama Oğul için «Ey Tanrı, tahtın sonsuzluklar boyunca sürer. Egemenliğinin asası adalet asasıdır.»",
    "«Doğruluğu sevdin, kötülüğü nefret ettin. Bu nedenle Tanrı, senin Tanrın seni sevinç yağıyla, arkadaşlarından üstün meshetti» diyor.",
    "Yine «Ya Rab, başlangıçta yeri sen kurdun. Gökler de senin ellerinin yapıtıdır.»",
    "«Onlar yok olacak, sen kalıcısın. Hepsi giysi gibi eskiyecek.»",
    "«Bir pelerin gibi katlayacaksın onları, giysi gibi değiştirilecekler. Ama sen aynısın, yılların tükenmeyecek.»",
    "Tanrı meleklerden hangisine «Benim sağımda otur, düşmanlarını ayaklarının taburesi yapayım» demiştir?",
    "Melekler hepsi kurtuluş mirasını alacaklara hizmet etmek için gönderilen hizmetkâr ruhlar değil midir?",
  ],
  // İbraniler 2 (18 ayet)
  [
    "Bu nedenle işittiğimiz sözlere daha sıkı sarılmalıyız. Yoksa akıntıya kapılıp gideriz.",
    "Melekler aracılığıyla iletilen söz sağlam çıktı. Her suç ve itaatsizlik hak ettiği karşılığı aldı.",
    "Rab'bin kurtardığı bu büyük kurtuluşu ihmal edersek nasıl kaçarız? Bu kurtuluş önce Rab tarafından duyuruldu. İşitenler bize onu doğruladı.",
    "Tanrı da belirtiler, harikalar, çeşitli mucizeler ve Kutsal Ruh'un dağıtımıyla tanıklık etti. Kendi isteğine göre.",
    "Çünkü meleklere boyun eğmeyen gelecek dünyayı -sözünü ettiğimiz dünyayı- bağımlı kılmadı.",
    "Bir yerde biri tanıklık edip şöyle demiş: «İnsan ne ki onu anımsayasın? İnsanoğlu ne ki ona ilgi göstereyim?»",
    "«Onu kısa süre meleklerden aşağı kıldın. Yücelik ve onur tacı giydirdin. Her şeyi ayakları altına serdin.»",
    "«Her şeyi O'na bağımlı kıldın» dediğinde hiçbir şeyi O'na bağımlı kılmadığını bıraktı. Ama şimdilik henüz her şeyin O'na bağımlı kılındığını görmüyoruz.",
    "Ama «kısa süre meleklerden aşağı kılınan» İsa'yı -ölüm acısı çekmesi sayesinde yücelik ve onur tacı giydirilmiş- görüyoruz. Öyle ki Tanrı'nın lütfuyla herkes için ölümü tatsın.",
    "Çünkü birçok oğulu yüceliğe götüren için -her şeyin kaynağı olan- kurtarıcıyı acılar aracılığıyla yetkinleştirmek uygundu.",
    "Kutsal kılan da kutsal kılınanlar da hepsi birdir. Bu nedenle O onlara «kardeş» demekten utanmıyor.",
    "«Senin adını kardeşlerime bildireceğim. Topluluk ortasında sana ilahi söyleyeceğim» diyor.",
    "Yine «Ben O'na güveneceğim» ve yine «İşte ben ve Tanrı'nın bana verdiği çocuklar» diyor.",
    "Çocuklar et ve kana ortak olduğu için O da aynı şekilde onlara ortak oldu. Ölüm gücüne sahip olanı -İblis'i- ölüm aracılığıyla yok etmek",
    "ve ölüm korkusu yüzünden yaşamları boyunca köle olanları özgür kılmak için.",
    "Kuşkusuz meleklere değil, İbrahim'in soyuna yardım ediyor.",
    "Bu nedenle her konuda kardeşlere benzemesi gerekiyordu. Öyle ki Tanrı'ya karşı bağışlayıcı, sadık başkâhin olsun, halkın günahlarını bağışlasın.",
    "Çünkü O kendisi denenip acı çektiği için denenene yardım edebilir.",
  ],
  // İbraniler 3 (19 ayet)
  [
    "Bu nedenle kutsal kardeşler, göksel çağrıya ortaklar olarak, elçi ve başkâhin olan -inandığımız- İsa'ya bakın.",
    "Musa'ya evinde nasıl sadıksa O da kendisini kuran'a öyle sadıktır.",
    "Ev O'nu kuran kişiden daha büyük onur görür. Her ev birini kurar. Oysa her şeyi kuran Tanrı'dır.",
    "Musa Tanrı'nın evinde hizmetkâr olarak -gelecekte söylenecek şeylere tanıklık etmek için- sadıktı.",
    "Mesih ise O'nun evinde Oğul olarak sadıktı. Biz de umudumuzu sürdürürsek O'nun eviyiz.",
    "Bu nedenle Kutsal Ruh diyor ki: «Bugün O'nun sesini işitirseniz,",
    "«Masa başında sınadığımız gibi, çölde atalarınızın beni denediği, sınadığı günlerde» diye yazıldığı gibi yüreklerinizi nasırlaştırmayın.»",
    "«Kırk yıl o kuşağı gücendirdim. Dedim ki: Yürekleri hep sapıktır. Yollarımı bilmediler.»",
    "«Bu yüzden öfkemde ant içtim: Huzuruma girmeyecekler.»",
    "Kardeşler, içinizde biri kötü, imansız yürekle diri Tanrı'dan uzaklaşmasın.",
    "Günahkârların nasırlaştırdığı gibi günahın aldatmasıyla yüreğinizi nasırlaştırmayın diye her gün birbirinizi yüreklendirin.",
    "O'nun sesini işiten, sınayanlarla birlikte nasırlaştıranların hepsinden bugüne dek paydaşız.",
    "Çünkü Mesih'te kalırsak -başlangıçtaki güvene sonuna dek sımsıkı sarılırsak- paydaş olmuş oluruz.",
    "«Bugün O'nun sesini işitirseniz yüreklerinizi nasırlaştırmayın» sözünde yer aldığı gibi.",
    "Kimler işitip nasırlaştırdı? Musa aracılığıyla Mısır'dan çıkanların hepsi değil miydi?",
    "Kırk yıl kimi gücendirdi? Günah işleyip cesetleri çölde düşenler değil miydi?",
    "«Huzuruma girmeyecekler» diye ant içtiği kişiler kimlerdi? İtaat etmeyenler değil miydi?",
    "İtaat etmediklerini görüyoruz. Giremediler.",
    "Giremedikleri için.",
  ],
  // İbraniler 4 (16 ayet)
  [
    "O'nun huzuruna girme vaadi hâlâ geçerli olduğuna göre, içinizden biri «geç kaldı» diye düşünmesin.",
    "Çünkü bize de onlara olduğu gibi Müjde duyuruldu. Ama işittikleri söz onlara yarar sağlamadı. İşitenler imanla birleşmediği için.",
    "İman edenler huzura girdik.",
    "«Bu yüzden öfkemde ant içtim: Huzuruma girmeyecekler» demişti. Oysa işleri dünya kurulduğundan beri tamamlanmıştı.",
    "Yedinci gün için bir yerde şöyle demişti: «Tanrı yedinci günde bütün işlerinden dinlendi.»",
    "Yine burada «Huzuruma girmeyecekler» diyor.",
    "Biri önce belirlenen günde O'nun huzuruna girsin diye, Davut aracılığıyla çok sonra «bugün» diye bir gün belirleniyor -daha önce söylendiği gibi: «Bugün O'nun sesini işitirseniz yüreklerinizi nasırlaştırmayın.»",
    "Yeşu onlara huzur verseydi Tanrı bundan sonra başka bir günden söz etmezdi.",
    "Böylece Tanrı halkı için bir Şabat dinlenmesi kalmıştır.",
    "O'nun huzuruna giren, kendi işlerinden dinlendiği gibi kendi işlerinden dinlenmiş olur.",
    "Bu nedenle huzura girmek için gayret edelim. Öyle ki kimse aynı itaatsizlik örneğine düşmesin.",
    "Tanrı'nın sözü diri ve etkindir. İki ağızlı kılıçtan keskin. Canla ruhu, eklemle iliği ayırır. Yüreğin düşüncelerini, niyetlerini yargılar.",
    "Yaratılmış O'nun önünde çıplaktır. Her şey gözlerinin önünde açıktır. O'na hesap vereceğiz.",
    "Göklerde büyük başkâhinimiz -Tanrı'nın Oğlu İsa- olduğuna göre açıkça tanıklık edelim.",
    "Zayıflıklarımızda bize yakınlık duymayan değil, her konuda bizim gibi denenmiş, ama günah işlememiş bir başkâhinimiz var.",
    "Bu nedenle merhametle lütuf tahtına cesaretle yaklaşalım. Öyle ki yardım alalım, lütuf bulalım.",
  ],
  // İbraniler 5 (14 ayet)
  [
    "Her başkâhin insanlar arasından seçilir. İnsanlar için Tanrı'ya sunulacak sunular ve kurbanlar sunmak üzere atanır.",
    "Zayıflığı bilerek bilgisizlere ve sapkınlara yumuşak davranabilir.",
    "Kendisi de zayıflıkla kuşatıldığı için günahkârlar için olduğu gibi kendi için de sunu sunmak zorundadır.",
    "Kimse kendisi bu onuru almaz. Harun gibi Tanrı tarafından çağrılır.",
    "Mesih de kendini yüceltene «Sen benim Oğlum'sun, bugün ben sana baba oldum» diyen Tanrı'ya başkâhin yapmadı. Başka yerde diyor ki:",
    "«Sen Melkisedek düzeninde sonsuza dek kâhinsin.»",
    "İsa yeryüzündeyken büyük feryat ve gözyaşıyla kendini ölümden kurtarabilen'e dualar ve yalvarışlar sundu. Dinlendi.",
    "Oğul olmasına karşın çektiği acılardan söz dinlemeyi öğrendi.",
    "Yetkinleşince kendisine söz dinleyen herkese sonsuz kurtuluş kaynağı oldu.",
    "Tanrı tarafından Melkisedek düzeninde başkâhin ilan edildi.",
    "Bu konuda söyleyeceğimiz çok şey var. Ama dinleyenler yavaş olduğu için anlatması güç.",
    "Zaman geçtikçe öğretide temel bilgileri öğrenmiş olmanız gerekirdi. Oysa yine Tanrı sözünün temelini, sütten kesilmiş bebekler gibi birinin size öğretmesi gerekiyor.",
    "Katı yiyecekle uğraşan yetişkindir. Duyuları alıştırılmış, iyiyi kötüden ayırt edebilir.",
    "Katı yiyecek, doğruluğu uygulayarak alıştırılmış duyulara sahip yetişkinler içindir.",
  ],
  // İbraniler 6 (20 ayet)
  [
    "Bu nedenle Mesih'in temel öğretisini bırakıp yetkinliğe doğru ilerleyelim. Ölü işlerden tövbe, Tanrı'ya iman, vaftizler, ellerin dayanması, ölülerin dirilişi ve sonsuz yargı öğretisi üzerine yeniden temel atmaya kalkışmayalım.",
    "Tanrı izin verirse bunu yapacağız.",
    "Bir kez aydınlanan, göksel armağanı tadan, Kutsal Ruh'a ortak olan,",
    "Tanrı sözünün iyiliğini ve gelecek çağın güçlerini tadan kişileri yeniden tövbeye getirmek olanaksızdır -kendi istekleriyle Mesih'i tekrar çarmıha gerip rezil ettikleri için.",
    "Toprak sık sık üzerine düşen yağmuru emip ürün verirse -ekeni için bereketli- Tanrı'nın bereketini alır.",
    "Diken ve çalı çıkaran toprak reddedilir, lanetlenir. Sonunda yakılır.",
    "Sevgili kardeşlerim, böyle konuşuyoruz ama sizde daha iyi, kurtuluşa ait şeyler görüyoruz.",
    "Tanrı adil değildir diye düşünmesin. Emeklerinizi ve kutsallara gösterdiğiniz sevgiyi unutmadı.",
    "Tanrı'nın adına yaptığınız hizmeti ve hâlâ yaptığınızı göstermek istiyoruz.",
    "Tanrı adil olsun diye her biriniz aynı gayreti sürdürsün. Umudunuzu sonuna dek tam güvenle taşıyın.",
    "Tembel olmayın. Vaade mirasçı olanların sabrıyla örnek alın.",
    "Tanrı İbrahim'e ant içerek vaat etti. Kimseye göre daha üstün biri olmadığı için kendi adıyla ant içti.",
    "«Seni kutsayacağım, seni çoğaltacağım» dedi.",
    "Böylece sabırla bekleyerek İbrahim vaade kavuştu.",
    "İnsanlar kendilerinden üstün olana ant içerler. Ant sözünü doğrular, her tartışmayı sona erdirir.",
    "Tanrı vaat mirasçılarına niyetini daha açık göstermek için antla pekiştirdi.",
    "İki değişmez şeyde -yalan söylemesi olanaksız Tanrı- büyük teselli bulan bizler, önümüze konan umuda sımsıkı sarılalım.",
    "Bu umut canımız için çapa gibi güvenli ve sağlam. Perdenin arkasına kadar girer.",
    "Öncü olarak oraya giren İsa -Melkisedek düzeninde sonsuza dek başkâhin- bizim için oraya girdi.",
    "Melkisedek düzeninde sonsuza dek başkâhin olarak.",
  ],
  // İbraniler 7 (28 ayet)
  [
    "Bu Melkisedek Salem kralı, Yüce Tanrı'nın kâhiniydi. Kralları bozguna uğratan İbrahim dönüşte gelince onu karşıladı ve kutsadı.",
    "İbrahim ona her şeyin ondalığını verdi. Önce adının anlamı «Doğruluk Kralı»dır. Sonra «Salem Kralı», yani «Esenlik Kralı»dır.",
    "Babasız, annesiz, soy kütüğü yok. Ne başlangıcı ne de yaşamın sonu var. Tanrı Oğlu gibi sürekli kâhin kalıyor.",
    "Bakın büyük atamız İbrahim ganimetten ondalığını verdi.",
    "Levioğullarından kâhinlik alanların Yasa'ya göre halktan -yani kardeşlerinden- ondalık alması buyruğu var. Kendileri de İbrahim'in bedeninden olmalarına karşın.",
    "Soyu sayılmayan Melkisedek ise İbrahim'den ondalık aldı ve vaatleri alanı kutsadı.",
    "Kuşkusuz küçük büyük tarafından kutsanır.",
    "Burada ölümlü insanlar ondalık alıyor. Orada «yaşadığı tanıklık edilen» alıyor.",
    "Levioğulları ondalık alanların İbrahim aracılığıyla ondalık verdiği söylenebilir.",
    "Çünkü Melkisedek İbrahim'i karşıladığında Levi hâlâ atasının bedenindeydi.",
    "Levioğullarına göre kâhinlik alanlar halka göre Yasa'yı aldı. Ama Melkisedek onlara benzemiyordu. İbrahim'den ondalık aldı, vaatleri alanı kutsadı.",
    "Kuşkusuz küçük büyük tarafından kutsanır. Birinde ölümlü insanlar ondalık alıyor. Öbüründe «yaşadığı tanıklık edilen» alıyor.",
    "Melkisedek'e benzer başka biri ortaya çıkıyor.",
    "O hangi oymaktandı biliniyor. Musa'ya göre kâhinlik alanların hiçbiri bu oymaktan değildi.",
    "Bu daha da açıktır. Benzer biçimde başka biri -Melkisedek benzeri- kâhin olarak geliyor.",
    "O bedensel buyruğa göre değil, yok edilemeyen yaşam gücüne göre atandı.",
    "Çünkü «Sen Melkisedek düzeninde sonsuza dek kâhinsin» diye tanıklık ediliyor.",
    "Önceki buyruk zayıf ve yararsız olduğu için geçersiz kılındı.",
    "Yasa hiçbir şeyi yetkinleştirmedi. Tersine daha iyi bir umut getirildi. Onunla Tanrı'ya yaklaşıyoruz.",
    "Bu ant olmadan yapılmadı. Ötekiler ant olmadan kâhin oldu.",
    "Ama O antla kâhin oldu. O'na «Rab ant etti, kararından dönmez: Sen sonsuza dek kâhinsin» diyen.",
    "Böylece İsa daha iyi antlaşmanın kefili oldu.",
    "Öncekiler çok oldu. Ölüm yüzünden hizmette kalamadılar.",
    "Ama O sonsuza dek kalıcı olduğu için değişmeyen kâhinliği var.",
    "Bu nedenle O'nun aracılığıyla Tanrı'ya yaklaşanları tamamen kurtarabilir. O hep yaşayarak onlara aracılık ediyor.",
    "Böyle bir başkâhinimiz var: Kutsal, suçsuz, lekesiz, günahkârlardan ayrılmış, göklerden daha yüce olan.",
    "Öbür başkâhinler gibi önce kendi günahları, sonra halkın günahları için her gün kurban sunması gerekmiyor. Bunu kendisi için bir kez yaptı.",
    "Yasa zayıf insanları başkâhin atar. Ama ant sözü -Yasa'dan sonra gelen- sonsuza dek yetkin olan Oğul'u atadı.",
  ],
  // İbraniler 8 (13 ayet)
  [
    "Söylediklerimizin özeti şudur: Gökte böyle bir başkâhinimiz var. Ululuğun tahtında Oturan'ın sağında oturan.",
    "Kutsal yerde ve gerçek çadırda -Rab'bin değil, insanın kurduğu- hizmetkâr.",
    "Her başkâhin sunular ve kurbanlar sunmak için atanır. Bu nedenle bunun da sunacak bir şeyi olması gerekir.",
    "O yeryüzünde olsaydı kâhin olmazdı. Yasa'ya göre sunu sunan kâhinler var.",
    "Bunlar göksel şeylerin örneği ve gölgesi olan tapınakta hizmet ediyor. Musa tapınağı kurmak üzere buyruk alırken şöyle uyarıldı: «Her şeyi dağda sana gösterilen örnek uyarınca yap.»",
    "Ama İsa şimdi daha üstün bir hizmete kavuştu. Çünkü daha iyi vaatler üzerine kurulmuş daha iyi antlaşmanın aracısıdır.",
    "İlk antlaşma kusursuz olsaydı ikincisine yer kalmazdı.",
    "Ama halkı kusur bulup diyor ki: «İşte günler geliyor» diyor Rab, «İsrail eviyle ve Yahuda eviyle yeni bir antlaşma yapacağım.»",
    "«Atalarının elinden Mısır'dan çıkardığım gün onlarla yaptığım antlaşmaya benzemeyecek. Çünkü onlar antlaşmama bağlı kalmadılar. Ben de onlara ilgi göstermedim» diyor Rab.",
    "«O günlerden sonra İsrail eviyle yapacağım antlaşma şudur» diyor Rab: «Yasalarımı aklarına koyacağım, yüreklerine yazacağım. Onların Tanrısı olacağım, onlar da benim halkım olacak.»",
    "«Kimse komşusunu ve kardeşini tanımayacak» demeyecek. «Rab'bi tanıyın» diyecek. Çünkü küçük büyük hepsi beni tanıyacak.",
    "«Suçlarına merhamet edeceğim. Günahlarını artık anımsamayacağım.»",
    "«Yeni» dediğinde ilkini eskitti. Eskiyen, yaşlanan yok olmaya yakındır.",
  ],
  // İbraniler 9 (28 ayet)
  [
    "İlk antlaşmanın da tapınma kuralları ve dünyevi kutsal yeri vardı.",
    "Kurulan bir çadır vardı. İlk bölmede kandillik, masa ve sunulan ekmekler vardı. Buna Kutsal Yer denir.",
    "İkinci perdenin arkasında Günahlar için sunulan buzağı ve keçinin kanıyla kutsal sayılan Kutsalların Kutsalı'na benzeyen bir bölme vardı.",
    "Altın buhurdan ve her yanı örtülen antlaşma sandığı vardı. İçinde altın testi -manna- ve filizlenen Harun'un asası ve antlaşma levhaları vardı.",
    "Üstünde Bağışlanma Kapağı'nın üzerinde yücelik keruvları vardı. Bunların ayrıntılarına şimdi girmeyelim.",
    "Bunlar böyle düzenlendi. Kâhinler her zaman birinci çadıra girip tapınma hizmetini yapıyor.",
    "Ama yalnız başkâhin ikinci çadıra yılda bir kez giriyor. Kendi kanı olmadan değil -halk için sunduğu kurbanın kanıyla.",
    "Kutsal Ruh bunu gösteriyor: Birinci çadır ayaktayken kutsal yere giden yol henüz açılmamış.",
    "Bu şimdiki çağın bir örneğidir. Sunulan sunular ve kurbanlar vicdanı yetkinleştiremiyor -tapınanı-.",
    "Yalnız yiyecek, içecek, çeşitli vaftizlerle -bedensel kurallarla- doğruluk zamanına dek dayatılıyor.",
    "Ama Mesih gelecekteki iyi şeylerin başkâhini olarak geldi. İnsan eliyle yapılan -bu yaratılışa ait olmayan- daha büyük, daha yetkin çadırdan geçti.",
    "Kendi kanıyla bir kez Kutsalların Kutsalı'na girdi. Ebedi kurtuluşu sağladı.",
    "Eğer keçilerin ve boğaların kanıyla, serpilen düve külleriyle kirlilere kusanları kutsal kılıyorsa,",
    "günahsız kendini sonsuz Ruh aracılığıyla Tanrı'ya sunan Mesih'in kanı vicdanınızı ölü işlerden arındırıp diri Tanrı'ya hizmet etmeniz için ne kadar daha etkindir?",
    "Bu nedenle O yeni antlaşmanın aracısıdır. Ölüm -ilk antlaşma altında olanların suçlarını bağışlatmak için- fidye olarak gerçekleşti. Öyle ki vaat edilen sonsuz mirasa kavuşanlar olsun.",
    "Vasiyet (vasiyetname) olduğu yerde vasiyet edenin ölümü gerekli.",
    "Vasiyet ancak ölümle geçerli. Vasiyet eden yaşadıkça hiçbir gücü yoktur.",
    "Bu nedenle ilk antlaşma da kan olmadan yürürlüğe girmedi.",
    "Musa bütün buyrukları halka bildirdikten sonra su, kırmızı yün, mercanköşotu ile buzağı ve keçilerin kanını alıp hem kitabın hem de bütün halkın üzerine serpti.",
    "«Antlaşmanın kanı budur. Tanrı size buyurdu» dedi.",
    "Çadırı ve tapınma hizmetinde kullanılan bütün kapları aynı şekilde kanla serpti.",
    "Neredeyse her şey Yasa'ya göre kanla temizlenir. Kan dökülmeden bağışlama yoktur.",
    "Göksel şeylerin örnekleri bunlarla temizleniyor. Ama göksel şeylerin kendisi bunlardan daha iyi kurbanlarla.",
    "Mesih kendini birçok kez sunmak için insanların kutsal yerine girmedi.",
    "Son çağın bir kez kendini kurban sunarak günahı ortadan kaldırmak için.",
    "İnsanlara bir kez ölüm, sonra yargı nasıl atanmışsa,",
    "Mesih de birçoklarının günahlarını taşımak için bir kez sunuldu. İkinci kez -kendini bekleyenlere- günah için değil, kurtuluş için görünecek.",
  ],
  // İbraniler 10 (39 ayet)
  [
    "Yasa gelecekteki iyi şeylerin gölgesidir, aslı değil. Bu nedenle aynı sunuları her yıl sürekli sunanlar yaklaşanları asla yetkinleştiremez.",
    "Aksi halde sunular kesilmez miydi? Tapınanlar bir kez temizlendikten sonra vicdanları günah duymazdı.",
    "Ama bu sunularda her yıl günah anımsatılıyor.",
    "Çünkü boğaların ve keçilerin kanı günahları ortadan kaldıramaz.",
    "Bu nedenle dünyaya gelirken diyor: «Kurban ve sunu istemedin. Ama bana bir beden hazırladın.»",
    "«Yakılan sunulardan ve günah sunularından hoşnut olmadın.»",
    "«O zaman dedim: İşte geldim. Kutsal Yazı tomarında benden yazıldığı gibi senin isteğini yapmak için.»",
    "Önce «Kurbanlar, sunular, yakılan sunular, günah sunuları istemedin, hoşnut olmadın» diyor -Yasa'ya göre sunuluyor-.",
    "Sonra «İşte geldim, senin isteğini yapmak için» diyor. İlkini kaldırıyor ki ikincisi geçerli olsun.",
    "Bu istek uyarınca İsa Mesih'in bedeninin bir kez sunulmasıyla kutsal kılınmışız.",
    "Her kâhin her gün ayakta durup hizmet ediyor. Aynı sunuları -asla günahları ortadan kaldıramayan- tekrar tekrar sunuyor.",
    "Ama Mesih günahlar için tek bir kurban sunduktan sonra sonsuza dek Tanrı'nın sağında oturdu.",
    "O zamandan beri düşmanlarının ayaklarının taburesi yapılmasını bekliyor.",
    "Tek bir sunuyla kutsal kılınanları sonsuza dek yetkinleştirdi.",
    "Kutsal Ruh da bize tanıklık ediyor. Önce diyor ki:",
    "«Rab diyor: O günlerden sonra onlarla yapacağım antlaşma budur. Yasalarımı yüreklerine koyacağım, aklarına yazacağım.»",
    "«Günahlarını ve suçlarını artık anımsamayacağım.»",
    "Bunların bağışlanması varsa artık günah sunusu yoktur.",
    "Bu nedenle kardeşler, İsa'nın kanı aracılığıyla kutsal yere -yeni ve diri yol- cesaretimiz var.",
    "O perde -yani kendi bedeni- aracılığıyla açtı.",
    "Büyük kâhinimiz Tanrı evinin üzerinde olduğuna göre,",
    "yüreği serpilen kötü vicdandan, bedeni pak suyla yıkanmış olarak gerçek yürekle imanın tam güveniyle Tanrı'ya yaklaşalım.",
    "Umudumuzu sürdürelim. Çünkü vaat eden güvenilirdir.",
    "Birbirimizi sevgi ve iyi işlere özendirmeyi düşünelim.",
    "Bazılarının alıştığı gibi toplantılara gelmeyi bırakmayalım. Tersine birbirimizi yüreklendirelim. O günün yaklaştığını gördükçe daha çok.",
    "Bilerek günah işleyip gerçeği aldıktan sonra günah sunusu kalmıyor.",
    "Yalnız korkunç bir yargı ve düşmanları yok edecek ateş bekleniyor.",
    "Musa'nın Yasası'nı reddeden iki üç tanık olmadan merhamet görmeden ölür.",
    "Tanrı'nın Oğlu'nu ayaklar altına alan, kutsal sayılan antlaşma kanını bayağı sayan, lütuf veren Ruh'a hakaret eden kişiden ne kadar daha ağır ceza hak eder?",
    "«Öç benim, ben karşılık vereceğim» diyen Tanrı'yı biliyoruz. Yine «Rab halkını yargılayacak» diyor.",
    "Diri Tanrı'nın eline düşmek korkunçtur.",
    "İlk günlerde aydınlandıktan sonra sıkıntıların büyük çatışmasına katlandığınızı anımsayın.",
    "Bazen hakaret ve sıkıntıya sergilendiniz. Bazen böyle acı çekenlere ortak oldunuz.",
    "Hapishanede olanlara acıdınız. Mallarınızın yağma edilmesini sevinçle kabul ettiniz. Göklerde daha iyi, kalıcı malınız olduğunu bilerek.",
    "Cesaretinizi yitirmeyin. Büyük ödülü var.",
    "Sabır gerekir. Tanrı'nın isteğini yapıp vaade kavuşmanız için.",
    "«Biraz, pek az zaman, gelecek olan gelecek, gecikmeyecek.»",
    "«Doğru kişi imanla yaşayacak. Ama çekilirse canımdan hoşnut değilim.»",
    "Biz çekilen değil, imanla canı kurtaranız.",
  ],
  // İbraniler 11 (40 ayet)
  [
    "İman, umut edilenlere güven, görülmeyenlerin kanıtıdır.",
    "Atalar buna tanıklık ettiler.",
    "İmanla evrenin Tanrı'nın sözüyle yaratıldığını anlıyoruz. Görünen şeyler görünmeyenlerden oluştu.",
    "İmanla Habil, Kayin'den daha iyi kurban sundu. Doğru sayıldı. Tanrı armağanlarına tanıklık etti. Ölmesine karşın hâlâ konuşuyor.",
    "İmanla Hanok ölümü görmedi. «Tanrı onu aldı» deniyor. Çünkü alınmadan önce Tanrı'yı hoşnut ettiği tanıklık edildi.",
    "İman olmadan O'nu hoşnut etmek olanaksız. Tanrı'ya yaklaşan O'nun var olduğuna ve kendisini arayanlara ödül veren olduğuna inanmalı.",
    "İmanla Nuh henüz görülmeyen şeyler konusunda uyarıldı. Korkuyla ev halkını kurtarmak için gemi yaptı. Dünyayı yargıladı. İmanla gelen doğruluğun mirasçısı oldu.",
    "İmanla İbrahim çağrıldığında itaat etti. Miras alacağı yere gitmek üzere çıktı. Nereye gideceğini bilmeden gitti.",
    "İmanla vaat edilen diyarda yabancı gibi yaşadı. İshak ve Yakup'la aynı vaadin mirasçısı olarak çadırlarda oturdu.",
    "Çünkü temelleri olan kenti -planlayan ve yapan Tanrı- bekliyordu.",
    "İmanla kendisi de Sara da yaşlılıkta çocuk sahibi olabildi. Çünkü vaat edeni güvenilir saydı.",
    "Bu nedenle tek bir kişiden -hemen ölü sayılan birinden- göklerin yıldızları kadar, kıyıların kumları kadar çok torun doğdu.",
    "Hepsi imanda öldüler. Vaade kavuşmadılar. Ama uzaktan görüp selamladılar. Yeryüzünde yabancı, göçmen olduklarını açıkça söylediler.",
    "Böyle konuşanlar vatan aradığını gösteriyor.",
    "Ayrıldıkları yeri düşünselerdi dönme fırsatları olurdu.",
    "Ama şimdi daha iyi bir vatan -göksel- arıyorlar. Bu nedenle Tanrı onların Tanrısı diye utanmıyor. Onlara kent hazırladı.",
    "İmanla İbrahim denenince İshak'ı sundu. Vaadi alan tek oğlunu sunuyordu.",
    "O'na «İshak'ın soyundan sana soy denecek» denmişti.",
    "Tanrı'nın ölüleri diriltebileceğini düşündü. Bu nedenle onu benzerinden geri aldı.",
    "İmanla İshak Yakup ve Esav'a geleceğe dair kutsadı.",
    "İmanla Yakup ölürken iki oğlunun her birine kutsadı. Değneğinin ucuna dayanarak tapındı.",
    "İmanla Yusuf ölürken İsrail oğullarının Mısır'dan çıkışını anımsattı. Kemikleri için buyruk verdi.",
    "İmanla Musa doğunca üç ay ana babası tarafından gizlendi. Çocuğun güzel olduğunu gördüler. Kralın buyruğundan korkmadılar.",
    "İmanla Musa büyüyünce Firavunun kızının oğlu sayılmayı reddetti.",
    "Günahın geçici zevkinden çok Mesih'in sıkıntısını çekmeyi yeğledi. Mısır hazinelerinden çok hakaretin zenginliğini saydı. Ödüle bakıyordu.",
    "İmanla Mısır'dan çıktı. Kralın öfkesinden korkmadı. Görünmeyeni görür gibi dayandı.",
    "İmanla Fısıh'ı, kan serpmeyi kurdu. Öldürenin İsrail'in ilk doğanlarına dokunmaması için.",
    "İmanla Kızıldeniz'den kuru toprakta geçtiler. Mısırlılar denediklerinde yutuldular.",
    "İmanla Eriha'nın surları yedi gün dönülünce yıkıldı.",
    "İmanla fahişe Rahav casusları barışla kabul etti. İtaat etmeyenlerle birlikte mahvolmadı.",
    "Daha ne söyleyeyim? Gidyon, Barak, Şimşon, Yiftah, Davut, Samuel ve peygamberlerin zamanı yetmez.",
    "İmanla krallıkları yendiler, doğruluk işlediler, vaatlere kavuştular, aslanların ağzını kapadılar.",
    "Ateşin gücünü söndürdüler, kılıcın keskininden kaçtılar. Zayıflıktan güçlü oldular, savaşta güçlü oldular, yabancı orduları bozguna uğrattılar.",
    "Kadınlar ölülerini dirilişle geri aldı. Başkalarıysa kurtulmayı reddedip daha iyi bir dirilişe kavuşmak için işkence gördü.",
    "Başkaları alay, kamçı, zincir, hapis denemesi gördü.",
    "Taşlandılar, testereyle biçildiler, kılıçla öldürüldüler. Koyun postu, keçi postu içinde dolaştılar. Yoksul, sıkıntılı, kötü muamele gördüler.",
    "Dünya onlara layık değildi. Çöllerde, dağlarda, mağaralarda, yerin yarıklarında dolaştılar.",
    "Hepsi imanlarıyla tanıklık ettiler. Vaade kavuşmadılar.",
    "Tanrı bizim için daha iyi bir şey öngördü. Öyle ki biz onsuz yetkinleşmesinler.",
    "Bizi yetkinleştirsin diye.",
  ],
  // İbraniler 12 (29 ayet)
  [
    "Bu nedenle üzerimize örülü büyük tanık bulutu olduğu için her yükü ve bizi kolayca kuşatan günahı sıyırıp atalım.",
    "Sabırla önümüze konan yarışta koşalım.",
    "Gözlerimizi imanın öncüsü ve yetkinleştiricisi İsa'ya çevirelim. O kendi önündeki sevinç uğruna utancı hiçe sayıp çarmıha dayandı. Tanrı tahtının sağında oturdu.",
    "O'nun günahkârlerin karşı koymasına katlanıp böyle düşündüğünü düşünün. Tükenmesin.",
    "Günaha karşı henüz kanınızı dökmediniz.",
    "«Oğlum, Rab'bin terbiyesini küçümseme. O'nun azarlamasından usanma.»",
    "«Rab sevdiğini terbiye eder. Her oğula kabul ettiği gibi dayağa vurur.»",
    "Terbiye için katlanın. Tanrı sizinle oğul gibi davranıyor. Hangi oğul terbiye edilmedi?",
    "Herkese ortak terbiyeden geçmediyseniz -oğullar değil, piçsiniz.",
    "Bedenimizin babaları bizi terbiye etti, saygı duyduk. Ruhların Babası'na daha çok boyun eğip yaşamalı değil miyiz?",
    "Onlar kısa süre kendi isteklerine göre terbiye ettiler. O ise yararımıza -kutsallığımızda payımız olsun diye- terbiye ediyor.",
    "Terbiye o an sevinçli görünmez, üzüntülüdür. Ama sonunda onunla eğitilenlere barışın doğruluğunu verir.",
    "Bu nedenle gevşek elleri, çökmüş dizleri doğrultun.",
    "Ayaklarınız için düz yollar açın. Öyle ki topal olan sarsılmasın, tersine iyileşsin.",
    "Herkesle barışı, kutsallığı kovalayın. Kutsallık olmadan kimse Rab'i görmeyecek.",
    "Kimse Tanrı'nın lütfundan yoksun kalmasın. Acı bir kök filizlenip sizi rahatsız etmesin. Birçokları kirlensin diye.",
    "Fahişe ya da kutsal olmayan biri -Esav gibi- bir yemek için ilk oğulluk hakkını sattı.",
    "Biliyorsunuz, sonra kutsamayı almak istedi. Reddedildi. Gözyaşıyla aradığı halde tövbe için yer bulamadı.",
    "Siz Siyon dağına, diri Tanrı'nın kenti göksel Yeruşalim'e yaklaşmadınız.",
    "Binlerce meleğen toplantısına, ilk doğanların yazıldığı göksel topluluğa, herkesi yargılayan Tanrı'ya, yetkinleşen doğruların ruhlarına,",
    "yeni antlaşmanın aracısı İsa'ya ve Habil'in kanından daha iyi konuşan serpilen kana yaklaşmadınız.",
    "Uyaranı reddetmeyin.",
    "Yeryüzünde uyaran konuştuğunda kaçmadılar. Biz gökteki O'ndan kaçarsak ne olur?",
    "O'nun sesi o zaman yeri salladı.",
    "Şimdi «Bir kez daha yalnız göğü değil, yeri de sallayacağım» diye vaat ediyor.",
    "«Bir kez daha» sözü değişebilir olanların -yaratılmışların- sarsılması, değişmeyenlerin kalması anlamına geliyor.",
    "Bu nedenle sarsılmayan bir egemenlik aldığımız için şükredelim. Öyle ki Tanrı'yı korku ve saygıyla kabul edelim.",
    "Çünkü Tanrımız tüketen ateştir.",
  ],
  // İbraniler 13 (25 ayet)
  [
    "Kardeş sevgisi sürsün.",
    "Konukseverliği unutmayın. Bununla bazıları bilmeden melekleri ağırladı.",
    "Zindandakileri -onlarla birlikte acı çekenler gibi- tutukluları anımsayın.",
    "Herkes evliliğe saygı göstersin. Yatak lekesiz olsun. Fuhuş yapanları ve zina edenleri Tanrı yargılayacak.",
    "Yaşayışınız açgözlü olmasın. Elinizdekilerle yetinin. Çünkü O «Seni asla bırakmam, seni terk etmem» demişti.",
    "Böylece cesaretle diyoruz: «Rab benim yardımcım. Korkmam. İnsan bana ne yapabilir?»",
    "Size söz verenlerin anısına siz de onları anımsayın. Yaşayışlarının sonucuna bakın. İmanlarını örnek alın.",
    "İsa Mesih dün, bugün ve sonsuza dek aynıdır.",
    "Çeşitli yabancı öğretilerle sürüklenmeyin. Yüreği lütufla güçlendirmek -yiyecekle değil- iyidir. Yiyecekle uğraşanlar yarar görmedi.",
    "Sunakımız var. Çadırda hizmet edenlerin ondan yemeye hakkı yok.",
    "Başkâhin günah sunularının kanını Kutsal Yer'e getiriyor. Ama cesetleri ordugahın dışında yakılıyor.",
    "Bu nedenle İsa da halkı kutsamak için kendi kanıyla kentin dışında acı çekti.",
    "O'nun utancını taşıyıp ordugahın dışına çıkalım.",
    "Burada kalıcı kentimiz yok. Gelecekteki kenti arıyoruz.",
    "O'nun aracılığıyla sürekli bir kurban -O'nun adına dudakların meyvesi- sunalım.",
    "İyilik yapmayı ve paylaşmayı unutmayın. Bu tür kurbanlardan Tanrı hoşnut olur.",
    "Önderlerinize boyun eğin, onlara bağımlı olun. Canlarınız için uyanık duruyorlar. Hesap verecekler. Öyle ki sevinçle yapsınlar, inlemeyle değil.",
    "Bize dua edin. Vicdanımız temiz. Her konuda saygın yaşamak istiyoruz.",
    "Özellikle sizi tekrar görmem için daha çok dua edin.",
    "Esenlik veren Tanrı -büyük çoban- koyunların Rabbi'ni ölümden diriltti. O'nun Oğlu İsa Mesih'in kanıyla sonsuz antlaşmayla.",
    "Her iyi işte sizi yetkinleştirsin. Öyle ki isteğini yapasınız. Gözünde hoş olanı Mesih İsa aracılığıyla sizde gerçekleştirsin. O'na sonsuza dek yücelik olsun! Amin.",
    "Kardeşler, bu yüreklendirme sözünü kabul edin. Kısa yazdım.",
    "Timoteos'un serbest bırakıldığını bilin. Onunla birlikte gelirse sizi göreceğim.",
    "Önderlerinizin hepsine ve bütün kutsallara selam söyleyin. İtalya'dan olanlar size selam eder.",
    "Tanrı'nın lütfu hepinizle birlikte olsun.",
  ],
];
