/** Yakup — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const JAMES_CHAPTER_VERSES: string[][] = [
  // Yakup 1 (27 ayet)
  [
    "Tanrı ve Rab İsa Mesih'in kulu Yakup'tan, dağılmış on iki oymağa selam!",
    "Kardeşlerim, çeşitli denemelerle karşılaştığınızda bunu tam sevinç sayın.",
    "Çünkü imanınızın sınanması dayanıklılık doğurur.",
    "Dayanıklılık da tam gelişsin ki, kusursuz ve eksiksiz olasınız, hiçbir konuda eksiğiniz kalmasın.",
    "Birinizde bilgelik eksiği varsa, cömertçe ve kınamadan veren Tanrı'dan istesin. Kendisine verilecektir.",
    "Ama imanla istesin, kuşku duymadan. Çünkü kuşku duyan rüzgârda sürüklenen dalga gibidir.",
    "Öyle bir kişi Rab'den bir şey alacağını sanmasın.",
    "Kararsız kişi her yönde sallanır.",
    "Alçakgönüllü kardeş övünsün - yükseldiği için.",
    "Zengin kardeş de alçaldığı için övünsün. Çünkü zengin çiçek gibi solar.",
    "Güneş doğup sıcaklığıyla otu kuruttuğunda çiçeği düşer, güzelliği yok olur. Zengin de yaşamında böyle solar.",
    "Dayanıklılıkta sınanan kişi mutludur. Çünkü sınavdan geçince yaşam tacını alacak. Rab kendisini sevenlere vaat etti.",
    "Ayartıldığında «Tanrı beni ayartıyor» demesin kimse. Çünkü Tanrı kötülükle ayartılmaz, kendisi de kimseyi ayartmaz.",
    "Her kişi kendi arzusuyla çekilip ayartılır.",
    "Arzu gebe kalınca günah doğurur. Günah olgunlaşınca ölüm doğurur.",
    "Sevgili kardeşlerim, aldanmayın.",
    "Her iyi armağan, her mükemmel bağış yukarıdan, ışıkların Babası'ndandır. O'nda değişme ya da dönme gölgesi yoktur.",
    "O, kendi isteğiyle bizi gerçeğin sözüyle doğurdu. Öyle ki, yaratılışın ilk ürünleri olalım.",
    "Sevgili kardeşlerim, bunu bilin: Her kişi dinlemekte çabuk, konuşmakta yavaş, öfkelenmekte yavaş olsun.",
    "Çünkü insanın öfkesi Tanrı'nın doğruluğunu gerçekleştirmez.",
    "Bu nedenle her pisliği ve her türlü kötülüğü üzerinizden sıyırıp atarak, size iletilen sözü uysalca kabul edin. O söz sizi kurtarabilir.",
    "Sadece sözü dinleyen olmayın, kendinizi aldatın. Sözü yapan olun.",
    "Çünkü sözü dinleyip yapmayan kişi aynada kendi yüzüne bakan kişiye benzer.",
    "Kendine baktı, gitti. Nasıl olduğunu hemen unuttu.",
    "Ama özgürlük yasasına -kusursuz yasaya- bakan ve onda sürekli kalan kişi, dinleyip unutan değil, yapan kişidir. Böyle biri yaptığında mutlu olacaktır.",
    "Bir kimse kendini dindar sayıp dilini dizginlemezse, yüreğini aldatır. Böyle birinin dindarlığı boştur.",
    "Baba Tanrı'nın gözünde pak ve kusursuz dindarlık şudur: Öksüzleri ve dulları sıkıntılarında ziyaret etmek, kendini dünyadan kirletmemek.",
  ],
  // Yakup 2 (26 ayet)
  [
    "Kardeşlerim, yüce Rabbimiz İsa Mesih'in yüce inancına sahip olun.",
    "Örneğin altın yüzüklü, şık giysili biri topluluğunuza gelir, kirli giysili yoksul da gelirse,",
    "şık giysiliye «Buraya, güzel otur» der, yoksula «Orada ayakta dur» ya da «Ayaklarımın yanına otur» derseniz,",
    "aranızda ayrım yapıp yanlış yargıya varmış olmaz mısınız?",
    "Sevgili kardeşlerim, dinleyin: Tanrı dünyada yoksul olanları iman açısından zengin ve kendisini sevenlere vaat edilen egemenliğin mirasçıları olarak seçmedi mi?",
    "Sizse yoksulu aşağıladınız. Oysa sizi sömüren zenginler değil mi?",
    "Sizi mahkemelere sürükleyen, adı güzel olan -üzerine vaftiz edildiğiniz- adı küfür eden onlar değil mi?",
    "Kutsal Yazı'ya göre «Komşunu kendin gibi seveceksin» diye Kral yasasına uyarsanız iyi edersiniz.",
    "Ama ayrım yaparsanız günah işlersiniz. Yasa sizi yasa uygulayıcı olarak mahkûm eder.",
    "Çünkü yasanın tümünde suçlu olan tek bir noktada suçlu olursa tümünde suçlu sayılır.",
    "«Zina etme» diyen «Öldürme» demişti. Zina etmesen de öldürürsen yasayı çiğnemiş olursun.",
    "Özgürlük yasasına göre yargılanacaksınız. Konuşun ve öyle davranın.",
    "Merhamet göstermeyene merhamet edilmez. Merhamet yargıya galip gelir.",
    "Kardeşlerim, bir kimse imanı var der ama işleri yoksa ne yararı var? İman onu kurtarabilir mi?",
    "Bir kardeş ya da kızkardeş çıplak ve günlük yiyecekten yoksunsa",
    "ve sizden biri onlara «Esenlikle git, ısının, doyun» der ama bedenin gereksinimlerini vermezse ne yararı var?",
    "Böylece iman da işleri yoksa kendi başına ölüdür.",
    "Ama biri diyecek: «Senin imanın var, benim işlerim var.» İmansız göster bana imanını. Ben de işlerimle imanımı göstereyim.",
    "Sen Tanrı'nın bir olduğuna inanıyorsun. İyi ediyorsun. Cinler de inanıyor ve titriyor.",
    "Ey boş insan, imanın işlerden ayrı işe yaramaz olduğunu bilmek ister misin?",
    "Atamız İbrahim oğlu İshak'ı sunakta kurban olarak sununca işlerle aklanmadı mı?",
    "Görüyorsun: İman işlerle birlikte etkindi. İman işlerle tamamlandı.",
    "«İbrahim Tanrı'ya iman etti, bu da ona doğruluk sayıldı» sözü yerine geldi. O'na Tanrı'nın dostu dendi.",
    "Görüyorsunuz: Kişi işlerle aklanır, yalnız imanla değil.",
    "Aynı şekilde fahişe Rahav da ulakları başka yoldan göndererek işlerle aklanmadı mı?",
    "Çünkü beden ruhsuz ölüdür. İman da işleri olmadan ölüdür.",
  ],
  // Yakup 3 (18 ayet)
  [
    "Kardeşlerim, birçoğunuz öğretmen olmasın. Biliyorsunuz, öğretmenler daha sıkı yargılanacak.",
    "Hepimiz birçok konuda sürçeriz. Sözle sürçmeyen kişi kusursuzdur. Tüm bedeni dizginleyebilir.",
    "Atların ağzına gem takıyoruz ki bizi dinlesinler. Böylece tüm bedenlerini yönlendiriyoruz.",
    "İşte gemiler de çok büyük, sert rüzgârların sürüklediği şeyler. Küçük bir dümenle istenen yöne çevrilir.",
    "Böylece dil de küçük bir organdır ama büyük işler övünür. Küçük bir kıvılcım büyük bir ormanı tutuşturur.",
    "Dil de bir ateştir. Bedenimizin üyeleri arasında dili koyuyoruz. O bütün bedeni kirletir. Cehennemden tutuşturulmuş yaşam tekerleğini ateşler.",
    "Her tür yabanıl hayvan, kuş, sürüngen, deniz hayvanı insan tarafından evcilleştirilmiştir.",
    "Ama dili hiçbir insan evcilleştiremez. Dinlenmez bir kötülük, ölümcül zehirle doludur.",
    "Onunla Rab'bi Baba'yı överiz. Onunla Tanrı'nın benzeri olarak yaratılmış insanlara söveriz.",
    "Aynı ağızdan övgü ve sövgü çıkar. Kardeşlerim, böyle olmamalı.",
    "Pınar aynı gözden tatlı ve acı su fışkırır mı?",
    "Kardeşlerim, incir ağacı zeytin, asma incir verebilir mi? Tuzlu su tatlı su da veremez.",
    "İçinizde bilge ve anlayışlı kim var? İyi yaşayışıyla bilgeliğin yumuşaklığıyla işlerini göstersin.",
    "Ama yüreğinizde acı kıskançlık, bencillik varsa övünmeyin, gerçeğe karşı yalan söylemeyin.",
    "Bu bilgelik yukarıdan gelen değil, dünyevi, benliğe ait, cinse aittir.",
    "Çünkü kıskançlık ve bencillik olduğunda orada karışıklık ve her kötü iş vardır.",
    "Yukarıdan gelen bilgelik önce pak, sonra barışçıl, yumuşak, uysal, merhamet ve iyi meyvelerle dolu, ayrım yapmayan, ikiyüzlü olmayandır.",
    "Doğruluğun meyvesi barış ekenlerce barışta yetiştirilir.",
  ],
  // Yakup 4 (17 ayet)
  [
    "Nereden geliyor savaşlar, nereden kavgalar aranızda? Bedeninizin üyelerinde savaşan tutkularınızdan değil mi?",
    "İstiyorsunuz, elinize geçmiyor. Kıskançlık ediyor, tutkuyla arzuluyorsunuz. Elde edemiyorsunuz. Kavga ediyor, savaşıyorsunuz. Elinize geçmiyor. İstemediğiniz için istemiyorsunuz.",
    "İstiyorsunuz, almıyorsunuz. Çünkü kötü niyetle istiyorsunuz. Hedefiniz zevk sürmek.",
    "Zina edenler, dünyayı sevenler! Tanrı'ya düşman olmak benliğe düşman olmak olduğunu bilmiyor musunuz? Kim dünyayı severse Baba'ya düşman olur.",
    "Kutsal Yazı boşuna «İçimizde yaşayan Ruh kıskançlıkla özler» demiyor.",
    "Ama O daha büyük lütuf veriyor. Bu nedenle diyor ki: «Tanrı kibirlilere karşıdır, alçakgönüllülere lütuf verir.»",
    "Öyleyse Tanrı'ya boyun eğin. İblis'e direnin, sizden kaçacaktır.",
    "Tanrı'ya yaklaşın, O da size yaklaşacaktır. Günahkârlar, ellerinizi paklayın. İki yürekliler, yüreklerinizi paklayın.",
    "Acı çekin, yas tutun, ağlayın. Gülmeniz keder, sevinciniz üzüntüye dönsün.",
    "Rab'bin önünde alçalın, O sizi yükseltecektir.",
    "Kardeşler, birbirinize karşı konuşmayın. Kardeşine karşı konuşan ya da kardeşini yargılayan, yasaya karşı konuşuyor ve yasayı yargılıyor. Yasayı yargılarsan yasa uygulayıcı değilsin.",
    "Tek Yasa Koyucu ve Yargıç var - kurtarabilen de mahvedebilen de. Ama komşusu kimsin sen?",
    "Şimdi «Bugün ya da yarın filan kente gideceğiz, orada bir yıl kalıp ticaret yapacağız, kazanacağız» diyorsunuz.",
    "Yarının ne getireceğini bilmiyorsunuz. Yaşamınız nedir? Kısa süre görünüp kaybolan buğu gibisiniz.",
    "«Rab dilerse yaşayacağız, şunu ya da bunu yapacağız» demeniz gerekir.",
    "Oysa siz kendinizle övünüyorsunuz. Bu tür övünmeler kötüdür.",
    "İyiyi bilip yapmayan kişi günah işler.",
  ],
  // Yakup 5 (20 ayet)
  [
    "Şimdi ey zenginler, başınıza gelecek felaketler için ağlayıp sızlayın.",
    "Servetiniz çürüdü, giysileriniz güve yedi.",
    "Altın ve gümüşünüz paslandı. Pası size karşı tanıklık edecek, bedenlerinizi ateş gibi yiyecek. Son günlerde servet biriktirdiniz.",
    "Tarlanızda biçtiğiniz işçilerin size ödediğiniz ücreti -sizin tarafınızdan kesilen ücret- haykırıyor. Biçicilerin feryatları Her Şeye Egemen'in kulağına ulaştı.",
    "Yeryüzünde zevk sürdünüz, şehvetle beslendiniz. Kurban gününde yüreklerinizi semirttiniz.",
    "Doğru kişiyi mahkûm ettiniz, öldürdünüz. Size karşı direnmiyor.",
    "Kardeşler, Rab'bin gelişine dek sabredin. Çiftçi toprağın değerli ürününü bekleyip sabırla üzerinde durur.",
    "Siz de sabredin. Yüreklerinizi güçlendirin. Çünkü Rab'bin gelişi yakındır.",
    "Kardeşler, birbirinize karşı söylenmeyin. Yoksa yargılanırsınız. İşte Yargıç kapıda.",
    "Kardeşler, sıkıntı ve sabırda peygamberleri örnek alın. Adlarına «Rab'bin adına konuşan» deniyor.",
    "İşte sabırda dayananları mutlu sayıyoruz. Eyub'un dayanıklılığını duydunuz. Rab'bin sonunu gördünüz. Rab çok merhametli ve acıyandır.",
    "Öncelikle kardeşlerim, ant içmeyin. Ne gök üzerine ne yer üzerine ne de başka bir ant. «Evet»iniz evet, «Hayır»ınız hayır olsun. Yargıya düşmeyesiniz.",
    "Biriniz sıkıntıda mı? Dua etsin. Mutlu mu? İlahi söylesin.",
    "Biriniz hasta mı? Topluluğun ihtiyarlarını çağırsın. Rab adına üzerine yağ sürüp dua etsinler.",
    "İman duası hastayı kurtaracak. Rab onu ayağa kaldıracak. Günah işlemişse bağışlanacak.",
    "Günahlarınızı birbirinize itiraf edin. Birbiriniz için dua edin. Öyle ki iyileşesiniz. Doğru kişinin yalvarışı çok güçlü etkindir.",
    "İlyas da bizim gibi insandı. «Yağmur yağmasın» diye yalvardı. Yeryüzüne üç yıl altı ay yağmur yağmadı.",
    "Yine yalvardı. Gök yağmur verdi, yer ürününü verdi.",
    "Kardeşlerim, biriniz gerçekten saparsa ve biri onu geri getirirse,",
    "Bilin ki günahkârı yanlış yoldan döndüren kişi canını ölümden kurtaracak, birçok günahı örtecektir.",
  ],
];
