/** 1. Yuhanna — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const JOHN1_CHAPTER_VERSES: string[][] = [
  // 1. Yuhanna 1 (10 ayet)
  [
    "Başlangıçtan beri var olanı, yaşam sözünü işittik. Gözlerimizle gördük, seyrettik, ellerimizle dokunduk.",
    "Yaşam açıklandı. Onu gördük ve tanıklık ediyoruz. Sizlere sonsuz yaşamı bildiriyoruz. O Baba'yla birlikteydi, bize açıklandı.",
    "Gördüğümüzü ve işittiğimizi size de bildiriyoruz. Öyle ki siz de bizimle paydaş olasınız. Paydaşlığımız Baba ile Oğlu Mesih İsa iledir.",
    "Bunları size yazıyoruz ki sevincimiz tam olsun.",
    "Tanrı ışıktır. O'nda hiç karanlık yoktur.",
    "«O'nunla paydaşlığımız var» deyip de karanlıkta yürürsek yalan söylemiş oluruz. Gerçeği yaşamayız.",
    "Ama O ışıkta olduğu gibi ışıkta yürürsek birbirimizle paydaşlığımız olur. Oğlu İsa'nın kanı bizi her günahtan arındırır.",
    "«Günahımız yok» dersek kendimizi aldatırız. İçimizde gerçek yoktur.",
    "Günahlarımızı itiraf edersek güvenilir ve adil olan Tanrı günahlarımızı bağışlayıp bizi her kötülükten arındırır.",
    "«Günah işlemedik» dersek O'nu yalancı saymış oluruz. Sözü içimizde yoktur.",
  ],
  // 1. Yuhanna 2 (29 ayet)
  [
    "Yavrularım, bunları size yazıyorum ki günah işlemeyin. Ama biri günah işlerse Baba'nın yanında bir savunucumuz var: Doğru olan İsa Mesih.",
    "O günahlarımız için kurbandır. Yalnız bizim günahlarımız için değil, bütün dünyanın günahları için.",
    "O'nun buyruklarını tutarsak O'nu tanıdığımızı biliriz.",
    "«O'nu tanıyorum» deyip de buyruklarını tutmayan yalancıdır. O'nda gerçek yoktur.",
    "Ama O'nun sözü gerçekten yaşanıyorsa, o kişide Tanrı sevgisi tamamlanmıştır. O'nda olduğumuzu böyle biliriz.",
    "«O'nda yaşıyorum» diyen, O'nun yürüdüğü gibi yürümelidir.",
    "Sevgili kardeşlerim, size yeni buyruk yazmıyorum. Başlangıçtan beri işittiğiniz eski buyruktur. Eski buyruk O'nun ilettiği sözdür.",
    "Yine de size yeni buyruk yazıyorum. O hem sizde hem sizde gerçekleşiyor. Çünkü karanlık geçiyor, gerçek ışık şimdiden parlıyor.",
    "«Işıkta olduğum» deyip de kardeşinden nefret eden hâlâ karanlıktadır.",
    "Kardeşini seven ışıkta kalır. O'nda tökezleme yoktur.",
    "Kardeşinden nefret eden karanlıktadır. Karanlıkta yürür. Nereye gittiğini bilmez. Çünkü karanlık gözlerini kör etmiştir.",
    "Yavrularım, size yazıyorum. Çünkü O'nun adı uğruna günahlarınız bağışlandı.",
    "Babalar, size yazıyorum. Çünkü başlangıçtan beri var olanı tanıdınız. Gençler, size yazıyorum. Çünkü İblis'i yendiniz.",
    "Çocuklar, size yazdım. Çünkü Baba'yı tanıdınız. Babalar, size yazdım. Çünkü başlangıçtan beri var olanı tanıdınız. Gençler, size yazdım. Çünkü güçlüsünüz, Tanrı'nın sözü sizde yaşıyor, İblis'i yendiniz.",
    "Dünyayı da dünyadaki şeyleri de sevmeyin. Kim dünyayı severse Baba'nın sevgisi onda yoktur.",
    "Çünkü dünyada olan her şey -benliğin arzusu, gözün arzusu, yaşamın kibirli güveni- Baba'dan değil, dünyadandır.",
    "Dünya da arzuları da geçiyor. Ama Tanrı'nın isteğini yapan sonsuza dek kalır.",
    "Yavrularım, son saat. «Mesih karşıtı geliyor» diye işittiniz. Şimdi birçok Mesih karşıtı çıktı. Son saat olduğunu böyle biliyoruz.",
    "Bunlar bizdendiler ama bizden değillerdi. Çünkü bizden olsalardı bizimle kalırlardı. Ayrılmaları her birinin bizden olmadığını gösterdi.",
    "Ama siz Kutsal Olan'dan meshettiniz. Hepiniz bilirsiniz.",
    "Gerçeği bilmeniz için değil, gerçeği bildiğiniz ve yalanın sizde olmadığı için size yazdım.",
    "Yalanı yapan kim? İsa'nın Mesih olduğunu yadsıyan. İşte Mesih karşıtı budur: Baba'yı ve Oğul'u yadsıyan.",
    "Oğul'u yadsıyanın Baba'sı yoktur. Oğul'u açıkça kabul edenin Baba'sı da vardır.",
    "Sizde işittiğiniz sözde kalın. Sizde işittiğiniz sözde kalırsanız Oğul'da ve Baba'da kalırsınız.",
    "O'nun bize vaat ettiği budur: Sonsuz yaşam.",
    "Sizi saptıranlar konusunda size yazdım. Ama sizde meshetme kalıyor. Kimseden öğrenmeniz gerekmiyor. Meshetme size her şeyi öğretiyor. Gerçektir, yalan değil. O'nda kaldığınız gibi O'nda kalın.",
    "Şimdi yavrularım, O'nda kalın. Öyle ki O göründüğünde cesaretle çıkalım. O'nun önünde utandırmasın.",
    "O doğru olduğu için doğru olanı yaptığınızı bilirsiniz.",
  ],
  // 1. Yuhanna 3 (24 ayet)
  [
    "Bakın, Baba bize ne büyük sevgi verdi: Tanrı'nın çocukları denilelim. Öyleyiz de. Dünya O'nu tanımıyor. Çünkü O'nu tanımadı.",
    "Sevgili kardeşlerim, şimdi Tanrı'nın çocuklarıyız. Ne olacağımız henüz açıkça görünmedi. Ama O göründüğünde O'na benzer olacağımızı biliyoruz. Çünkü O'nu olduğu gibi göreceğiz.",
    "O'nda bu umudu taşıyan kendini paklar. O paktır.",
    "Günah işleyen yasayı çiğner. Günah yasanın çiğnenmesidir.",
    "O'nun günahı kaldırmak için göründüğünü biliyorsunuz. O'nda günah yoktur.",
    "O'nda kalan günah işlemez. Günah işleyen O'nu görmemiş, tanımamıştır.",
    "Yavrularım, kimse sizi saptırmasın. Doğru olanı yapan doğrudur. O doğru gibidir.",
    "Günah işleyen İblis'tendir. Çünkü İblis başlangıçtan beri günah işliyor. Tanrı'nın Oğlu bunun için göründü: İblis'in işlerini yok etmek için.",
    "Tanrı'dan doğan günah işlemez. Çünkü O'nun tohumu onda kalır. Günah işleyemez. Çünkü Tanrı'dan doğmuştur.",
    "Tanrı'nın çocuklarıyla İblis'in çocukları böyle ayırt edilir: Doğru olanı yapmayan Tanrı'dan değildir. Kardeşini sevmeyen de öyle.",
    "Çünkü işittiğiniz bildiri baştan beri şudur: Birbirimizi sevelim.",
    "Kayin gibi olmayalım. O Kötü Olan'dandı ve kardeşini öldürdü. Neden öldürdü? Kendi işleri kötü, kardeşininki doğru olduğu için.",
    "Kardeşlerim, dünya sizden nefret ederse şaşmayın.",
    "Kardeşimizi sevdiğimizi biliyoruz. Ölümden yaşama geçmişiz. Sevmeyen ölümde kalır.",
    "Kardeşinden nefret eden katildir. Hiçbir katilin sonsuz yaşamı sizde kalmadığını biliyorsunuz.",
    "Sevgiyi böyle tanıdık: O canını bizim için verdi. Biz de kardeşler için canlarımızı vermeliyiz.",
    "Dünya malına sahip olup kardeşini ihtiyaç içinde görüp yüreğini kapayan kişide Tanrı sevgisi nasıl kalır?",
    "Yavrularım, sözle ve dille değil, eylemle ve gerçekle sevelim.",
    "Böylece gerçeğe ait olduğumuzu bileceğiz. O'nun önünde yüreğimizi yatıştıracağız.",
    "Yürek bizi mahkûm ederse Tanrı yürekten büyüktür. Her şeyi bilir.",
    "Sevgili kardeşlerim, yürek bizi mahkûm etmezse Tanrı'ya cesaretimiz olur.",
    "Ne dilersek O'ndan alırız. Çünkü buyruklarını tutuyor, O'nun gözünde hoş olanı yapıyoruz.",
    "Buyruğu şudur: Oğlu Mesih İsa'ya iman edelim, birbirimizi sevelim. O'nun bize verdiği buyruk uyarınca.",
    "Buyruklarını tutan O'nda kalır, O da onda. O'nda yaşadığını Ruh'tan verdiğiyle biliriz.",
  ],
  // 1. Yuhanna 4 (21 ayet)
  [
    "Sevgili kardeşlerim, her ruha inanmayın. Ruhların Tanrı'dan olup olmadığını sınayın. Çünkü birçok sahte peygamber dünyaya çıktı.",
    "Tanrı'nın Ruh'u şöyle tanıyorsunuz: İsa Mesih'in beden alıp geldiğini kabul eden her ruh Tanrı'dandır.",
    "İsa Mesih'i kabul etmeyen her ruh Tanrı'dan değildir. İşte Mesih karşıtının ruhu budur. Onun geleceğini işittiniz. Şimdi de dünyadadır.",
    "Yavrularım, siz Tanrı'dansınız ve onları yendiniz. Çünkü sizde olan dünyadakinden büyüktür.",
    "Onlar dünyadandır. Bu nedenle dünyadan konuşuyorlar. Dünya onları dinliyor.",
    "Biz Tanrı'danız. Bizi tanıyan dinler. Tanrı'dan olmayan dinlemez. Gerçeği sahte olandan böyle ayırt ederiz.",
    "Sevgili kardeşlerim, birbirimizi sevelim. Çünkü sevgi Tanrı'dandır. Seven herkes Tanrı'dan doğmuştur. Tanrı'yı tanır.",
    "Sevmeyen Tanrı'yı tanımadı. Çünkü Tanrı sevgidir.",
    "Tanrı'nın sevgisi şöyle açıklandı: Tanrı biricik Oğlu'nu dünyaya gönderdi. Öyle ki O'nun aracılığıyla yaşayalım.",
    "Sevgi şudur: Biz Tanrı'yı sevmedik, O bizi sevdi. Oğlu'nu günahlarımız için kurtarıcı kurban olarak gönderdi.",
    "Sevgili kardeşlerim, Tanrı bizi böyle sevdiyse biz de birbirimizi sevmek zorundayız.",
    "Tanrı'yı hiç kimse hiçbir zaman görmedi. Birbirimizi seversek Tanrı bizde yaşar. Sevgisi bizde tamamlanır.",
    "O'nda yaşadığımızı ve O'nun bizde yaşadığını biliyoruz. Bize Ruh'undan verdi.",
    "Baba'nın Oğul'u dünyanın Kurtarıcısı olarak gönderdiğini gördük. Tanıklık ediyoruz.",
    "İsa'nın Tanrı'nın Oğlu olduğunu açıkça kabul eden kişide Tanrı yaşar, o da Tanrı'da.",
    "Tanrı'nın bize beslediği sevgiyi tanıdık, buna inandık. Tanrı sevgidir. Sevgiyle yaşayan Tanrı'da yaşar, Tanrı da onda.",
    "Sevgi bizde böyle tamamlandı. Yargı gününde cesaretimiz olsun. Çünkü O nasılsa bu dünyada biz de öyleyiz.",
    "Sevgide korku yoktur. Yetkin sevgi korkuyu dışarı atar. Çünkü korku cezayla ilgilidir. Korkan sevgide yetkinleşmemiştir.",
    "Seviyoruz. Çünkü O önce bizi sevdi.",
    "«Tanrı'yı seviyorum» deyip de kardeşinden nefret eden yalancıdır. Görmediği kardeşini sevmeyen, gördüğü Tanrı'yı sevemez.",
    "O'nun buyruğu şudur: Tanrı'yı seven kardeşini de sevsin.",
  ],
  // 1. Yuhanna 5 (21 ayet)
  [
    "İsa'nın Mesih olduğuna inanan herkes Tanrı'dan doğmuştur. Baba'yı seven O'ndan doğanı da sever.",
    "Tanrı'yı sevip buyruklarını tuttuğumuzda Tanrı'nın çocuklarını sevdiğimizi biliriz.",
    "Tanrı'yı sevmek O'nun buyruklarını tutmaktır. Buyrukları ağır değildir.",
    "Çünkü Tanrı'dan doğan herkes dünyayı yener. Dünyayı yenen zafer budur: İmanımız.",
    "Dünyayı yenen kim? İsa'nın Tanrı'nın Oğlu olduğuna iman eden.",
    "İsa Mesih -su ve kanla gelen- O'dur. Yalnız suyla değil, su ve kanla. Tanıklık eden Ruh'tur. Çünkü Ruh gerçektir.",
    "Tanıklık eden üçtür: Ruh, su ve kan. Bu üçü uyum içindedir.",
    "İnsanın tanıklığını kabul ediyoruz. Tanrı'nın tanıklığı daha büyüktür. Çünkü Tanrı'nın tanıklığı Oğlu için verdiği tanıklıktır.",
    "Tanrı'nın Oğlu'na iman edenin tanıklığı kendindedir. Tanrı'ya iman etmeyen O'nu yalancı saymıştır. Çünkü Tanrı'nın Oğlu hakkında verdiği tanıklığa iman etmemiştir.",
    "Tanıklık şudur: Tanrı bize sonsuz yaşam verdi. Bu yaşam O'nun Oğlu'ndadır.",
    "Oğul'a sahip olanın yaşamı vardır. Tanrı'nın Oğlu'na sahip olmayanın yaşamı yoktur.",
    "Size Tanrı'nın Oğlu'na iman edenlere yazdım. Öyle ki sonsuz yaşamınız olduğunu bilesiniz.",
    "O'na cesaretle yaklaşabileceğimiz umudumuz budur.",
    "O'ndan ne dilersek işitir. Çünkü buyruklarını tutuyoruz, gözünde hoş olanı yapıyoruz.",
    "O'nun buyruğu şudur: Oğlu Mesih İsa'ya iman edelim, birbirimizi sevelim.",
    "O'nun buyruklarını tutan O'nda kalır, O da onda. O'nda yaşadığını Ruh'tan verdiğiyle biliriz.",
    "Sevgili kardeşim, günah işlemeyen birini görürsen bilsin ki doğru olanı yapan doğrudur. O doğru gibidir.",
    "Günah işleyen İblis'tendir. Çünkü İblis başlangıçtan beri günah işliyor. Tanrı'nın Oğlu bunun için göründü: İblis'in işlerini yok etmek için.",
    "Tanrı'dan doğan günah işlemez. Çünkü O'nun tohumu onda kalır. Günah işleyemez. Çünkü Tanrı'dan doğmuştur.",
    "Tanrı'nın çocuklarıyla İblis'in çocukları böyle ayırt edilir.",
    "Bunları size yazdım. Tanrı'nın Oğlu'nun adına iman edesiniz, iman ederek sonsuz yaşamınız olsun diye.",
    "Sevgili çocuklar, kendinizi putlardan koruyun.",
  ],
];
