/** Markos — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const MARK_CHAPTER_VERSES: string[][] = [
  // Markos 1 (45 ayet)
  [
    "Tanrı'nın Oğlu İsa Mesih'le ilgili Müjde'nin başlangıcı.",
    "Peygamber Yeşaya'nın Kitabı'nda şöyle yazılmıştır: \"İşte, habercimi senin önünden gönderiyorum; O senin yolunu hazırlayacak.\"",
    "\"Çölde haykıran, 'Rab'bin yolunu hazırlayın, Geçeceği patikaları düzleyin' diye sesleniyor.\"",
    "Böylece Vaftizci Yahya çölde ortaya çıktı. İnsanları, günahlarının bağışlanması için tövbe edip vaftiz olmaya çağırıyordu.",
    "Bütün Yahudiye halkı ve Yeruşalimliler'in hepsi ona geliyor, günahlarını itiraf ediyor, onun tarafından Şeria Irmağı'nda vaftiz ediliyordu.",
    "Yahya'nın deve tüyünden giysisi, belinde deri kuşağı vardı. Çekirge ve yaban balı yerdi.",
    "Şu haberi yayıyordu: \"Benden sonra benden daha güçlü olan geliyor. Eğilip O'nun çarıklarının bağını çözmeye bile layık değilim.",
    "Ben sizi suyla vaftiz ettim, ama O sizi Kutsal Ruh'la vaftiz edecektir.\"",
    "O günlerde Celile'nin Nasıra Kenti'nden çıkıp gelen İsa, Yahya tarafından Şeria Irmağı'nda vaftiz edildi.",
    "Tam sudan çıkarken, göklerin yarıldığını ve Ruh'un güvercin gibi üzerine indiğini gördü.",
    "Göklerden, \"Sen benim sevgili Oğlum'sun, senden hoşnudum\" diyen bir ses duyuldu.",
    "O an Ruh, İsa'yı çöle gönderdi.",
    "İsa çölde kaldığı kırk gün boyunca Şeytan tarafından denendi. Yabanıl hayvanlar arasındaydı, melekler O'na hizmet ediyordu.",
    "Yahya'nın tutuklanmasından sonra İsa, Tanrı'nın Müjdesi'ni duyura duyura Celile'ye gitti.",
    "\"Zaman doldu\" diyordu, \"Tanrı'nın Egemenliği yaklaştı. Tövbe edin, Müjde'ye inanın!\"",
    "İsa, Celile Gölü'nün kıyısından geçerken, göle ağ atmakta olan Simun ile kardeşi Andreas'ı gördü. Bu adamlar balıkçıydı.",
    "İsa onlara, \"Ardımdan gelin\" dedi, \"Sizleri insan tutan balıkçılar yapacağım.\"",
    "Onlar da hemen ağlarını bırakıp O'nun ardından gittiler.",
    "İsa biraz ileri gidince Zebedi'nin oğulları Yakup'la Yuhanna'yı gördü. Teknede ağlarını onarıyorlardı.",
    "Hemen onları çağırdı. Onlar da babaları Zebedi'yi işçilerle birlikte teknede bırakıp İsa'nın ardından gittiler.",
    "Kefarnahum'a girdiler. Şabat Günü İsa havraya gidip öğretmeye başladı.",
    "Halk O'nun öğretişine şaşıp kaldı. Çünkü onlara din bilginleri gibi değil, yetkili biri gibi öğretiyordu.",
    "Tam o sırada havrada bulunan ve kötü ruha tutulmuş bir adam, \"Ey Nasıralı İsa, bizden ne istiyorsun?\" diye bağırdı.",
    "\"Bizi mahvetmeye mi geldin? Senin kim olduğunu biliyorum, Tanrı'nın Kutsalı'sın sen!\"",
    "İsa, \"Sus, çık adamdan!\" diyerek kötü ruhu azarladı.",
    "Kötü ruh adamı sarstı ve büyük bir çığlık atarak içinden çıktı.",
    "Herkes şaşıp kaldı. Birbirlerine, \"Bu nasıl şey?\" diye sormaya başladılar. \"Yepyeni bir öğreti! Kötü ruhlara bile yetkiyle buyruk veriyor, onlar da sözünü dinliyor.\"",
    "Böylece İsa'yla ilgili haber, Celile bölgesinin her yerine hızla yayıldı.",
    "İsa havradan çıkar çıkmaz, Yakup ve Yuhanna ile birlikte Simun ve Andreas'ın evine gitti.",
    "Simun'un kaynanası ateşler içinde yatıyordu. Durumu hemen İsa'ya bildirdiler.",
    "O da hastaya yaklaştı, elinden tutup kaldırdı. Kadının ateşi düştü, onlara hizmet etmeye başladı.",
    "Akşam olup güneş batınca, bütün hastaları ve cinlileri İsa'ya getirdiler.",
    "Bütün kent halkı kapıya toplanmıştı.",
    "İsa, çeşitli hastalıklara yakalanmış birçok kişiyi iyileştirdi, birçok cini kovdu. Cinlerin konuşmasına izin vermiyordu. Çünkü onlar kendisinin kim olduğunu biliyorlardı.",
    "Sabah çok erkenden, ortalık henüz ağarmadan İsa kalktı, evden çıkıp ıssız bir yere gitti, orada dua etmeye başladı.",
    "Simun ile yanındakiler İsa'yı aramaya çıktılar.",
    "O'nu bulunca, \"Herkes seni arıyor!\" dediler.",
    "İsa onlara, \"Başka yerlere, yakın kasabalara gidelim\" dedi. \"Oralarda da Tanrı sözünü duyurayım. Bunun için çıkıp geldim.\"",
    "Böylece havralarında Tanrı sözünü duyurarak ve cinleri kovarak bütün Celile bölgesini dolaştı.",
    "İsa'ya cüzamlı biri geldi, diz çökerek, \"İstersen beni temiz kılabilirsin\" diye yalvardı.",
    "İsa'nın yüreği sızladı, elini uzatıp adama dokundu, \"İsterim, temiz ol!\" dedi.",
    "Adam anında cüzamdan kurtulup tertemiz oldu.",
    "İsa onu sıkıca uyararak hemen yanından uzaklaştırdı.",
    "\"Sakın kimseye bir şey söyleme!\" dedi. \"Git, kâhine görün ve cüzamdan temizlendiğini herkese kanıtlamak için Musa'nın buyurduğu sunuları sun.\"",
    "Ne var ki, adam çıkıp gitti, olayla ilgili haberi her tarafa yayıp duyurmaya başladı. Öyle ki, İsa artık hiçbir kente açıkça giremez oldu. Ancak dışarıda, ıssız yerlerde kalıyordu. Ve halk her yerden O'na akın ediyordu.",
  ],
  // Markos 2 (28 ayet)
  [
    "Birkaç gün sonra İsa tekrar Kefarnahum'a geldiğinde, evde olduğu duyuldu.",
    "O kadar çok insan toplandı ki, artık kapının önünde bile duracak yer kalmamıştı. İsa onlara Tanrı sözünü anlatıyordu.",
    "Bu arada O'na dört kişinin taşıdığı felçli bir adamı getirdiler.",
    "Kalabalıktan O'na yaklaşamadıkları için, bulunduğu yerin üzerindeki damı delip açarak felçliyi üstünde yattığı şilteyle birlikte aşağı indirdiler.",
    "İsa onların imanını görünce felçliye, \"Oğlum, günahların bağışlandı\" dedi.",
    "Orada oturan bazı din bilginleri ise içlerinden şöyle düşündüler: \"Bu adam neden böyle konuşuyor? Tanrı'ya küfrediyor! Tanrı'dan başka kim günahları bağışlayabilir?\"",
    "Akıllarından geçeni hemen ruhunda sezen İsa onlara, \"Aklınızdan neden böyle şeyler geçiriyorsunuz?\" dedi.",
    "\"Hangisi daha kolay, felçliye, 'Günahların bağışlandı' demek mi, yoksa, 'Kalk, şilteni topla, yürü' demek mi?",
    "Ne var ki, İnsanoğlu'nun yeryüzünde günahları bağışlama yetkisine sahip olduğunu bilesiniz diye...\"",
    "Sonra felçliye, \"Sana söylüyorum, kalk, şilteni topla, evine git!\" dedi.",
    "Adam kalktı, hemen şiltesini topladı, hepsinin gözü önünde çıkıp gitti.",
    "Herkes şaşakalmıştı. Tanrı'yı övüyorlar, \"Böylesini hiç görmemiştik\" diyorlardı.",
    "İsa yine çıkıp göl kıyısına gitti. Bütün halk yanına geldi, O da onlara öğretmeye başladı.",
    "Yoldan geçerken, vergi toplama yerinde oturan Alfay oğlu Levi'yi gördü. Ona, \"Ardımdan gel\" dedi. Levi de kalkıp İsa'nın ardından gitti.",
    "Sonra İsa, Levi'nin evinde yemek yerken, birçok vergi görevlisiyle günahkâr O'nunla ve öğrencileriyle birlikte sofraya oturmuştu. O'nu izleyen böyle birçok kişi vardı.",
    "Ferisiler'den bazı din bilginleri, O'nu günahkârlar ve vergi görevlileriyle birlikte yemekte görünce öğrencilerine, \"Niçin vergi görevlileri ve günahkârlarla birlikte yemek yiyor?\" diye sordular.",
    "Bunu duyan İsa onlara, \"Sağlamların değil, hastaların hekime ihtiyacı var\" dedi. \"Ben doğru kişileri değil, günahkârları çağırmaya geldim.\"",
    "Yahya'nın öğrencileriyle Ferisiler oruç tutarken, bazı kişiler İsa'ya gelip, \"Yahya'nın ve Ferisiler'in öğrencileri oruç tutuyor da senin öğrencilerin neden tutmuyor?\" diye sordular.",
    "İsa şöyle karşılık verdi: \"Güvey aralarında olduğu sürece davetliler oruç tutar mı? Güvey aralarında oldukça oruç tutmazlar!",
    "Ama güveyin aralarından alınacağı günler gelecek, onlar işte o zaman, o gün oruç tutacaklar.",
    "Hiç kimse eski giysiyi yeni kumaş parçasıyla yamamaz. Yoksa yeni yama çeker, eski giysiden kopar, yırtık daha beter olur.",
    "Hiç kimse yeni şarabı eski tulumlara doldurmaz. Yoksa şarap tulumları patlatır, şarap da tulumlar da mahvolur. Yeni şarap yeni tulumlara doldurulur.\"",
    "Bir Şabat Günü İsa ekinler arasından geçiyordu. Öğrencileri yolda giderken başakları koparmaya başladılar.",
    "Ferisiler İsa'ya, \"Bak, Şabat Günü yasak olanı neden yapıyorlar?\" dediler.",
    "İsa onlara, \"Davut'la yanındakiler aç ve muhtaç kalınca Davut'un ne yaptığını hiç okumadınız mı?\" diye sordu.",
    "\"Başkâhin Aviyatar'ın zamanında Davut, Tanrı'nın evine girdi, kâhinlerden başkasının yemesi yasak olan adak ekmeklerini yedi ve yanındakilere de verdi.\"",
    "Sonra onlara, \"İnsan Şabat Günü için değil, Şabat Günü insan için yaratıldı\" dedi.",
    "\"Bu nedenle İnsanoğlu Şabat Günü'nün de Rabbi'dir.\"",
  ],
  // Markos 3 (35 ayet)
  [
    "İsa yine havraya girdi. Orada eli sakat bir adam vardı.",
    "Bazıları İsa'yı suçlamak amacıyla, Şabat Günü hastayı iyileştirecek mi diye O'nu gözlüyorlardı.",
    "İsa, eli sakat adama, \"Kalk, öne çık!\" dedi.",
    "Sonra havradakilere, \"Kutsal Yasa'ya göre Şabat Günü iyilik yapmak mı doğru, kötülük yapmak mı? Can kurtarmak mı doğru, can almak mı?\" diye sordu. Onlardan ses çıkmadı.",
    "İsa, çevresindekilere öfkeyle baktı. Yüreklerinin duygusuzluğu O'nu kederlendirmişti. Adama, \"Elini uzat!\" dedi. Adam elini uzattı, eli yine sapasağlam oluverdi.",
    "Bunun üzerine Ferisiler dışarı çıktılar, İsa'yı yok etmek için Hirodes yanlılarıyla hemen görüşmeye başladılar.",
    "İsa, öğrencileriyle birlikte göl kıyısına çekildi. Celile'den büyük bir kalabalık O'nun ardından geldi.",
    "Ayrıca, bütün yaptıklarını duyan büyük kalabalıklar Yahudiye'den, Yeruşalim'den, İdumeya'dan, Şeria Irmağı'nın karşı yakasından, Sur ve Sayda bölgelerinden kendisine akın etti.",
    "İsa, kalabalığın arasında sıkışıp kalmamak için öğrencilerine bir kayık hazır bulundurmalarını söyledi.",
    "Birçoklarını iyileştirmiş olduğundan, çeşitli hastalıklara yakalananlar O'na dokunmak için üzerine üşüşüyordu.",
    "Kötü ruhlar O'nu görünce ayaklarına kapanıyor, \"Sen Tanrı'nın Oğlu'sun!\" diye bağırıyorlardı.",
    "Ama İsa, kim olduğunu açıklamamaları için onları sıkı sıkıya uyardı.",
    "İsa, dağa çıkarak istediği kişileri yanına çağırdı. Onlar da yanına gittiler.",
    "İsa bunlardan on iki kişiyi yanında bulundurmak, Tanrı sözünü duyurmaya göndermek ve cinleri kovmaya yetkili kılmak üzere seçti.",
    "Seçtiği bu on iki kişi şunlardır: Petrus adını verdiği Simun, Beni-Regeş, yani Gökgürültüsü Oğulları adını verdiği Zebedi'nin oğulları Yakup ve Yuhanna, Andreas, Filipus, Bartalmay, Matta, Tomas, Alfay oğlu Yakup, Taday, Yurtsever Simun ve İsa'ya ihanet eden Yahuda İskariot.",
    "İsa bundan sonra eve gitti. Yine öyle büyük bir kalabalık toplandı ki, İsa'yla öğrencileri yemek bile yiyemediler.",
    "Yakınları bunu duyunca, \"Aklını kaçırmış\" diyerek O'nu almaya geldiler.",
    "Yeruşalim'den gelen din bilginleri ise, \"Baalzevul O'nun içine girmiş\" ve \"Cinleri, cinlerin önderinin gücüyle kovuyor\" diyorlardı.",
    "Bunun üzerine İsa din bilginlerini yanına çağırıp onlara benzetmelerle seslendi. \"Şeytan, Şeytan'ı nasıl kovabilir?\" dedi.",
    "\"Bir ülke kendi içinde bölünmüşse, ayakta kalamaz.",
    "Bir ev kendi içinde bölünmüşse, ayakta kalamaz.",
    "Şeytan da kendine karşı gelip kendi içinde bölünmüşse, artık ayakta kalamaz; sonu gelmiş demektir.",
    "Hiç kimse güçlü adamın evine girip malını çalamaz. Ancak onu bağladıktan sonra evini soyabilir.",
    "Size doğrusunu söyleyeyim, insanların işlediği her günah, ettiği her küfür bağışlanacak, ama Kutsal Ruh'a küfreden asla bağışlanmayacak. Bunu yapan, asla silinmeyecek bir günah işlemiş olur.\"",
    "İsa bu sözleri, \"O'nda kötü ruh var\" dedikleri için söyledi.",
    "Daha sonra İsa'nın annesiyle kardeşleri geldi. Dışarıda durdular, haber gönderip O'nu çağırdılar.",
    "İsa'nın çevresinde oturan kalabalıktan bazıları, \"Bak\" dediler, \"Annenle kardeşlerin dışarıda, seni istiyorlar.\"",
    "İsa buna karşılık onlara, \"Kimdir annem ve kardeşlerim?\" dedi.",
    "Sonra çevresinde oturanlara bakıp şöyle dedi: \"İşte annem, işte kardeşlerim!",
    "Tanrı'nın isteğini kim yerine getirirse, kardeşim, kızkardeşim ve annem odur.\"",
  ],
  // Markos 4 (41 ayet)
  [
    "İsa göl kıyısında halka yine öğretmeye başladı. Çevresinde çok büyük bir kalabalık toplandı. Bu yüzden İsa göldeki bir tekneye binip oturdu. Bütün kalabalık göl kıyısında duruyordu.",
    "İsa onlara benzetmelerle birçok şey öğretiyordu. Öğretirken, \"Şunu dinleyin\" dedi.",
    "\"Ekincinin biri tohum ekmeye çıktı.",
    "Ektiği tohumlardan kimi yol kenarına düştü. Kuşlar gelip bunları yedi.",
    "Kimi, toprağı az kayalık yerlere düştü. Toprak derin olmadığından hemen filizlendi.",
    "Ne var ki, güneş doğunca kavruldular, kök salamadıkları için kuruyup gittiler.",
    "Kimi, dikenler arasına düştü. Dikenler büyüdü, filizleri boğdu ve filizler ürün vermedi.",
    "Kimi ise iyi toprağa düştü, büyüyüp çoğaldı, ürün verdi. Bazısı otuz, bazısı altmış, bazısı da yüz kat ürün verdi.\"",
    "Sonra İsa şunu ekledi: \"İşitecek kulağı olan işitsin!\"",
    "Onikiler'le öbür izleyicileri İsa'yla yalnız kalınca, kendisinden benzetmelerin anlamını sordular.",
    "O da onlara şöyle dedi: \"Tanrı'nın Egemenliği'nin sırrı sizlere açıklandı, ama dışarıda olanlara her şey benzetmelerle anlatılır.",
    "Öyle ki, 'Bakıp bakıp görmesinler, Duyup duyup anlamasınlar da, Dönüp bağışlanmasınlar.'\"",
    "İsa sonra onlara, \"Siz bu benzetmeyi anlamıyor musunuz?\" dedi. \"Öyleyse bütün benzetmeleri nasıl anlayacaksınız?",
    "Ekincinin ektiği, Tanrı sözüdür.",
    "Bazı insanlar sözün ekildiği yerde yol kenarına düşen tohumlara benzer. Bunlar sözü işitir işitmez, Şeytan gelir, yüreklerine ekilen sözü alır götürür.",
    "Kayalık yerlere ekilenler ise, işittikleri sözü hemen sevinçle kabul eden, ama kök salamadıkları için ancak bir süre dayanan kişilerdir. Böyleleri Tanrı sözünden ötürü sıkıntı ya da zulme uğrayınca hemen sendeleyip düşerler.",
    "Yine bazıları dikenler arasında ekilen tohumlara benzerler. Bunlar sözü işitirler, ama dünyasal kaygılar, zenginliğin aldatıcılığı ve daha başka hevesler araya girip sözü boğar ve ürün vermesini engeller.",
    "İyi toprağa ekilenler ise, sözü işiten, onu benimseyen, kimi otuz, kimi altmış, kimi de yüz kat ürün veren kişilerdir.\"",
    "Onlara, \"Kandili, tahıl ölçeğinin ya da yatağın altına koymak için mi getirirler?\" dedi. \"Kandilliğe koymak için değil mi?",
    "Gizli olan ne varsa, açığa çıkarılmak üzere gizlenmiştir; saklı olan ne varsa, aydınlığa çıkmak üzere saklanmıştır.",
    "İşitecek kulağı olan işitsin!\"",
    "İsa şöyle devam etti: \"İşittiklerinize dikkat edin! Hangi ölçekle verirseniz, aynı ölçekle alacaksınız. Hatta size daha fazlası verilecek.",
    "Çünkü kimde varsa, ona daha çok verilecek. Ama kimde yoksa, elindeki de alınacak.\"",
    "Sonra İsa şöyle dedi: \"Tanrı'nın Egemenliği, toprağa tohum saçan adama benzer.",
    "Gece olur, uyur; gündüz olur, kalkar. Kendisi nasıl olduğunu bilmez ama, tohum filizlenir, gelişir.",
    "Toprak kendiliğinden ürün verir. Önce filizi, sonra başağı, sonunda da başağı dolduran taneleri verir.",
    "Ürün olgunlaşınca, adam hemen orağı vurur. Çünkü biçim vakti gelmiştir.\"",
    "İsa sonra şöyle dedi: \"Tanrı'nın Egemenliği'ni neye benzetelim, nasıl bir benzetmeyle anlatalım?",
    "Tanrı'nın Egemenliği, hardal tanesine benzer. Hardal, yeryüzünde toprağa ekilen tohumların en küçüğü olmakla birlikte, ekildikten sonra gelişir, bütün bahçe bitkilerinin boyunu aşar. Öylesine dal budak salar ki, kuşlar gölgesinde barınabilir.\"",
    "İsa, Tanrı sözünü, buna benzer birçok benzetmeyle halkın anlayabildiği ölçüde anlatırdı.",
    "Benzetme kullanmadan onlara hiçbir şey anlatmazdı. Ama kendi öğrencileriyle yalnız kaldığında, onlara her şeyi açıklardı.",
    "O gün akşam olunca öğrencilerine, \"Karşı yakaya geçelim\" dedi.",
    "Öğrenciler kalabalığı geride bırakarak İsa'yı, içinde bulunduğu tekneyle götürdüler. Yanında başka tekneler de vardı.",
    "Bu sırada büyük bir fırtına koptu. Dalgalar tekneye öyle bindirdi ki, tekne neredeyse suyla dolmuştu.",
    "İsa, teknenin kıç tarafında bir yastığa yaslanmış uyuyordu. Öğrenciler O'nu uyandırıp, \"Öğretmenimiz, öleceğiz! Hiç aldırmıyor musun?\" dediler.",
    "İsa kalkıp rüzgarı azarladı, göle, \"Sus, sakin ol!\" dedi. Rüzgar dindi, ortalık sütliman oldu.",
    "İsa öğrencilerine, \"Neden korkuyorsunuz? Hâlâ imanınız yok mu?\" dedi.",
    "Onlar ise büyük korku içinde birbirlerine, \"Bu adam kim ki, rüzgar da göl de O'nun sözünü dinliyor?\" dediler.",
  ],
  // Markos 5 (43 ayet)
  [
    "Gölün karşı yakasına, Gerasalılar'ın memleketine vardılar.",
    "İsa tekneden iner inmez, kötü ruha tutulmuş bir adam mezarlık mağaralardan çıkıp O'nu karşıladı.",
    "Mezarların içinde yaşayan bu adamı artık kimse zincirle bile bağlı tutamıyordu.",
    "Birçok kez zincir ve kösteklerle bağlandığı halde, zincirleri koparmış, köstekleri parçalamıştı. Hiç kimse onunla başa çıkamıyordu.",
    "Gece gündüz mezarlarda, dağlarda bağırıp duruyor, kendini taşlarla yaralıyordu.",
    "Uzaktan İsa'yı görünce koşup geldi, O'nun önünde yere kapandı.",
    "Yüksek sesle haykırarak, \"Ey İsa, yüce Tanrı'nın Oğlu, benden ne istiyorsun? Tanrı hakkı için sana yalvarırım, bana işkence etme!\" dedi.",
    "Çünkü İsa, \"Ey kötü ruh, adamın içinden çık!\" demişti.",
    "Sonra İsa adama, \"Adın ne?\" diye sordu. \"Adım Tümen. Çünkü sayımız çok\" dedi.",
    "Ruhları o bölgeden çıkarmaması için İsa'ya yalvarıp yakardı.",
    "Orada, dağın yamacında otlayan büyük bir domuz sürüsü vardı.",
    "Kötü ruhlar İsa'ya, \"Bizi şu domuzlara gönder, onlara girelim\" diye yalvardılar.",
    "İsa'nın izin vermesi üzerine kötü ruhlar adamdan çıkıp domuzların içine girdiler. Yaklaşık iki bin domuzdan oluşan sürü, dik yamaçtan aşağı koşuşarak göle atlayıp boğuldu.",
    "Domuzları güdenler kaçıp kentte ve köylerde olayın haberini yaydılar. Halk olup biteni görmeye çıktı.",
    "İsa'nın yanına geldiklerinde, önceleri bir tümen cine tutulan adamı giyinmiş, aklı başına gelmiş, oturmuş görünce korktular.",
    "Olayı görenler, cinli adama olanları ve domuzların başına gelenleri halka anlattılar.",
    "Bunun üzerine halk, bölgelerinden ayrılması için İsa'ya yalvarmaya başladı.",
    "İsa tekneye binerken, önceleri cinli olan adam O'na, \"Seninle geleyim\" diye yalvardı.",
    "Ama İsa adama izin vermedi. Ona, \"Evine, yakınlarının yanına dön\" dedi. \"Rab'bin senin için neler yaptığını, sana nasıl merhamet ettiğini onlara anlat.\"",
    "Adam da gitti, İsa'nın kendisi için neler yaptığını Dekapolis'te duyurmaya başladı. Anlattıklarına herkes şaşıp kalıyordu.",
    "İsa tekneyle karşı yakaya dönünce, çevresinde büyük bir kalabalık toplandı. Kendisi gölün kıyısında duruyordu.",
    "Bu sırada havra yöneticilerinden Yair adında biri geldi. İsa'yı görünce ayaklarına kapandı, \"Küçük kızım can çekişiyor. Gelip ellerini onun üzerine koy da kurtulsun, yaşasın!\" diye yalvardı.",
    "İsa adamla birlikte gitti. Büyük bir kalabalık da ardından gidiyor, O'nu sıkıştırıyordu.",
    "Orada, on iki yıldır kanaması olan bir kadın vardı.",
    "Birçok hekimin elinden çok çekmiş, varını yoğunu harcamış, ama iyileşeceğine daha da kötüleşmişti.",
    "Kadın, İsa hakkında anlatılanları duymuştu. Bu nedenle, kalabalıkta O'nun arkasından gelip giysisine dokundu.",
    "İçinden, \"Giysilerine bile dokunsam kurtulurum\" diyordu.",
    "O anda kanaması kesiliverdi. Kadın, bedeninin derinliğinde acıdan kurtulduğunu hissetti.",
    "İsa ise, kendisinden bir gücün akıp gittiğini hemen anladı. Kalabalığın ortasında dönüp, \"Giysilerime kim dokundu?\" diye sordu.",
    "Öğrencileri O'na, \"Seni sıkıştıran kalabalığı görüyorsun! Nasıl oluyor da, 'Bana kim dokundu' diye soruyorsun?\" dediler.",
    "İsa kendisine dokunanı görmek için çevresine bakındı.",
    "Kadın da kendisindeki değişikliği biliyordu. Korkuyla titreyerek geldi, İsa'nın ayaklarına kapandı ve O'na bütün gerçeği anlattı.",
    "İsa ona, \"Kızım\" dedi, \"İmanın seni kurtardı. Esenlikle git. Acıların son bulsun.\"",
    "İsa daha konuşurken, havra yöneticisinin evinden adamlar geldi. Yöneticiye, \"Kızın öldü\" dediler. \"Öğretmeni neden hâlâ rahatsız ediyorsun?\"",
    "İsa bu sözlere aldırmadan havra yöneticisine, \"Korkma, yalnız iman et!\" dedi.",
    "İsa, Petrus, Yakup ve Yakup'un kardeşi Yuhanna'dan başka hiç kimsenin kendisiyle birlikte gitmesine izin vermedi.",
    "Havra yöneticisinin evine vardıklarında İsa, acı acı ağlayıp feryat eden gürültülü bir kalabalıkla karşılaştı.",
    "İçeri girerek onlara, \"Niye gürültü edip ağlıyorsunuz?\" dedi. \"Çocuk ölmedi, uyuyor.\"",
    "Onlar ise kendisiyle alay ettiler. Ama İsa hepsini dışarı çıkardıktan sonra çocuğun annesini babasını ve kendisiyle birlikte olanları alıp çocuğun bulunduğu odaya girdi.",
    "Çocuğun elini tutarak ona, \"Talita kumi!\" dedi. Bu söz, \"Kızım, sana söylüyorum, kalk\" demektir.",
    "On iki yaşında olan kız hemen ayağa kalktı, yürümeye başladı. Oradakileri derin bir şaşkınlık aldı.",
    "İsa, \"Bunu kimse bilmesin\" diyerek onları sıkı sıkıya uyardı ve kıza yemek verilmesini buyurdu.",
  ],
  // Markos 6 (56 ayet)
  [
    "İsa oradan ayrılarak kendi memleketine gitti. Öğrencileri de ardından gittiler.",
    "Şabat Günü olunca İsa havrada öğretmeye başladı. Söylediklerini işiten birçok kişi şaşıp kaldı. \"Bu adam bunları nereden öğrendi?\" diye soruyorlardı. \"Kendisine verilen bu bilgelik nedir? Nasıl böyle mucizeler yapabiliyor?",
    "Meryem'in oğlu, Yakup, Yose, Yahuda ve Simun'un kardeşi olan marangoz değil mi bu? Kızkardeşleri burada, aramızda yaşamıyor mu?\" Ve gücenip O'nu reddettiler.",
    "İsa da onlara, \"Bir peygamber, kendi memleketinden, akraba çevresinden ve kendi evinden başka yerde hor görülmez\" dedi.",
    "Orada birkaç hastayı, üzerlerine ellerini koyarak iyileştirmekten başka hiçbir mucize yapamadı.",
    "Halkın imansızlığına şaşıyordu.",
    "On iki öğrencisini yanına çağırdı ve onları ikişer ikişer halk arasına göndermeye başladı. Onlara kötü ruhlar üzerinde yetki verdi.",
    "Yolculuk için yanlarına değnekten başka bir şey almamalarını söyledi. Ne ekmek, ne torba, ne de kuşaklarında para götüreceklerdi.",
    "Onlara çarık giymelerini söyledi. Ama, \"İki mintan giymeyin\" dedi.",
    "\"Bir yere gittiğiniz zaman, oradan ayrılıncaya dek hep aynı evde kalın\" diye devam etti.",
    "\"İnsanların sizi kabul etmedikleri, sizi dinlemedikleri bir yerden ayrılırken, onlara uyarı olsun diye ayağınızın altındaki tozu silkin!\"",
    "Böylece öğrenciler yola çıkıp insanları tövbeye çağırmaya başladılar.",
    "Birçok cin kovdular; birçok hastayı, üzerlerine yağ sürerek iyileştirdiler.",
    "Kral Hirodes de olup bitenleri duydu. Çünkü İsa'nın ünü her tarafa yayılmıştı. Bazıları, \"Bu adam, ölümden dirilen Vaftizci Yahya'dır. Olağanüstü güçlerin onda etkin olmasının nedeni budur\" diyordu.",
    "Başkaları, \"O İlyas'tır\" diyor, yine başkaları, \"Eski peygamberlerden biri gibi bir peygamberdir\" diyordu.",
    "Hirodes bunları duyunca, \"Başını kestirdiğim Yahya dirildi!\" dedi.",
    "Hirodes'in kendisi, kardeşi Filipus'un karısı Hirodiya'nın yüzünden adam gönderip Yahya'yı tutuklatmış, zindana attırıp zincire vurdurmuştu. Çünkü Hirodes bu kadınla evlenince Yahya ona, \"Kardeşinin karısıyla evlenmen Kutsal Yasa'ya aykırıdır\" demişti.",
    "Hirodiya bu yüzden Yahya'ya kin bağlamıştı; onu öldürtmek istiyor, ama başaramıyordu.",
    "Çünkü Yahya'nın doğru ve kutsal bir adam olduğunu bilen Hirodes ondan korkuyor ve onu koruyordu. Yahya'yı dinlediği zaman büyük bir şaşkınlık içinde kalıyor, yine de onu dinlemekten zevk alıyordu.",
    "Ne var ki, Hirodes'in kendi doğum gününde saray büyükleri, komutanlar ve Celile'nin ileri gelenleri için verdiği şölende beklenen fırsat doğdu.",
    "Hirodiya'nın kızı içeri girip dans etti. Bu, Hirodes'le konuklarının hoşuna gitti. Kral genç kıza, \"Dile benden, ne dilersen veririm\" dedi.",
    "Ant içerek, \"Benden ne dilersen, krallığımın yarısı da olsa, veririm\" dedi.",
    "Kız dışarı çıkıp annesine, \"Ne isteyeyim?\" diye sordu. \"Vaftizci Yahya'nın başını iste\" dedi annesi.",
    "Kız hemen koşup kralın yanına girdi, \"Vaftizci Yahya'nın başını bir tepsi üzerinde hemen bana vermeni istiyorum\" diyerek dileğini açıkladı.",
    "Kral buna çok üzüldüyse de, konuklarının önünde içtiği anttan ötürü kızı reddetmek istemedi.",
    "Hemen bir cellat gönderip Yahya'nın başını getirmesini buyurdu. Cellat zindana giderek Yahya'nın başını kesti.",
    "Kesik başı bir tepsi üzerinde getirip genç kıza verdi, kız da annesine götürdü.",
    "Yahya'nın öğrencileri bunu duyunca gelip cesedi aldılar ve mezara koydular.",
    "Elçiler, İsa'nın yanına dönerek yaptıkları ve öğrettikleri her şeyi O'na anlattılar.",
    "İsa onlara, \"Gelin, tek başımıza tenha bir yere gidelim de biraz dinlenin\" dedi. Gelen giden öyle çoktu ki, yemek yemeye bile vakit bulamıyorlardı.",
    "Tekneye binip tek başlarına tenha bir yere doğru yol aldılar.",
    "Gittiklerini gören birçok kişi onları tanıdı. Halk civardaki bütün kentlerden yaya olarak yola dökülüp onlardan önce oraya vardı.",
    "İsa tekneden inince büyük bir kalabalıkla karşılaştı. Çobansız koyunlara benzeyen bu insanlara acıdı ve onlara birçok konuda öğretmeye başladı.",
    "Vakit ilerlemişti. Öğrencileri İsa'ya gelip, \"Burası ıssız bir yer\" dediler, \"Vakit de ilerledi. Halkı salıver de çevredeki çiftlik ve köylere gidip kendilerine yiyecek alsınlar.\"",
    "İsa ise, \"Onlara siz yiyecek verin\" diye karşılık verdi. Öğrenciler İsa'ya, \"Gidip iki yüz dinarlık ekmek alıp onlara yedirelim mi yani?\" diye sordular.",
    "İsa onlara, \"Kaç ekmeğiniz var, gidin bakın\" dedi. Öğrenip geldiler, \"Beş ekmekle iki balığımız var\" dediler.",
    "İsa herkesi küme küme yeşil çayıra oturtmalarını buyurdu.",
    "Halk yüzer ellişer kişilik bölükler halinde oturdu.",
    "İsa beş ekmekle iki balığı aldı, gözlerini göğe kaldırarak şükretti; sonra ekmekleri böldü ve halka dağıtmaları için öğrencilerine verdi. İki balığı da hepsinin arasında paylaştırdı.",
    "Herkes yiyip doydu. Artakalan ekmek ve balıktan on iki sepet dolusu topladılar.",
    "Yemek yiyen erkeklerin sayısı beş bin kadardı.",
    "Bundan hemen sonra İsa öğrencilerine, tekneye binip kendisinden önce karşı yakada bulunan Beytsayda'ya geçmelerini buyurdu. Bu arada kendisi halkı evlerine gönderecekti.",
    "Onları uğurladıktan sonra, dua etmek için dağa çıktı.",
    "Akşam olduğunda, tekne gölün ortasına varmıştı. Yalnız başına karada kalan İsa, öğrencilerinin kürek çekmekte çok zorlandıklarını gördü. Çünkü rüzgar onlara karşı esiyordu. Sabaha karşı İsa, gölün üstünde yürüyerek onlara yaklaştı. Yanlarından geçip gidecekti.",
    "Onlar ise, gölün üstünde yürüdüğünü görünce O'nu hayalet sanarak bağrıştılar.",
    "Hepsi O'nu görmüş ve dehşete kapılmıştı. İsa hemen onlara seslenerek, \"Cesur olun, benim, korkmayın!\" dedi.",
    "Tekneye binip onlara katılınca rüzgar dindi. Onlarsa büyük bir şaşkınlık içindeydi.",
    "Ekmekle ilgili mucizeyi bile anlamamışlardı; zihinleri körelmişti.",
    "İsa'yla öğrencileri gölü aştılar, Ginnesar'da karaya çıkıp tekneyi bağladılar.",
    "Onlar tekneden inince, halk İsa'yı hemen tanıdı.",
    "Bazıları koşarak bütün yöreyi dolaştı. İsa'nın bulunduğu yeri öğrenenler, hastaları şilteleriyle oraya götürmeye başladılar.",
    "Köy olsun, kent ya da çiftlik olsun, İsa'nın gittiği her yerde, hastaları meydanlara yatırıyor, sadece giysisinin eteğine dokunmalarına izin vermesi için yalvarıyorlardı. Dokunanların hepsi de iyileşti.",
  ],
  // Markos 7 (37 ayet)
  [
    "Yeruşalim'den gelen Ferisiler ve bazı din bilginleri, İsa'nın çevresinde toplandılar.",
    "O'nun öğrencilerinden bazılarının murdar, yani yıkanmamış ellerle yemek yediklerini gördüler.",
    "Ferisiler, hatta bütün Yahudiler, atalarının töresi uyarınca ellerini iyice yıkamadan yemek yemezler.",
    "Çarşıdan dönünce de, yıkanmadan yemek yemezler. Ayrıca kâse, testi ve bakır kapların yıkanmasıyla ilgili başka birçok töreye de uyarlar.",
    "Ferisiler ve din bilginleri İsa'ya, \"Öğrencilerin neden atalarımızın töresine uymuyorlar, niçin murdar ellerle yemek yiyorlar?\" diye sordular.",
    "İsa onları şöyle yanıtladı: \"Yeşaya'nın siz ikiyüzlülerle ilgili peygamberlik sözü ne kadar yerindedir! Yazmış olduğu gibi, 'Bu halk, dudaklarıyla beni sayar, Ama yürekleri benden uzak.",
    "Bana boşuna taparlar. Çünkü öğrettikleri, sadece insan buyruklarıdır.'",
    "Siz Tanrı buyruğunu bir yana bırakmış, insan töresine uyuyorsunuz.\"",
    "İsa onlara ayrıca şunu söyledi: \"Kendi törenizi sürdürmek için Tanrı buyruğunu bir kenara itmeyi ne de güzel beceriyorsunuz!",
    "Musa, 'Annene babana saygı göstereceksin' ve, 'Annesine ya da babasına söven kesinlikle öldürülecektir' diye buyurmuştu.",
    "Ama siz, 'Eğer bir adam annesine ya da babasına, benden alacağın bütün yardım kurbandır, yani Tanrı'ya adanmıştır derse, artık annesi ya da babası için bir şey yapmasına izin yok' diyorsunuz.",
    "Böylece kuşaktan kuşağa aktardığınız törelerle Tanrı'nın sözünü geçersiz kılıyorsunuz. Buna benzer daha birçok şey yapıyorsunuz.\"",
    "İsa, halkı yine yanına çağırıp onlara, \"Hepiniz beni dinleyin ve şunu belleyin\" dedi.",
    "\"İnsanın dışında olup içine giren hiçbir şey onu kirletemez. İnsanı kirleten, insanın içinden çıkandır.\"",
    "İsa kalabalığı bırakıp eve girince, öğrencileri O'na bu benzetmenin anlamını sordular.",
    "O da onlara, \"Demek siz de anlamıyorsunuz, öyle mi?\" dedi. \"Dışarıdan insanın içine giren hiçbir şeyin onu kirletemeyeceğini bilmiyor musunuz?",
    "Dıştan giren, insanın yüreğine değil, midesine gider, oradan da helaya atılır.\" İsa bu sözlerle, bütün yiyeceklerin temiz olduğunu bildirmiş oluyordu.",
    "İsa şöyle devam etti: \"İnsanı kirleten, insanın içinden çıkandır.",
    "Çünkü kötü düşünceler, fuhuş, hırsızlık, cinayet, zina, açgözlülük, kötülük, hile, sefahat, kıskançlık, iftira, kibir ve akılsızlık içten, insanın yüreğinden kaynaklanır.",
    "Bu kötülüklerin hepsi içten kaynaklanır ve insanı kirletir.\"",
    "İsa oradan ayrılarak Sur bölgesine gitti. Burada bir eve girdi. Kimsenin bunu bilmesini istemiyordu, ama gizlenemedi.",
    "Küçük kızı kötü ruha tutulmuş bir kadın, İsa'yla ilgili haberi duyar duymaz geldi, ayaklarına kapandı.",
    "Yahudi olmayan bu kadın Suriye-Fenike ırkındandı. Kızından cini kovması için İsa'ya rica etti.",
    "İsa ona, \"Bırak, önce çocuklar doysunlar\" dedi. \"Çocukların ekmeğini alıp köpeklere atmak doğru değildir.\"",
    "Kadın buna karşılık, \"Haklısın, Rab\" dedi. \"Ama köpekler de sofranın altında çocukların ekmek kırıntılarını yer.\"",
    "İsa ona, \"Bu sözden ötürü cin kızından çıktı, gidebilirsin\" dedi.",
    "Kadın evine gittiğinde çocuğunu cinden kurtulmuş, yatakta yatar buldu.",
    "Sur bölgesinden ayrılan İsa, Sayda yoluyla Dekapolis bölgesinin ortasından geçerek tekrar Celile Gölü'ne geldi.",
    "Ona sağır ve dili tutuk bir adam getirdiler, elini üzerine koyması için yalvardılar.",
    "İsa adamı kalabalıktan ayırıp bir yana çekti. Parmaklarını adamın kulaklarına soktu, tükürüp onun diline dokundu.",
    "Sonra göğe bakarak içini çekti ve adama, \"Effata\", yani \"Açıl!\" dedi.",
    "Adamın kulakları hemen açıldı, dili çözüldü ve düzgün bir şekilde konuşmaya başladı.",
    "İsa orada bulunanları, bunu kimseye söylememeleri için uyardı. Ama onları ne kadar uyardıysa, onlar da haberi o kadar yaydılar.",
    "Halk büyük bir hayret içinde kalmıştı. \"Yaptığı her şey iyi. Sağırların kulaklarını açıyor, dilsizleri konuşturuyor!\" diyorlardı.",
  ],
  // Markos 8 (38 ayet)
  [
    "O günlerde yine büyük bir kalabalık toplanmıştı. Yiyecek bir şeyleri olmadığı için İsa öğrencilerini yanına çağırıp, \"Halka acıyorum\" dedi. \"Üç gündür yanımdalar, yiyecek hiçbir şeyleri yok.",
    "Onları aç aç evlerine gönderirsem, yolda bayılırlar. Hem bazıları uzak yoldan geliyor.\"",
    "Öğrencileri buna karşılık, \"Böyle ıssız bir yerde bu kadar kişiyi doyuracak ekmeği insan nereden bulabilir?\" dediler.",
    "İsa, \"Kaç ekmeğiniz var?\" diye sordu. \"Yedi tane\" dediler.",
    "Bunun üzerine İsa, halka yere oturmalarını buyurdu. Sonra yedi ekmeği aldı, şükredip bunları böldü, dağıtmaları için öğrencilerine verdi. Onlar da halka dağıttılar.",
    "Birkaç küçük balıkları da vardı. İsa şükredip bunları da dağıtmalarını söyledi.",
    "Herkes yiyip doydu. Artakalan parçalardan yedi küfe dolusu topladılar.",
    "Orada yaklaşık dört bin kişi vardı. İsa onları evlerine gönderdikten sonra öğrencileriyle birlikte hemen tekneye binip Dalmanuta bölgesine geçti.",
    "Ferisiler gelip İsa'yla tartışmaya başladılar. O'nu denemek amacıyla gökten bir belirti göstermesini istediler.",
    "İsa içten bir ah çekerek, \"Bu kuşak neden bir belirti istiyor?\" dedi. \"Size doğrusunu söyleyeyim, bu kuşağa hiçbir belirti gösterilmeyecek.\"",
    "Sonra onları orada bırakıp yine tekneye bindi ve karşı yakaya yöneldi.",
    "Öğrenciler ekmek almayı unutmuşlardı. Teknede, yanlarında yalnız bir ekmek vardı.",
    "İsa onlara şu uyarıda bulundu: \"Dikkatli olun, Ferisiler'in mayasından ve Hirodes'in mayasından sakının!\"",
    "Onlar ise kendi aralarında, \"Ekmeğimiz olmadığı için böyle diyor\" şeklinde tartıştılar.",
    "Bunun farkında olan İsa, \"Ekmeğiniz yok diye niçin tartışıyorsunuz?\" dedi. \"Hâlâ akıl erdiremiyor, anlamıyor musunuz? Zihniniz köreldi mi?",
    "Gözleriniz olduğu halde görmüyor musunuz? Kulaklarınız olduğu halde işitmiyor musunuz? Hatırlamıyor musunuz, beş ekmeği beş bin kişiye bölüştürdüğümde kaç sepet dolusu yemek fazlası topladınız?\" \"On iki\" dediler.",
    "\"Yedi ekmeği dört bin kişiye bölüştürdüğümde kaç küfe dolusu yemek fazlası topladınız?\" \"Yedi\" dediler.",
    "İsa onlara, \"Hâlâ anlamıyor musunuz?\" dedi.",
    "İsa ile öğrencileri Beytsayda'ya geldiler. Orada bazı kişiler İsa'ya kör bir adam getirip ona dokunması için yalvardılar.",
    "İsa körün elinden tutarak onu köyün dışına çıkardı. Gözlerine tükürüp ellerini üzerine koydu ve, \"Bir şey görüyor musun?\" diye sordu.",
    "Adam başını kaldırıp, \"İnsanlar görüyorum\" dedi, \"Ağaçlara benziyorlar, ama yürüyorlar.\"",
    "Sonra İsa ellerini yeniden adamın gözleri üzerine koydu. Adam gözlerini açtı, baktı; iyileşmiş ve her şeyi açık seçik görmeye başlamıştı.",
    "İsa, \"Köye bile girme!\" diyerek onu evine gönderdi.",
    "İsa, öğrencileriyle birlikte Filipus Sezariyesi'ne bağlı köylere gitti. Yolda öğrencilerine, \"Halk benim kim olduğumu söylüyor?\" diye sordu.",
    "Öğrencileri O'na şu karşılığı verdiler: \"Vaftizci Yahya diyorlar. Ama kimi İlyas, kimi de peygamberlerden biri olduğunu söylüyor.\"",
    "O da onlara, \"Siz ne dersiniz, sizce ben kimim?\" diye sordu. Petrus, \"Sen Mesih'sin\" yanıtını verdi.",
    "Bunun üzerine İsa bu konuda kimseye bir şey söylememeleri için onları uyardı.",
    "İsa, İnsanoğlu'nun çok acı çekmesi, ileri gelenler, başkâhinler ve din bilginlerince reddedilmesi, öldürülmesi ve üç gün sonra dirilmesi gerektiğini onlara anlatmaya başladı.",
    "Bunları açıkça söylüyordu. Bunun üzerine Petrus O'nu bir kenara çekip azarlamaya başladı.",
    "İsa dönüp öteki öğrencilerine baktı; Petrus'u azarlayarak, \"Çekil önümden, Şeytan!\" dedi. \"Düşüncelerin Tanrı'ya değil, insana özgüdür.\"",
    "Öğrencileriyle birlikte halkı da yanına çağırıp şöyle konuştu: \"Ardımdan gelmek isteyen kendini inkâr etsin, çarmıhını yüklenip beni izlesin.",
    "Canını kurtarmak isteyen onu yitirecek, canını benim ve Müjde'nin uğruna yitiren ise onu kurtaracaktır.",
    "İnsan bütün dünyayı kazanıp da canından olursa, bunun kendisine ne yararı olur?",
    "İnsan kendi canına karşılık ne verebilir?",
    "Bu vefasız ve günahkâr kuşağın ortasında, kim benden ve benim sözlerimden utanırsa, İnsanoğlu da, Babası'nın görkemi içinde kutsal meleklerle birlikte geldiğinde o kişiden utanacaktır.\"",
  ],
  // Markos 9 (50 ayet)
  [
    "İsa, \"Size doğrusunu söyleyeyim\" diye devam etti, \"Burada bulunanlar arasında, Tanrı Egemenliği'nin güçlü biçimde gerçekleştiğini görmeden ölümü tatmayacak olanlar var.\"",
    "Altı gün sonra İsa, yanına yalnız Petrus, Yakup ve Yuhanna'yı alarak yüksek bir dağa çıktı. Onların gözü önünde İsa'nın görünümü değişti.",
    "Giysileri göz kamaştırıcı bir beyazlığa büründü; yeryüzünde hiçbir çamaşırcının erişemeyeceği bir beyazlıktı bu.",
    "O anda Musa'yla İlyas öğrencilere göründü. İsa'yla konuşuyorlardı.",
    "Petrus İsa'ya, \"Rabbî, burada bulunmamız ne iyi oldu! Üç çardak kuralım: Biri sana, biri Musa'ya, biri de İlyas'a\" dedi.",
    "Ne söyleyeceğini bilmiyordu. Çünkü çok korkmuşlardı.",
    "Bu sırada bir bulut gelip onlara gölge saldı. Buluttan gelen bir ses, \"Sevgili Oğlum budur, O'nu dinleyin!\" dedi.",
    "Öğrenciler birden çevrelerine baktılar, ama bu kez yanlarında İsa'dan başka kimseyi göremediler.",
    "Dağdan inerlerken İsa, İnsanoğlu ölümden dirilmeden orada gördüklerini hiç kimseye söylememeleri için onları uyardı.",
    "Bu uyarıya uymakla birlikte kendi aralarında, \"Ölümden dirilmek ne demek?\" diye tartışıp durdular.",
    "İsa'ya, \"Din bilginleri neden önce İlyas'ın gelmesi gerektiğini söylüyorlar?\" diye sordular.",
    "O da onlara şöyle dedi: \"Gerçekten de önce İlyas gelir ve her şeyi yeniden düzene koyar. Ama nasıl oluyor da İnsanoğlu'nun çok acı çekeceği ve hiçe sayılacağı yazılmıştır?",
    "Size şunu söyleyeyim, İlyas geldi bile, onun hakkında yazılmış olduğu gibi, ona yapmadıklarını bırakmadılar.\"",
    "Öteki öğrencilerin yanına döndüklerinde, onların çevresinde büyük bir kalabalığın toplandığını, birtakım din bilginlerinin onlarla tartıştığını gördüler.",
    "Kalabalık İsa'yı görünce büyük bir şaşkınlığa kapıldı ve koşup O'nu selamladı.",
    "İsa öğrencilerine, \"Onlarla ne tartışıyorsunuz?\" diye sordu.",
    "Halktan biri O'na, \"Öğretmenim\" diye karşılık verdi, \"Dilsiz bir ruha tutulan oğlumu sana getirdim.",
    "Ruh onu nerede yakalarsa yere çarpıyor. Çocuk ağzından köpükler saçıyor, dişlerini gıcırdatıyor ve kaskatı kesiliyor. Ruhu kovmaları için öğrencilerine başvurdum, ama başaramadılar.\"",
    "İsa onlara, \"Ey imansız kuşak!\" dedi. \"Sizinle daha ne kadar kalacağım? Size daha ne kadar katlanacağım? Çocuğu bana getirin!\"",
    "Çocuğu kendisine getirdiler. Ruh, İsa'yı görür görmez çocuğu şiddetle sarstı; çocuk yere düştü, ağzından köpükler saçarak yuvarlanmaya başladı.",
    "İsa çocuğun babasına, \"Bu hal çocuğun başına geleli ne kadar oldu?\" diye sordu. \"Küçüklüğünden beri böyle\" dedi babası.",
    "\"Üstelik ruh onu öldürmek için sık sık ateşe, suya attı. Elinden bir şey gelirse, bize yardım et, halimize acı!\"",
    "İsa ona, \"Elimden gelirse mi? İman eden biri için her şey mümkün!\" dedi.",
    "Çocuğun babası hemen, \"İman ediyorum, imansızlığımı yenmeme yardım et!\" diye feryat etti.",
    "İsa, halkın koşuşup geldiğini görünce kötü ruhu azarlayarak, \"Sana buyuruyorum, dilsiz ve sağır ruh, çocuğun içinden çık ve ona bir daha girme!\" dedi.",
    "Bunun üzerine ruh bir çığlık attı ve çocuğu şiddetle sarsarak çıktı. Çocuk ölü gibi hareketsiz kaldı, öyle ki oradakilerin birçoğu, \"Öldü!\" diyordu.",
    "Ama İsa elinden tutup kaldırınca, çocuk ayağa kalktı.",
    "İsa eve girdikten sonra öğrencileri özel olarak O'na, \"Biz kötü ruhu neden kovamadık?\" diye sordular.",
    "İsa onlara, \"Bu tür ruhlar ancak duayla kovulabilir\" yanıtını verdi.",
    "Oradan ayrılmış, Celile bölgesinden geçiyorlardı. İsa hiç kimsenin bunu bilmesini istemiyordu.",
    "Öğrencilerine öğretirken şöyle diyordu: \"İnsanoğlu, insanların eline teslim edilecek ve öldürülecek, ama öldürüldükten üç gün sonra dirilecek.\"",
    "Onlar bu sözleri anlamıyor, İsa'ya soru sormaktan da korkuyorlardı.",
    "Kefarnahum'a vardılar. Eve girdikten sonra İsa onlara, \"Yolda neyi tartışıyordunuz?\" diye sordu.",
    "Hiç birinden ses çıkmadı. Çünkü yolda aralarında kimin en büyük olduğunu tartışmışlardı.",
    "İsa oturup Onikiler'i yanına çağırdı. Onlara şöyle dedi: \"Birinci olmak isteyen en sonuncu olsun, herkesin hizmetkârı olsun.\"",
    "Küçük bir çocuğu alıp orta yere dikti, sonra onu kucağına alarak onlara şöyle dedi: \"Böyle bir çocuğu benim adım uğruna kabul eden, beni kabul etmiş olur. Beni kabul eden de beni değil, beni göndereni kabul etmiş olur.\"",
    "Yuhanna O'na, \"Öğretmenim\" dedi, \"Senin adınla cin kovan birini gördük, ama bizi izleyenlerden olmadığı için ona engel olmaya çalıştık.\"",
    "\"Ona engel olmayın!\" dedi İsa. \"Çünkü benim adımla mucize yapıp da ardından beni kötüleyecek kimse yoktur.",
    "Bize karşı olmayan, bizden yanadır.",
    "Size doğrusunu söyleyeyim, Mesih'e ait olduğunuz için sizlere bir bardak su veren ödülsüz kalmayacaktır.\"",
    "\"Kim bana iman eden bu küçüklerden birini günaha düşürürse, boynuna kocaman bir değirmen taşı geçirilip denize atılması kendisi için daha iyi olur.",
    "Eğer elin günah işlemene neden olursa, onu kes. Tek elle yaşama kavuşman, iki elle sönmez ateşe, cehenneme gitmenden iyidir.",
    "Eğer ayağın günah işlemene neden olursa, onu kes. Tek ayakla yaşama kavuşman, iki ayakla cehenneme atılmandan iyidir.",
    "Eğer gözün günah işlemene neden olursa, onu çıkar at. Tanrı'nın Egemenliği'ne tek gözle girmen, iki gözle cehenneme atılmandan iyidir.",
    "'Oradakileri kemiren kurt ölmez, Yakan ateş sönmez.'",
    "Çünkü herkes ateşle tuzlanacaktır.",
    "Tuz yararlıdır. Ama tuz tuzluluğunu yitirirse, bir daha ona nasıl tat verebilirsiniz? İçinizde tuz olsun ve birbirinizle barış içinde yaşayın!\"",
  ],
  // Markos 10 (52 ayet)
  [
    "İsa oradan ayrılıp Yahudiye'nin Şeria Irmağı'nın karşı yakasındaki topraklarına geçti. Çevresinde yine kalabalıklar toplanmıştı; her zamanki gibi onlara öğretiyordu.",
    "Yanına gelen bazı Ferisiler O'nu denemek amacıyla, \"Bir erkeğin, karısını boşaması Kutsal Yasa'ya uygun mudur?\" diye sordular.",
    "İsa karşılık olarak, \"Musa size ne buyurdu?\" dedi.",
    "Onlar, \"Musa, erkeğin bir boşanma belgesi yazarak karısını boşamasına izin vermiştir\" dediler.",
    "İsa onlara, \"İnatçı olduğunuz için Musa bu buyruğu yazdı\" dedi.",
    "\"Tanrı, yaratılışın başlangıcından 'İnsanları erkek ve dişi olarak yarattı.'",
    "'Bu nedenle adam annesini babasını bırakıp karısına bağlanacak, ikisi tek beden olacak.' Şöyle ki, onlar artık iki değil, tek bedendir.",
    "O halde Tanrı'nın birleştirdiğini insan ayırmasın.\"",
    "Öğrencileri evde O'na yine bu konuyla ilgili bazı sorular sordular.",
    "İsa onlara, \"Karısını boşayıp başkasıyla evlenen, karısına karşı zina etmiş olur\" dedi.",
    "\"Kocasını boşayıp başkasıyla evlenen kadın da zina etmiş olur.\"",
    "Bu arada bazıları küçük çocukları İsa'nın yanına getiriyor, onlara dokunmasını istiyorlardı. Ne var ki, öğrenciler onları azarladılar.",
    "İsa bunu görünce kızdı. Öğrencilerine, \"Bırakın, çocuklar bana gelsin\" dedi. \"Onlara engel olmayın! Çünkü Tanrı'nın Egemenliği böylelerinindir.",
    "Size doğrusunu söyleyeyim, Tanrı'nın Egemenliği'ni bir çocuk gibi kabul etmeyen, bu egemenliğe asla giremez.\"",
    "Çocukları kucağına aldı, ellerini üzerlerine koyup onları kutsadı.",
    "İsa yola çıkarken, biri koşarak yanına geldi. Önünde diz çöküp O'na, \"İyi öğretmenim, sonsuz yaşama kavuşmak için ne yapmalıyım?\" diye sordu.",
    "İsa, \"Bana neden iyi diyorsun?\" dedi. \"İyi olan yalnız biri var, O da Tanrı'dır.",
    "O'nun buyruklarını biliyorsun: 'Adam öldürmeyeceksin, zina etmeyeceksin, çalmayacaksın, yalan yere tanıklık etmeyeceksin, kimsenin hakkını yemeyeceksin, annene babana saygı göstereceksin.'\"",
    "Adam, \"Öğretmenim, bunların hepsini gençliğimden beri yerine getiriyorum\" dedi.",
    "Ona sevgiyle bakan İsa, \"Bir eksiğin var\" dedi. \"Git neyin varsa sat, parasını yoksullara ver; böylece gökte hazinen olur. Sonra gel, beni izle.\"",
    "Bu sözler üzerine adamın yüzü asıldı, üzüntü içinde oradan uzaklaştı. Çünkü çok malı vardı.",
    "İsa çevresine göz gezdirdikten sonra öğrencilerine, \"Varlıklı kişilerin Tanrı Egemenliği'ne girmesi ne güç olacak!\" dedi.",
    "Öğrenciler O'nun sözlerine şaştılar. Ama İsa onlara yine, \"Çocuklar\" dedi, \"Tanrı'nın Egemenliği'ne girmek ne güçtür!",
    "Devenin iğne deliğinden geçmesi, zenginin Tanrı Egemenliği'ne girmesinden daha kolaydır.\"",
    "Öğrenciler büsbütün şaşırmışlardı. Birbirlerine, \"Öyleyse kim kurtulabilir?\" diyorlardı.",
    "İsa onlara bakarak, \"İnsanlar için bu imkânsız, ama Tanrı için değil. Tanrı için her şey mümkündür\" dedi.",
    "Petrus O'na, \"Bak, biz her şeyi bırakıp senin ardından geldik\" demeye başladı.",
    "\"Size doğrusunu söyleyeyim\" dedi İsa, \"Benim ve Müjde'nin uğruna evini, kardeşlerini, anne ya da babasını, çocuklarını ya da topraklarını bırakıp da şimdi, bu çağda çekeceği zulümlerle birlikte yüz kat daha fazla eve, kardeşe, anneye, çocuğa, toprağa ve gelecek çağda sonsuz yaşama kavuşmayacak hiç kimse yoktur.",
    "Ne var ki, birincilerin birçoğu sonuncu, sonuncuların birçoğu da birinci olacak.\"",
    "Yola çıkmış Yeruşalim'e gidiyorlardı. İsa önlerinde yürüyordu. Öğrencileri şaşkınlık içindeydi, ardından gelenler ise korkuyorlardı. İsa Onikiler'i yine bir yana çekip kendi başına gelecekleri anlatmaya başladı: \"Şimdi Yeruşalim'e gidiyoruz\" dedi. \"İnsanoğlu, başkâhinlerin ve din bilginlerinin eline teslim edilecek. Onlar da O'nu ölüm cezasına çarptıracak ve öteki uluslara teslim edecekler.",
    "O'nunla alay edecek, üzerine tükürecek ve O'nu kamçılayıp öldürecekler. Ne var ki O, üç gün sonra dirilecek.\"",
    "Zebedi'nin oğulları Yakup ile Yuhanna İsa'ya yaklaşıp, \"Öğretmenimiz, bir dileğimiz var, bunu yapmanı istiyoruz\" dediler.",
    "İsa onlara, \"Sizin için ne yapmamı istiyorsunuz?\" diye sordu.",
    "\"Sen yüceliğine kavuşunca birimize sağında, ötekimize de solunda oturma ayrıcalığını ver\" dediler.",
    "\"Siz ne dilediğiniz bilmiyorsunuz\" dedi İsa. \"Benim içeceğim kâseden siz içebilir misiniz? Benim vaftiz olacağım gibi siz de vaftiz olabilir misiniz?\"",
    "\"Evet, olabiliriz\" dediler. İsa onlara, \"Benim içeceğim kâseden siz de içeceksiniz, benim vaftiz olacağım gibi siz de vaftiz olacaksınız\" dedi. \"Ama sağımda ya da solumda oturmanıza izin vermek benim elimde değil. Bu yerler belirli kişiler için hazırlanmıştır.\"",
    "Bunu işiten on öğrenci Yakup'la Yuhanna'ya kızmaya başladılar.",
    "İsa onları yanına çağırıp şöyle dedi: \"Bilirsiniz ki, ulusların önderleri sayılanlar, onlara egemen kesilir, ileri gelenleri de onlara ağırlıklarını hissettirirler.",
    "Sizin aranızda böyle olmayacak. Aranızda büyük olmak isteyen, ötekilerin hizmetkârı olsun.",
    "Aranızda birinci olmak isteyen, hepinizin kulu olsun.",
    "Çünkü İnsanoğlu bile hizmet edilmeye değil, hizmet etmeye ve canını birçokları için fidye olarak vermeye geldi.\"",
    "Sonra Eriha'ya geldiler. İsa, öğrencileri ve büyük bir kalabalıkla birlikte Eriha'dan ayrılırken, Timay oğlu Bartimay adında kör bir dilenci yol kenarında oturuyordu.",
    "Nasıralı İsa'nın orada olduğunu duyunca, \"Ey Davut Oğlu İsa, halime acı!\" diye bağırmaya başladı.",
    "Birçok kimse onu azarlayarak susturmak istediyse de o, \"Ey Davut Oğlu, halime acı!\" diyerek daha çok bağırdı.",
    "İsa durdu, \"Çağırın onu\" dedi. Kör adama seslenerek, \"Ne mutlu sana! Kalk, seni çağırıyor!\" dediler.",
    "Adam abasını üstünden atarak ayağa fırladı ve İsa'nın yanına geldi.",
    "İsa, \"Senin için ne yapmamı istiyorsun?\" diye sordu. Kör adam, \"Rabbuni, gözlerim görsün\" dedi.",
    "İsa, \"Gidebilirsin, imanın seni kurtardı\" dedi. Adam o anda yeniden görmeye başladı ve yol boyunca İsa'nın ardından gitti.",
  ],
  // Markos 11 (33 ayet)
  [
    "Yeruşalim'e yaklaşıp Zeytin Dağı'nın yamacındaki Beytfaci ile Beytanya'ya geldiklerinde İsa iki öğrencisini önden gönderdi. Onlara, \"Karşınızdaki köye gidin\" dedi, \"Köye girer girmez, üzerine daha hiç kimsenin binmediği, bağlı duran bir sıpa bulacaksınız. Onu çözüp bana getirin.",
    "\"Biri size, 'Bunu niye yapıyorsunuz?' derse, 'Rab'bin ona ihtiyacı var, hemen geri gönderecek' dersiniz.\"",
    "Gittiler ve yol üzerinde, bir evin sokak kapısının yanında bağlı buldukları sıpayı çözdüler.",
    "Orada duranlardan bazıları, \"Sıpayı ne diye çözüyorsunuz?\" dediler.",
    "Öğrenciler İsa'nın kendilerine söylediklerini tekrarlayınca, adamlar onları rahat bıraktı.",
    "Sıpayı İsa'ya getirip üzerine kendi giysilerini yaydılar. İsa sıpaya bindi.",
    "Birçokları giysilerini, bazıları da çevredeki ağaçlardan kestikleri dalları yola serdiler.",
    "Önden gidenler ve arkadan gelenler şöyle bağırıyorlardı: \"Hozana! Rab'bin adıyla gelene övgüler olsun!",
    "Atamız Davut'un yaklaşan egemenliği kutlu olsun! En yücelerde hozana!\"",
    "İsa Yeruşalim'e varınca tapınağa gitti, her tarafı gözden geçirdi. Sonra vakit ilerlemiş olduğundan Onikiler'le birlikte Beytanya'ya döndü.",
    "Ertesi gün Beytanya'dan çıktıklarında İsa acıkmıştı.",
    "Uzakta, yapraklanmış bir incir ağacı görünce belki incir bulurum diye yaklaştı. Ağacın yanına vardığında yapraktan başka bir şey bulamadı. Çünkü incir mevsimi değildi.",
    "İsa ağaca, \"Artık sonsuza dek senden kimse meyve yiyemesin!\" dedi. Öğrencileri de bunu duydular.",
    "Oradan Yeruşalim'e geldiler. İsa tapınağın avlusuna girerek oradaki alıcı ve satıcıları dışarı kovdu. Para bozanların masalarını, güvercin satanların sehpalarını devirdi.",
    "Yük taşıyan hiç kimsenin tapınağın avlusundan geçmesine izin vermedi.",
    "Halka öğretirken şunları söyledi: \"'Evime, bütün ulusların dua evi denecek' diye yazılmamış mı? Ama siz onu haydut inine çevirdiniz.\"",
    "Başkâhinler ve din bilginleri bunu duyunca İsa'yı yok etmek için bir yol aramaya başladılar. O'ndan korkuyorlardı. Çünkü bütün halk O'nun öğretisine hayrandı.",
    "Akşam olunca İsa'yla öğrencileri kentten ayrıldı.",
    "Sabah erkenden incir ağacının yanından geçerken, ağacın kökten kurumuş olduğunu gördüler.",
    "Olayı hatırlayan Petrus, \"Rabbî, bak! Lanetlediğin incir ağacı kurumuş!\" dedi.",
    "İsa onlara şöyle karşılık verdi: \"Tanrı'ya iman edin.",
    "Size doğrusunu söyleyeyim, kim şu dağa, 'Kalk, denize atıl!' der ve yüreğinde kuşku duymadan dediğinin olacağına inanırsa, dileği yerine gelecektir.",
    "Bunun için size diyorum ki, duayla dilediğiniz her şeyi daha şimdiden almış olduğunuza inanın, dileğiniz yerine gelecektir.",
    "Kalkıp dua ettiğiniz zaman, birine karşı bir şikâyetiniz varsa onu bağışlayın ki, göklerdeki Babanız da sizin suçlarınızı bağışlasın.\"",
    "Yine Yeruşalim'e geldiler. İsa tapınakta gezinirken başkâhinler, din bilginleri ve ileri gelenler O'nun yanına gelip, \"Bunları hangi yetkiyle yapıyorsun, bunları yapma yetkisini sana kim verdi?\" diye sordular.",
    "İsa da onlara, \"Size bir soru soracağım\" dedi. \"Bana yanıt verin, ben de size bunları hangi yetkiyle yaptığımı söylerim.",
    "Yahya'nın vaftiz etme yetkisi Tanrı'dan mıydı, insanlardan mı? Yanıt verin bana.\"",
    "Bunu aralarında şöyle tartışmaya başladılar: \"'Tanrı'dan' dersek, 'Öyleyse ona niçin inanmadınız?' diyecek.",
    "Yok eğer 'İnsanlardan' dersek...\" Halkın tepkisinden korkuyorlardı. Çünkü herkes Yahya'yı gerçekten peygamber sayıyordu.",
    "İsa'ya, \"Bilmiyoruz\" diye yanıt verdiler. İsa da onlara, \"Ben de size bunları hangi yetkiyle yaptığımı söylemeyeceğim\" dedi.",
  ],
  // Markos 12 (44 ayet)
  [
    "İsa onlara benzetmelerle konuşmaya başladı. \"Adamın biri bağ dikti, çevresini çitle çevirdi, üzüm sıkmak için bir çukur kazdı, bir de bekçi kulesi yaptı. Sonra bağı bağcılara kiralayıp yolculuğa çıktı.",
    "Mevsimi gelince bağın ürününden payına düşeni almak üzere bağcılara bir köle yolladı.",
    "Bağcılar köleyi yakalayıp dövdü ve eli boş gönderdi.",
    "Bağ sahibi bu kez onlara başka bir köle yolladı. Onu da başından yaralayıp aşağıladılar.",
    "Birini daha yolladı, onu öldürdüler. Daha birçok köle yolladı. Kimini dövüp kimini öldürdüler.",
    "\"Bağ sahibinin yanında tek kişi kaldı, o da sevgili oğluydu. 'Oğlumu sayarlar' diyerek bağcılara en son onu yolladı.",
    "\"Ama bağcılar birbirlerine, 'Mirasçı budur, gelin onu öldürelim, miras bizim olur' dediler.",
    "Böylece onu yakaladılar, öldürüp bağdan dışarı attılar.",
    "\"Bu durumda bağın sahibi ne yapacak? Gelip bağcıları yok edecek, bağı da başkalarına verecek.",
    "Şu Kutsal Yazı'yı okumadınız mı? 'Yapıcıların reddettiği taş, İşte köşenin baş taşı oldu. Rab'bin işidir bu, Gözümüzde harika bir iş!'\"",
    "İsa'nın bu benzetmede kendilerinden söz ettiğini anlayan Yahudi önderler O'nu tutuklamak istediler; ama halkın tepkisinden korktukları için O'nu bırakıp gittiler.",
    "Daha sonra İsa'yı söyleyeceği sözlerle tuzağa düşürmek amacıyla Ferisiler'den ve Hirodes yanlılarından bazılarını O'na gönderdiler.",
    "Bunlar gelip İsa'ya, \"Öğretmenimiz\" dediler, \"Senin dürüst biri olduğunu, kimseyi kayırmadan, insanlar arasında ayrım yapmadan Tanrı yolunu dürüstçe öğrettiğini biliyoruz. Sezar'a vergi vermek Kutsal Yasa'ya uygun mu, değil mi? Verelim mi, vermeyelim mi?\"",
    "Onların ikiyüzlülüğünü bilen İsa şöyle dedi: \"Beni neden deniyorsunuz? Bana bir dinar getirin bakayım.\"",
    "Parayı getirdiler. İsa, \"Bu resim, bu yazı kimin?\" diye sordu. \"Sezar'ın\" dediler.",
    "İsa da, \"Sezar'ın hakkını Sezar'a, Tanrı'nın hakkını Tanrı'ya verin\" dedi. İsa'nın sözlerine şaşakaldılar.",
    "Ölümden sonra diriliş olmadığını söyleyen Sadukiler İsa'ya gelip şunu sordular: \"Öğretmenimiz, Musa yazılarında bize şöyle buyurmuştur: 'Eğer bir adam ölür, geride bir dul bırakır, ama çocuk bırakmazsa, kardeşi onun karısını alıp soyunu sürdürsün.'",
    "Yedi kardeş vardı. Birincisi evlendi ve çocuk bırakmadan öldü.",
    "İkincisi aynı kadını aldı, o da çocuk sahibi olmadan öldü. Üçüncüsüne de öyle oldu.",
    "Yedisi de çocuksuz öldü. Hepsinden sonra kadın da öldü.",
    "Diriliş günü, ölümden dirildiklerinde kadın bunlardan hangisinin karısı olacak? Çünkü yedisi de onunla evlendi.\"",
    "İsa onlara şöyle karşılık verdi: \"Ne Kutsal Yazılar'ı ne de Tanrı'nın gücünü biliyorsunuz. Yanılmanızın nedeni de bu değil mi?",
    "İnsanlar ölümden dirilince ne evlenir ne evlendirilir, göklerdeki melekler gibidirler.",
    "Ölülerin dirilmesi konusuna gelince, Musa'nın Kitabı'nda, alevlenen çalıyla ilgili bölümde Tanrı'nın Musa'ya söylediklerini okumadınız mı? 'Ben İbrahim'in Tanrısı, İshak'ın Tanrısı ve Yakup'un Tanrısı'yım' diyor.",
    "Tanrı ölülerin değil, dirilerin Tanrısı'dır. Siz büyük bir yanılgı içindesiniz.\"",
    "Onların tartışmalarını dinleyen ve İsa'nın onlara güzel yanıt verdiğini gören bir din bilgini yaklaşıp O'na, \"Buyrukların en önemlisi hangisidir?\" diye sordu.",
    "İsa şöyle karşılık verdi: \"En önemlisi şudur: 'Dinle, ey İsrail! Tanrımız Rab tek Rab'dir.",
    "Tanrın Rab'bi bütün yüreğinle, bütün canınla, bütün aklınla ve bütün gücünle seveceksin.'",
    "İkincisi de şudur: 'Komşunu kendin gibi seveceksin.' Bunlardan daha büyük buyruk yoktur.\"",
    "Din bilgini İsa'ya, \"İyi söyledin, öğretmenim\" dedi. \"'Tanrı tektir ve O'ndan başkası yoktur' demekle doğruyu söyledin.",
    "İnsanın Tanrı'yı bütün yüreğiyle, bütün anlayışıyla ve bütün gücüyle sevmesi, komşusunu da kendi gibi sevmesi, bütün yakmalık sunulardan ve kurbanlardan daha önemlidir.\"",
    "İsa onun akıllıca yanıt verdiğini görünce, \"Sen Tanrı'nın Egemenliği'nden uzak değilsin\" dedi. Bundan sonra kimse O'na soru sormaya cesaret edemedi.",
    "İsa tapınakta öğretirken şunu sordu: \"Nasıl oluyor da din bilginleri, 'Mesih, Davut'un Oğlu'dur' diyorlar?",
    "Davut'un kendisi, Kutsal Ruh'tan esinlenerek şöyle demişti: 'Rab Rabbim'e dedi ki, Ben düşmanlarını Ayaklarının altına serinceye dek Sağımda otur.'",
    "Davut'un kendisi O'ndan Rab diye söz ettiğine göre, O nasıl Davut'un Oğlu olur?\" Oradaki büyük kalabalık O'nu zevkle dinliyordu.",
    "İsa öğretirken şöyle dedi: \"Uzun kaftanlar içinde dolaşmaktan, meydanlarda selamlanmaktan, havralarda en seçkin yerlere ve şölenlerde başköşelere kurulmaktan hoşlanan din bilginlerinden sakının.",
    "Dul kadınların malını mülkünü sömüren, gösteriş için uzun uzun dua eden bu kişilerin cezası daha ağır olacaktır.\"",
    "İsa tapınakta bağış toplanan yerin karşısında oturmuş, kutulara para atan halkı seyrediyordu. Birçok zengin kişi kutuya bol para attı.",
    "Yoksul bir dul kadın da geldi, birkaç kuruş değerinde iki bakır para attı.",
    "İsa öğrencilerini yanına çağırarak, \"Size doğrusunu söyleyeyim\" dedi, \"Bu yoksul dul kadın kutuya herkesten daha çok para attı.",
    "Çünkü ötekilerin hepsi, zenginliklerinden artanı attılar. Bu kadın ise yoksulluğuna karşın, varını yoğunu, geçinmek için elinde ne varsa, tümünü verdi.\"",
  ],
  // Markos 13 (37 ayet)
  [
    "İsa tapınaktan çıkarken öğrencilerinden biri O'na, \"Öğretmenim\" dedi, \"Şu güzel taşlara, şu görkemli yapılara bak!\"",
    "İsa ona, \"Bu büyük yapıları görüyor musun? Burada taş üstünde taş kalmayacak, hepsi yıkılacak!\" dedi.",
    "İsa, Zeytin Dağı'nda, tapınağın karşısında otururken Petrus, Yakup, Yuhanna ve Andreas özel olarak kendisine şunu sordular: \"Söyle bize, bu dediklerin ne zaman olacak, bütün bunların gerçekleşmek üzere olduğunu gösteren belirti ne olacak?\"",
    "İsa onlara anlatmaya başladı: \"Sakın kimse sizi saptırmasın\" dedi.",
    "\"Birçokları, 'Ben O'yum' diyerek benim adımla gelip birçok kişiyi saptıracaklar.",
    "Savaş gürültüleri, savaş haberleri duyunca korkmayın. Bunların olması gerek, ama bu daha son demek değildir.",
    "Ulus ulusa, devlet devlete savaş açacak; yer yer depremler, kıtlıklar olacak. Bunlar, doğum sancılarının başlangıcıdır.",
    "\"Ama siz kendinize dikkat edin! İnsanlar sizi mahkemelere verecek, havralarda dövecekler. Benden ötürü valilerin, kralların önüne çıkarılacak, böylece onlara tanıklık edeceksiniz.",
    "Ne var ki, önce Müjde'nin bütün uluslara duyurulması gerekir.",
    "Sizi tutuklayıp mahkemeye verdiklerinde, 'Ne söyleyeceğiz?' diye önceden kaygılanmayın. O anda size ne esinlenirse onu söyleyin. Çünkü konuşan siz değil, Kutsal Ruh olacak.",
    "Kardeş kardeşi, baba çocuğunu ölüme teslim edecek. Çocuklar anne babalarına başkaldırıp onları öldürtecek.",
    "Benim adımdan ötürü herkes sizden nefret edecek. Ama sonuna kadar dayanan kurtulacaktır.",
    "\"Yıkıcı iğrenç şeyin, bulunmaması gereken yerde dikildiğini gördüğünüz zaman -okuyan anlasın- Yahudiye'de bulunanlar dağlara kaçsın.",
    "Damda olan, evinden bir şey almak için aşağı inmesin, içeri girmesin.",
    "Tarlada olan, abasını almak için geri dönmesin.",
    "O günlerde gebe olan, çocuk emziren kadınların vay haline!",
    "Dua edin ki, kaçışınız kışa rastlamasın.",
    "Çünkü o günlerde öyle bir sıkıntı olacak ki, Tanrı'nın var ettiği yaratılışın başlangıcından bu yana böylesi olmamış, bundan sonra da olmayacaktır.",
    "Rab o günleri kısaltmamış olsaydı, hiç kimse kurtulamazdı. Ama Rab, seçilmiş olanlar, kendi seçtiği kişiler uğruna o günleri kısaltmıştır.",
    "Eğer o zaman biri size, 'İşte Mesih burada', ya da, 'İşte şurada' derse, inanmayın.",
    "Çünkü sahte mesihler, sahte peygamberler türeyecek; bunlar, belirtiler ve harikalar yapacaklar. Öyle ki, ellerinden gelse seçilmiş olanları saptıracaklar.",
    "Ama siz dikkatli olun. İşte size her şeyi önceden söylüyorum.\"",
    "\"Ama o günlerde, o sıkıntıdan sonra, 'Güneş kararacak, Ay ışık vermez olacak, Yıldızlar gökten düşecek, Göksel güçler sarsılacak.'",
    "\"O zaman İnsanoğlu'nun bulutlar içinde büyük güç ve görkemle geldiğini görecekler.",
    "İnsanoğlu o zaman meleklerini gönderecek, seçtiklerini yeryüzünün bir ucundan göğün öbür ucuna dek, dünyanın dört bucağından toplayacak.",
    "\"İncir ağacından ders alın. Dalları filizlenip yaprakları sürünce, yaz mevsiminin yakın olduğunu anlarsınız.",
    "Aynı şekilde, bu olayların gerçekleştiğini gördüğünüzde bilin ki İnsanoğlu yakındır, kapıdadır.",
    "Size doğrusunu söyleyeyim, bütün bunlar olmadan bu kuşak ortadan kalkmayacak.",
    "Yer ve gök ortadan kalkacak, ama benim sözlerim asla ortadan kalkmayacaktır.\"",
    "\"O günü ve o saati, ne gökteki melekler, ne de Oğul bilir; Baba'dan başka kimse bilmez.",
    "Dikkat edin, uyanık kalın, dua edin. Çünkü o anın ne zaman geleceğini bilemezsiniz.",
    "Bu, yolculuğa çıkan bir adamın durumuna benzer. Evinden ayrılırken kölelerine yetki ve görev verir, kapıdaki nöbetçiye de uyanık kalmasını buyurur.",
    "Siz de uyanık kalın. Çünkü ev sahibi ne zaman gelecek, akşam mı, gece yarısı mı, horoz öttüğünde mi, sabaha doğru mu, bilemezsiniz.",
    "Ansızın gelip sizi uykuda bulmasın!",
    "Size söylediklerimi herkese söylüyorum; uyanık kalın!\"",
  ],
  // Markos 14 (72 ayet) - kısaltılmış bloklar
  [
    "Fısıh ve Mayasız Ekmek Bayramı'na iki gün kalmıştı. Başkâhinlerle din bilginleri İsa'yı hileyle tutuklayıp öldürmenin bir yolunu arıyorlardı.",
    "\"Bayramda olmasın, yoksa halk arasında kargaşalık çıkar\" diyorlardı.",
    "İsa Beytanya'da cüzamlı Simun'un evinde sofrada otururken yanına bir kadın geldi. Kadın kaymaktaşından bir kap içinde çok değerli, saf hintsümbülü yağı getirmişti. Kabı kırarak yağı O'nun başına döktü.",
    "Bazıları buna kızdılar; birbirlerine, \"Bu yağ niçin böyle boş yere harcandı? Üç yüz dinardan fazlaya satılabilir, parası yoksullara verilebilirdi\" diyerek kadını azarlamaya başladılar.",
    "\"Kadını rahat bırakın\" dedi İsa. \"Neden üzüyorsunuz onu? Benim için güzel bir şey yaptı.",
    "Yoksullar her zaman aranızdadır, dilediğiniz anda onlara yardım edebilirsiniz; ama ben her zaman aranızda olmayacağım.",
    "Kadın elinden geleni yaptı, beni gömülmeye hazırlamak üzere daha şimdiden bedenimi yağladı.",
    "Size doğrusunu söyleyeyim, Müjde dünyanın neresinde duyurulursa, bu kadının yaptığı da onun anılması için anlatılacak.\"",
    "Bu arada Onikiler'den biri olan Yahuda İskariot, İsa'yı ele vermek amacıyla başkâhinlerin yanına gitti.",
    "Onlar bunu işitince sevindiler, Yahuda'ya para vermeyi vaat ettiler. O da İsa'yı ele vermek için fırsat kollamaya başladı.",
    "Fısıh kurbanının kesildiği Mayasız Ekmek Bayramı'nın ilk günü öğrencileri İsa'ya, \"Fısıh yemeğini yemen için nereye gidip hazırlık yapmamızı istersin?\" diye sordular.",
    "O da öğrencilerinden ikisini şu sözlerle önden gönderdi: \"Kente gidin, orada su testisi taşıyan bir adam çıkacak karşınıza. Onu izleyin.",
    "Adamın gideceği evin sahibine şöyle deyin: 'Öğretmen, öğrencilerimle birlikte Fısıh yemeğini yiyeceğim konuk odası nerede? diye soruyor.'",
    "Ev sahibi size üst katta döşenmiş, hazır büyük bir oda gösterecek. Orada bizim için hazırlık yapın.\"",
    "Öğrenciler yola çıkıp kente gittiler. Her şeyi, İsa'nın kendilerine söylediği gibi buldular ve Fısıh yemeği için hazırlık yaptılar.",
    "Akşam olunca İsa Onikiler'le birlikte geldi.",
    "Sofraya oturmuş yemek yerlerken İsa, \"Size doğrusunu söyleyeyim\" dedi, \"Sizden biri, benimle yemek yiyen biri bana ihanet edecek.\"",
    "Onlar da kederlenerek birer birer kendisine, \"Beni demek istemedin ya?\" diye sormaya başladılar.",
    "İsa onlara, \"Onikiler'den biridir, ekmeğini benimle birlikte sahana batırandır\" dedi.",
    "\"Evet, İnsanoğlu kendisi için yazılmış olduğu gibi gidiyor, ama İnsanoğlu'na ihanet edenin vay haline! O adam hiç doğmamış olsaydı, kendisi için daha iyi olurdu.\"",
    "İsa yemek sırasında eline ekmek aldı, şükredip ekmeği böldü ve, \"Alın, bu benim bedenimdir\" diyerek öğrencilerine verdi.",
    "Sonra bir kâse alıp şükretti ve bunu öğrencilerine verdi. Hepsi bundan içti.",
    "\"Bu benim kanım\" dedi İsa, \"Birçokları uğruna akıtılan antlaşma kanıdır.",
    "Size doğrusunu söyleyeyim, Tanrı'nın Egemenliği'nde tazesini içeceğim o güne dek, asmanın ürününden bir daha içmeyeceğim.\"",
    "İlahi söyledikten sonra dışarı çıkıp Zeytin Dağı'na doğru gittiler.",
    "Bu arada İsa öğrencilerine, \"Hepiniz sendeleyip düşeceksiniz\" dedi. \"Çünkü şöyle yazılmıştır: 'Çobanı vuracağım, Koyunlar darmadağın olacak.'",
    "Ama ben dirildikten sonra sizden önce Celile'ye gideceğim.\"",
    "Petrus O'na, \"Herkes sendeleyip düşse bile ben düşmem\" dedi.",
    "\"Sana doğrusunu söyleyeyim\" dedi İsa, \"Bugün, bu gece, horoz iki kez ötmeden sen beni üç kez inkâr edeceksin.\"",
    "Ama Petrus üsteleyerek, \"Seninle birlikte ölmem gerekse bile seni asla inkâr etmem\" dedi. Öğrencilerin hepsi de aynı şeyi söyledi.",
    "Sonra Getsemani denilen yere geldiler. İsa öğrencilerine, \"Ben dua ederken siz burada oturun\" dedi.",
    "Petrus'u, Yakup'u ve Yuhanna'yı yanına aldı. Hüzünlenmeye ve ağır bir sıkıntı duymaya başlamıştı.",
    "Onlara, \"Ölesiye kederliyim\" dedi. \"Burada kalın, uyanık durun.\"",
    "Biraz ilerledi, yüzüstü yere kapanıp dua etmeye başladı. \"Mümkünse o saati yaşamayayım\" dedi.",
    "\"Abba, Baba, senin için her şey mümkün, bu kâseyi benden uzaklaştır. Ama benim değil, senin istediğin olsun.\"",
    "Öğrencilerinin yanına döndüğünde onları uyumuş buldu. Petrus'a, \"Simun\" dedi, \"Uyuyor musun? Bir saat uyanık kalamadın mı?",
    "Uyanık durup dua edin ki, ayartılmayasınız. Ruh isteklidir, ama beden güçsüzdür.\"",
    "Yine uzaklaştı, aynı sözleri tekrarlayarak dua etti.",
    "Geri geldiğinde öğrencilerini yine uyumuş buldu. Onların göz kapaklarına ağırlık çökmüştü. İsa'ya ne diyeceklerini bilemiyorlardı.",
    "İsa üçüncü kez yanlarına döndü, \"Hâlâ uyuyor, dinleniyor musunuz?\" dedi. \"Yeter! Saat geldi. İşte İnsanoğlu günahkârların eline veriliyor.",
    "Kalkın, gidelim. İşte bana ihanet eden geldi!\"",
    "Tam o anda, İsa daha konuşurken, Onikiler'den biri olan Yahuda çıkageldi. Yanında başkâhinler, din bilginleri ve ileri gelenler tarafından gönderilmiş kılıçlı sopalı bir kalabalık vardı.",
    "İsa'ya ihanet eden Yahuda, \"Kimi öpersem, İsa O'dur. O'nu tutuklayın, güvenlik altına alıp götürün\" diye onlarla sözleşmişti.",
    "Gelir gelmez İsa'ya yaklaştı, \"Rabbî\" diyerek O'nu öptü.",
    "Onlar da İsa'yı yakalayıp tutukladılar.",
    "İsa'nın yanında bulunanlardan biri kılıcını çekti, başkâhinin kölesine vurup kulağını uçurdu.",
    "İsa onlara, \"Niçin bir haydutmuşum gibi beni kılıç ve sopalarla yakalamaya geldiniz?\" dedi.",
    "\"Her gün tapınakta, yanıbaşınızda öğretiyordum, beni tutuklamadınız. Ama bu, Kutsal Yazılar yerine gelsin diye oldu.\"",
    "O zaman öğrencilerinin hepsi O'nu bırakıp kaçtı.",
    "İsa'nın ardından sadece keten beze sarınmış bir genç gidiyordu. Bu genç de yakalandı.",
    "Ama keten bezden sıyrılıp çıplak olarak kaçtı.",
    "İsa'yı görevli başkâhine götürdüler. Bütün başkâhinler, ileri gelenler ve din bilginleri de orada toplandı.",
    "Petrus, İsa'yı başkâhinin avlusunun içine kadar uzaktan izledi. Avluda nöbetçilerle birlikte ateşin başında oturup ısınmaya başladı.",
    "Başkâhinler ve Yüksek Kurul'un öteki üyeleri, İsa'yı ölüm cezasına çarptırmak için kendisine karşı tanık arıyor, ama bulamıyorlardı.",
    "Birçok kişi O'na karşı yalan yere tanıklık ettiyse de, tanıklıkları birbirini tutmadı.",
    "Bazıları kalkıp O'na karşı yalan yere şöyle tanıklık ettiler: \"Biz O'nun, 'Elle yapılmış bu tapınağı yıkacağım ve üç günde, elle yapılmamış başka bir tapınak kuracağım' dediğini işittik.\"",
    "Ama bu noktada bile tanıklıkları birbirini tutmadı.",
    "Sonra başkâhin topluluğun ortasında ayağa kalkarak İsa'ya, \"Hiç yanıt vermeyecek misin? Nedir bunların sana karşı ettiği bu tanıklıklar?\" diye sordu.",
    "Ne var ki, İsa susmaya devam etti, hiç yanıt vermedi. Başkâhin O'na yeniden, \"Yüce Olan'ın Oğlu Mesih sen misin?\" diye sordu.",
    "İsa, \"Benim\" dedi. \"Ve sizler, İnsanoğlu'nun Kudretli Olan'ın sağında oturduğunu ve göğün bulutlarıyla geldiğini göreceksiniz.\"",
    "Başkâhin giysilerini yırtarak, \"Artık tanıklara ne ihtiyacımız var?\" dedi. \"Küfürü işittiniz. Buna ne diyorsunuz?\" Hepsi İsa'nın ölüm cezasını hak ettiğine karar verdiler.",
    "Bazıları O'nun üzerine tükürmeye, gözlerini bağlayarak O'nu yumruklamaya başladılar. \"Haydi, peygamberliğini göster!\" diyorlardı. Nöbetçiler de O'nu aralarına alıp tokatladılar.",
    "Petrus aşağıda, avludayken, başkâhinin hizmetçi kızlarından biri geldi. Isınmakta olan Petrus'u görünce onu dikkatle süzüp, \"Sen de Nasıralı İsa'yla birlikteydin\" dedi.",
    "Petrus ise bunu inkâr ederek, \"Senin neden söz ettiğini bilmiyorum, anlamıyorum\" dedi ve dışarıya, dış kapının önüne çıktı. Bu arada horoz öttü.",
    "Hizmetçi kız Petrus'u görünce çevrede duranlara yine, \"Bu adam onlardan biri\" demeye başladı.",
    "Petrus tekrar inkâr etti. Çevrede duranlar az sonra Petrus'a yine, \"Gerçekten onlardansın; sen de Celileli'sin\" dediler.",
    "Petrus kendine lanet okuyup ant içerek, \"Sözünü ettiğiniz o adamı tanımıyorum\" dedi.",
    "Tam o anda horoz ikinci kez öttü. Petrus, İsa'nın kendisine, \"Horoz iki kez ötmeden beni üç kez inkâr edeceksin\" dediğini hatırladı ve hüngür hüngür ağlamaya başladı.",
  ],
  // Markos 15 (47 ayet) - kısaltılmış
  [
    "Sabah olunca başkâhinler, ileri gelenler, din bilginleri ve Yüksek Kurul'un öteki üyeleri bir danışma toplantısı yaptıktan sonra İsa'yı bağladılar, götürüp Pilatus'a teslim ettiler.",
    "Pilatus O'na, \"Sen Yahudiler'in Kralı mısın?\" diye sordu. İsa, \"Söylediğin gibidir\" yanıtını verdi.",
    "Başkâhinler O'na karşı birçok suçlamada bulundular.",
    "Pilatus O'na yeniden, \"Hiç yanıt vermeyecek misin?\" diye sordu. \"Bak, seni ne çok şeyle suçluyorlar!\"",
    "Ama İsa artık yanıt vermiyordu. Pilatus buna şaştı.",
    "Pilatus, her Fısıh Bayramı'nda halkın istediği bir tutukluyu salıverirdi.",
    "Ayaklanma sırasında adam öldüren isyancılarla birlikte Barabba adında bir tutuklu da vardı.",
    "Halk, Pilatus'a gelip her zamanki gibi kendileri için birini salıvermesini istedi.",
    "Pilatus onlara, \"Sizin için Yahudiler'in Kralı'nı salıvermemi ister misiniz?\" dedi.",
    "Başkâhinlerin İsa'yı kıskançlıktan ötürü kendisine teslim ettiklerini biliyordu.",
    "Ne var ki başkâhinler, İsa'nın değil, Barabba'nın salıverilmesini istemeleri için halkı kışkırttılar.",
    "Pilatus onlara tekrar seslenerek, \"Öyleyse Yahudiler'in Kralı dediğiniz adamı ne yapayım?\" diye sordu.",
    "\"O'nu çarmıha ger!\" diye bağırdılar yine.",
    "Pilatus onlara, \"O ne kötülük yaptı ki?\" dedi. Onlar ise daha yüksek sesle, \"O'nu çarmıha ger!\" diye bağrıştılar.",
    "Halkı memnun etmek isteyen Pilatus, onlar için Barabba'yı salıverdi. İsa'yı ise kamçılattıktan sonra çarmıha gerilmek üzere askerlere teslim etti.",
    "Askerler İsa'yı, Pretorium denilen vali konağına götürüp bütün taburu topladılar.",
    "O'na mor bir giysi giydirdiler, dikenlerden bir taç örüp başına geçirdiler.",
    "\"Selam, ey Yahudiler'in Kralı!\" diyerek O'nu selamlamaya başladılar.",
    "Başına bir kamışla vuruyor, üzerine tükürüyor, diz çöküp önünde yere kapanıyorlardı.",
    "O'nunla böyle alay ettikten sonra mor giysiyi üzerinden çıkarıp kendi giysilerini giydirdiler ve çarmıha germek üzere O'nu dışarı götürdüler.",
    "Kırdan gelmekte olan Simun adında Kireneli bir adam oradan geçiyordu. İskender ve Rufus'un babası olan bu adama İsa'nın çarmıhını zorla taşıttılar.",
    "İsa'yı Golgota, yani Kafatası denilen yere götürdüler.",
    "O'na mürle karışık şarap vermek istediler, ama içmedi.",
    "Sonra O'nu çarmıha gerdiler. Kim ne alacak diye kura çekerek giysilerini aralarında paylaştılar.",
    "İsa'yı çarmıha gerdiklerinde saat dokuzdu.",
    "Üzerindeki suç yaftasında \"Yahudiler'in Kralı\" diye yazılıydı.",
    "İsa'yla birlikte, biri sağında öbürü solunda olmak üzere iki haydudu da çarmıha gerdiler.",
    "Oradan geçenler başlarını sallayıp İsa'ya sövüyor, \"Hani sen tapınağı yıkıp üç günde yeniden kuracaktın? Çarmıhtan in de kurtar kendini!\" diyorlardı.",
    "Aynı şekilde başkâhinler ve din bilginleri de O'nunla alay ederek aralarında, \"Başkalarını kurtardı, kendini kurtaramıyor\" diye konuşuyorlardı.",
    "\"İsrail'in Kralı Mesih şimdi çarmıhtan insin de görüp iman edelim.\" İsa'yla birlikte çarmıha gerilenler de O'na hakaret ettiler.",
    "Öğleyin on ikiden üçe kadar bütün ülkenin üzerine karanlık çöktü.",
    "Saat üçte İsa yüksek sesle, \"Elohi, Elohi, lema şevaktani\" yani, \"Tanrım, Tanrım, beni neden terk ettin?\" diye bağırdı.",
    "Orada duranlardan bazıları bunu işitince, \"Bakın, İlyas'ı çağırıyor\" dediler.",
    "Aralarından biri koşup bir süngeri ekşi şaraba batırdı, bir kamışın ucuna takarak İsa'ya içirdi. \"Dur bakalım, İlyas gelip O'nu indirecek mi?\" dedi.",
    "Ama İsa yüksek sesle bağırarak son nefesini verdi.",
    "O anda tapınaktaki perde yukarıdan aşağıya yırtılarak ikiye bölündü.",
    "İsa'nın karşısında duran yüzbaşı, O'nun bu şekilde son nefesini verdiğini görünce, \"Bu adam gerçekten Tanrı'nın Oğlu'ydu\" dedi.",
    "Olup bitenleri uzaktan izleyen bazı kadınlar da vardı. Aralarında Mecdelli Meryem, küçük Yakup ile Yose'nin annesi Meryem ve Salome bulunuyordu.",
    "İsa daha Celile'deyken bu kadınlar O'nun ardından gitmiş, O'na hizmet etmişlerdi. O'nunla birlikte Yeruşalim'e gelmiş olan daha birçok kadın da olup bitenleri izliyordu.",
    "O gün Hazırlık Günü, yani Şabat Günü'nden önceki gündü. Artık akşam oluyordu. Bu nedenle, Yüksek Kurul'un saygın bir üyesi olup Tanrı'nın Egemenliği'ni umutla bekleyen Aramatyalı Yusuf geldi, cesaretini toplayarak Pilatus'un huzuruna çıktı, İsa'nın cesedini istedi.",
    "Pilatus, İsa'nın bu kadar çabuk ölmüş olmasına şaştı. Yüzbaşıyı çağırıp, \"Öleli çok oldu mu?\" diye sordu.",
    "Yüzbaşıdan durumu öğrenince Yusuf'a, cesedi alması için izin verdi.",
    "Yusuf keten bez satın aldı, cesedi çarmıhtan indirip beze sardı, kayaya oyulmuş bir mezara yatırarak mezarın girişine bir taş yuvarladı.",
    "Mecdelli Meryem ile Yose'nin annesi Meryem, İsa'nın nereye konulduğunu gördüler.",
  ],
  // Markos 16 (20 ayet)
  [
    "Şabat Günü geçince, Mecdelli Meryem, Yakup'un annesi Meryem ve Salome gidip İsa'nın cesedine sürmek üzere baharat satın aldılar.",
    "Haftanın ilk günü sabah çok erkenden, güneşin doğuşuyla birlikte mezara gittiler.",
    "Aralarında, \"Mezarın girişindeki taşı bizim için kim yana yuvarlayacak?\" diye konuşuyorlardı.",
    "Başlarını kaldırıp bakınca, o kocaman taşın yana yuvarlanmış olduğunu gördüler.",
    "Mezara girip sağ tarafta, beyaz kaftan giyinmiş genç bir adamın oturduğunu görünce çok şaşırdılar.",
    "Adam onlara, \"Şaşırmayın!\" dedi. \"Çarmıha gerilen Nasıralı İsa'yı arıyorsunuz. O dirildi, burada yok. İşte O'nu yatırdıkları yer.",
    "Şimdi öğrencilerine ve Petrus'a gidip şöyle deyin: 'İsa sizden önce Celile'ye gidiyor. Size bildirdiği gibi, kendisini orada göreceksiniz.'\"",
    "Kadınlar mezardan çıkıp kaçtılar. Onları bir titreme, bir şaşkınlık almıştı. Korkularından kimseye bir şey söylemediler.",
    "İsa, haftanın ilk günü sabah erkenden dirildiği zaman önce Mecdelli Meryem'e göründü. Ondan yedi cin kovmuştu.",
    "Meryem gitti, İsa'yla bulunmuş olan, şimdiyse yas tutup gözyaşı döken öğrencilerine haberi verdi.",
    "Ne var ki onlar, İsa'nın yaşadığını, Meryem'e göründüğünü duyunca inanmadılar.",
    "Bundan sonra İsa kırlara doğru yürümekte olan öğrencilerinden ikisine değişik bir biçimde göründü.",
    "Bunlar geri dönüp öbürlerine haber verdiler, ama öbürleri bunlara da inanmadılar.",
    "İsa daha sonra, sofrada otururlarken Onbirler'e göründü. Onları imansızlıklarından ve yüreklerinin duygusuzluğundan ötürü azarladı. Çünkü kendisini diri görenlere inanmamışlardı.",
    "İsa onlara şöyle buyurdu: \"Dünyanın her yanına gidin, Müjde'yi bütün yaratılışa duyurun.",
    "İman edip vaftiz olan kurtulacak, iman etmeyen ise hüküm giyecek.",
    "İman edenlerle birlikte görülecek belirtiler şunlardır: Benim adımla cinleri kovacaklar, yeni dillerle konuşacaklar, yılanları elleriyle tutacaklar. Öldürücü bir zehir içseler bile, zarar görmeyecekler. Ellerini hastaların üzerine koyacaklar ve hastalar iyileşecek.\"",
    "Rab İsa, onlara bu sözleri söyledikten sonra göğe alındı ve Tanrı'nın sağında oturdu.",
    "Öğrencileri de gidip Tanrı sözünü her yere yaydılar. Rab onlarla birlikte çalışıyor, görülen belirtilerle sözünü doğruluyordu.",
  ],
];
