/** 2. Petrus — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const PETER2_CHAPTER_VERSES: string[][] = [
  // 2. Petrus 1 (21 ayet)
  [
    "Rabbimiz ve Kurtarıcımız İsa Mesih'in doğruluğuyla aynı değerli imana kavuşmuş olan ben Simun Petrus'tan sizlere selam!",
    "Tanrı'yı ve Rabbimiz İsa'yı tanımakla lütuf ve esenlik sizinle çok artsın.",
    "Kendi yüce gücü bize yaşam ve tanrı yolunda yaşamak için gereken her şeyi bağışladı. Kendi yüce ve görkemli çağrısıyla bizi tanıdı.",
    "Bunlar sayesinde bize çok büyük ve değerli vaatler verildi. Öyle ki, dünyada kötü arzularla gelen bozulmadan kurtulup Tanrı'nın paydaşı olasınız.",
    "Bu nedenle her türlü gayreti gösterin. İmanınıza erdem, erdeme bilgi,",
    "bilgiye özdenetim, özdenetime dayanıklılık, dayanıklılığa tanrı yolunda yaşam, tanrı yolunda yaşama kardeş sevgisi, kardeş sevgisine de sevgi ekleyin.",
    "Çünkü bunlar sizde var ve artıyorsa, sizi işe yaramaz ve meyvesiz bırakmaz.",
    "Bunlar sizde yoksa kör, kısa görüşlüsünüz. Eski günahlarınızın silindiğini unutmuşsunuz.",
    "Bu nedenle kardeşler, Rabbimiz İsa Mesih'in Rabbi'ni ve Kurtarıcı'sını tanımakta daha da gayretli olun. Çağrınızı ve seçiminizi pekiştirin. Bunları yaparsanız hiçbir zaman sendeleyip düşmezsiniz.",
    "Böylece Tanrı'nın egemenliğine giriş size bol bol verilecektir.",
    "Bu nedenle her zaman bunları size anımsatacağım. Bunları bilseniz de, şimdi gerçekte pekişmiş olsanız da.",
    "Bu dünyadan ayrılmamın yakın olduğunu düşünüyorum. Rabbimiz İsa Mesih bana bunu açıkladı.",
    "Bunları her an anımsamanız için uygun bulduğum sürece sizinle birlikte olmaya gayret edeceğim.",
    "Çünkü Rabbimiz İsa Mesih'in bana gösterdiği gibi, çadırımdan ayrılmamın zamanı yaklaştı.",
    "Bu nedenle ölümümden sonra da bunları her zaman anımsamanızı sağlayacağım.",
    "Size Rabbimiz İsa Mesih'in yüce gücünü ve gelişini bildirirken uydurma masallara dayanmadık. O'nun görkemini kendi gözlerimizle gördük.",
    "Baba Tanrı'dan yüce onur ve yücelik alırken O'na şu ses ulaştı: «Sevgili Oğlum budur. O'ndan hoşnudum.»",
    "Kutsal dağda O'nunla birlikte olduğumuz için gökten gelen bu sesi biz de işittik.",
    "Peygamberlerin sözü bizde daha sağlam bir temel buluyor. Gündüz doğan yıldız gibi karanlık yerde parlayana dek bu söze dikkat ediyorsunuz.",
    "Öncelikle şunu bilin: Kutsal Yazıların hiçbir peygamberlik sözü kişisel yorumdan kaynaklanmaz.",
    "Çünkü hiçbir peygamberlik sözü insan isteğinden gelmedi. Kutsal Ruh tarafından yönlendirilen insanlar Tanrı'nın sözünü ilettiler.",
  ],
  // 2. Petrus 2 (22 ayet)
  [
    "Geçmişte de halk arasında sahte peygamberler vardı. Sizin aranızda da sahte öğretmenler olacak. Bunlar mahvedici sapkınlıkları gizlice sokacak. Kendilerini satın alan Efendiyi bile reddedecekler. Bu da onlara çabuk yıkım getirecek.",
    "Birçokları onların sefahatinin ardından gidecek. Gerçeğin yoluna küfür edilecek.",
    "Açgözlülükle sizden para sızdıracaklar. Uydurma sözlerle sömürecekler. Onların yargısı eskiden beri işliyor, yıkımları uyumuyor.",
    "Tanrı günahkâr melekleri bağışlamadı. Onları cehenneme atıp karanlık çukurlara teslim etti. Yargılanana dek tutulsunlar.",
    "Eski dünyayı da bağışlamadı. Nuh'u -doğruluğun duyurucusunu- yedinci kişi olarak korudu. Tanrısızların dünyasına tufan gönderdi.",
    "Sodom ve Gomora kentlerini yargılayıp yok etti. Gelecek tanrısızlara örnek olarak kül ettti.",
    "Doğru Lut'u da kurtardı. O, tanrısızların edepsiz yaşayışından bunalmıştı.",
    "Doğru kişi onların arasında yaşarken gördükleri ve işittikleriyle günahkâr ruhu gün be gün eziyet çekiyordu.",
    "Rab bilir nasıl tanrısızları yargılamadan kurtarmak, doğruları denemek için yargı gününe dek tutmak.",
    "Özellikle benliğin arzuladığı kirliliğin ardından giden, yönetimi reddedenlere gelince. Küstah, kendini beğenmiş, yüce varlıklara sövmekten çekinmiyorlar.",
    "Oysa güç ve kudret sahibi melekler bile Rab'bin önünde onlara karşı küfür içeren yargı vermiyor.",
    "Ama bunlar anlamadıkları şeylere söverler. Anlayışlı hayvanlar gibi, doğaları gereği yakalanıp mahvedilirler.",
    "Böyle yaparak aldıkları haksız ücretin cezasını çekecekler. Gündüz zevk sürerler. Sizlerle birlikte yemek yerken leke ve ayıp sayılırlar.",
    "Gözleri zinada. Günah doymak bilmez. Kararsız canları ayartır. Yürekleri açgözlülükle eğitilmiş. Lanetli çocuklardır.",
    "Doğru yolu bırakıp saptılar. Balam'ın -Beor oğlunun- yolunu izlediler. O, haksız ücreti sevdi.",
    "Eşeğinin onu insan sesiyle uyarmasıyla kendi sapkınlığı durduruldu.",
    "Bunlar su kaynağı olmayan kuyular, fırtınayla savrulan sis gibidir. Onlar için koyu karanlık saklı tutulmuştur.",
    "Boş ve küstah sözler söyleyerek benliğin tutkularıyla, sefahatte yaşayanları aldatıyorlar. Gerçekten kaçanları ayartıyorlar.",
    "Onlara özgürlük vaat ediyorlar. Oysa kendileri yozlaşmanın kölesidir. Çünkü kişi kendini neye yenik düşürürse ona köledir.",
    "Gerçeği tanıyıp Rabbimiz ve Kurtarıcımız İsa Mesih'in yolunu öğrendikten sonra dünyanın kirine dönmüşlerse, son durumları ilkinden beterdir.",
    "Doğruluk yolunu bilip de kendilerine iletilen kutsal buyruğu bırakmak, onlar için daha iyi olurdu.",
    "Gerçek şu sözde doğrulanıyor: «Köpek kustuğuna döner», «Yıkanan domuz çamurda yuvarlanmaya.»",
  ],
  // 2. Petrus 3 (18 ayet)
  [
    "Sevgili kardeşlerim, size bu ikinci mektubu yazıyorum. Her ikisinde de düşüncenizi uyarıp sağlam durmanızı sağlamak istiyorum.",
    "Kutsal peygamberlerin önceden söylediklerini ve Kurtarıcınız Rab'bin elçilerinin ilettiği buyruğu anımsayın.",
    "Öncelikle şunu bilin: Son günlerde alaycılar gelecek. Kendi tutkularına göre yaşayacak ve alay ederek soracaklar:",
    "«O vaat nerede? Atalarımız öldüğünden beri her şey yaratılışın başından beri olduğu gibi sürüyor.»",
    "Bilerek unutuyorlar: Tanrı'nın sözüyle gökler ve yer eskiden vardı. Yer sudan ve su aracılığıyla oluştu.",
    "O zamanın dünyası suyla batırılıp yok oldu.",
    "Ama şimdiki gökler ve yer aynı sözle saklanıyor. Tanrısızların yargılanıp yok edileceği güne dek ateşe verilmek üzere.",
    "Sevgili kardeşlerim, şu tek şeyi unutmayın: Rab'bin gözünde bir gün bin yıl gibi, bin yıl bir gün gibidir.",
    "Rab vaadini yerine getirmekte gecikmez. Bazıları gecikme sayıyor. Ama O size karşı sabırlı. Kimsenin mahvolmasını istemiyor. Herkesin tövbeye gelmesini istiyor.",
    "Rab'bin günü hırsız gibi gelecek. O gün gökler büyük gürültüyle geçip gidecek. Öğeler yanıp eriyecek. Yer ve yaptıkları yargılanacak.",
    "Bunların hepsi böyle eriyeceğine göre, siz nasıl kişiler olmalısınız? Kutsal yaşamda ve tanrı yolunda yaşamakta,",
    "Tanrı'nın gününün gelişini bekleyip çabuklaştırmalısınız. O gün gökler yanıp eriyecek, öğeler kızgın ateşte eriyecek.",
    "Ama O'nun vaadine göre yeni gökler ve yeni bir yer bekliyoruz. Orada doğruluk konut kuracak.",
    "Sevgili kardeşlerim, bunu beklerken O'nun gözünde lekesiz, kusursuz ve esenlikte bulunmak için gayret gösterin.",
    "Rabbimizin sabrını kurtuluş sayın. Sevgili kardeşimiz Pavlus da bilgeliğiyle size yazdığı gibi.",
    "Tüm mektuplarında bunlardan söz ediyor. İçlerinde anlaşılması zor bazı yerler var. Bilgisiz ve kararsız kişiler -öbür Kutsal Yazılar gibi- bunları çarpıtarak kendi mahvoluşlarını hazırlıyorlar.",
    "Siz de sevgili kardeşlerim, bunu önceden bilerek, sapkınların sapkınlığıyla sürüklenip kendi sağlam duruşunuzu yitirmeyin.",
    "Rabbimiz ve Kurtarıcımız İsa Mesih'in lütfuyla ve O'nu tanımakla büyüyün. O'na şimdi ve sonsuza dek yücelik olsun! Amin.",
  ],
];
