/** 1. Petrus — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const PETER1_CHAPTER_VERSES: string[][] = [
  // 1. Petrus 1 (25 ayet)
  [
    "Mesih İsa'nın elçisi ben Petrus'tan, Pontus, Galatya, Kapadokya, Asya ve Bitinya'da dağılmış olan seçilmişlere selam!",
    "Baba Tanrı'nın önbilgisi uyarınca Ruh'un kutsal kılmasıyla itaate ve Mesih İsa'nın kanının serpilmesine seçildiniz. Sizlere lütuf ve esenlik çok artsın.",
    "Rabbimiz İsa Mesih'in Babası Tanrı'ya övgüler olsun. O büyük merhametiyle dirilişle Mesih İsa'yı ölümden dirilterek bizi diri bir umuda,",
    "çürümez, lekesiz ve solmaz mirasa kavuşturdu. Göklerde sizin için saklı tutuluyor.",
    "Siz de imanla Tanrı'nın gücüyle korunuyorsunuz. Son zamanlarda açıklanacak kurtuluşa kavuşmak için.",
    "Bunun için çok seviniyorsunuz. Şimdi kısa bir süre çeşitli denemelerle gerekirse üzülüyorsunuz.",
    "Böylece kanıtlanmış imanınız -ateşte arıtılan ama yok olan altından çok daha değerli- İsa Mesih göründüğünde övgü, yücelik ve onur getirir.",
    "O'nu görmeden seviyorsunuz. Şimdi O'nu görmeden O'na iman ediyorsunuz. Sözle anlatılamayan ve yüce bir sevinçle seviniyorsunuz.",
    "İmanınızın sonucu olan kurtuluşa -canlarınızın kurtuluşuna- kavuşuyorsunuz.",
    "Bu kurtuluşla ilgili peygamberler araştırıp incelediler. Sizin için yapılan lütfu önceden bildirdiler.",
    "İçlerinde olan Mesih'in Ruh'u, Mesih'in çekeceği sıkıntıları ve sonraki yüceliği önceden tanıklık etti. Bunların hangi zamana ya da ne tür zamana ait olduğunu araştırdılar.",
    "Kendilerine bildirildi ki, bunlar sizin için değil, sizin adınıza duyurulan bu şeylerde sizlerle paydaş olan melekler için bildirildi. Bunları görevliler aracılığıyla gökten gönderen Kutsal Ruh aracılığıyla size ilettiler.",
    "Bu nedenle belinizi bağlayın, aklı başında olun. Umudunuzu tamamen, İsa Mesih'in görünümünde size getirilecek lütfa bağlayın.",
    "Söz dinleyen çocuklar gibi olun. Önceki bilgisizlik dönemindeki tutkularınıza uymayın.",
    "Sizi çağıran kutsal olduğu gibi siz de her davranışınızda kutsal olun.",
    "Çünkü «Kutsal olun, çünkü ben kutsalım» diye yazılmıştır.",
    "Her şeyi kişisel çıkar gözetmeden, adil yargılayan Baba'ya «Baba» diye sesleniyorsanız, sürgünde geçirdiğiniz günlerde korkuyla yaşayın.",
    "Biliyorsunuz, atalarınızdan gelen boş yaşayıştan altın ya da gümüş gibi geçici şeylerle değil, değerli kan -kusursuz ve lekesiz kuzu Mesih'in kanı- ile fidye ödenerek kurtuldunuz.",
    "O dünyanın kuruluşundan önce önceden bilindi. Ama son zamanlarda sizin için açıklandı.",
    "O'nun aracılığıyla siz Mesih'e iman edenlersiniz. O'nu ölümden dirilten ve O'na yücelik veren Tanrı'ya iman ediyorsunuz. Öyle ki iman ve umudunuz Tanrı'da olsun.",
    "Gerçeğe uyarak canlarınızı pakladınız. Kardeşlere içten sevgi için. Yürekten birbirinizi candan sevin.",
    "Ölümlü değil, ölümsüz tohumdan -Tanrı'nın diri ve kalıcı sözüyle- yeniden doğdunuz.",
    "Çünkü «Bütün insanlar ot gibi, bütün yücelikleri otun çiçeği gibidir. Ot kurur, çiçek düşer.»",
    "«Ama Rab'bin sözü sonsuza dek kalır.»",
    "İşte size müjdelenen söz budur.",
  ],
  // 1. Petrus 2 (25 ayet)
  [
    "Bu nedenle her kötülüğü, her hileyi, ikiyüzlülüğü, kıskançlığı ve her türlü kötü sözü sıyırıp atın.",
    "Yeni doğan bebekler gibi sözün pak ve ruhsal sütünü özleyin. Öyle ki onunla büyüyesiniz.",
    "Rab iyidir. O'na yaklaşanlar O'nun tadına vardı.",
    "İnsanlarca reddedildi ama Tanrı tarafından seçilmiş, değerli, diri taşa yaklaşın.",
    "Siz de diri taşlar olarak ruhsal bir ev kuruluyorsunuz. Kutsal bir kâhinlik olarak Mesih İsa aracılığıyla Tanrı'ya kabul edilen ruhsal sunular sunun.",
    "Çünkü Kutsal Yazı'da şöyle deniyor: «İşte Siyon'a -seçilmiş, değerli köşe taşına- koyuyorum. O'na inanan utandırılmayacak.»",
    "Siz inananlar için değerli. Ama inanmayanlar için «Yapıcıların reddettiği taş, köşe taşı oldu» ve «Tökezleme taşı, sendeleyen kaya».",
    "Söz dinlemedikleri için tökezliyorlar. Bunun için de atandılar.",
    "Ama siz seçilmiş soy, kraliyet kâhinliği, kutsal ulus, Tanrı'ya ait halksınız. Sizi karanlıktan çağırıp kendi harika ışığına getirenin erdemlerini duyurmak için.",
    "Bir zamanlar halk değildiniz, şimdi Tanrı'nın halkısınız. Bir zamanlar merhamet görmemiştiniz, şimdi merhamet görmüşsünüz.",
    "Sevgili kardeşlerim, sürgün ve yabancı olarak ruhsal arzularınızı çağıranlardan kaçının.",
    "Öteki uluslar arasında güzel yaşayışınız olsun. Öyle ki, sizi kötüleyenler iyi işlerinizi görüp Tanrı'yı yücelik gününde överler.",
    "İnsanın her kurumuna -ister krala üstün olarak ister kralın gönderdiği valilere- Rab uğruna boyun eğin.",
    "İyilik edenleri övmek, kötülük edenleri cezalandırmak için gönderildiler.",
    "Çünkü Tanrı'nın isteği, iyilik yaparak bilgisizlerin bilgisizliğini susturmanızdır.",
    "Özgür olarak -Tanrı'nın kulları olarak- insanlara değil Tanrı'ya boyun eğin.",
    "Herkese saygı gösterin. Kardeşleri sevin. Tanrı'dan korkun. Krala saygı gösterin.",
    "Ey hizmetkârlar, tüm saygıyla efendilerinize boyun eğin. Yalnız iyi ve yumuşak olanlara değil, sert olanlara da.",
    "Çünkü biri bilinçli olarak haksız acıya katlanırsa bu Tanrı katında lütuftur.",
    "Suç işleyip dayak yiyip katlanırsanız ne övünç? Ama iyilik edip acı çekip katlanırsanız bu Tanrı katında lütuftur.",
    "Bunun için çağrıldınız. Çünkü Mesih de sizin için acı çekti. Size örnek bıraktı. O'nun izinden gidesiniz.",
    "O günah işlemedi. Ağzında hile bulunmadı.",
    "Sövdüğünde sövmeyle karşılık vermedi. Acı çektiğinde tehdit etmedi. Tersine adil Yargıç'a bıraktı.",
    "O günahlarımızı kendi bedeninde çarmıhta taşıdı. Günaha ölmemiz, doğruluğa yaşamamız için. O'nun yaralarıyla şifa buldunuz.",
    "Siz koyun gibi sapıtmıştınız. Şimdi canlarınızın Çobanı ve Gözetmeni'ne döndünüz.",
  ],
  // 1. Petrus 3 (22 ayet)
  [
    "Aynı şekilde ey kadınlar, kocalarınıza boyun eğin. Öyle ki, söz dinlemeseler bile söz olmadan, davranışlarıyla kazanılsınlar.",
    "Pak yaşayışınızı, saygılı korkunuzu görsünler.",
    "Süsünüz dıştakiler -saç örmesi, altın takısı, giysi- değil,",
    "yürekteki gizli insan -sakin ve yumuşak ruhun kalıcı süsü- olsun. Tanrı'nın gözünde çok değerlidir.",
    "Çünkü eskiden kutsal kadınlar da böyle Tanrı'ya umut bağlayarak kendilerini süslerdi. Kocalarına boyun eğerdi.",
    "Örneğin Sara İbrahim'e «efendim» diye seslendi. İyilik yapıp hiçbir tehditle yılmadıysanız onun çocukları oldunuz.",
    "Aynı şekilde ey kocalar, karılarınızla bilgiye göre yaşayın. Onlar daha zayıf kap olarak kadınlıkla mirasçılık lütfuna ortak olsunlar. Dualarınız engellenmesin.",
    "Sonuç olarak hepiniz aynı düşüncede olun, sevecen, kardeş sevgisiyle yürekten, merhametli, alçakgönüllü olun.",
    "Kötülüğe kötülükle, sövgüye sövgüyle karşılık vermeyin. Tersine kutsasınız. Çünkü bunun için çağrıldınız. Öyle ki kutsamayı miras alasınız.",
    "«Yaşamı sevip iyilik görmek isteyen dudaklarını kötü sözden kessin. Barışı arasın, ardınca gitsin.»",
    "Çünkü Rab'bin gözleri doğruların üzerindedir. Kulakları yalvarışlarına açıktır. Ama Rab kötülük yapanlara karşıdır.",
    "Siz doğru yaşarsanız kim size zarar verebilir?",
    "Doğruluk uğruna acı çekseniz bile mutlusunuz. «Onların korkusundan korkmayın, heyecanlanmayın» demeyin.",
    "Yüreklerinizde Mesih'i Rab olarak kutsayın. Size karşı umut soran herkese yanıt vermeye her zaman hazır olun. Ama yumuşaklık ve saygıyla.",
    "Temiz vicdanınız olsun. Öyle ki, sizi kötüleyenler Mesih'teki güzel yaşayışınızı görüp utansın.",
    "İyilik etmek isteseniz de acı çekmek Tanrı'nın isteğiyse, kötü etmekten iyidir.",
    "Çünkü Mesih de günahlar uğruna bir kez acı çekti -doğru, doğrular uğruna- sizi Tanrı'ya getirmek için. Bedence öldürüldü, ruhça diriltildi.",
    "O ruhça zindandaki ruhlara gidip duyurdu.",
    "Bir zamanlar Nuh'un günlerinde gemi yapılırken sabırla bekleyenlere itaat etmeyenlere duyuruldu. Az kişi -sekiz kişi- suda kurtuldu.",
    "Şimdi vaftiz -bedenin kirden arınması değil, Tanrı'ya karşı temiz vicdanın isteği- sizi de kurtarıyor. İsa Mesih'in dirilişi aracılığıyla.",
    "O göğe gitmiş olup Tanrı'nın sağındadır. Melekler, yönetimler ve güçler O'na bağımlı kılınmıştır.",
  ],
  // 1. Petrus 4 (19 ayet)
  [
    "Mesih bedence acı çektiği için siz de aynı düşünceyle silah alın. Bedence acı çeken günaha son vermiştir.",
    "Öyle ki artık insanın arzularına değil, Tanrı'nın isteğine göre bedende kalan günlerini geçirsin.",
    "Geçmişte putperestlerin isteğine göre -sefahet, tutku, sarhoşluk, şölenler, içki partileri ve yasak putperest tapınmalarına- yeterince zaman harcadınız.",
    "Sizin de onlarla aynı sefahate koşmadığınıza şaşırıp küfür ediyorlar.",
    "Ama onlar dirilerle ölülere hesap verecek Olan'a hesap verecekler.",
    "Ölülere de Müjde duyuruldu. Öyle ki bedence insanlarca yargılansalar da ruhça Tanrı'ya göre yaşasınlar.",
    "Her şeyin sonu yaklaştı. Bu nedenle aklı başında olun, dualarda uyanık olun.",
    "Her şeyden önce birbirinizi candan sevin. Çünkü sevgi birçok günahı örter.",
    "Birbirinize konuksever olmaktan çekinmeyin.",
    "Her biri aldığı armağanla öbürüne hizmet etsin. İyi çeşitli lütuf dağıtıcıları olarak.",
    "Konuşan kişi Tanrı'nın sözlerini söylesin. Hizmet eden Tanrı'nın verdiği güçle hizmet etsin. Öyle ki her şeyde Mesih aracılığıyla Tanrı yüceltilsin. Yücelik ve güç sonsuza dek O'nun olsun! Amin.",
    "Sevgili kardeşlerim, sizi deneyen ateşe düşmüş gibi garipsemeyin. Başınıza gelenler garip değil.",
    "Mesih'in acılarına ortak olduğunuz ölçüde sevinin. Öyle ki O'nun yüceliği açıklandığında da sevinçle coşasınız.",
    "Mesih'in adı uğruna küfür edilirseniz mutlusunuz. Çünkü yüce Tanrı'nın Ruh'u sizin üzerinizdedir.",
    "Aranızda kimse katil, hırsız, kötülük eden ya da işe karışan olarak acı çekmesin.",
    "Ama Hıristiyan diye acı çekerse utansın. Tersine bu addan ötürü Tanrı'yı yüceltsin.",
    "Çünkü yargı evinden başlamak zamanıdır. Önce bizden başlarsa Tanrı'nın Müjdesi'ne uymayanların sonu ne olur?",
    "«Doğru kişi güçlükle kurtuluyorsa, tanrısız ve günahkâr nerede görünecek?»",
    "Bu nedenle Tanrı'nın isteği uyarınca acı çekenler, iyilik ederek canlarını güvenilir Yaradan'a emanet etsinler.",
  ],
  // 1. Petrus 5 (14 ayet)
  [
    "Aranızdaki ihtiyarlara yalvarıyorum -ben de ihtiyar, Mesih'in acılarına tanık ve açıklanacak yüceliğe ortak olarak-:",
    "Sizin aranızda Tanrı'nın sürüsünü gütün. Zorunlulukla değil, Tanrı'nın isteğiyle. Para hırsıyla değil, gönüllü olarak.",
    "Sürüye egemen olmayın. Tersine örnek olun.",
    "Baş Çoban göründüğünde solmaz yücelik tacını alacaksınız.",
    "Aynı şekilde ey gençler, ihtiyarlara boyun eğin. Hepiniz birbirinize alçakgönüllülük kuşanın. Çünkü «Tanrı kibirlilere karşıdır, alçakgönüllülere lütuf verir.»",
    "Öyleyse Tanrı'nın güçlü eli altında alçalın. Öyle ki sizi uygun zamanda yüceltsin.",
    "Tüm kaygılarınızı O'na yükleyin. Çünkü O sizi önemsiyor.",
    "Aklı başında olun, uyanık olun. Düşmanınız İblis kükreyen aslan gibi yutacak birini arayarak dolaşıyor.",
    "Ona imanda dimdik durarak direnin. Dünyada kardeşlerinizin de aynı acıları çektiğini biliyorsunuz.",
    "Sıkıntılarınızı tamamladıktan sonra sizi her lütufta çağıran sonsuz yücelikteki Tanrı, Mesih İsa'da sizi kendisi yenileyecek, güçlendirecek, pekiştirecek, temel atacaktır.",
    "Güç O'nun olsun sonsuza dek! Amin.",
    "Gerçeğe uygun olarak size kısa yazdım. Sizi yüreklendirip tanıklık ediyorum. Bu Tanrı'nın gerçek lütfudur. Buna bağlı kalın.",
    "Seçilmiş olanlarla birlikte Babil'deki topluluk ve oğlum Markos sana selam eder.",
    "Birbirinizi kutsal öpüşle selamlayın. Mesih'e ait olanların hepsine esenlik olsun.",
  ],
];
