/** En çok okunan Mezmurlar — Türkçe Kutsal Kitap (Yeni Çeviri) */

export type PsalmVerse = {
  number: number;
  text: string;
};

export type Psalm = {
  number: number;
  title: string;
  verses: PsalmVerse[];
};

export const psalms: Psalm[] = [
  {
    number: 1,
    title: '1. Mezmur',
    verses: [
      { number: 1, text: 'Ne mutlu o insana ki, kötülerin öğüdüyle yürümez, Günahkârların yolunda durmaz, Alaycıların arasında oturmaz.' },
      { number: 2, text: "Ancak zevkini RAB'bin Yasası'ndan alır Ve gece gündüz onun üzerinde derin derin düşünür." },
      { number: 3, text: 'Böylesi akarsu kıyılarına dikilmiş ağaca benzer, Meyvesini mevsiminde verir, Yaprağı hiç solmaz. Yaptığı her işi başarır.' },
      { number: 4, text: 'Kötüler böyle değil, Rüzgarın savurduğu saman çöpüne benzerler.' },
      { number: 5, text: 'Bu yüzden yargılanınca aklanamaz, Doğrular topluluğunda yer bulamaz günahkârlar.' },
      { number: 6, text: "Çünkü RAB doğruların yolunu gözetir, Kötülerin yolu ise ölüme götürür." },
    ],
  },
  {
    number: 8,
    title: '8. Mezmur',
    verses: [
      { number: 1, text: "Ey Egemen RAB, adın bütün yeryüzünde ne yüce! Gökleriyle görkemini sergiledin." },
      { number: 2, text: "Düşmanları susturmak, son intikamı almak için düşman ve öç alandan ötürü küçük çocukların ve emziklilerin ağzından kuvvet oluşturdun." },
      { number: 3, text: "Göklerini, parmağının eserini, yerleştirdiğin ayı ve yıldızları görünce," },
      { number: 4, text: "İnsan nedir ki onu anasın, İnsanoğlu nedir ki ona baktasın?" },
      { number: 5, text: "Onu tanrılardan biraz aşağı kıldın, Başına yücelik ve onur tacı giydirdin." },
      { number: 6, text: "Eserlerinin üzerine onu atadın, Her şeyi ayaklarının altına serdin;" },
      { number: 7, text: "Koyunlar, sığırların hepsi, Yabanıl hayvanlar," },
      { number: 8, text: "Gök kuşları, deniz balıkları, Denizde kıpır kıpır kıpırdayan her şey." },
      { number: 9, text: "Ey Egemen RAB, adın bütün yeryüzünde ne yüce!" },
    ],
  },
  {
    number: 19,
    title: '19. Mezmur',
    verses: [
      { number: 1, text: "Gökler Tanrı'nın görkemini açıklar, Gökkubbe ellerinin işini duyurur." },
      { number: 2, text: "Gün güne söz söyler, Gece geceye bilgi verir." },
      { number: 3, text: "Ne konuşma var, ne söz var, Sesleri duyulmaz." },
      { number: 4, text: "Ama sesleri bütün yeryüzüne yayılır, Sözleri dünyanın ucuna kadar ulaşır. Gökler için güneş çadır kurdu." },
      { number: 5, text: "O, düğün odasından çıkan güveye benzer, Koşucu gibi yürümekten sevinç duyar." },
      { number: 6, text: "Göğün bir ucundan çıkar, Öbür ucuna döner, Hiçbir şey sıcaklığından kaçamaz." },
      { number: 7, text: "RAB'bin yasası kusursuzdur, cana can katar. RAB'bin buyruğu güvenilirdir, sade kişiyi aydınlatır." },
      { number: 8, text: "RAB'bin kuralları doğrudur, yüreği sevindirir. RAB'bin buyruğu paklıktır, gözleri aydınlatır." },
      { number: 9, text: "RAB'be duyulan korku tertemizdir, sonsuza dek sürer. RAB'bin hükümleri gerçektir, hepsi adildir." },
      { number: 10, text: "Altından, bol saf altından daha değerli, Baldan, süzme petek balından daha tatlıdır." },
      { number: 11, text: "Uyarıları vardır kulun için, Onlara uyanın ödülü büyüktür." },
      { number: 12, text: "Kim kusurlarını fark edebilir? Gizli hatalarımdan beni arındır." },
      { number: 13, text: "Kulunun bile isteye işlediği günahlardan beni uzak tut, Onların beni yönetmesine izin verme. O zaman büyük suçlardan arınmış olurum." },
      { number: 14, text: "Ağzımdan çıkan sözler, Yüreğimdeki düşünceler Senin önünde kabul görsün, Ey kayam ve kurtarıcım RAB!" },
    ],
  },
  {
    number: 22,
    title: '22. Mezmur',
    verses: [
      { number: 1, text: "Ey Tanrım, ey Tanrım, beni neden terk ettin? Yardımına uzak, feryadımın sözlerinden ötürü." },
      { number: 2, text: "Ey Tanrım, gündüz sesleniyorum, yanıt vermiyorsun; Gece de susmuyorum." },
      { number: 3, text: "Oysa sen kutsalsın, İsrail'in övgüleri üzerine taht kuran sensin." },
      { number: 4, text: "Atalarımız sana güvendi, güvendin, kurtardın." },
      { number: 5, text: "Sana seslendiler, kurtuldular; Sana güvendiler, utandırılmadılar." },
      { number: 6, text: "Bense bir solucanım, insan değilim, İnsanların aşağıladığı, halkın hor gördüğü." },
      { number: 7, text: "Beni gören herkes alay ediyor, Ağızlarını açıp baş sallıyorlar:" },
      { number: 8, text: "\"RAB'be dayandı, kurtarsın onu, Madem ki onu seviyor, kurtarsın!\"" },
      { number: 9, text: "Evet, sen beni annemin rahminden çıkardın, Annemin memesinde güven verdin bana." },
      { number: 10, text: "Doğduğum andan beri sana bırakıldım, Annem rahminden beri Tanrım sensin." },
      { number: 11, text: "Benden uzak durma, çünkü sıkıntı yakın, Yardım eden yok." },
      { number: 12, text: "Beni boğalar sarmış, Başan'ın güçlü boğaları kuşatmış beni." },
      { number: 13, text: "Ağızlarını bana açıyorlar, Parçalayan, kükreyen aslan gibi." },
      { number: 14, text: "Su gibi dökülüyorum, Bütün kemiklerim oynaklarından çıkıyor, Yüreğim balmumu gibi eriyor içimde." },
      { number: 15, text: "Gücüm çömlek parçası gibi kurudu, Dilim damağıma yapışıyor. Beni ölüm toprağına yatırıyorsun." },
      { number: 16, text: "Çünkü köpekler kuşatmış beni, Kötüler sürüsü sarmış, Ellerimi, ayaklarımı deliyorlar." },
      { number: 17, text: "Bütün kemiklerimi sayabilirim; Onlar bakıp seyrediyorlar." },
      { number: 18, text: "Giysilerimi aralarında bölüşüyor, Elbisem için kura çekiyorlar." },
      { number: 19, text: "Ama sen, ey RAB, uzak durma, Ey gücüm, yardımıma koş!" },
      { number: 20, text: "Canımı kılıçtan, Biricik hayatımı köpeklerin pençesinden kurtar." },
      { number: 21, text: "Aslanın ağzından kurtar beni, Yabanı öküzlerin boynuzlarından kurtar." },
      { number: 22, text: "Adını kardeşlerime duyuracağım, Topluluk ortasında sana övgüler sunacağım." },
      { number: 23, text: "\"RAB'den korkanlar, O'nu övün! Yakup soyu, O'nu yüceltin! İsrail soyu, O'ndan korkun!\"" },
      { number: 24, text: "Çünkü O düşkünün çektiği acıya aldırmadı, Utançtan yüzünü gizlemedi ondan. Feryadını duyunca ona kulak verdi." },
      { number: 25, text: "Büyük toplulukta övgüm senden gelir, Senden korkanların önünde adaklarımı yerine getireceğim." },
      { number: 26, text: "Düşkünler doyacak, RAB'bi arayanlar O'na övgüler sunacak. Yürekleriniz sonsuza dek yaşasın!" },
      { number: 27, text: "Yeryüzünün dört bucağı düşünüp RAB'be dönecek, Ulusların bütün aileleri O'nun önünde eğilecek." },
      { number: 28, text: "Çünkü egemenlik RAB'bindir, Uluslara O hükmeder." },
      { number: 29, text: "Yeryüzündeki bütün zenginler doyup secde edecek, Toprağa inen herkes O'nun önünde diz çökecek. Canını yaşatamayan kimse." },
      { number: 30, text: "Soyum O'na kulluk edecek, RAB'den gelecek kuşaklara anlatılacak;" },
      { number: 31, text: "Gelecek kuşağa O'nun doğruluğu, Henüz doğmamış halka O'nun yaptıkları duyurulacak." },
    ],
  },
  {
    number: 23,
    title: "23. Mezmur — Davut'un mezmuru",
    verses: [
      { number: 1, text: "RAB çobanımdır, Eksiğim olmaz." },
      { number: 2, text: "Beni yemyeşil çayırlarda yatırır, Sakin suların kıyısına götürür." },
      { number: 3, text: "İçimi tazeler, Adı uğruna bana doğru yollarda öncülük eder." },
      { number: 4, text: "Karanlık ölüm vadisinden geçsem bile, Kötülükten korkmam. Çünkü sen benimlesin. Çomağın, değneğin güven verir bana." },
      { number: 5, text: "Düşmanlarımın önünde bana sofra kurarsın, Başıma yağ sürersin, Kâsem taşıyor." },
      { number: 6, text: "Ömrüm boyunca yalnız iyilik ve sevgi izleyecek beni, Hep RAB'bin evinde oturacağım." },
    ],
  },
  {
    number: 24,
    title: '24. Mezmur',
    verses: [
      { number: 1, text: "RAB'bindir yeryüzü ve içindeki her şey, Dünya ve üzerinde yaşayanlar." },
      { number: 2, text: "Çünkü O denizlerin üzerinde onu kurdu, Irmakların üzerinde onu temellendirdi." },
      { number: 3, text: "RAB'bin dağına kim çıkabilir? O'nun kutsal yerine kim girebilir?" },
      { number: 4, text: "Elleri pak, yüreği temiz olan, Gönlü putlara yönelmeyen, Yalan ant içmeyen." },
      { number: 5, text: "RAB'den kutsama, Doğruluk Tanrısı'ndan kurtuluş alacak." },
      { number: 6, text: "İşte RAB'bi arayan kuşak böyledir, Yüzünü arayan, Yakup'un Tanrısı'nı arayan." },
      { number: 7, text: "Ey kapılar, başlarınızı kaldırın! Ey eski kapılar, açılın! Görkemli Kral girsin!" },
      { number: 8, text: "Bu görkemli Kral kim? Güçlü ve yiğit RAB, Savaşta yiğit RAB!" },
      { number: 9, text: "Ey kapılar, başlarınızı kaldırın! Ey eski kapılar, açılın! Görkemli Kral girsin!" },
      { number: 10, text: "Bu görkemli Kral kim? Her Şeye Egemen RAB — O görkemli Kral!" },
    ],
  },
  {
    number: 27,
    title: '27. Mezmur',
    verses: [
      { number: 1, text: "RAB ışığım ve kurtuluşumdur, Korkacak kim var? RAB hayatımın kalesidir, Yılgınlığa düşecek kim var?" },
      { number: 2, text: "Kötüler bana saldırdığında, Düşmanlarım, hasımlarım üzerime yürüdüğünde, Beni yiyip bitirmek için, Onlar sendeleyip düştüler." },
      { number: 3, text: "Bir ordu üzerime kamp kursa bile, Yüreğim korkmaz. Bana karşı savaş açılsa bile, Yine de güvenirim." },
      { number: 4, text: "RAB'den tek bir şey dilerim, Onu isterim: RAB'bin evinde ömrüm boyunca oturmak, O'nun güzelliğini seyretmek, Tapınağında O'na yakın olmak." },
      { number: 5, text: "Çünkü sıkıntı gününde beni çardağında gizleyecek, Çadırının içinde saklayacak, Kayalığın üzerine çıkaracak." },
      { number: 6, text: "Başım düşmanlarımı çevreleyenlerin üzerinde yükselecek. Tapınağında sevinç kurbanları sunacağım, RAB'bi ezgilerle öveceğim." },
      { number: 7, text: "Dinle, ey RAB, seslendiğimde yanıt ver, Bana lütfet, yanıt ver." },
      { number: 8, text: "Yüreğim senden, \"Yüzümü ara\" diyor. Ya RAB, yüzünü arıyorum." },
      { number: 9, text: "Yüzünü benden gizleme, Kulunu öfkeyle reddetme. Yardımcım sensin, beni bırakma, terk etme, ey Kurtarıcı Tanrım." },
      { number: 10, text: "Annem babam beni bıraksa bile, RAB beni kabul eder." },
      { number: 11, text: "Ya RAB, yolunu öğret bana, Düşmanlarım yüzünden düz yolda yürümemi sağla." },
      { number: 12, text: "Bana hasımlarımın isteğini verme, Çünkü sana karşı yalan uyduran, Zorba tanıklar ayağa kalkıyor." },
      { number: 13, text: "Yaşayanlar diyarında RAB'bin iyiliğini göreceğime inıyorum." },
      { number: 14, text: "RAB'bi bekle, güçlü ol, yüreğin güçlü olsun. Evet, RAB'bi bekle!" },
    ],
  },
  {
    number: 34,
    title: '34. Mezmur',
    verses: [
      { number: 1, text: "RAB'bi her zaman öveceğim, O'na övgüm hep dudaklarımda olacak." },
      { number: 2, text: "RAB'le yüreğim övünecek, Düşkünler işitip sevinecek." },
      { number: 3, text: "Benimle birlikte RAB'bi yüceltin, Adını birlikte yüceltelim." },
      { number: 4, text: "RAB'bi aradım, yanıt verdi, Bütün korkularımdan kurtardı beni." },
      { number: 5, text: "O'na baktılar, aydınlandılar, Yüzleri asla utandırılmadı." },
      { number: 6, text: "Bu düşkün feryat etti, RAB işitti, Bütün sıkıntılarından kurtardı onu." },
      { number: 7, text: "RAB'bin meleği RAB'den korkanların çevresinde ordugah kurar, Onları kurtarır." },
      { number: 8, text: "Tadın ve görün RAB'bin ne iyi olduğunu! Ne mutlu O'na sığınan insana!" },
      { number: 9, text: "RAB'den korkun, ey kutsalları O'nun! Çünkü O'ndan korkanlara hiçbir şey eksik olmaz." },
      { number: 10, text: "Genç aslanlar aç kalıp ihtiyaç çeker, Ama RAB'bi arayanlara iyi bir şey eksik olmaz." },
    ],
  },
  {
    number: 46,
    title: '46. Mezmur',
    verses: [
      { number: 1, text: "Tanrı sığınağımız ve gücümüzdür, Sıkıntıda her zaman yardım eden hazır kuvvettir." },
      { number: 2, text: "Bu yüzden yeryüzü değişse, Dağlar denizin ortasına çökse bile korkmayız." },
      { number: 3, text: "Suları gürlese, köpürse, Dağlar sarsılsa bile." },
      { number: 4, text: "Bir ırmak var — kolları Tanrı kentini, Yüce Olan'ın konutunu sevindirir. Tanrı o kentin ortasındadır, Sarsılmaz. Tanrı ona tan ağarmadan yardım eder." },
      { number: 5, text: "Uluslar gürlüyor, krallıklar sarsılıyor. O sesini duyurdu, yeryüzü eriyor." },
      { number: 6, text: "Her Şeye Egemen RAB bizimle, Yakup'un Tanrısı kalemizdir." },
      { number: 7, text: "Gelin, RAB'bin işlerini görün, Yeryüzünde nasıl yıkımlar yaptı." },
      { number: 8, text: "Savaşları dünyanın dört bucağında sona erdirir. Yayı kırar, mızrağı parçalar, Kalkanları ateşe atar." },
      { number: 9, text: "\"Sakin olun, bilin ki ben Tanrı'yım. Uluslar arasında yüceltileceğim, Yeryüzünde yüceltileceğim.\"" },
      { number: 10, text: "Her Şeye Egemen RAB bizimle, Yakup'un Tanrısı kalemizdir." },
    ],
  },
  {
    number: 51,
    title: '51. Mezmur',
    verses: [
      { number: 1, text: "Tanrım, sevgin uyarınca bana lütfet, Bol merhametinle suçlarımı sil." },
      { number: 2, text: "Suçumu bütünüyle yıka, Günahımdan beni arındır." },
      { number: 3, text: "Çünkü suçumu biliyorum, Günahım hep önümde." },
      { number: 4, text: "Sana karşı, yalnız sana karşı günah işledim, Gözünde kötü olanı yaptım. Öyle ki, konuşurken haklı çıkacak, Yargılayınca temize çıkacaksın." },
      { number: 5, text: "Nitekim suç içinde doğdum, Günah içinde annem bana hamile kaldı." },
      { number: 6, text: "İşte sen içtenliği istiyorsun, Gizlide bana bilgelik öğretiyorsun." },
      { number: 7, text: "Mercanköşotuyla arındır beni, paklanayım. Yıkarsan kardan beyaz olurum." },
      { number: 8, text: "Sevinç ve mutluluk sesi duyur bana, Ezilmiş kemikler sevinsin." },
      { number: 9, text: "Yüzünü günahlarımdan gizle, Bütün suçlarımı sil." },
      { number: 10, text: "Pak yürek yarat bende, ey Tanrı, İçimde sağlam bir ruh yenile." },
      { number: 11, text: "Beni huzurundan atma, Kutsal Ruh'unu benden alma." },
      { number: 12, text: "Kurtuluşunun sevincini geri ver bana, İstekli bir ruhla destekle beni." },
      { number: 13, text: "Suçlulara yolunu öğreteceğim, Günahkârlar sana dönecek." },
      { number: 14, text: "Kan dökme suçundan kurtar beni, ey Tanrım, Kurtarıcım! Dilim senin kurtarışını ilahilerle söylesin." },
      { number: 15, text: "Ya Rab, dudaklarımı aç, Ağzım senin övgünü ilan etsin." },
      { number: 16, text: "Kurban istemezsin — isteseydin verirdim. Yakmalık sunudan hoşnut değilsin." },
      { number: 17, text: "Tanrı'nın kabul ettiği kurban: Kırık bir ruh. Kırık ve ezik yüreği, ey Tanrım, hor görmezsin." },
      { number: 18, text: "İyiliğin uğruna Siyon'a lütfet, Yeruşalim'in surlarını onar." },
      { number: 19, text: "O zaman doğru kurbanları, Yakmalık sunuları, tüm sunuları kabul edeceksin. O zaman sunakta boğalar sunulacak sana." },
    ],
  },
  {
    number: 91,
    title: '91. Mezmur',
    verses: [
      { number: 1, text: "Yüce Olan'ın sığınağında oturan, Her Şeye Egemen RAB'bin gölgesinde yaşayan" },
      { number: 2, text: "RAB'be şöyle der: \"Sığınağım, kalem, kurtarıcı Tanrım sensin.\"" },
      { number: 3, text: "O seni tuzaktan, Ölümcül hastalıktan kurtarır." },
      { number: 4, text: "Tüyleriyle seni örter, Kanatlarının altına sığınırsın. O'nun sadakati kalkan ve siperdir." },
      { number: 5, text: "Gece korkusundan, Gündüz uçan oktan," },
      { number: 6, text: "Karanlıkta yayılan hastalıktan, Öğleyin kasıp kavuran salgından korkmayacaksın." },
      { number: 7, text: "Bin kişi yanı başında, On bin kişi sağında düşse bile, Bu bela sana dokunmaz." },
      { number: 8, text: "Yalnız gözlerinle bakacak, Kötülerin cezasını göreceksin." },
      { number: 9, text: "Çünkü \"RAB sığınağım\" dedin, Yüce Olan'ı konut edindin." },
      { number: 10, text: "Başına felaket gelmeyecek, Çadırına veba yaklaşmayacak." },
      { number: 11, text: "Çünkü meleklerine buyruk verecek, Senin için bütün yollarında seni korusunlar diye." },
      { number: 12, text: "Seni elleri üzerinde taşıyacaklar, Ayağın taşa çarpmasın diye." },
      { number: 13, text: "Aslan ve engerek üzerine basacaksın, Genç aslanla yılanı çiğneyeceksin." },
      { number: 14, text: "\"Bana bağlandığı için onu kurtaracağım, Tanıdığım için onu koruyacağım.\"" },
      { number: 15, text: "\"Bana seslenince yanıt vereceğim, Sıkıntıda onunla olacağım. Onu kurtaracağım, onu yücelteceğim.\"" },
      { number: 16, text: "\"Uzun ömürle doyuracağım onu, Kurtuluşumu göstereceğim ona.\"" },
    ],
  },
  {
    number: 100,
    title: '100. Mezmur',
    verses: [
      { number: 1, text: "Bütün yeryüzü, RAB'be sevinç çığlıkları atın!" },
      { number: 2, text: "RAB'be sevinçle kulluk edin, O'nun huzuruna ezgilerle çıkın!" },
      { number: 3, text: "Bilin ki RAB Tanrı'dır. Bizi O yarattı, O'nunuz biz. O'nun halkı, otlağının koyunlarıyız." },
      { number: 4, text: "Kapılarına şükranla girin, Avlularına övgüyle girin. O'na şükredin, adını kutsayın!" },
      { number: 5, text: "Çünkü RAB iyidir, sevgisi sonsuzdur. Sadakati kuşaklar boyu sürer." },
    ],
  },
  {
    number: 103,
    title: '103. Mezmur',
    verses: [
      { number: 1, text: "Ruhum, RAB'bi öv, Bütün iç varlığım, kutsal adını övsün!" },
      { number: 2, text: "Ruhum, RAB'bi öv, O'nun sana yaptığı iyilikleri unutma!" },
      { number: 3, text: "O bütün günahlarını bağışlar, Bütün hastalıklarını iyileştirir." },
      { number: 4, text: "Canını çukurdan kurtarır, Sana sevgi ve şefkat tacı takar." },
      { number: 5, text: "İsteklerini iyiliklerle doyurur, Gençliğin kartal gibi yenilenir." },
      { number: 6, text: "RAB kendi işlerini, İsrail halkına yaptığı doğruluğu yerine getirir." },
      { number: 7, text: "Kendi yollarını Musa'ya, İşlerini İsrail halkına açıkladı." },
      { number: 8, text: "RAB rahmetli ve lütfedicidir, Tez öfkelenmez, sevgisi engindir." },
      { number: 9, text: "Sürekli suçlamaz, Öfkesini sonsuza dek sürdürmez." },
      { number: 10, text: "Suçlarımıza göre davranmadı bize, Günahlarımıza göre karşılık vermedi." },
      { number: 11, text: "Çünkü gök yerden ne kadar yüksekse, O'nun korkusu da O'ndan korkanlar üzerinde o kadar büyüktür." },
      { number: 12, text: "Doğu batıdan ne kadar uzaksa, O da isyanlarımızı bizden o kadar uzaklaştırdı." },
      { number: 13, text: "Baba nasıl çocuklarına acırsa, RAB de O'ndan korkanlara öyle acır." },
      { number: 14, text: "Çünkü O yapımızı bilir, Toprak olduğumuzu anımsar." },
      { number: 15, text: "İnsan ömrü ot gibidir, Çiçek açar gibi açar." },
      { number: 16, text: "Üzerine rüzgar eser, geçer gider, Bulunduğu yeri artık tanımaz." },
      { number: 17, text: "Ama RAB'bin sevgisi O'ndan korkanlara sonsuza dek sürer. Doğruluğu çocuklarının çocuklarına," },
      { number: 18, text: "Antlaşmasını bilenlere, Buyruklarını unutmayanlara ulaşır." },
      { number: 19, text: "RAB tahtını gökte kurdu, Egemenliği her şeye hükmeder." },
      { number: 20, text: "RAB'bi övün, ey melekleri, Güçlü sözünü yerine getiren, O'nun sözünü işiten kullar!" },
      { number: 21, text: "RAB'bi övün, ey O'nun bütün orduları, O'na kulluk eden, O'nun isteğini yapan sizler!" },
      { number: 22, text: "RAB'bi övün, ey O'nun bütün yapıtları, Egemenliğinin her yerinde! Ruhum, RAB'bi öv!" },
    ],
  },
  {
    number: 119,
    title: '119. Mezmur (Alef–He, ilk 32 ayet)',
    verses: [
      { number: 1, text: "Dosdoğru yaşayan, RAB'bin yasasına uyan ne mutludur!" },
      { number: 2, text: "RAB'bin öğütlerine uyan, O'nu bütün yüreğiyle arayan ne mutludur!" },
      { number: 3, text: "Kötülük yapmaz, O'nun yollarında yürürler." },
      { number: 4, text: "Sen buyruklarını çok iyi verdin, Onlara tam uyulsun diye." },
      { number: 5, text: "Keşke yollarım senin kurallarına sıkı sıkıya uysa!" },
      { number: 6, text: "Senin bütün buyruklarına dikkat edersem utandırılmam." },
      { number: 7, text: "Doğru yargılarını öğrenince, Sana içten şükrederim." },
      { number: 8, text: "Kurallarına uyacağım, beni tamamen bırakma!" },
      { number: 9, text: "Genç kişi yolunu nasıl temiz tutar? Senin sözüne göre yaşayarak." },
      { number: 10, text: "Bütün yüreğimle seni aradım, Beni buyruklarından saptırma." },
      { number: 11, text: "Sözünü yüreğimde sakladım, Sana karşı günah işlememek için." },
      { number: 12, text: "Övülesi RAB, kurallarını öğret bana." },
      { number: 13, text: "Dudaklarımla bütün yargılarını anlattım." },
      { number: 14, text: "Öğütlerinin yolunda, Malın her şeyden çok sevindirdi beni." },
      { number: 15, text: "Buyrukların üzerinde derin derin düşüneceğim, Yollarına dikkat edeceğim." },
      { number: 16, text: "Kurallarından zevk alacağım, Sözünü unutmayacağım." },
      { number: 17, text: "Kuluna iyilik et, yaşayayım, Sözüne uyayım." },
      { number: 18, text: "Gözlerimi aç, yasanın harikalarını göreyim." },
      { number: 19, text: "Ben yeryüzünde bir garibim, Buyruklarını benden gizleme." },
      { number: 20, text: "Yargılarına duyduğum özlemle ruhum tükeniyor her an." },
      { number: 21, text: "Sapık küstahları azarladın, Buyruklarından sapanlara lanet yağdırdın." },
      { number: 22, text: "Benden aşağılama ve hor görme kaldır, Çünkü öğütlerine uydum." },
      { number: 23, text: "Önderler bile oturup bana karşı konuştu, Kulun ise kuralların üzerinde derin derin düşünüyor." },
      { number: 24, text: "Öğütlerin benim sevincim, Bana öğüt verenler." },
      { number: 25, text: "Tozda yatıyor canım, Sözünle yaşama kavuştur beni." },
      { number: 26, text: "Yollarımı anlattım, yanıt verdin. Kurallarını öğret bana." },
      { number: 27, text: "Buyruklarının yolunu anlamama izin ver, Harikaların üzerinde derin derin düşüneyim." },
      { number: 28, text: "Ruhum kederden eriyor, Sözünle güçlendir beni." },
      { number: 29, text: "Yalandan yolu benden uzak tut, Lütfen yasanı bana bağışla." },
      { number: 30, text: "Doğruluk yolunu seçtim, Yargılarına bağlı kaldım." },
      { number: 31, text: "Öğütlerine yapıştım, ya RAB, Utanma beni." },
      { number: 32, text: "Buyruklarının yolunda koşacağım, Çünkü yüreğimi genişlettin." },
    ],
  },
  {
    number: 121,
    title: '121. Mezmur',
    verses: [
      { number: 1, text: "Gözlerimi dağlara kaldırıyorum, Yardımım nereden gelecek?" },
      { number: 2, text: "Yardımım gökleri ve yeri yaratan RAB'den gelir." },
      { number: 3, text: "Ayağının kaymasına izin vermez, Seni bekleyen sarsılmaz." },
      { number: 4, text: "İsrail'in bekçisi ne uyur ne uyuklar." },
      { number: 5, text: "RAB senin bekçindir, RAB sağında gölgedir." },
      { number: 6, text: "Gündüz güneş seni yakmaz, Gece ay ışığına çarpmaz." },
      { number: 7, text: "RAB seni her kötülükten korur, Canını korur." },
      { number: 8, text: "Gidişinden gelişine dek RAB seni şimdi ve sonsuza dek korur." },
    ],
  },
  {
    number: 122,
    title: '122. Mezmur',
    verses: [
      { number: 1, text: "\"RAB'bin evine gidelim\" dediklerinde sevindim." },
      { number: 2, text: "Ayaklarımız senin kapılarında, ey Yeruşalim!" },
      { number: 3, text: "Yeruşalim, sen bir kent gibi bir araya getirilmiş kentsin." },
      { number: 4, text: "Oraya oymaklar, RAB'bin oymakları çıkar, İsrail'e şükran sunmak üzere RAB'bin adına." },
      { number: 5, text: "Çünkü yargı kürsüleri orada kurulur, Davut'un evinin kürsüleri." },
      { number: 6, text: "Yeruşalim'in esenliği için dua edin: \"Seni sevenler esenlikte kalsın.\"" },
      { number: 7, text: "Surların içinde esenlik, Kalelerinde güvenlik olsun." },
      { number: 8, text: "Kardeşlerim ve dostlarım uğruna, \"Esenlik olsun sana\" diyeceğim." },
      { number: 9, text: "RAB Tanrımız'ın evi uğruna, Senin iyiliğini dileyeceğim." },
    ],
  },
  {
    number: 130,
    title: '130. Mezmur',
    verses: [
      { number: 1, text: "Derinliklerden sana sesleniyorum, ya RAB." },
      { number: 2, text: "Ya Rab, sesimi işit, Yalvarışlarıma kulak ver." },
      { number: 3, text: "Suçları hesaba katacak olsaydın, ya Rab, Kim dayanırdı?" },
      { number: 4, text: "Ama bağışlama seninle, Böylece senden korkulur." },
      { number: 5, text: "RAB'be umut bağladım, Umudum O'na bağlı." },
      { number: 6, text: "Nöbetçi sabahı beklediğinden çok, Canım Rab'bi bekliyor." },
      { number: 7, text: "Ey İsrail, RAB'be umut bağla! Çünkü RAB'de sevgi, Bol kurtuluş var." },
      { number: 8, text: "İsrail'i bütün suçlarından O kurtaracak." },
    ],
  },
  {
    number: 139,
    title: '139. Mezmur',
    verses: [
      { number: 1, text: "Ya RAB, beni sınadın, tanıdın." },
      { number: 2, text: "Oturup kalkmamı bilirsin, Düşüncemi uzaktan anlarsın." },
      { number: 3, text: "Yolculuğumu ve dinlenmemi yoklarsın, Bütün yollarıma alışkınsın." },
      { number: 4, text: "Dilimden söz daha çıkmadan, Ya RAB, hepsini bilirsin." },
      { number: 5, text: "Önden arkadan kuşatırsın beni, Elini üzerime koyarsın." },
      { number: 6, text: "Bu bilgi bana çok yüce geliyor, Erişemiyorum." },
      { number: 7, text: "Ruhundan nereye kaçabilirim? Huzurundan nereye gidebilirim?" },
      { number: 8, text: "Göklere çıksam, oradasın. Ölüler diyarına yatsam, oradasın." },
      { number: 9, text: "Şafak kanatlarına binsem, Denizin öbür ucuna konsam," },
      { number: 10, text: "Orada bile elin bana rehberlik eder, Sağ elin tutar beni." },
      { number: 11, text: "\"Karanlık beni örtsün\" desem, Gece bile ışık olur çevremde." },
      { number: 12, text: "Karanlık sana karanlık değil, Gece gündüz gibi aydınlık. Karanlık ve aydınlık sana birdir." },
      { number: 13, text: "Çünkü böbreklerimi sen yarattın, Annemin rahminde beni sen dokudun." },
      { number: 14, text: "Sana övgüler sunarım, çünkü müthiş ve harika yaratıldım. Yaptıkların harika, bunu ruhum çok iyi bilir." },
      { number: 15, text: "Kemiklerim senden gizli değildi, Gizlilikte yapıldığımda, Yerin derinliklerinde işlendiğimde." },
      { number: 16, text: "Gözlerin embriyonumu gördü. Hepsi kitaba yazılmıştı, Günler oluşturuldu, hiçbiri yoktu onlardan." },
      { number: 17, text: "Tanrım, düşüncelerin bana ne kadar değerli! Ne kadar çok toplamları!" },
      { number: 18, text: "Saymaya kalksam kumdan çok. Uyansam hâlâ seninleyim." },
      { number: 19, text: "Keşke sen, ey Tanrı, kötüyü öldürsen! Kan dökücüler benden uzak dursun." },
      { number: 20, text: "Çünkü seni düşman bilerek konuşuyorlar, Adını boş yere kullanıyorlar." },
      { number: 21, text: "Senin düşmanlarını senden nefret ediyorum değil mi, ya RAB? Sana başkaldıranlardan tiksinmiyor muyum?" },
      { number: 22, text: "Onlardan tam nefret ediyorum, Düşmanlarım sayıyorum onları." },
      { number: 23, text: "Beni sına, ey Tanrı, yüreğimi bil. Beni yokla, kaygılarımı bil." },
      { number: 24, text: "Bak, bende kötü yol var mı, Bana sonsuz yolda öncülük et." },
    ],
  },
  {
    number: 145,
    title: '145. Mezmur',
    verses: [
      { number: 1, text: "Ey Kral, seni yücelteceğim, Adını sonsuza dek öveceğim." },
      { number: 2, text: "Her gün seni öveceğim, Adını sonsuza dek kutsayacağım." },
      { number: 3, text: "RAB uludur, çok övülmeye layıktır, Büyüklüğü araştırılamaz." },
      { number: 4, text: "Kuşak kuşağa senin işlerini anlatacak, Kudretini bildirecekler." },
      { number: 5, text: "Görkemli yüceliğini, Harika işlerini düşüneceğim." },
      { number: 6, text: "İnsanlar korkunç gücünü söyleyecek, Ben de büyüklüğünü ilan edeceğim." },
      { number: 7, text: "Bolluğunun anısını yayacaklar, Senin doğruluğunu sevinçle haykıracaklar." },
      { number: 8, text: "RAB lütfedicidir, rahmetlidir, Tez öfkelenmez, sevgisi engindir." },
      { number: 9, text: "RAB herkese iyidir, Bütün yaratıklarına şefkatlidir." },
      { number: 10, text: "Bütün yapıtların sana şükredecek, ya RAB, Kutsalların seni kutsayacak." },
      { number: 11, text: "Egemenliğinin görkemini söyleyecekler, Kudretini bildirecekler." },
      { number: 12, text: "İnsanlara senin kudretini, Egemenliğinin görkemli yüceliğini bildirecekler." },
      { number: 13, text: "Egemenliğin sonsuz egemenlik, Hükümranlığın kuşaklar boyu sürer." },
      { number: 14, text: "RAB düşenleri destekler, Eğilenleri doğrultur." },
      { number: 15, text: "Her canlı gözlerini sana diker, Zamanında yiyeceğini verirsin." },
      { number: 16, text: "Elini açarsın, Her canlının isteğini doyurursun." },
      { number: 17, text: "RAB bütün yollarında doğru, Bütün işlerinde sevecendir." },
      { number: 18, text: "RAB kendine yakaran herkese, İçtenlikle kendine yakaran herkese yakındır." },
      { number: 19, text: "O'ndan korkanların isteğini yerine getirir, Feryatlarını işitir, onları kurtarır." },
      { number: 20, text: "RAB kendini seven herkesi korur, Ama kötülerin hepsini yok eder." },
      { number: 21, text: "RAB'bin övgüsü ağzımdan eksik olmasın, Her canlı kutsal adını sonsuza dek kutsasın." },
    ],
  },
  {
    number: 150,
    title: '150. Mezmur',
    verses: [
      { number: 1, text: "RAB'bi övün! Kutsal konutunda O'nu övün, Kudretinin gökkubbesinde övün O'nu!" },
      { number: 2, text: "Güçlü işleri için O'nu övün, Eşsiz büyüklüğüne yaraşır biçimde övün O'nu!" },
      { number: 3, text: "Boru çalarak O'nu övün, Çenk ve lirle övün O'nu!" },
      { number: 4, text: "Tef ve dansla O'nu övün, Saz ve neyle övün O'nu!" },
      { number: 5, text: "Çınlayan zillerle O'nu övün, Yüksek sesli zillerle övün O'nu!" },
      { number: 6, text: "Soluk alan her canlı RAB'bi övsün! RAB'bi övün!" },
    ],
  },
];

export function getPsalmByNumber(n: number): Psalm | undefined {
  return psalms.find((p) => p.number === n);
}

export const psalmNumbers: number[] = psalms.map((p) => p.number);
