/** Romalılar — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
const ROMANS_VERSES = [32, 29, 31, 25, 21, 23, 25, 39, 33, 21, 36, 21, 14, 23, 33, 27];

export const ROMANS_CHAPTER_VERSES: string[][] = [
  // Romalılar 1 (32 ayet)
  [
    "İsa Mesih'in kulu, Tanrı'nın Müjdesi'ni yaymak üzere seçilip elçi olmaya çağrılan ben Pavlus'tan selam!",
    "Tanrı, Oğlu Rabbimiz İsa Mesih'le ilgili bu Müjde'yi peygamberleri aracılığıyla Kutsal Yazılar'da önceden vaat etti.",
    "Rabbimiz İsa Mesih beden açısından Davut'un soyundandır; kutsallık ruhu açısından ise ölümden dirilmekle Tanrı'nın Oğlu olduğu kudretle ilan edildi.",
    "Her ulustan insanın iman edip söz dinlemesini sağlamak için Mesih aracılığıyla ve O'nun adı uğruna Tanrı lütfuna ve elçilik görevine sahip olduk.",
    "İsa Mesih'in çağrılmışları olan sizler de bu uluslardansınız.",
    "Tanrı'nın Roma'da bulunan, kutsal olmaya çağrılan bütün sevdiklerine, Babamız Tanrı'dan ve Rab İsa Mesih'ten size lütuf ve esenlik olsun.",
    "İlkin hepiniz için İsa Mesih aracılığıyla Tanrım'a şükrediyorum. Çünkü imanınız bütün dünyada duyuruluyor.",
    "Oğlu'nun Müjdesi'ni yaymakta bütün varlığımla kulluk ettiğim Tanrı, sizi durmadan, her zaman dualarımda andığıma tanıktır. Tanrı'nın isteğiyle sonunda bir yol bulup yanınıza gelmek için dua ediyorum.",
    "Çünkü ruhça pekişmeniz için size ruhsal bir armağan ulaştırmak üzere sizi görmeyi çok istiyorum.",
    "Yani, ben aranızdayken karşılıklı olarak birbirimizin imanıyla cesaret buluruz demek istiyorum.",
    "Kardeşler, öteki uluslar arasında olduğu gibi, çalışmalarımın sizin aranızda da ürün vermesi için yanınıza gelmeyi birçok kez amaçladığımı, ama şimdiye dek hep engellendiğimi bilmenizi istiyorum.",
    "Grekler'e ve Grek olmayanlara, bilgelere ve bilgisizlere karşı sorumluluğum var.",
    "Bu nedenle Roma'da bulunan sizlere de Müjde'yi elimden geldiğince bildirmek için sabırsızlanıyorum.",
    "Çünkü Müjde'den utanmıyorum. Müjde iman eden herkesin -önce Yahudiler'in, sonra Yahudi olmayanların- kurtuluşu için Tanrı gücüdür.",
    "Tanrı'nın insanı akladığı, Müjde'de açıklanır. Aklanma yalnız imanla olur. Yazılmış olduğu gibi, \"İmanla aklanan yaşayacaktır.\"",
    "Haksızlıkla gerçeğe engel olan insanların bütün tanrısızlığına ve haksızlığına karşı Tanrı'nın gazabı gökten açıkça gösterilmektedir.",
    "Çünkü Tanrı'ya ilişkin bilinen ne varsa, gözlerinin önündedir; Tanrı hepsini gözlerinin önüne sermiştir.",
    "Tanrı'nın görünmeyen nitelikleri -sonsuz gücü ve Tanrılığı- dünya yaratılalı beri O'nun yaptıklarıyla anlaşılmakta, açıkça görülmektedir. Bu nedenle özürleri yoktur.",
    "Tanrı'yı bildikleri halde O'nu Tanrı olarak yüceltmediler, O'na şükretmediler. Tersine, düşüncelerinde budalalığa düştüler; anlayışsız yüreklerini karanlık bürüdü.",
    "Akıllı olduklarını ileri sürerken akılsız olup çıktılar.",
    "Ölümsüz Tanrı'nın yüceliği yerine ölümlü insana, kuşlara, dört ayaklılara, sürüngenlere benzeyen putları yeğlediler.",
    "Bu yüzden Tanrı, birbirlerinin bedenlerini aşağılasınlar diye, onları yüreklerinin tutkuları içinde ahlaksızlığa teslim etti.",
    "Tanrı'yla ilgili gerçeğin yerine yalanı koydular. Yaradan'ın yerine yaratığa tapıp kulluk ettiler. Oysa Tanrı sonsuza dek övülmeye layıktır! Amin.",
    "İşte böylece Tanrı onları utanç verici tutkulara teslim etti. Kadınları bile doğal ilişki yerine doğal olmayanı yeğlediler.",
    "Aynı şekilde erkekler de kadınla doğal ilişkilerini bırakıp birbirleri için şehvetle yanıp tutuştular. Erkekler erkeklerle utanç verici ilişkilere girdiler ve kendi bedenlerinde sapıklıklarına yaraşan karşılığı aldılar.",
    "Tanrı'yı tanımakta yarar görmedikleri için Tanrı onları yararsız düşüncelere, yakışıksız davranışlara teslim etti.",
    "Her türlü haksızlık, kötülük, açgözlülük ve kinle doldular. Kıskançlık, öldürme hırsı, çekişme, hile, kötü niyetle doludurlar.",
    "Dedikoducu, yerici, Tanrı'dan nefret eden, küstah, kibirli, övüngen, kötülük üreten, anne baba sözü dinlemeyen, anlayışsız, sözünde durmaz, sevgiden yoksun, acımasız insanlardır.",
    "Böyle davrananların ölümü hak ettiğine ilişkin Tanrı buyruğunu bildikleri halde, bunları yalnız yapmakla kalmaz, yapanları da onaylarlar.",
    "Bu nedenle Tanrı onları bıraktı.",
    "Onlar Tanrı'yı tanımaya yönelmedikleri için Tanrı da onları yararsız düşüncelere teslim etti; yakışıksız işler yapmaya bıraktı.",
    "Tanrı'nın buyruğuna göre böyle davrananların ölümü hak ettiğini bildikleri halde, bunları yalnız yapmakla kalmaz, yapanları da onaylarlar.",
  ],
  // Romalılar 2 (29 ayet)
  [
    "Bu nedenle sen, ey başkasını yargılayan insan, kim olursan ol, özrün yoktur. Başkasını yargıladığın konuda kendini mahkûm ediyorsun. Çünkü ey yargılayan sen, aynı şeyleri yapıyorsun.",
    "Böyle davrananları Tanrı'nın haklı olarak yargıladığını biliriz.",
    "Bu gibi şeyleri yapanları yargılayan, ama aynısını yapan ey insan, Tanrı'nın yargısından kaçabileceğini mi sanıyorsun?",
    "Tanrı'nın sınırsız iyiliğini, hoşgörüsünü, sabrını hor mu görüyorsun? O'nun iyiliğinin seni tövbeye yönelttiğini bilmiyor musun?",
    "İnatçılığın ve tövbesiz yüreğin yüzünden Tanrı'nın adil yargısının açıklanacağı gazap günü için kendine karşı gazap biriktiriyorsun.",
    "Tanrı \"herkese, yaptıklarının karşılığını verecektir.\"",
    "Sürekli iyilik ederek yücelik, saygınlık, ölümsüzlük arayanlara sonsuz yaşam verecek.",
    "Bencillerin, gerçeğe uymayıp haksızlık peşinden gidenlerin üzerineyse gazap ve öfke yağdıracak.",
    "Kötülük eden herkese -önce Yahudi'ye, sonra Yahudi olmayana- sıkıntı ve elem verecek; iyilik eden herkese -yine önce Yahudi'ye, sonra Yahudi olmayana- yücelik, saygınlık, esenlik verecektir.",
    "Çünkü Tanrı insanlar arasında ayrım yapmaz.",
    "Kutsal Yasa'yı bilmeden günah işleyenler Yasa olmadan da mahvolacaklar. Yasa'yı bilerek günah işleyenlerse Yasa'yla yargılanacaklar.",
    "Çünkü Tanrı katında aklanacak olanlar Yasa'yı işitenler değil, yerine getirenlerdir.",
    "Kutsal Yasa'dan yoksun uluslar Yasa'nın gereklerini kendiliklerinden yaptıkça, Yasa'dan habersiz olsalar bile kendi yasalarını koymuş olurlar.",
    "Böylelikle Kutsal Yasa'nın gerektirdiklerinin yüreklerinde yazılı olduğunu gösterirler. Vicdanları buna tanıklık eder. Düşünceleriyse onları ya suçlar ya da savunur.",
    "Yaydığım Müjde'ye göre Tanrı'nın, insanları gizlice yaptıkları şeylerden ötürü İsa Mesih aracılığıyla yargılayacağı gün böyle olacaktır.",
    "Ya sen? Kendine Yahudi diyor, Kutsal Yasa'ya dayanıp Tanrı'yla övünüyorsun.",
    "Tanrı'nın isteğini biliyorsun. En üstün değerleri ayırt etmeyi Yasa'dan öğrenmişsin.",
    "Kutsal Yasa'da bilginin ve gerçeğin özüne kavuşmuş olarak körlerin kılavuzu, karanlıkta kalanların ışığı, akılsızların eğiticisi, çocukların öğretmeni olduğuna inanmışsın.",
    "Öyleyse başkasına öğretirken, kendine de öğretmez misin? Çalmamayı öğütlerken, çalar mısın?",
    "\"Zina etmeyin\" derken, zina eder misin? Putlardan tiksinirken, tapınakları yağmalar mısın?",
    "Kutsal Yasa'yla övünürken, Yasa'ya karşı gelerek Tanrı'yı aşağılar mısın?",
    "Nitekim şöyle yazılmıştır: \"Sizin yüzünüzden uluslar arasında Tanrı'nın adına küfrediliyor.\"",
    "Kutsal Yasa'yı yerine getirirsen, sünnetin elbet yararı vardır. Ama Yasa'ya karşı gelirsen, sünnetli olmanın hiçbir anlamı kalmaz.",
    "Bu nedenle, sünnetsizler Yasa'nın buyruklarına uyarsa, sünnetli sayılmayacak mı?",
    "Sen Kutsal Yazılar'a ve sünnete sahip olduğun halde Yasa'yı çiğnersen, bedence sünnetli olmayan ama Yasa'ya uyan kişi seni yargılamayacak mı?",
    "Çünkü ne dıştan Yahudi olan gerçek Yahudi'dir, ne de görünüşte, bedensel olan sünnet gerçek sünnettir.",
    "Ancak içten Yahudi olan Yahudi'dir. Sünnet de yürekle ilgilidir; yazılı yasanın değil, Ruh'un işidir. İçten Yahudi olan kişi, insanların değil, Tanrı'nın övgüsünü kazanır.",
    "İnsan övünmesi boştur.",
    "Yasa'yı çiğnersen, sünnetin sünnetsizliğe döner.",
  ],
  // Romalılar 3 (31 ayet) — 1878 uyarlaması
  [
    "O halde Yahudi'nin ne üstünlüğü var? Ya da sünnetin faydası ne?",
    "Elbette her bakımdan çoktur. Öncelikle Tanrı, vahiylerini Yahudilere emanet etti.",
    "Peki, bazı Yahudiler o emanete sadık kalmadıysa onların sadakatsizliği Tanrı'nın sadakatini ortadan kaldırır mı?",
    "Olmaz öyle şey! Bütün insanlar yalancı çıksa bile, bilin ki Tanrı doğruyu söyler. Tanrı hakkında yazılmış olduğu gibi: \"Sen sözlerinle haklı çıkarsın. Seni suçladıkları zaman davayı kazanırsın.\"",
    "Peki, eğer yaptığımız doğru olmayan şeyler Tanrı'nın doğruluğunu gösterirse, ne diyelim? Ben insanların bakış açısından konuşuyorum. Bizi öfkeyle cezalandıran Tanrı haksız mı?",
    "Olmaz öyle şey! Öyle olsa Tanrı dünyayı nasıl yargılayabilir?",
    "Eğer benim yalanımla Tanrı'nın doğruluğu daha belli oluyorsa ve bu Tanrı'yı yüceltiyorsa, nasıl oluyor da, ben hâlâ bir günahkâr olarak yargılanıyorum?",
    "Niçin \"Kötülük yapalım ki bundan iyilik çıksın\" demeyelim? Zaten bazıları bizi tam bunu söylemekle suçluyorlar. Bu iftiradır! Böyle konuşanlar hak ettikleri cezayı alacaklar.",
    "Öyleyse, ne diyelim? Biz Yahudiler diğer milletlerden daha üstün bir durumda mıyız? Elbette hayır! Çünkü ister Yahudi, ister diğer milletlerden olsun, herkesi günaha esir olmakla suçladık.",
    "Yazılmış olduğu gibi: \"Doğru kimse yok, tek kişi bile yok.\"",
    "\"Aklı başında kimse yok, Tanrı'yı izleyen yok.\"",
    "\"Hepsi yoldan saptı, tümü değersiz oldu. İyilik yapan kimse yok, bir kişi bile yok.\"",
    "\"Boğazları açık birer mezardır. Dilleriyle aldatırlar.\" \"Dudaklarından yılan zehri dökülür.\"",
    "\"Ağızları lanet ve acıyla doludur.\"",
    "\"Ayakları kan dökmeye koşar.\"",
    "\"Gittikleri her yerde yıkım ve perişanlık bırakırlar.\"",
    "\"Esenlik yolunu bilmezler.\"",
    "\"Tanrı'dan korkmak onların aklına bile gelmez.\"",
    "Tevrat kanunlarında emredilen her şeyin bu kanunlara uymaya mecbur olan kişilere söylendiğini biliyoruz. Öyle ki her ağız susturulsun ve bütün dünya Tanrı'ya hesap versin.",
    "Çünkü Tevrat kanunlarını yerine getirmekle hiç kimse Tanrı'nın gözünde doğru sayılmayacak. Tevrat kanunları sayesinde günahın ne olduğunu öğreniyoruz.",
    "Ama şimdi kanuna dayanmadan Tanrı'nın insanı nasıl doğru sayabileceği açıklandı. Tevrat ve peygamberler buna şahitlik eder.",
    "Tanrı İsa Mesih'e iman edenleri doğru sayar. Bu, iman eden herkes için geçerlidir. Çünkü Tanrı insanların arasında ayrım yapmaz.",
    "Herkes günah işledi bu yüzden Tanrı'nın yüceliğinden yoksun kalır.",
    "Tanrı hiçbir karşılık beklemeden insanları kendi lütfuyla doğru sayar. Çünkü Mesih İsa onları günaha esir olmaktan kurtarır.",
    "Tanrı O'nu bizim için kurban olarak sundu. Mesih kendi kanını akıtarak iman edenlerin günahlarını bağışlattı. Tanrı böylece doğruluğunu açıkça gösterdi. Çünkü geçmişte hep sabretmiş ve işlenen günahları cezasız bırakmıştı.",
    "Tanrı böyle sabrederek şimdiki zamanda doğruluğunu gösterdi. Neticede hem kendi doğruluğunu korudu, hem de İsa'ya iman edenleri doğru sayabildi.",
    "Öyleyse, insanın övünmesi için sebep var mı? Hiç yok. Bu hangi prensibe dayanır? Tevrat'ın kanunlarını yerine getirmek prensibine mi? Hayır, iman prensibine dayanarak insanın övünmesine sebep yoktur.",
    "Çünkü şu sonuca vardık: Tanrı insanları, Tevrat'taki kanunları yerine getirdikleri için değil, iman ettikleri için doğru sayar.",
    "Yoksa Tanrı sadece Yahudilerin Tanrısı mı? Diğer milletlerin de Tanrısı değil mi? Elbette, diğer milletlerin de Tanrısı'dır.",
    "Mademki Tanrı birdir, O, sünnetli olan Yahudileri iman sayesinde doğru sayacak, sünnetsiz olan diğer milletleri de imanlarıyla doğru sayacak.",
    "Öyleyse, imanla kurtuluruz demekle Tevrat kanunlarını geçersiz mi kılıyoruz? Olmaz öyle şey! Tam tersine, Tevrat'ı daha da geçerli kılıyoruz.",
  ],
  // Romalılar 4 (25 ayet)
  [
    "Öyleyse biz Yahudilerin atası İbrahim'in neye kavuştuğu konusunda ne diyelim?",
    "İbrahim kendi yaptıkları sayesinde doğru sayılmadı. Öyle olsaydı övünmeye hakkı olurdu, ama Tanrı'nın önünde övünemez.",
    "Kutsal Yazı ne diyor? \"İbrahim Tanrı'ya iman etti ve bu ona doğruluk sayıldı.\"",
    "Çalışan adamın aldığı karşılık lütuf sayılmaz, hak sayılır.",
    "Ama bir kişi Tevrat'ın buyurduğu işleri yapmazsa, sadece günahkârları doğru sayan Tanrı'ya iman ederse, o kişi imanı sayesinde doğru sayılır.",
    "Bunun gibi Davud da Tanrı tarafından doğru sayılmayı hak edecek bir şey yapmayan, yine de doğru sayılan insanların mutluluğunu şöyle anlatır:",
    "\"Ne mutlu o kişilere ki, suçları bağışlandı, günahları affedildi.\"",
    "\"Ne mutlu o insana ki, Rab onun günahlarını hesaba katmaz.\"",
    "Peki, bu mutluluk sadece sünnetliler, yani Yahudiler için mi, yoksa aynı zamanda sünnetsiz olan diğer milletler için de mi geçerli? Hani diyoruz ki, İbrahim'in imanı ona doğruluk sayıldı.",
    "İbrahim hangi durumdayken doğru sayıldı? Sünnetliyken mi, sünnetsizken mi? Sünnetliyken değil, sünnetsizken doğru sayıldı.",
    "Evet, İbrahim daha sünnetsizken iman ederek doğru sayılmıştı. Daha sonra sünnet oldu. Sünnet bu doğruluğun işareti ve mührüydü. Öyle ki İbrahim, sünnet olmadan iman eden herkesin babası olsun. Böylece Tanrı onları da doğru saysın.",
    "İbrahim aynı zamanda sünnetlilerin de babasıdır. O sünnetliler ki, sünnetli olmakla kalmayıp, babamız İbrahim'in sünnetsizken sahip olduğu iman yolundan giderler.",
    "Tanrı İbrahim'e ve soyundan gelenlere dünyayı miras alacaklarına vaat etti. Ama Tanrı bu vaadi, Tevrat kanunlarına değil, imandan gelen doğruluğa dayanarak verdi.",
    "Çünkü insan Tevrat kanunlarını yerine getirmekle mirasçı olsaydı, imanın değeri kalmaz ve Tanrı'nın vaadi de geçersiz olurdu.",
    "Tevrat kanunları Tanrı'nın ceza vermesine yol açar. Ama kanunun olmadığı yerde kanun çiğnenemez.",
    "Bunun için Tanrı'nın vaadi imana dayanır. Öyle ki, bu vaat Tanrı'nın lütfuyla İbrahim'in bütün soyu için geçerli olsun. Yalnız İbrahim'in Tevrat'a sahip olan soyu için değil, İbrahim'in imanına sahip olan soyu için de geçerli olsun. Çünkü İbrahim, iman ettiği Tanrı'nın gözünde hepimizin babasıdır.",
    "Aynı yazıldığı gibi: \"Tanrı dedi ki, 'Ben seni birçok milletin babası yaptım.'\" İbrahim'in iman ettiği Tanrı, ölülere yaşam veren ve henüz var olmayan şeyleri var edendir.",
    "İbrahim, umutsuz durumdayken umutla iman etti. Böylece birçok milletin babası oldu. Bu da Tanrı'nın şu sözüne dayanır: \"Senin soyun böyle çok olacak.\"",
    "İbrahim, neredeyse yüz yaşındaydı. Ölüme yaklaşmış bedenini ve karısı Sara'nın kısır rahmini aklına getirdiğinde imanı hiç zayıflamadı.",
    "Tanrı'nın vaadinden şüphelenmedi. İmansızlık etmedi. Tam tersine, imanıyla kuvvetlendi. Tanrı'yı yüceltti.",
    "Tanrı'nın, verdiği sözü yerine getirecek güçte olduğuna tamamen güvendi.",
    "Bu sebeple Tanrı İbrahim'i iman ettiği için doğru saydı.",
    "\"Doğru saydı\" sözü sadece İbrahim için yazılmadı.",
    "Bu söz bizim için de geçerlidir. Rabbimiz İsa'yı ölümden dirilten Tanrı'ya iman ettiğimiz için, Tanrı bizi de doğru sayacak.",
    "İsa suçlarımız için ölüme teslim edildi ve doğru sayılmamız için ölümden diriltildi.",
  ],
  // Romalılar 5 (21 ayet)
  [
    "Böylece, madem imanla doğru sayıldık, Rabbimiz İsa Mesih aracılığıyla Tanrı'yla barışmış oluyoruz.",
    "İman ederek İsa Mesih sayesinde Tanrı'nın lütfuna kavuşma hakkına sahip olduk. Bu lütfa dayanarak ayaktayız ve Tanrı'nın yüceliğine erişmek umuduyla seviniyoruz.",
    "Üstelik sadece bu umutla değil, çektiğimiz sıkıntılarla bile seviniyoruz. Çünkü biliriz ki, sıkıntı bize dayanma gücü verir.",
    "Dayanma gücü de bize değeri kanıtlanmış karakter kazandırır. Kanıtlanmış karaktere sahip olmak bizi umutla doldurur.",
    "Bu umut da bizi utandırmaz, çünkü Tanrı bize verdiği Kutsal Ruh aracılığıyla sevgisini yüreklerimize dökmüştür.",
    "Yani, biz daha çaresizken, Mesih bizim gibi Tanrı'yı saymayan kişiler için tam zamanında öldü.",
    "Dürüst bir insan için ölecek birisi zor bulunur. Yine de belki iyi bir insan için ölmeyi göze alan birisi bulunabilir.",
    "Ama Tanrı bize kendi sevgisini şununla kanıtlıyor: biz daha günahkârken, Mesih bizim için öldü.",
    "İsa'nın kanı sayesinde Tanrı şimdi bizi doğru insanlar olarak kabul ediyor. Bu sebeple İsa aracılığıyla Tanrı'nın öfkesinden kurtulacağımız çok daha kesindir.",
    "Çünkü biz daha Tanrı'ya düşmanken, O'nun Oğlu'nun ölümü sayesinde kendisiyle barıştık. Barıştıktan sonra, Oğlu'nun yaşamı sayesinde kurtulacağımız çok daha kesindir.",
    "Üstelik Rabbimiz İsa Mesih aracılığıyla Tanrı'ya kavuştuğumuz için de seviniyoruz. Mesih sayesinde şimdi Tanrı'yla barıştık.",
    "İşte böyle, günah tek bir adam yüzünden, ölüm de günah yüzünden dünyaya girdi. Böylece ölüm bütün insanlara yayıldı. Çünkü hepsi günah işledi.",
    "Tevrat kanunları verilmeden önce bile dünyada günah vardı. Ama kanunun olmadığı yerde günahların hesabı tutulmaz.",
    "Ne var ki, ölüm Adem'den Musa'nın zamanına kadar herkesin üzerinde hüküm sürdü. Adem'in suçuna benzer bir günah işlememiş olanlar bile ölümün hükmü altındaydı. Adem, bir bakıma, kendisinden sonra gelecek olan Mesih'in örneğidir.",
    "Ancak Tanrı'nın bağışladığı lütuf Adem'in yoldan sapmasına benzemez. Eğer bir adamın yoldan sapması yüzünden birçok insan öldüyse, Tanrı'nın lütfu ve bir adamın, yani İsa Mesih'in lütfuyla verilen bağış, birçok insana daha büyük bollukla ulaştı.",
    "Tanrı'nın bağışı o tek adamın işlediği günahın sonucuna benzemez. Çünkü o tek adamın günahı onun yargılanmasına ve suçlu çıkarılmasına sebep oldu. İnsanlar birçok suç işlediler. Fakat Tanrı, bağışladığı lütufla onları doğru saydı.",
    "Tek bir adamın yoldan sapması yüzünden o tek adamın aracılığıyla ölüm hüküm sürdü. Ama bundan çok daha kesin bir şey var: Tanrı'nın bol lütfunu ve bağışını alan insanlar O'nun tarafından doğru sayıldılar. Bu insanlar, tek adam, yani İsa Mesih sayesinde kavuştukları yaşamda hüküm sürecekler.",
    "Demek ki tek bir günah sonucunda tüm insanlık suçlu çıkarıldı. Aynı bunun gibi tek bir doğru davranış sayesinde tüm insanlığın doğru sayılarak yaşam bulması mümkün oldu.",
    "Bir tek adamın itaatsizliği yüzünden birçok kişi günahkâr kılındı. Aynı bunun gibi bir tek adamın itaati sayesinde birçok kişi doğru kılınacak.",
    "Tevrat kanunları suç çoğalsın diye getirildi. Fakat günahın çoğaldığı yerde Tanrı'nın lütfu daha da çoğaldı.",
    "Böylece günah nasıl herkesin üzerinde hüküm sürdü ve onlara ölüm getirdiyse, şimdi Tanrı'nın lütfu da doğruluk aracılığıyla hüküm sürüyor. Bunun sonucu Rabbimiz İsa Mesih sayesinde sonsuz yaşamdır.",
  ],
  // Romalılar 6 (23 ayet)
  [
    "O halde ne diyelim? Tanrı bizlere daha fazla lütuf göstersin diye günah işlemeye devam mı edelim?",
    "Olmaz öyle şey! Günaha öldük. Artık nasıl günah içinde yaşayabiliriz?",
    "Hepimiz vaftiz olunca Mesih İsa'yla bir olduk; vaftiz olmakla O'nun ölümüne ortak olduk. Yoksa bunu bilmiyor musunuz?",
    "Biz vaftiz edilirken Mesih İsa'yla birlikte ölüp gömüldük. Mesih'in Baba Tanrı'nın görkemli gücüyle ölümden dirildiği gibi biz de yepyeni bir yaşam sürelim.",
    "İsa Mesih'in ölümüne benzer bir ölümde O'nunla birleştik. Buna göre O'nun dirilişinde de O'nunla birleşeceğiz.",
    "Bildiğimiz gibi eski kişiliğimiz Mesih'le birlikte çarmıha gerildi. Öyle ki, günahlı tabiatımız gücünü kaybetsin ve artık günaha esir olmayalım.",
    "Çünkü ölmüş kişi günahın hükmünden kurtulmuştur.",
    "Mesih'le birlikte öldüğümüze göre O'nunla birlikte de yaşayacağımıza inanıyoruz.",
    "Biliyoruz ki, Mesih ölümden dirildi ve bir daha ölmeyecek. Ölümün artık O'nun üzerinde hükmü yok.",
    "Çünkü Mesih ölümüyle günah karşısında ilk ve son defa öldü. Şimdiyse hayatını Tanrı için yaşıyor.",
    "Siz de bunun gibi, kendinizi günah karşısında ölü ve Mesih İsa'ya bağlı olarak Tanrı karşısında diri sayın.",
    "Buna göre günahın ölümlü bedeninizde hüküm sürmesine izin vermeyin, bedenin heveslerine uymayın.",
    "Bedeninizin hiçbir yerini kötülük yapan alet olarak günaha teslim etmeyin. Tam tersine, ölümden yaşama geçmiş olanlar olarak, kendinizi Tanrı'ya teslim edin. Bedeninizin her yerini doğru olanı yapan alet olarak Tanrı'ya adayın.",
    "Günah efendiniz olmasın. Çünkü herhangi bir kanuna değil, Tanrı'nın lütfuna bağlısınız.",
    "Bunun için ne diyelim? Herhangi bir kanuna değil, Tanrı'nın lütfuna bağlı olduğumuza göre günah mı işleyelim? Olmaz öyle şey!",
    "Bilmiyor musunuz ki, kime kendinizi köle olarak teslim edip itaat ederseniz, onun kölesi olursunuz? Ya günahın ya da itaatin kölesi olursunuz. Günah sizi ölüme, itaat ise doğruluğa götürür.",
    "Eskiden günahın kölesiydiniz. Ama Tanrı'ya şükürler olsun, size emanet edilen öğretilerin tamamına yürekten bağlandınız.",
    "Günahtan özgür kılınıp doğruluğun kölesi oldunuz.",
    "İnsan tabiatınız zayıf olduğu için günlük yaşamdan örnek veriyorum. Eskiden bedeninizi köle olarak rezil davranışlara ve kötülük yapmak için kötülüğe teslim ederdiniz. Tıpkı bunun gibi, şimdi bedeninizi doğruluğa köle olarak teslim edin ki, Tanrı'ya adanmış insanlar olasınız.",
    "Eskiden günahın kölesiyken doğru olanı yapmaya mecbur değildiniz.",
    "Şimdi utanç duyduğunuz o şeyleri yapmakla ne elde ettiniz? Onların sonucu ölümdür.",
    "Ama şimdi günaha köle olmaktan kurtuldunuz ve Tanrı'ya köle oldunuz. Bundan kazancınız Tanrı'ya adanmışlık ve sonucu sonsuz yaşamdır.",
    "Çünkü günahın bedeli ölümdür, ama Tanrı'nın bağışı Rabbimiz Mesih İsa sayesinde sonsuz yaşamdır.",
  ],
  // Romalılar 7-16: gerçek "Yeni Çeviri" metni henüz eklenmedi.
  // Telifli bir çeviri olduğu için doğrulanmamış bir kaynaktan kopyalanmadı.
  ...ROMANS_VERSES.slice(6).map((_, i) => [
    `Romalılar ${i + 7}. bölümün metni bu sürümde henüz eklenmedi.`,
  ]),
];
