/** 1. Selanikliler — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const THESSALONIANS1_CHAPTER_VERSES: string[][] = [
  // 1. Selanikliler 1 (10 ayet)
  [
    "Pavlus, Silvanus ve Timoteos'tan Baba Tanrı'ya ve Rab İsa Mesih'e ait olan Selanik kilisesine selam! Sizlere lütuf ve esenlik olsun.",
    "Dualarımızda sizleri anıyor, her zaman hepiniz için Tanrı'ya şükrediyoruz.",
    "İmanın ürünü olan etkinliğinizi, sevgiye dayanan emeğinizi ve Rabbimiz İsa Mesih'e bağladığınız umuttan kaynaklanan dayanıklılığınızı Babamız Tanrı'nın önünde durmadan anıyoruz.",
    "Tanrı'nın sevdiği kardeşlerim, sizleri O'nun seçtiğini biliyoruz.",
    "Çünkü yaydığımız Müjde size yalnız sözle değil, kudretle, Kutsal Ruh'la ve büyük güvenle ulaştı. Nitekim aranızdayken sizin yararınıza nasıl yaşadığımızı bilirsiniz.",
    "Siz de büyük sıkıntılara karşın, Kutsal Ruh'un verdiği sevinçle Tanrı sözünü kabul ederek bizi ve Rab'bi örnek aldınız.",
    "Böylece Makedonya ve Ahaya'daki bütün imanlılara örnek oldunuz.",
    "Rab'bin sözü sizden yayıldı. Tanrı'ya imanınızın haberi yalnız Makedonya ve Ahaya'ya değil, her yere ulaştı. Artık bizim bir şey söylememize gerek kalmadı.",
    "Çünkü herkes bizi ne kadar iyi karşıladığınızı anlatıp duruyor.",
    "Yaşayan gerçek Tanrı'ya kulluk etmek, O'nun ölümden dirilttiği ve bizleri gelecek gazaptan kurtaran Oğlu İsa'nın göklerden gelişini beklemek üzere putlardan Tanrı'ya nasıl döndüğünüzü anlatıyorlar.",
  ],
  // 1. Selanikliler 2 (20 ayet)
  [
    "Kardeşler, sizin yanınıza gelişimizin boşuna olmadığını kendiniz de bilirsiniz.",
    "Daha önce Filipi'de gördüğünüz gibi sıkıntı ve hakaretlere uğradığımız halde, Tanrımızın yardımıyla Müjde'yi büyük cesaretle size ilettik.",
    "Çağrımız yanıltmadan, pislikten ve hileden kaynaklanmıyor.",
    "Tanrı tarafından Müjde'yi emanet almaya layık görüldüğümüz için insanları değil, bizi sınayan Tanrı'yı hoşnut etmeye çalışıyoruz.",
    "Bildiğiniz gibi, ne zaman pohpohlayıcı sözler kullandık ne de açgözlülük maskesi taktık - Tanrı buna tanıktır.",
    "İnsanlardan övgü beklemedik; ne sizden ne de başkalarından.",
    "Mesih'in elçileri olarak ağırlığımızı hissettirebilirdik. Ama sizin aranızda çocukların annesi gibi nazik davrandık.",
    "Sizi öyle çok özledik ki, kendi canımızı bile vermeye hazırdık. Çünkü siz bize sevgili oldunuz.",
    "Kardeşler, emeğimizi ve uğraşımızı anımsayın. Gece gündüz çalışarak hiçbirinize yük olmamak için Müjde'yi size duyurduk.",
    "Siz de tanıksınız, Tanrı'ya inananlara nasıl kutsal, doğru ve kusursuz davrandığımıza.",
    "Baba gibi her birinize kendi çocuklarınız gibi öğüt verdik, sizi yüreklendirdik.",
    "Yaşamı uğruna kendini feda eden Rab'be yaraşır biçimde yaşamanız için size çağrıda bulunduk.",
    "Bu nedenle Tanrı'nın sözünü bizden işittiğinizde bunu insan sözü olarak değil, gerçekte ne olduğu gibi, Tanrı'nın sözü olarak kabul etmeniz için sürekli şükrediyoruz. Bu söz siz imanlılarda da etkin.",
    "Kardeşler, siz Yahudiye'de Mesih İsa'ya ait olan kiliselere benzeyenler oldunuz. Onlar da Yahudilerden sizin gibi sıkıntı çektiler.",
    "Yahudiler hem Rab İsa'yı hem peygamberleri öldürdüler, bizi de kovdular. Tanrı'yı hoşnut etmiyorlar, bütün insanlara düşman.",
    "Öteki ulusların günahlarına kavuşmaları için sözü onlardan esirgiyorlar. Ama Tanrı'nın gazabı sonunda onlara ulaştı.",
    "Kardeşler, kısa bir süre sizden ayrı kaldık; yüzümüzle değil, yüreğimizle. Sizi tekrar görmek için büyük istek duyduk.",
    "Bu yüzden -ben Pavlus- bir iki kez gelmek istedim, ama İblis bizi engelledi.",
    "Çünkü umudumuz, övüncümüz, övünç kaynağımız kim? Rab İsa gelince O'nun önünde siz değil misiniz?",
    "Evet, siz bizim övüncümüz ve sevincimizsiniz.",
  ],
  // 1. Selanikliler 3 (13 ayet)
  [
    "Bu yüzden daha fazla dayanamayıp Atina'da tek başımıza kalmayı yeğledik.",
    "Ve Rab İsa'da emektaşımız, Tanrı'nın Müjdesi'nde Mesih uğruna hizmet eden sevgili kardeşimiz Timoteos'u size gönderdik. İmandaki sarsılmazlığınız konusunda sizi yüreklendirip güçlendirmek için.",
    "Öyle ki, bu sıkıntılarda hiç kimse sarsılmasın. Sizin de sıkıntı çekeceğinizi biliyorsunuz.",
    "Çünkü yanınızdayken size, sıkıntı çekeceğimizi önceden söylemiştik. Nitekim öyle oldu, biliyorsunuz.",
    "Bu nedenle ben de artık dayanamayıp imanınızı öğrenmek için gönderdim. Ayartıcı sizi ayartmış ve emeğimiz boşa gitmiş olmasın diye.",
    "Şimdi Timoteos sizin yanınızdan dönüp bize imanınız ve sevginizle ilgili iyi haber getirdi. Bizi her zaman iyi anımsadığınızı, gelmek için nasıl özlediğinizi anlattı.",
    "Kardeşler, bu sıkıntılarımız içinde sizin yüzünüzden sizdeki iman sayesinde teselli bulduk.",
    "Çünkü siz Rab'de dimdik duruyorsanız, şimdi yaşıyoruz.",
    "Tanrımızın önünde sizin yüzünüzden duyduğumuz bütün sevinç için O'na nasıl şükretmemiz gerekir?",
    "Gece gündüz O'ndan yürekten sizi tekrar görmeyi ve imanınızdaki eksikleri tamamlamayı diliyoruz.",
    "Rabbimiz İsa kendisi ve bizimle birlikte Baba Tanrı bize kavuşma yolunu açsın.",
    "Rab sizi birbirinize ve herkese beslediğiniz sevgide üstün kılsın, bizim sizi sevdiğimiz gibi.",
    "Öyle ki, Rabbimiz İsa kendi kutsallarıyla birlikte geldiğinde Baba Tanrı'nın önünde kutsallığınızda kusursuz ve pak olasınız.",
  ],
  // 1. Selanikliler 4 (18 ayet)
  [
    "Sonuç olarak kardeşler, Rab İsa'da size nasıl yaşamanız gerektiğini öğrettik; siz de öyle yaşıyorsunuz. Rab'be daha çok yaraşır biçimde yaşamanız için sizi Rab adına yalvarıp yüreklendiriyoruz.",
    "Çünkü hangi buyrukları size ilettiğimizi biliyorsunuz.",
    "Tanrı'nın isteği şudur: Kutsal olmanız, fuhştan kaçınmanız,",
    "her birinizin kendi karısına kutsal ve saygılı biçimde sahip olması,",
    "putperestler gibi şehvet tutkusuyla değil.",
    "Bu konuda kimse kardeşine haksızlık etmesin ya da onu aldatmasın. Rab bütün bu suçların öcünü alır. Daha önce size söyledik, ciddi uyardık.",
    "Çünkü Tanrı bizi pisliğe değil, kutsal yaşama çağırdı.",
    "Dolayısıyla bu buyruğu reddeden kişi insanı değil, size Kutsal Ruh'unu veren Tanrı'yı reddeder.",
    "Kardeşler arasındaki sevgi konusunda size yazmaya gerek yok. Çünkü Tanrı size birbirinizi sevmeyi öğretti.",
    "Makedonya'daki bütün kardeşlere zaten bunu yapıyorsunuz. Kardeşler, sizi buna daha da çok özendiriyoruz.",
    "Sakin bir yaşam sürmeye, kendi işinizle uğraşmaya, ellerinizle çalışmaya özen gösterin. Daha önce size buyurduğumuz gibi.",
    "Öteki insanlara bağımlı olmadan saygın biçimde yaşamanız için.",
    "Kardeşler, ölenler konusunda bilgisiz kalmanızı istemiyoruz. Umutsuzlukta öbür umuttan yoksun insanlar gibi olmayasınız.",
    "İsa'nın ölüp dirildiğine inanıyoruz. Aynı şekilde Tanrı, İsa'ya bağlı olarak gözleri kapalı olanları da O'nunla birlikte getirecektir.",
    "Rab'bin sözüne dayanarak size diyoruz: Biz yaşayanlar, Rab'bin gelişine kadar hayatta kalanlar, gözleri kapalı olanların önüne geçmeyeceğiz.",
    "Rab kendisi bir buyrukla, başmeleğin sesiyle ve Tanrı'nın borazanıyla gökten inecek. Önce Mesih'e ait ölüler dirilecek.",
    "Sonra biz yaşayanlar, hayatta kalanlar, onlarla birlikte bulutlar içinde Rab'bi karşılamak üzere havada alınacağız. Böylece her zaman Rab'le birlikte olacağız.",
    "Bu sözlerle birbirinizi yüreklendirin.",
  ],
  // 1. Selanikliler 5 (28 ayet)
  [
    "Kardeşler, o günler ve saatler konusunda size yazmaya gerek yok.",
    "Çünkü Rab'bin günü gece hırsız gibi geleceğini kendiniz çok iyi biliyorsunuz.",
    "İnsanlar «Esenlik ve güvenlik» dedikleri anda ansızın yıkım gelir; tıpkı doğum sancısı gibi. Ve kaçış olmaz.",
    "Ama siz kardeşler karanlıkta değilsiniz ki o gün sizi hırsız gibi yakalasın.",
    "Hepiniz ışık çocukları, gündüz çocuklarısınız. Geceye ya da karanlığa ait değiliz.",
    "Öyleyse öbürleri gibi uyumayalım. Uyanık ve ayık olalım.",
    "Uyuyanlar gece uyur, sarhoşlar gece sarhoş olur.",
    "Ama biz gündüze ait olduğumuz için ayık olalım. İman ve sevgi zırhını kuşanıp kurtuluş umudunu miğfer gibi başımıza geçirelim.",
    "Çünkü Tanrı bizi gazaba değil, Rabbimiz İsa Mesih aracılığıyla kurtuluşa kavuşmaya belirledi.",
    "O bizim için öldü ki, ister uyanık ister uykuda olalım, O'nunla birlikte yaşayalım.",
    "Bu nedenle şimdi yaptığınız gibi birbirinizi yüreklendirip birbirinizi geliştirin.",
    "Kardeşler, sizden rica ediyoruz: Aranızda çalışanları, Rab'be önderlik edenleri, size öğüt verenleri saygıyla tanıyın.",
    "Onları sevgide en üst derecede sayın. Esenlik içinde olun.",
    "Kardeşler, sizi yüreklendiriyoruz: Düzensizleri uyarın, cesareti kırılanları yüreklendirin, güçsüzlere yardım edin, herkese sabırlı olun.",
    "Sakın kimse kötülüğe kötülükle karşılık vermesin. Tersine, birbiriniz ve herkes için her zaman iyiyi amaçlayın.",
    "Her zaman sevinin.",
    "Sürekli dua edin.",
    "Her durumda şükredin. Çünkü Tanrı'nın Mesih İsa'da sizin için istediği budur.",
    "Ruh'u söndürmeyin.",
    "Peygamberlikleri küçümsemeyin.",
    "Her şeyi sınayın, iyi olana sımsıkı sarılın.",
    "Her türlü kötülükten kaçının.",
    "Esenlik veren Tanrı'nın kendisi sizi tümüyle kutsal kılsın. Ruhunuz, canınız ve bedeniniz Rabbimiz İsa Mesih'in gelişinde kusursuz ve eksiksiz korusun.",
    "Sizi çağıran güvenilirdir; bunu yapacaktır.",
    "Kardeşler, bizim için dua edin.",
    "Kutsal öpüşle bütün kardeşlere selam söyleyin.",
    "Rab adına size buyuruyorum: Bu mektup bütün kardeşlere okunsun.",
    "Rabbimiz İsa Mesih'in lütfu sizinle birlikte olsun.",
  ],
];
