/** 2. Selanikliler — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const THESSALONIANS2_CHAPTER_VERSES: string[][] = [
  // 2. Selanikliler 1 (12 ayet)
  [
    "Pavlus, Silvanus ve Timoteos'tan Baba Tanrı'ya ve Rab İsa Mesih'e ait olan Selanik'teki kiliseye selam!",
    "Babamız Tanrı'dan ve Rab İsa Mesih'ten sizlere lütuf ve esenlik olsun.",
    "Kardeşler, her zaman sizin için Tanrı'ya şükretmemiz gerekir. Bu çok yerinde. Çünkü imanınız fazlasıyla gelişiyor, hepinizin birbirinize sevgisi artıyor.",
    "Öyle ki, Tanrı'nın kiliseleri arasında sizin yüzünüzden kendimizle övünüyoruz. Sizin sıkıntılarınıza ve zulme karşı sabrınız sayesinde.",
    "Bu, Tanrı'nın adil yargısının kanıtıdır. Öyle ki, O'nun egemenliğine layık sayılasınız. Sizin de çektiğiniz sıkıntılara katlanıyorsunuz.",
    "Tanrı adildir. Sıkıntı çekenlere sıkıntıyla karşılık verecek.",
    "Sıkıntı çeken sizlere de bizimle birlikte rahatlık verecek. Rab İsa güçlü melekleriyle ateş alevi içinde gökten göründüğü zaman.",
    "Tanrı'yı tanımayanlara ve Rabbimiz İsa'nın Müjdesi'ne uymayanlara ceza verecek.",
    "Böyleleri Rab'bin huzurundan ve yüce gücünün yüceliğinden uzak kalacak.",
    "O gün Rab gelecek ve kutsallarında yüceltilecek, inanmış olan herkeste hayranlık uyandıracak. Çünkü size ilettiğimiz tanıklığa siz inandınız.",
    "Bunun için sürekli sizin için dua ediyoruz. Tanrımız sizi bu çağrıya layık saysın, iyiliğe olan her isteğinizi ve iman uğrundaki her çabanızı gücüyle tamamlasın.",
    "Öyle ki, Rabbimiz İsa'nın adı sizde yüceltilsin, siz de O'nda -Tanrımızın lütfuna göre Rabbimiz İsa Mesih'le- yüceltilesiniz.",
  ],
  // 2. Selanikliler 2 (17 ayet)
  [
    "Kardeşler, Rabbimiz İsa Mesih'in gelişi ve O'nun önünde toplanmamız konusunda size yalvarıyoruz:",
    "Rab'bin günü gelmiş sayılmadan, birinin yanıltıcı bir şekilde sizi sarsmaması için -ne ruh, ne söz, ne de bizden gelmiş gibi görünen bir mektupla- hemen heyecana kapılmayın.",
    "Kimse sizi hiçbir şekilde aldatmasın. Çünkü o gün gelmeden önce sapıklık gelecek ve mahvolan o kişi, yani yasalara karşı gelip kendini her şeyin Tanrısı'nın üzerinde gösteren adam ortaya çıkacak.",
    "O, tapınağa oturup kendini Tanrı ilan edecek.",
    "Yanınızdayken size bunları söylediğimi anımsamıyor musunuz?",
    "Şimdi onu tutan gücü biliyorsunuz. Öyle ki, kendi zamanında ortaya çıksın.",
    "Aslında yasalara aykırılık gücü şimdiden etkindir. Ama onu şimdi tutan ortadan kalkınca,",
    "o zaman yasalara aykırı kişi ortaya çıkacak. Rab İsa O'nu ağzının nefesiyle öldürecek ve gelişinin görkemiyle yok edecek.",
    "Yasalara aykırı kişinin gelişi Şeytan'ın etkisiyle olacak. Her türlü sahte güç, belirti ve şaşırtıcı işaret,",
    "ve mahvolanların aldandığı her türlü haksızlıkla gelecek. Çünkü gerçeği sevip kurtulmayı kabul etmediler.",
    "Bu yüzden Tanrı onlara yanıltıcı bir güç gönderiyor. Öyle ki, yalana inansınlar.",
    "Böylece gerçeğe inanmayan, haksızlıktan zevk alan hepsi yargılansın.",
    "Rab'bi seven siz kardeşlere gelince, sizin için sürekli şükretmemiz gerekir. Çünkü Tanrı başlangıçtan sizi kurtuluşla ve Kutsal Ruh'un kutsal kılmasıyla seçti.",
    "Buna Müjde'mize imanla ulaştınız. Öyle ki, Rabbimiz İsa Mesih'in yüceliğine kavuşasınız.",
    "Bu nedenle kardeşler, dimdik durun. Öğrettiğimiz sözlere -ister sözle ister mektupla- sımsıkı sarılın.",
    "Rabbimiz İsa Mesih ve bizi seven Baba Tanrı, lütfuyla bize sonsuz teselli ve güzel umut bağışlamıştır.",
    "Yüreklerinizi güçlendirsin, her iyi sözde ve işte sizi sağlam kılsın.",
  ],
  // 2. Selanikliler 3 (18 ayet)
  [
    "Sonuç olarak kardeşler, Rabbimiz İsa Mesih adına size yalvarıyoruz: Öğrettiğimiz uygun yaşayışa uygun yaşayın. Sizi daha da buna özendirin.",
    "Biliyorsunuz, Rabbimiz İsa Mesih'in hangi buyrukları verdiğini.",
    "Rab güvenilirdir. Sizi güçlendirecek ve kötü olandan koruyacaktır.",
    "Rab'de sizde güvenimiz var. Verdiğimiz buyrukları şimdi yapıyor, ileride de yapacaksınız.",
    "Rab yüreklerinizi Tanrı sevgisine ve Mesih'in sabrına yöneltsin.",
    "Kardeşler, Rabbimiz İsa Mesih adına size buyuruyoruz: Düzensiz yaşayan, öğretimize uymayan her kardeşten uzak durun.",
    "Kendiniz nasıl bizi örnek almanız gerektiğini biliyorsunuz. Aranızda düzensiz davranmadık.",
    "Kimsenin ekmeğini bedavadan yemedik. Tersine, gece gündüz emek vererek, hiçbirinize yük olmamak için çalıştık.",
    "Yetkimiz olmadığı halde size Müjde'yi duyurduk. Tersine, size yük olmamak için çalıştık.",
    "İnananlar arasında düzensiz yaşayan, işle uğraşmayan, boş işlerle meşgul olanlara gelince - onlara böyle davranmalarını buyuruyoruz.",
    "Çünkü yanınızdayken onlara şunu buyurmuştuk: Kim çalışmak istemezse yemek de yemesin.",
    "Bazılarının aranızda düzensiz yaşadığını, hiçbir iş yapmadığını, boş işlerle uğraştığını duyuyoruz.",
    "Böylelerini Rab İsa Mesih adına uyarıyoruz: Sakin bir yaşam sürsünler, kendi ekmeğini yesinler.",
    "Siz kardeşler, iyi olanı yapmakta yorulmayın.",
    "Bu mektuptaki buyruğa uymayan birini not edin. Onunla arkadaşlık etmeyin ki utansın.",
    "Yine de onu düşman saymayın, kardeş olarak uyarın.",
    "Rab esenliğin kendisi size her zaman her yönden esenlik versin. Rab hepinizle birlikte olsun.",
    "Ben Pavlus bu selamı kendi elimle yazıyorum. Tüm mektuplarımda böyle yazarım. İşte benim yazım.",
    "Rabbimiz İsa Mesih'in lütfu hepinizle birlikte olsun.",
  ],
];
