/** 2. Timoteos — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const TIMOTHY2_CHAPTER_VERSES: string[][] = [
  // 2. Timoteos 1 (18 ayet)
  [
    "Tanrı'nın isteğiyle Mesih İsa'nın elçisi atanan ben Pavlus'tan, Mesih İsa'daki yaşam vaadi uyarınca sevgili oğlum Timoteos'a selam!",
    "Baba Tanrı'dan ve Rabbimiz Mesih İsa'dan sana lütuf, merhamet ve esenlik olsun.",
    "Atalarım gibi pak bir vicdanla sürekli hizmet ettiğim Tanrı'ya şükrediyorum. Dualarımda gece gündüz seni anıyorum.",
    "Gözyaşlarını anımsayarak seni tekrar görmek için büyük özlem duyuyorum. Öyle ki sevincim dolsun.",
    "İlk atan annen Loide'de ve büyük annen Yuniya'da olan içten imanı anımsıyorum. Aynı imanın senin de içinde olduğuna eminim.",
    "Bu nedenle sana hatırlatıyorum: Tanrı'nın ellerini senin üzerine koymasıyla sana verilen armağanı alevlendir.",
    "Çünkü Tanrı bize korkaklık ruhu değil, güç, sevgi ve özdenetim ruhu verdi.",
    "Bu nedenle Rabbimizin tanıklığından ya da benim O'nun tutuklusu olduğumdan utanma. Tersine Tanrı'nın gücüyle Müjde uğruna benimle birlikte sıkıntıya katlan.",
    "Bizi kurtaran ve kutsal çağrıyla çağıran Tanrı kendi yaptıklarına ya da yapacaklarımıza göre değil, kendi amacına ve bize Mesih İsa'da zamanın başlangıcından önce verilen lütfa göre yaptı.",
    "Bu lütuf şimdi Kurtarıcımız Mesih İsa'nın gelişiyle açığa çıktı. O ölümü yok etti, Müjde aracılığıyla yaşamı ve ölümsüzlüğü ışığa çıkardı.",
    "Bunun için ben sahte sözlü, Müjdeci ve elçi atandım.",
    "Bu nedenle bu sıkıntılara katlanıyorum. Ama utanmıyorum. Çünkü kime inandığımı biliyorum. O'nun o güne dek koruyabileceğine güveniyorum.",
    "Senden işittiğin sağlam sözlere iman ve sevgiyle Mesih İsa'da örnek al. Pak yürekle bana emanet edilen iyi emaneti koru.",
    "Asiya'dakilerin hepsi benden ayrıldı. Fijellus ile Hermogenes bunlardandır.",
    "Rabbimiz onun ev halkına merhamet etsin. Çünkü sık sık yüreğimi ferahlattı, zincire vuruluşumdan utanmadı.",
    "Roma'da olduğunda bana yan gözle baktı, gelmek için büyük istek duydu.",
    "Ama gelince ne kadar yararlı olduğunu göreceksin.",
    "Efes'te bıraktığım kötülükleri biliyorsun.",
  ],
  // 2. Timoteos 2 (26 ayet)
  [
    "Oğlum, Mesih İsa'da olan lütfle güçlen.",
    "Birçok tanık önünde benden işittiğin sözleri güvenilir kişilere emanet et. Onlar da başkalarına öğretsin.",
    "İsa Mesih'in iyi askeri olarak benimle birlikte sıkıntıya katlan.",
    "Askerlik yapan kişi günlük yaşamın işlerine karışmaz. Öyle ki komutanını hoşnut etsin.",
    "Yarışan kişi kurallara uymadan yarışırsa çelenk almaz.",
    "Emeği geçen çiftçi ürününden önce pay almalıdır.",
    "Söylediklerimi düşün. Rab her konuda anlayış verecektir.",
    "Rabbimiz İsa Mesih'i anımsa. O Davut'un soyundandır, ölümden dirildi. İşte benim Müjde'm budur.",
    "Bunun uğruna suçlu gibi zincire vurulana dek sıkıntı çekiyorum. Ama Tanrı'nın sözü zincire vurulmadı.",
    "Bu yüzden seçilmişler uğruna her şeye katlanıyorum. Öyle ki onlar da Mesih İsa'da kurtuluşa, sonsuz yüceliğe kavuşsunlar.",
    "Şu söz güvenilirdir: O'nunla birlikte öldüysek, O'nunla birlikte yaşayacağız.",
    "Dayanırsak O'nunla birlikte egemenlik süreceğiz. O'nu yadsırsak O da bizi yadsıyacak.",
    "Biz sadık kalmasak da O sadık kalır. Çünkü kendini yadsıyamaz.",
    "Bunları onlara hatırlat. Tanrı'nın önünde tartışmaya girmemelerini buyur. Yararsızdır, dinleyenleri mahveder.",
    "Tanrı yolunda kendini onaylı sunmaya özen göster. Utanılacak bir şey yapmayan, gerçeğin sözünü doğru kullanan işçi gibi.",
    "Kutsalsız boş sözlerden kaçın. Çünkü bunlar tanrı yolunda giderek daha da kötüleşir.",
    "Sözleri kangren gibi yayılır. Himeneos ile Filetos bunlardandır.",
    "Gerçekle ilgili olarak sapıtmışlardır. Dirilişin zaten olup bittiğini söylüyorlar. Böylece bazılarının imanını sarsıyorlar.",
    "Ama Tanrı'nın sağlam temeli duruyor. Şu mühür taşır: «Rab kendininkileri bilir» ve «Rab'bin adını anan herkes kötülükten uzak dursun.»",
    "Büyük bir evde yalnız altın ve gümüş kaplar yok; tahta ve toprak kaplar da vardır. Kimi onur, kimi rezillik için.",
    "Bunun için kişi kendini bunlardan arındırırsa onur için kullanılan, kutsal, efendisine yararlı, her iyi işe hazır bir kap olur.",
    "Gençlik tutkularından kaç. Doğruluk, iman, sevgi ve esenlik peşinde koşan, pak yürekle Rab'be yakaranlarla birlikte ol.",
    "Anlamsız, budalaca tartışmalara girme. Bunlar kavga doğurduğunu bilirsin.",
    "Rab'bin kulu kavga etmemeli. Tersine herkese yumuşak, öğretmeye yeten, kötüye sabırlı olmalı.",
    "Yumuşaklıkla karşı çıkanları eğitmeli. Belki Tanrı onlara tövbe nasip eder de gerçeği tanırlar.",
    "Böylece ayartıcının tuzağından kurtulup O'nun isteğiyle yakalanırlar.",
  ],
  // 2. Timoteos 3 (17 ayet)
  [
    "Şunu bil ki, son günlerde çetin anlar olacaktır.",
    "İnsanlar kendilerini seven, para düşkünü, övüngen, kibirli, küfürbaz, anne baba sözü dinlemez, nankör,",
    "kutsallıktan ve sevgiden yoksun, uzlaşmaz, iftiracı, özünü denetleyemeyen, azgın, iyilik düşmanı olacaklar.",
    "Hain, aceleci, kendini beğenmiş, Tanrı'dan çok eğlenceyi seven,",
    "Tanrı yolundaymış gibi görünüp bu yolun gücünü inkâr edenler olacaklar. Böylelerinden uzak dur.",
    "Bunların arasında evlerin içine sokulup günahla yüklü, çeşitli arzularla sürüklenen,",
    "her zaman öğrenen, ama gerçeğin bilgisine bir türlü erişemeyen zayıf iradeli kadınları adeta tutsak eden adamlar var.",
    "Yannis'le Yambris nasıl Musa'ya karşı geldilerse, bunlar da gerçeğe karşı gelirler. Düşünceleri yozlaşmış, iman konusunda reddedilmiş insanlardır.",
    "Ama daha ileri gidemeyecekler. Çünkü Yannis'le Yambris örneğindeki gibi, bunların da akılsızlığını herkes açıkça görecektir.",
    "Sense benim öğretimi, davranışımı, amacımı, imanımı, sabrımı, sevgimi, dayanma gücümü, çektiğim zulüm ve acıları, örneğin Antakya'da, Konya'da ve Listra'da başıma gelenleri yakından izledin.",
    "Ne zulümlere katlandım! Ama Rab beni hepsinden kurtardı.",
    "Mesih İsa'ya ait olup Tanrı yoluna yaraşır bir yaşam sürmek isteyenlerin hepsi zulüm görecek.",
    "Ama kötüler ve sahtekârlar, aldatarak ve aldanarak gittikçe daha beter olacaklar.",
    "Sense öğrendiğin ve güvendiğin ilkelere bağlı kal. Çünkü bunları kimlerden öğrendiğini biliyorsun.",
    "Mesih İsa'ya iman aracılığıyla seni bilge kılıp kurtuluşa kavuşturacak güçte olan Kutsal Yazılar'ı da çocukluğundan beri biliyorsun.",
    "Kutsal Yazılar'ın tümü Tanrı esinlemesidir ve öğretmek, azarlamak, yola getirmek, doğruluk konusunda eğitmek için yararlıdır.",
    "Bunlar sayesinde Tanrı adamı her iyi iş için donatılmış olarak yetkin olur.",
  ],
  // 2. Timoteos 4 (22 ayet)
  [
    "Tanrı'nın ve dirilerle ölüleri yargılayacak olan Mesih İsa'nın önünde, O'nun gelişi ve egemenliği hakkı için sana buyuruyorum:",
    "Tanrı sözünü duyur. Zaman uygun olsun olmasın, bu görevi sürdür. İnsanları tam bir sabırla eğiterek ikna et, uyar, isteklendir.",
    "Çünkü öyle bir zaman gelecek ki, sağlam öğretiye katlanamayacaklar. Kulaklarını okşayan sözler duymak için çevrelerine kendi arzularına uygun öğretmenler toplayacaklar.",
    "Kulaklarını gerçeğe tıkayıp masallara sapacaklar.",
    "Ama sen her durumda ayık ol, sıkıntıya göğüs ger, müjdeci olarak işini yap, görevini tamamla.",
    "Çünkü kanım adak şarabı gibi dökülmek üzere. Benim için ayrılma zamanı geldi.",
    "Yüce mücadeleyi sürdürdüm, yarışı bitirdim, imanı korudum.",
    "Bundan böyle doğruluk tacı benim için hazır duruyor. Adil yargıç olan Rab o gün bu tacı bana, yalnız bana değil, O'nun gelişini özlemle beklemiş olanların hepsine verecektir.",
    "Yanıma tez gelmeye gayret et.",
    "Çünkü Dimas bu dünyayı sevdiği için beni terk edip Selanik'e gitti. Kriskis Galatya'ya, Titus Dalmaçya'ya gitti.",
    "Yanımda yalnız Luka var. Markos'u alıp beraberinde getir, yapacağım hizmette bana yardım eder.",
    "Tihikos'u Efes'e gönderdim.",
    "Troas'ta Karp'ın yanında bıraktığım abayı, kitapları, özellikle yazı derilerini gelirken beraberinde getir.",
    "Bakırcı İskender bana çok kötülük etti. Rab ona yaptıklarının karşılığını verecektir.",
    "Sen de ondan sakın. Çünkü söylediklerimize şiddetle karşı koydu.",
    "İlk savunmamda benden yana çıkan olmadı, hepsi beni terk etti. Bunun hesabı onlardan sorulmasın.",
    "Ama Tanrı bildirisi aracılığımla tam olarak açıklansın, bütün uluslar bunu duysun diye Rab yardımıma gelip beni güçlendirdi. Aslanın ağzından böyle kurtuldum!",
    "Rab beni her kötülükten kurtarıp güvenlik içinde göksel egemenliğine ulaştıracak. Sonsuzlara dek O'na yücelik olsun! Amin.",
    "Priska, Akvila ve Onisiforos'un ev halkına selam söyle.",
    "Erastus, Korint'te kaldı. Trofimos'u da Milet'te hasta bıraktım.",
    "Kış bastırmadan gelmeye gayret et. Evvulus, Pudens, Linus, Klavdiya ve bütün kardeşler sana selam ederler.",
    "Rab ruhunla birlikte olsun. Tanrı'nın lütfu sizlerle olsun.",
  ],
];
