/** 1. Timoteos — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const TIMOTHY1_CHAPTER_VERSES: string[][] = [
  // 1. Timoteos 1 (20 ayet)
  [
    "Kurtarıcımız Tanrı'nın ve umudumuz Mesih İsa'nın buyruğuyla Mesih İsa'nın elçisi atanan ben Pavlus'tan selam!",
    "Ortak imanımıza göre gerçek oğlum Timoteos'a Baba Tanrı'dan ve Mesih İsa Rabbimiz'den lütuf, merhamet ve esenlik olsun.",
    "Makedonya'ya giderken sana rica ettiğim gibi, Efes'te kalıp bazı kişilerin farklı öğretiler yaymamasını sağla.",
    "Masallara, bitmeyen soyağaçlarına dikkat etmesinler. Bunlar tartışmalara yol açar; Tanrı'nın imanla yürüttüğü plana hizmet etmez.",
    "Buyruğun amacı, pak yürekten, temiz vicdandan ve içten imandan doğan sevgidir.",
    "Bazıları bunlardan sapıp boş konuşmalara saptılar.",
    "Kutsal Yasa öğretmeni olmak istiyorlar; ama ne söylediklerini ne de üzerinde bu kadar ısrar ettikleri konuları anlıyorlar.",
    "Kutsal Yasa iyi kullanılırsa iyidir.",
    "Şunu bilmeliyiz: Yasa doğru insan için değil, yasasız ve asi olanlar, tanrısız ve günahkârlar, kutsal olmayan ve dünyevi olanlar, anne babasını öldürenler, katiller,",
    "fuhuş yapanlar, erkeklerle yatanlar, insan kaçıranlar, yalancılar, yalan yere ant içenler ve sağlam öğretiye aykırı başka her şey için konulmuştur.",
    "Müjde, yüce Tanrı'nın, bana emanet ettiği yüce Müjde'ye uygundur.",
    "Rabbimiz Mesih İsa'ya, bana güç veren Tanrı'ya şükrediyorum. Beni hizmete layık sayıp görevlendirdi.",
    "Daha önce küfürbaz, zorba ve hakaretçiydim. Ama merhamet gördüm. Çünkü bilmeden, imansızken yaptım bunları.",
    "Rabbimizin lütfu, Mesih İsa'da iman ve sevgiyle birlikte bol bol üzerime yağdı.",
    "Sözü güvenilir ve her kabulü hak eden şudur: Mesih İsa, günahkârları kurtarmak için dünyaya geldi. Onların en başında da ben geliyorum.",
    "Ama bu yüzden merhamet gördüm. Önce bende bütün sabrı sergileyerek, sonsuz yaşama inananlara örnek olsun diye Mesih İsa bana sabır gösterdi.",
    "Sonsuzların Kralı'na -soluk, görünmez, tek Tanrı'ya- saygı ve yücelik sonsuzlara dek olsun! Amin.",
    "Timoteos oğlum, sana şu buyruğu veriyorum: Önceki peygamberlikler uyarınca senin için yapılan iyi savaşımı sürdür.",
    "İmanı ve temiz vicdanı reddeden bazı kişiler gemi batırdı.",
    "Bunlardan Himeneos ile İskender'dir. Gerçeği reddetmek üzere onları Şeytan'a teslim ettim. Böylece küfretmeyi bırakmayı öğrensinler.",
  ],
  // 1. Timoteos 2 (15 ayet)
  [
    "Her şeyden önce şunu öğütlüyorum: Dilekler, dualar, yakarışlar ve şükürler bütün insanlar için sunulsun.",
    "Krallar ve bütün üst yetkililer için de. Öyle ki, sakin ve huzurlu bir yaşam sürelim; bu, Tanrı yolunda saygılı ve ağırbaşlı olmamız içindir.",
    "Bu iyi ve Kurtarıcımız Tanrı'nın önünde kabul görendir.",
    "O bütün insanların kurtulmasını ve gerçeğin bilgisine ulaşmasını ister.",
    "Çünkü tek Tanrı ve Tanrı ile insanlar arasında tek Aracı vardır. O da insan olan ve kendini herkes için fidye olarak sunan Mesih İsa'dır.",
    "Uygun zamanda buna tanıklık edildi.",
    "Bunun için ben sahte sözlü, imanlı ve gerçekte doğru sözlü olarak atandım. Uluslara Müjde'yi öğretmek için.",
    "Erkeklerin öfke ve çekişme olmadan, pak yürekle her yerde dua etmelerini isterim.",
    "Kadınlar da sade giyinsin. Uygun ve utanç verici olmayan bir biçimde, saç örmesi, altın, inci ya da pahalı giysilerle değil.",
    "İyi işlerle süslenmiş, Tanrı'ya yakışan kadınlar olsun.",
    "Kadın sakinlik ve tam bağımlılıkla öğrensin.",
    "Kadının öğretmesine ya da erkeğe egemen olmasına izin vermiyorum. Sakin olsun.",
    "Çünkü önce Adem, sonra Havva yaratıldı.",
    "Adem aldatılmadı, ama kadın aldatıldı ve suça düştü.",
    "Ama çocuk doğurursa, iman, sevgi ve kutsallıkla kendini denetleyerek kurtulacaktır.",
  ],
  // 1. Timoteos 3 (16 ayet)
  [
    "Güvenilir söz şudur: Gözetmen olmak isteyen kişi iyi bir işe göz dikmiş olur.",
    "Gözetmen eleştirilecek yönü olmayan, tek karılı, ölçülü, sağduyulu, saygın, konuksever, öğretmeye yeten biri olmalı.",
    "Şarap düşkünü, zorba olmamalı. Tersine uysal, kavga etmeyen, paraya düşkün olmayan biri olmalı.",
    "Kendi evini iyi yönetmeli, çocuklarını söz dinler ve her yönden saygılı yetiştirmeli.",
    "Kendi evini yönetmeyi bilmeyen, Tanrı'nın topluluğuna nasıl bakar?",
    "Yeni iman etmiş olmamalı. Sonra gurura kapılıp İblis gibi yargılanabilir.",
    "Dışarıdakilerden de iyi bir tanıklığı olmalı. Sonra aşağılanıp İblis'in tuzağına düşer.",
    "Görevliler de aynı şekilde saygın, iki sözlü olmayan, çok şarap içmeyen, haksız kazanç peşinde koşmayan kişiler olmalı.",
    "Temiz vicdanla imanın sırrına sımsıkı sarılmalılar.",
    "Bunlar önce sınansın; kusursuzlarsa görevlilik yapsınlar.",
    "Kadınlar da aynı şekilde saygın, iftiracı değil, ölçülü, her konuda güvenilir olmalı.",
    "Görevli tek karılı olsun. Çocukları ve kendi evini iyi yönetsin.",
    "Görevlilik iyi yapanlar iyi bir düzey ve Mesih İsa'ya olan imanda büyük cesaret kazanırlar.",
    "Bunları sana yazıyorum. Yakında yanına gelmeyi umuyorum.",
    "Ama gelirsem, Tanrı'nın evinde nasıl davranmak gerektiğini bilirsin. O ev yaşayan Tanrı'nın topluluğu, gerçeğin direği ve temelidir.",
    "Açıkça bilinen sır, tanrılık açısından büyüktür: Bedende görünendi, Ruh'ta aklanmıştır, meleklere göründü, uluslara duyuruldu, dünyada iman edildi, yücelikte alındı.",
  ],
  // 1. Timoteos 4 (16 ayet)
  [
    "Ruh açıkça diyor ki: Son zamanlarda bazıları aldatarak, cinlerin öğretilerine kulak vererek imandan dönecek.",
    "Yalan söyleyenlerin kendi vicdanları mühürlüdür.",
    "Evliliği yasaklayan, bazı yiyeceklerden kaçınmayı buyuran kişiler çıkacak. Oysa Tanrı bunları, inanan ve gerçeği bilenlerin şükrederek yemesi için yarattı.",
    "Çünkü Tanrı'nın yarattığı her şey iyidir. Şükürle kabul edilirse reddedilecek hiçbir şey yoktur.",
    "Tanrı'nın sözü ve duayla kutsanır.",
    "Bunları kardeşlere hatırlatırsan, Mesih İsa'nın iyi bir hizmetkârı olursun. İman ve senin izlediğin iyi öğretiyle beslenmiş olursun.",
    "Kutsalsız, bayağı masallardan kaçın. Tanrı yolunda kendini eğit.",
    "Beden eğitimi az yarar sağlar; ama tanrı yolunda eğitim her şeyde yarar sağlar. Çünkü hem bu yaşamda hem gelecekte vaat vardır.",
    "Bu söz güvenilirdir ve her kabulü hak eder.",
    "Bunun için emek veriyoruz, uğraşıyoruz. Çünkü umudumuzu yaşayan Tanrı'ya bağladık. O bütün insanların, özellikle iman edenlerin Kurtarıcısı'dır.",
    "Bunları buyur ve öğret.",
    "Genç yaşta olduğun için kimse seni küçümsemesin. Sözde, davranışta, sevgide, imanda, paklıkta inanlılara örnek ol.",
    "Okuma, öğüt ve öğretiye verilene dek yanına gelene kadar kendini buna ver.",
    "Sana verilen, peygamberlikle ve ihtiyarların ellerini senin üzerine koymasıyla iletilen armağanı ihmal etme.",
    "Bunları düşün, böylece ilerlemen herkese açık olsun.",
    "Kendine ve öğretine dikkat et. Bunda sür. Çünkü böyle yaparak hem kendini hem de seni dinleyenleri kurtaracaksın.",
  ],
  // 1. Timoteos 5 (25 ayet)
  [
    "Yaşlı bir erkeği azarlama. Tersine baba gibi yüreklendir. Genç erkeklere kardeş gibi,",
    "yaşlı kadınlara anne gibi, genç kadınlara tam paklıkla kızkardeş gibi davran.",
    "Dul bırakılan gerçek dullara saygı göster.",
    "Ama dulun çocukları ya da torunları varsa, önce kendi evlerinde ailelerine yardım etmeyi öğrensinler. Çünkü bu Tanrı'nın önünde kabul görendir.",
    "Gerçek dul ve yalnız kalan, umudunu Tanrı'ya bağlamış olup gece gündüz dilek ve dualarla O'na yönelir.",
    "Buna karşılık zevk düşkünü dul yaşarken ölmüş sayılır.",
    "Bunları buyur ki kusursuz olsunlar.",
    "Ailesinin, özellikle ev halkının gözetimini yapmayan kişi imanı yadsımış olur. İman etmemiş olandan beterdir.",
    "Listeye ancak altmış yaşından fazla, tek kocası olmuş bir dul yazılsın.",
    "İyi işlerle tanınmış olmalı: Çocukları büyütmüş, konukları ağırlamış, kutsalların ayaklarını yıkamış, sıkıntıda olanlara yardım etmiş, her iyi işe özen göstermiş olmalı.",
    "Genç dulları listeye alma. Çünkü Mesih'e bağlılıktan ayrılıp zevk düşkünü olunca evlenmek isterler.",
    "Böylece ilk imanı reddetmiş olurlar.",
    "Ayrıca tembel olmayı öğrenir, ev ev dolaşırlar. Yalnız tembel değil, geveze ve işe karışan da olurlar. Söylemem gerekeni söylememeliyim.",
    "Genç dullar evlensin, çocuk doğursun, evi yönetsin. Karşı tarafa sövgü fırsatı verilmesin.",
    "Bazıları zaten sapıtarak Şeytan'ın ardına düştü.",
    "İmanlı bir kadının yanında dul akrabası varsa ona yardım etsin. Kilise yük olmasın. Gerçek dullara kilise yardım etsin.",
    "İyi yöneten ihtiyarlar, özellikle söz ve öğretide emek verenler iki kat saygıya layık sayılsın.",
    "Çünkü Kutsal Yazı diyor ki: «Harman döven öküzün ağzını bağlama» ve «İşçi ücretini hak eder.»",
    "İhtiyara yönelik bir suçlama, iki üç tanık olmadan kabul edilmesin.",
    "Suçlayanları herkesin önünde uyar ki ötekiler de korksun.",
    "Tanrı'nın, Mesih İsa'nın ve seçilmiş meleklerin önünde, ön yargıya kapılmadan, bir şey yapmada taraf tutmadan bu kurallara uymanı buyuruyorum.",
    "Kimsenin elini hemen koyma. Başkalarının günahlarına ortak olma. Kendini pak tut.",
    "Artık suya değil, midenin rahatı için biraz şaraba yönel. Sık sık hastalanıyorsun.",
    "Bazı insanların günahları açıktır, yargıya götürür. Bazılarınınki de sonra ortaya çıkar.",
    "İyi işler de öyle. Gizli olanlar gizli kalamaz.",
  ],
  // 1. Timoteos 6 (21 ayet)
  [
    "Boyunduruk altındaki köleler kendi efendilerini her yönden saygıya layık saysın. Öyle ki Tanrı'ya ve öğretimize küfür edilmesin.",
    "İmanlı efendileri olanlar, kardeş oldukları için onları küçümsemesin. Tersine daha iyi hizmet etsinler. Çünkü yararlananlar sevgili inanlılardır. Bunları öğret ve yüreklendir.",
    "Biri farklı bir öğreti yayar, sağlam sözlere -Rabbimiz Mesih İsa'nın sözlerine- ve tanrı yolundaki öğretiye ulaşmazsa,",
    "kibirli, hiçbir şey bilmeyen biri olmuştur. Tartışmalara, söz dalaşına hastalıktır. Bunlardan kıskançlık, kavga, küfür, kötü kuşkular doğar.",
    "Zihni bozuk, gerçekten yoksun, tanrı yolunu kazanç sayan kişilerin sürekli çekişmesi doğar. Böyle düşünmek yıkımdır.",
    "Oysa tanrı yolunda büyük kazanç, yetinmektir.",
    "Dünyaya hiçbir şey getirmedik; götürecek de bir şeyimiz yok.",
    "Yiyeceğimiz ve giyeceğimiz varsa bunlarla yetinelim.",
    "Zengin olmak isteyenler ayartıya, tuzağa, insanları yıkıma götüren birçok budalaca ve zararlı isteğe düşer.",
    "Para sevgisi her kötülüğün köküdür. Kimi buna kapılıp imandan saptı, kendini birçok acıyla delik deşik etti.",
    "Sen ise ey Tanrı adamı, bunlardan kaçın. Doğruluk, tanrı yolunda yaşam, iman, sevgi, dayanıklılık ve yumuşak huyluluk peşinde koş.",
    "İman uğruna iyi savaşımı sürdür. Sonsuz yaşama kavuş. Bunun için çağrıldın ve birçok tanık önünde iyi tanıklık ettin.",
    "Yaşamı her şeyde var eden Tanrı'nın ve Pontius Pilatus önünde iyi tanıklık etmiş olan Mesih İsa'nın önünde sana buyuruyorum:",
    "Buyruğu kusursuz, lekesiz, Rabbimiz İsa Mesih'in görünümüne dek sür.",
    "Bunu uygun zamanda mutlu ve tek olan Egemen, Kralların Kralı, Rablerin Rabbi gösterecek.",
    "O tek ölümsüz, erişilmez ışıkta yaşar. O'nu hiçbir insan görmedi, göremez. O'na saygı ve sonsuz egemenlik olsun! Amin.",
    "Bu dünyada zengin olanlara böbürlenmemelerini, gelip geçici zenginliğe umut bağlamamalarını buyur. Tersine bize her şeyi bol bol sunan Tanrı'ya umut bağlasınlar.",
    "İyilik yapmaları, iyilikte zenginleşmeleri, cömert ve paylaşmaya istekli olmaları için.",
    "Böylece gelecek çağ için kendilerine sağlam temel biriktirerek gerçek yaşama kavuşsunlar.",
    "Ey Timoteos, sana emanet edileni koru. Kutsalsız boş sözlerden, sahte adı «bilgi» olan karşıt savlardan kaçın.",
    "Bunu savunan bazı kişiler imandan saptı. Tanrı'nın lütfu sizinle birlikte olsun.",
  ],
];
