/** 2. Timoteos — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const TIMOTHY2_CHAPTER_VERSES: string[][] = [
  // 2. Timoteos 1 (18 ayet)
  [
    "Tanrı'nın isteğiyle Mesih İsa'nın elçisi atanan ben Pavlus'tan, Mesih İsa'daki yaşam vaadi uyarınca sevgili oğlum Timoteos'a selam!",
    "Baba Tanrı'dan ve Rabbimiz Mesih İsa'dan sana lütuf, merhamet ve esenlik olsun.",
    "Atalarım gibi pak bir vicdanla sürekli hizmet ettiğim Tanrı'ya şükrediyorum. Dualarımda gece gündüz seni anıyorum.",
    "Gözyaşlarını anımsayarak seni tekrar görmek için büyük özlem duyuyorum. Öyle ki sevincim dolsun.",
    "İlk atan annen Loide'de ve büyük annen Yuniya'da olan içten imanı anımsıyorum. Aynı imanın senin de içinde olduğuna eminim.",
    "Bu nedenle sana hatırlatıyorum: Tanrı'nın ellerini senin üzerine koymasıyla sana verilen armağanı alevlendir.",
    "Çünkü Tanrı bize korkaklık ruhu değil, güç, sevgi ve özdenetim ruhu verdi.",
    "Bu nedenle Rabbimizin tanıklığından ya da benim O'nun tutuklusu olduğumdan utanma. Tersine Tanrı'nın gücüyle Müjde uğruna benimle birlikte sıkıntıya katlan.",
    "Bizi kurtaran ve kutsal çağrıyla çağıran Tanrı kendi yaptıklarına ya da yapacaklarımıza göre değil, kendi amacına ve bize Mesih İsa'da zamanın başlangıcından önce verilen lütfa göre yaptı.",
    "Bu lütuf şimdi Kurtarıcımız Mesih İsa'nın gelişiyle açığa çıktı. O ölümü yok etti, Müjde aracılığıyla yaşamı ve ölümsüzlüğü ışığa çıkardı.",
    "Bunun için ben sahte sözlü, Müjdeci ve elçi atandım.",
    "Bu nedenle bu sıkıntılara katlanıyorum. Ama utanmıyorum. Çünkü kime inandığımı biliyorum. O'nun o güne dek koruyabileceğine güveniyorum.",
    "Senden işittiğin sağlam sözlere iman ve sevgiyle Mesih İsa'da örnek al. Pak yürekle bana emanet edilen iyi emaneti koru.",
    "Asiya'dakilerin hepsi benden ayrıldı. Fijellus ile Hermogenes bunlardandır.",
    "Rabbimiz onun ev halkına merhamet etsin. Çünkü sık sık yüreğimi ferahlattı, zincire vuruluşumdan utanmadı.",
    "Roma'da olduğunda bana yan gözle baktı, gelmek için büyük istek duydu.",
    "Ama gelince ne kadar yararlı olduğunu göreceksin.",
    "Efes'te bıraktığım kötülükleri biliyorsun.",
  ],
  // 2. Timoteos 2 (26 ayet)
  [
    "Oğlum, Mesih İsa'da olan lütfle güçlen.",
    "Birçok tanık önünde benden işittiğin sözleri güvenilir kişilere emanet et. Onlar da başkalarına öğretsin.",
    "İsa Mesih'in iyi askeri olarak benimle birlikte sıkıntıya katlan.",
    "Askerlik yapan kişi günlük yaşamın işlerine karışmaz. Öyle ki komutanını hoşnut etsin.",
    "Yarışan kişi kurallara uymadan yarışırsa çelenk almaz.",
    "Emeği geçen çiftçi ürününden önce pay almalıdır.",
    "Söylediklerimi düşün. Rab her konuda anlayış verecektir.",
    "Rabbimiz İsa Mesih'i anımsa. O Davut'un soyundandır, ölümden dirildi. İşte benim Müjde'm budur.",
    "Bunun uğruna suçlu gibi zincire vurulana dek sıkıntı çekiyorum. Ama Tanrı'nın sözü zincire vurulmadı.",
    "Bu yüzden seçilmişler uğruna her şeye katlanıyorum. Öyle ki onlar da Mesih İsa'da kurtuluşa, sonsuz yüceliğe kavuşsunlar.",
    "Şu söz güvenilirdir: O'nunla birlikte öldüysek, O'nunla birlikte yaşayacağız.",
    "Dayanırsak O'nunla birlikte egemenlik süreceğiz. O'nu yadsırsak O da bizi yadsıyacak.",
    "Biz sadık kalmasak da O sadık kalır. Çünkü kendini yadsıyamaz.",
    "Bunları onlara hatırlat. Tanrı'nın önünde tartışmaya girmemelerini buyur. Yararsızdır, dinleyenleri mahveder.",
    "Tanrı yolunda kendini onaylı sunmaya özen göster. Utanılacak bir şey yapmayan, gerçeğin sözünü doğru kullanan işçi gibi.",
    "Kutsalsız boş sözlerden kaçın. Çünkü bunlar tanrı yolunda giderek daha da kötüleşir.",
    "Sözleri kangren gibi yayılır. Himeneos ile Filetos bunlardandır.",
    "Gerçekle ilgili olarak sapıtmışlardır. Dirilişin zaten olup bittiğini söylüyorlar. Böylece bazılarının imanını sarsıyorlar.",
    "Ama Tanrı'nın sağlam temeli duruyor. Şu mühür taşır: «Rab kendininkileri bilir» ve «Rab'bin adını anan herkes kötülükten uzak dursun.»",
    "Büyük bir evde yalnız altın ve gümüş kaplar yok; tahta ve toprak kaplar da vardır. Kimi onur, kimi rezillik için.",
    "Bunun için kişi kendini bunlardan arındırırsa onur için kullanılan, kutsal, efendisine yararlı, her iyi işe hazır bir kap olur.",
    "Gençlik tutkularından kaç. Doğruluk, iman, sevgi ve esenlik peşinde koşan, pak yürekle Rab'be yakaranlarla birlikte ol.",
    "Anlamsız, budalaca tartışmalara girme. Bunlar kavga doğurduğunu bilirsin.",
    "Rab'bin kulu kavga etmemeli. Tersine herkese yumuşak, öğretmeye yeten, kötüye sabırlı olmalı.",
    "Yumuşaklıkla karşı çıkanları eğitmeli. Belki Tanrı onlara tövbe nasip eder de gerçeği tanırlar.",
    "Böylece ayartıcının tuzağından kurtulup O'nun isteğiyle yakalanırlar.",
  ],
  // 2. Timoteos 3 (17 ayet)
  [
    "Şunu bil: Son günlerde zorlu anlar gelecek.",
    "İnsanlar kendini seven, parayı seven, övüngen, kibirli, küfürbaz, anne babaya söz dinlemeyen, nankör, kutsal olmayan,",
    "sevgisiz, uzlaşmaz, iftiracı, ölçüsüz, sert, iyilik düşmanı,",
    "hain, pervasız, kendini beğenmiş, Tanrı'dan çok zevke düşkün olacak.",
    "Görünüşte tanrı yolunda ama gücünü yadsıyacaklar. Bunlardan uzak dur.",
    "Bunların arasında evlere sızan, günah yüklü, her türlü tutkuya sürüklenen, her an öğrenen ama gerçeğin bilgisine hiç ulaşamayan kadınların peşine takılan kişiler vardır.",
    "Yannes ile Yambres Musa'ya nasıl karşı geldiyse bunlar da gerçeğe öyle karşı geliyor. Zihinleri bozuk, iman konusunda reddedilmişler.",
    "Ama bunlar daha ileri gidemeyecek. Çünkü budalalıkları herkese açık olacak, o iki kişininki gibi.",
    "Ama sen öğretimime, davranışıma, amacıma, imanıma, sabrıma, sevgime, dayanıklılığıma,",
    "Antakya, İkonium, Listra'da çektiğim sıkıntılara katlandın. Ne sıkıntılar çektim! Ama Rab beni hepsinden kurtardı.",
    "İsa Mesih'te tanrı yolunda yaşamak isteyenlerin hepsi zulüm görecek.",
    "Kötü kişilerle aldatanlar da giderek kötüleşecek. Aldatıp aldatılacaklar.",
    "Ama sen öğrendiğin ve güvendiğin konularda sür. Kimlerden öğrendiğini biliyorsun.",
    "Çocukluğundan beri Kutsal Yazıları biliyorsun. Mesih İsa'da iman aracılığıyla kurtuluş sağlayan bilgelik onlardadır.",
    "Kutsal Yazıların tümü Tanrı esinlemesidir. Öğretmek, azarlamak, düzeltmek, tanrı yolunda eğitmek için yararlıdır.",
    "Öyle ki Tanrı adamı her iyi iş için donatılmış olsun.",
  ],
  // 2. Timoteos 4 (22 ayet)
  [
    "Tanrı'nın önünde ve dirilerle ölüleri yargılayacak Mesih İsa'nın önünde, O'nun görünümü ve egemenliği uğruna sana buyuruyorum:",
    "Sözü duyur. Uygun ya da uygunsuz zamanda hazır ol. Sabırla, tüm öğretiyle yüreklendirerek düzelt, uyar.",
    "Çünkü sağlam öğretiye kulak vermeyecek, kendi tutkularına uygun öğretmenler toplayacak bir zaman gelecek. Kulaklarını gerçekten kapayacaklar.",
    "Kendilerini masallara verecekler. Ama sen her konuda ayık ol, sıkıntıya katlan, Müjdeci işini yap, hizmetini tamamla.",
    "Ben artık sunu olarak dökülüyorum. Ayrılma zamanım geldi.",
    "İyi savaşımı savaştım, yarışı bitirdim, imanı korudum.",
    "Bundan böyle doğruluk tacı benim için hazır. O gün Rab -adil Yargıç- bana onu verecek. Yalnız bana değil, O'nun görünümünü özleyenlerin hepsine.",
    "Elimden geldiğince yanıma gel.",
    "Çünkü Dimas bu dünyayı sevdiği için beni bırakıp Selanik'e gitti. Kreskes Galatya'ya, Titus Dalmaçya'ya gitti.",
    "Yanımda yalnız Luka var. Markos'u alıp yanına getir. Çünkü hizmetimde bana yararlıdır.",
    "Tihikos'u Efes'e gönderdim.",
    "Troas'ta Karpus'ta bıraktığım paltoyu getirirken gel. Ayrıca kitapları, özellikle deri tomar olanları getir.",
    "Bakır işçisi Aleksandros bana çok kötülük etti. Rab yaptıklarının karşılığını ona verecektir.",
    "Sen de ondan sakın. Çünkü öğretimize büyük ölçüde karşı geldi.",
    "İlk savunmamda yanımda kimse yoktu. Hepsi beni bıraktı. Bunun onlara sayılmasın.",
    "Ama Rab yanımda durdu, güç verdi. Öyle ki Müjde aracılığımda duyuru tamamlansın, bütün uluslar işitsin. Aslanın ağzından kurtuldum.",
    "Rab beni her kötü işten kurtaracak, göksel egemenliğe kavuşturacaktır. O'na sonsuzlara dek yücelik olsun! Amin.",
    "Priska ile Akvila'ya ve Onesiforus'un ev halkına selam söyle.",
    "Efes'te birçok kez yüreğimi ferahlattı. Zincire vuruluşumdan utanmadı.",
    "Roma'da olduğunda bana yan gözle baktı, gelmek için büyük istek duydu.",
    "Erastus Korint'te kaldı. Trofimus'u Milet'te hasta bıraktım.",
    "Kış gelmeden yanıma gel.",
    "Evbulus, Pudens, Linus, Klavdiya ve bütün kardeşler sana selam eder.",
    "Rabbimiz İsa Mesih lütfu ruhunla birlikte olsun. Tanrı'nın lütfu sizinle birlikte olsun.",
  ],
];
