/** Titus — Türkçe Kutsal Kitap (Yeni Çeviri) ayet metinleri */
export const TITUS_CHAPTER_VERSES: string[][] = [
  // Titus 1 (16 ayet)
  [
    "Tanrı'nın seçtiği kişilerin iman etmeleri, Tanrı yoluna uygun gerçeği anlamaları için Tanrı'nın kulu ve İsa Mesih'in elçisi atanan ben Pavlus'tan selam!",
    "Elçiliğim, yalan söylemeyen Tanrı'nın zamanın başlangıcından önce vaat ettiği sonsuz yaşam umuduna dayanmaktadır.",
    "Kurtarıcımız Tanrı'nın buyruğuyla bana emanet edilen bildiride Tanrı, kendi sözünü uygun zamanda açıklamıştır.",
    "Ortak imanımıza göre öz oğlum olan Titus'a Baba Tanrı'dan ve Kurtarıcımız Mesih İsa'dan lütuf ve esenlik olsun.",
    "Geri kalan işleri düzene sokman ve sana buyurduğum gibi her kentte ihtiyarlar ataman için seni Girit'te bıraktım.",
    "İhtiyar seçilecek kişi eleştirilecek yönü olmayan, tek karılı biri olsun. Çocukları imanlı olmalı, sefahatle suçlanan ya da asi çocuklar olmamalı.",
    "Gözetmen, Tanrı evinin kâhyası olduğuna göre, eleştirilecek yönü olmamalı. Dikbaşlı, tez öfkelenen, şarap düşkünü, zorba, haksız kazanç peşinde koşan biri olmamalı.",
    "Tersine, konuksever, iyiliksever, sağduyulu, adil, pak, kendini denetleyebilen biri olmalı.",
    "Hem başkalarını sağlam öğretiyle yüreklendirmek, hem de karşı çıkanları ikna edebilmek için imanlılara öğretilen güvenilir söze sımsıkı sarılmalı.",
    "Çünkü asi, boşboğaz, aldatıcı birçok kişi vardır. Özellikle sünnet yanlıları bunlardandır.",
    "Onların ağzını kapamak gerek. Haksız kazanç uğruna, öğretmemeleri gerekeni öğreterek bazı aileleri tümüyle yıkıyorlar.",
    "Kendilerinden biri, öz peygamberlerinden biri şöyle demiştir: «Giritliler hep yalancıdır, azgın canavarlar, tembel oburlardır.»",
    "Bu tanıklık doğrudur. Bu nedenle onları sert bir şekilde uyar.",
    "Yahudi masallarına, gerçeği reddedenlerin buyruklarına kulak vermeyip sağlam imana sahip olmaları için.",
    "Yüreği temiz olanlar için her şey temizdir, ama yüreği kirli olanlar ve imansızlar için hiçbir şey temiz değildir. Çünkü onların zihinleri de vicdanları da kirlenmiştir.",
    "Tanrı'yı tanıdıklarını ileri sürer, ama yaptıklarıyla O'nu yadsırlar. Söz dinlemez, hiçbir iyi işe yaramaz iğrenç kişilerdir.",
  ],
  // Titus 2 (15 ayet)
  [
    "Sen ise sağlam öğretiye uygun olanı söyle.",
    "Yaşlı erkeklere ölçülü, ağırbaşlı, sağduyulu olmalarını, iman, sevgi ve dayanıklılıkta sağlam olmalarını öğret.",
    "Yaşlı kadınlara da aynı şekilde kutsal davranışta bulunmalarını, iftiracı olmamalarını, şaraba köle olmamalarını, iyiyi öğretenler olmalarını öğret.",
    "Böylece genç kadınları kocalarını ve çocuklarını sevmeye özendirirler.",
    "Sağduyulu, pak, ev işlerine bağlı, iyi yürekli, kocalarına bağımlı olsunlar ki Tanrı'nın sözü kötülenmesin.",
    "Genç erkeklere de aynı şekilde sağduyulu olmalarını öğütle.",
    "Her konuda kendin örnek ol. İyi işlerde özenli, öğretide doğruluk, ağırbaşlılık,",
    "sözü bozuk, kınanacak bir yanı olmayan, karşıtların utandırıp susturacak söz bulamayacakları biri ol.",
    "Köleler kendi efendilerine her konuda saygılı olsunlar, onları hoşnut etsinler, karşı gelmesinler.",
    "Çalıntı mal aşırmasınlar, tersine tüm bağlılığı göstersinler ki öğretimizi, Kurtarıcımız Tanrı'nın öğretisini her yönde süslesinler.",
    "Çünkü bütün insanlara kurtuluş getiren Tanrı'nın lütfu göründü.",
    "O bizi tanrısızlıktan ve dünyasal tutkularndan vazgeçirip bu çağda ölçülü, doğru ve Tanrı yolunda yaşamamız için eğitiyor.",
    "Sevgili Oğlu'muz aracılığıyla bize vaat ettiği yüce umuda uygun olarak kutlu bir umutla bekleyerek.",
    "Kendini bizim için feda eden Mesih İsa, bizi her kötülükten kurtarıp kendine ait, iyi işlere hevesli bir halk olsun diye kendini bize verdi.",
    "Bunları söyle, yüreklendir ve tüm yetkiyle uyar. Kimse seni küçümsemesin.",
  ],
  // Titus 3 (15 ayet)
  [
    "Hükümete, yönetime boyun eğmelerini, söz dinlemelerini, her iyi işe hazır olmalarını hatırlat.",
    "Kimseyi kötülemesinler, kavga etmesinler, uysal olsunlar, herkese her konuda yumuşak davransınlar.",
    "Bir zamanlar biz de anlayışsız, söz dinlemez, sapık, türlü tutku ve zevklere köle, kötülük ve kıskançlık içinde, nefret edilen ve birbirimizden nefret eden kişilerdik.",
    "Ama Kurtarıcımız Tanrı iyiliği ve insanlara olan sevgisi görününce,",
    "bizi işlediğimiz doğruluk işleriyle değil, kendi merhametiyle kurtardı. Kutsal Ruh'un yenilemesi ve yeniden doğuş yıkamasıyla.",
    "Tanrı bu Kutsal Ruh'u Kurtarıcımız İsa Mesih aracılığıyla üzerimize cömertçe döktü.",
    "Öyle ki, O'nun lütfuyla aklanıp umut edilen sonsuz yaşamın mirasçıları olalım.",
    "Bu söz güvenilirdir. Tanrı'ya inananların iyi işlere özen göstermelerini isterim. Bunlar insanlar için iyi ve yararlıdır.",
    "Ama akılsız tartışmalardan, soyağacı kayıtlarından, kavga ve Kutsal Yasa ile ilgili çekişmelerden kaçın. Bunlar yararsız ve boştur.",
    "Ayrılıkçı bir kişiyi bir iki uyarıdan sonra reddet.",
    "Böyle birinin sapıtmış olduğunu ve günah işleyerek kendi kendini mahkûm ettiğini bilirsin.",
    "Artemas ya da Tihikos'u yanına gönderdiğimde Nikopolis'e bana gelmeye çalış. Çünkü kışı orada geçirmeye karar verdim.",
    "Hukukçu Zenas'ı ve Apollos'u gayretle yolcu et. Hiçbir şeyleri eksik kalmasın.",
    "Bizimkiler de zorunlu ihtiyaçları karşılamak için iyi işlere özensinler. Meyve vermesiz kalmasınlar.",
    "Burada olanların hepsi sana selam eder. Bize iman edenlere selam söyle. Tanrı'nın lütfu hepinizle birlikte olsun.",
  ],
];
